### ISSUE TITLE
Real time data doesn't work on line chart

### ISSUE THREAD

**Issue by Sendrea** [swimlane/ngx-charts#1003]
I tried many solutions discussed on git but none of them worked.
I get this error 
`Error: <rect> attribute x: Expected length, "NaN".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2906
BaseAnimationRenderer.setAttribute @ animations.js:548
DebugRenderer2.setAttribute @ core.js:15503
setElementAttribute @ core.js:10894
checkAndUpdateElementValue @ core.js:10861
checkAndUpdateElementInline @ core.js:10810
checkAndUpdateNodeInline @ core.js:14093
checkAndUpdateNode @ core.js:14040
debugCheckAndUpdateNode @ core.js:14933
debugCheckRenderNodeFn @ core.js:14912
(anonymous) @ TooltipArea.ngfactory.js:114
debugUpdateRenderer @ core.js:14897
checkAndUpdateView @ core.js:14011
callViewAction @ core.js:14357
execComponentViewsAction @ core.js:14289
checkAndUpdateView @ core.js:14012
callViewAction @ core.js:14357
execEmbeddedViewsAction @ core.js:14315
checkAndUpdateView @ core.js:14007
callViewAction @ core.js:14357
execComponentViewsAction @ core.js:14289
checkAndUpdateView @ core.js:14012
callViewAction @ core.js:14357
execEmbeddedViewsAction @ core.js:14315
checkAndUpdateView @ core.js:14007
callViewAction @ core.js:14357
execComponentViewsAction @ core.js:14289
checkAndUpdateView @ core.js:14012
callViewAction @ core.js:14357
execEmbeddedViewsAction @ core.js:14315
checkAndUpdateView @ core.js:14007
callViewAction @ core.js:14357
execComponentViewsAction @ core.js:14289
checkAndUpdateView @ core.js:14012
callViewAction @ core.js:14357
execEmbeddedViewsAction @ core.js:14315
checkAndUpdateView @ core.js:14007
callViewAction @ core.js:14357
execComponentViewsAction @ core.js:14289
checkAndUpdateView @ core.js:14012
callWithDebugContext @ core.js:15260
debugCheckAndUpdateView @ core.js:14797
ViewRef_.detectChanges @ core.js:11778
(anonymous) @ core.js:6110
ApplicationRef.tick @ core.js:6110
(anonymous) @ core.js:5943
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4952
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4769
next @ core.js:5943
schedulerFn @ core.js:4538
SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
SafeSubscriber.next @ Subscriber.js:185
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.js:4518
checkStable @ core.js:4917
onLeave @ core.js:4996
onInvokeTask @ core.js:4946
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1427
globalZoneAwareCallback @ zone.js:1445`
Even with async pipe doesn't work.

**Expected behavior**
Line chart support real time data

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by aomegax** [comment]
What I am using: 

ngx-charts version: 10.0.0
Angular version: 6.0.0
Browser: all
Language: TypeScript 2.7.2

**Comment by ranouf** [comment]
Did you find a solution? I have the same error
