### ISSUE TITLE
Fix NPM warnings with Angular 7

### ISSUE THREAD

**Issue by kathomas921** [swimlane/ngx-charts#1012]
**I'm submitting a ...**  (check one with "x")

- [X] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
After upgrading to Angular 7.0.0 and running NPM install, I see
`npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/cdk@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/common@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/core@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/animations@6.x but none is installed. You must install peer dependencies yourself.
npm WARN @swimlane/ngx-charts@9.0.0 requires a peer of @angular/platform-browser@6.x but none is installed. You must install peer dependencies yourself.`

**Expected behavior**
There should be no warnings.

**Reproduction of the problem**

* **ngx-charts version:** 9.0.0

* **Angular version:** 7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript 3.1.1]

**Comment by bop10** [comment]
In fact, you can't use ng update @angular/material to update Angular Material or CDK to 7 right now cause of this:

```
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/cdk" (requires "6.x", would install "7.0.1").
Incompatible peer dependencies found. See above.
```

**Comment by estechco** [comment]
It does seem to work with ng7, but I had to ensure I'd upgrade @angular bits (as above) BEFORE I installed @swimlane/ngx-charts. Temporary uninstall/upgrade/reinstall should work?

**Comment by mbeckenbach** [comment]
If you want to update using ng update:
ng update @angular/cli @angular/core @angular/cdk @angular/material **--force**

This ignores the incompatible error.

**Comment by marjan-georgiev** [comment]
Released 10.0.0 which should address this. Please let me know if you still see issues.

**Comment by bop10** [comment]
thanks @marjan-georgiev

**Comment by kuadrosx** [comment]
Hi, I am getting message
`Package "@swimlane/ngx-charts" has a missing peer dependency of "d3" @ "^4.10.2"`
Updating to 10.0.0

**Comment by marjan-georgiev** [comment]
@kuadrosx you need to install d3 in your app.

`npm i --save d3@4.10.2`

**Comment by the-ult** [comment]
> @kuadrosx you need to install d3 in your app.
> 
> `npm i --save d3@4.10.2`

Is this something to add to the `install` docs?

**Comment by abishekram** [comment]
> npm WARN @swimlane/ngx-charts@12.0.1 requires a peer of @angular/cdk@7.x || 8.x but none is installed. You must install peer dependencies yourself. 

Is angular cdk mandatory for ngx-charts.?  Currently we are not having angular material as dependency !

**Comment by limthengwai** [comment]
getting same warning as @abishekram .

`npm WARN @swimlane/ngx-charts@12.0.1 requires a peer of @angular/cdk@7.x || 8.x but none is installed. You must install peer dependencies yourself`

Please update us if anyone encounter it before. Thanks

**Comment by Rajeshsekaran4488** [comment]
@limthengwai ,  Am also facing this same warning. 

Could any one let us know,  whether we ignore this warning.

**Comment by estechco** [comment]
Re-install or update, I suspect, will now work? Think the original issue was eventually fixed

**Comment by limthengwai** [comment]
> Re-install or update, I suspect, will now work? Think the original issue was eventually fixed

nope, @Rajeshsekaran4488  facing the same issue too.

**Comment by chadupton** [comment]
> @marjan-georgiev Is angular cdk mandatory for ngx-charts.? or I can just simply ignore the warnings

It seem like it is required -- I had to install CDK to get it working...

npm install @angular/cdk --save

**Comment by Hypercubed** [comment]
Yes... `@angular/cdk` is required.

**Comment by celesteking** [comment]
```
$ ng update  @angular/material@7
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/common" (requires "7.x" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "7.x" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/core" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-datatable" has an incompatible peer dependency to "@angular/compiler" (requires "<8.0.0" (extended), would install "10.1.6").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/platform-browser" (requires "7.2.15" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.10.3").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/forms" (requires "7.x" (extended), would install "10.1.6").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "7.x" (extended), would install "10.1.6").
Incompatible peer dependencies found. See above.

$ npm list @swimlane/ngx-charts  @swimlane/ngx-datatable
+-- @swimlane/ngx-charts@10.0.0 
`-- @swimlane/ngx-datatable@14.0.0 

```
fix your shit, man.
