### ISSUE TITLE
Line Chart Extra Data not exposed

### ISSUE THREAD

**Issue by iWumbo1** [swimlane/ngx-charts#1030]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

The standard line chart doesnt expose the "extra" field in their data when clicked on (in the emitter).

**Expected behavior**

The standard line chart should expose the "extra" field in the data.

**Reproduction of the problem**

Any line chart example with the extra-field set.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular CLI: 7.0.4
Node: 10.13.0
OS: win32 x64
Angular: 7.0.2

* **ngx-charts version:** 10.0.0

* **Angular version:** 7.0.2

* **Browser:** [all]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by fabmelo** [comment]
Hello. Did you solve it? Is the extra data in the line chart appearing in the ng-template? I'm having the same problem and I do not know how to solve it.

I did this test on GITHUB.

https://github.com/fabmelo/test-ngx-charts

**Comment by iWumbo1** [comment]
Nope i didnt :-(p

**Comment by fabmelo** [comment]
My God. I will have to find another library for generating line graphs with customizable tooltip. Thanks for the feedback.

**Comment by sebastiangug** [comment]
Any luck on this?

**Comment by iWumbo1** [comment]
Nope, i just map the click event data to sth i can work with and go from there :(

**Comment by sebastiangug** [comment]
@iWumbo1 the guy has given up on maintaining the package, I'm looking through the forks to see who's implemented what and then maybe have a second official fork where we try to fix all of these things and continue improving the package? There's tons of valuable fixes/features in the pull requests currently open.

**Comment by sebastiangug** [comment]
@iWumbo1  because its not there -- I'm working on adding this as a feature and make a pull request. 

For now, you can try to use my 'test' package ngx-charts-extra on npm -- Its up to date with the current ngx-charts version but I'm making public features there before making a pull request to the main package as that requires more testing & updating docs.

**Comment by jzer0** [comment]
Bump.

**Comment by iWumbo1** [comment]
i want this out of my face
