### ISSUE TITLE
d3 peer dependencies

### ISSUE THREAD

**Issue by dapullar** [swimlane/ngx-charts#1032]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
`package.json` declares each `d3` package as a `dependency` as well as a `peerDependency`. Would expect `peerDependency` & `devDependency` or just `dependency`. This results in unnecessary warnings.

**Expected behavior**
Declare `d3` packages as dependencies, `peerDependencies` seems extraneous. 

**Reproduction of the problem**
`yarn` / `npm install`

**What is the motivation / use case for changing the behavior?**
No need for extra packages

**Please tell us about your environment:**

* **ngx-charts version:** 10.0.0

* **Angular version:** 7.0.2

* **Browser:** all

* **Language:** all

**Comment by jotatoledo** [comment]
Seems like #1008 removed the d3 deps from devDeps, but not from peerDeps...

**Comment by Springrbua** [comment]
How can I solve this issue until it is fixed in the library? Do I need to install all d3 dependencies?

**Comment by Springrbua** [comment]
@dapullar thanks for the information. The problem was that I was using ng update, which treats warnings as errors. Using the --forcs flag solved the issue for me.

**Comment by jerguslejko** [comment]
any updates on this? 🙏

**Comment by wunderkind2k1** [comment]
I noticed, that I get seriously in trouble when I put the peerDependencies into the package.json:
Basically the animations stop working as expected (due to errors in node.transition()...).
When I remove the peerDependencies from package.json I get warnings like this:
```
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3@^4.10.2".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-array@^1.2.1".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-brush@^1.0.4".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-color@^1.0.3".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-force@^1.1.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-format@^1.2.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-hierarchy@^1.1.5".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-interpolate@^1.1.5".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-scale@^1.0.6".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-selection@^1.1.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-shape@^1.2.0".
warning " > @swimlane/ngx-charts@10.0.0" has unmet peer dependency "d3-time-format@^2.1.0".
```
but everything works fine.

**Comment by dapullar** [comment]
This is the worlds easiest fix, what is the hold up here? Do I need to make a PR?

**Comment by jotatoledo** [comment]
@dapullar its an open source project, so feel free to contribute

**Comment by adumesny** [comment]
having peer (which is better for app to pick and share with other modules, and what I do with my librabroes) and dep is wrong. Also having d3 and each d3-modules cuase issue because adding d3 (which brings all children) will still make yarn complain the modules listed as missing (even though they are there).

My bigger issue is with size of the index.js - doesn't appear to have tree shacking working correctly - see image
![image](https://user-images.githubusercontent.com/3496166/54298933-017e7400-4577-11e9-9264-9ea48f99ed5d.png)

**Comment by marjan-georgiev** [comment]
Merged the PR, thanks for the contribution!

**Comment by adumesny** [comment]
this is the wrong fix - lib should have peer dependencies and let the app brings the rev they might need, instead of dependencies. Should have removed the last section.

**Comment by marjan-georgiev** [comment]
@adumesny we wen't back and forth between these in the past. I believe they should stay as dependencies, as they would have to be installed manually and the list gets bigger now that d3 is split into separate packages.

I do agree about the bundle being too big, but that is a different problem that we need to solve, and fix tree shaking so it doesn't bundle the modules you are not using in your application.

**Comment by adumesny** [comment]
well the app can just include d3 upper package (yes yarn will warn that individual packages are not listed but it will find and compile just fine) and the app has also better control about what rev of a particular version of d3-xyz to use rather then having multiple copies because this lib had 1 rev, but app wants a later rev... then you get 2 copies compiled in.

**Comment by rbirkgit** [comment]
Any reason swimlane still uses 4.x instead of 5.x?

**Comment by rbirkgit** [comment]
Second question, if you are adding the main d3 package, why do you also need to add the individual sub-packages? Seems redundant.
