### ISSUE TITLE
if x and y axis are set to [not shown], the line chart doesn't produce gradient on hover

### ISSUE THREAD

**Issue by cvetlicni** [swimlane/ngx-charts#1062]
**I'm submitting a ...**  (check one with "x")

- [ x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
What happens is that when I don't define `[xAxis]=true` or `[yAxis]=true`, ie. when both are `false`, the area under the line doesn't get the gradient color stemming from its primary color, but some default-looking gray one. I'm not sure whether this is a bug or am I missing something?

P.S. it works if I change data / resize the window, but this probably isnt the expected behavior...

**Expected behavior**
On hover It should produce the standard gradient under the line.

**Reproduction of the problem**
[https://stackblitz.com/edit/angular-5p3snm](https://stackblitz.com/edit/angular-5p3snm)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:** OS X

* **ngx-charts version:** 10.0.0

* **Angular version:** 7.1.3/7.0.1 (tried both)

* **Browser:** [ Chrome 70.x | Latest Safari, probably others as well. ]

**Comment by bobbyg603** [comment]
We have published a mirrored version ngx-charts that should fix this issue via [@bugsplat/ngx-charts](https://www.npmjs.com/package/@bugsplat/ngx-charts) and opened PR #1637
