### ISSUE TITLE
(select) events on charts should return key event data

### ISSUE THREAD

**Issue by DonaldAlan** [swimlane/ngx-charts#1075]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

(select) events include only name and value, not key events. That makes me do more work to determine if the control or shift key is down.
**Expected behavior**

I would like to be able to test if the control or shift key is down. The event that is returned should have more information than just name and value.
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

10.0.0

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by pstyrna** [comment]
I second that request.
Useful when we need for example to stopPropagation() of click event.

**Comment by galvakojis** [comment]
agree, event should give us more information about element

**Comment by DonaldAlan** [comment]
In fact, not only should it return more click data (mouse info, plus ctrl-key and shift-key status) but it should also return user data attached to the element. The name and value may not be unique among the data points.   Compare how JavaFX lets the user set userData on a node.

**Comment by lanierhall** [comment]
> In fact, not only should it return more click data (mouse info, plus ctrl-key and shift-key status) but it should also return user data attached to the element. The name and value may not be unique among the data points. Compare how JavaFX lets the user set userData on a node.

There is an 'extra' field for holding and returning any data you need on a select event.
See: https://github.com/swimlane/ngx-charts/issues/1269

**Comment by marjan-georgiev** [comment]
Closing this as resolved.

**Comment by Ghostbird** [comment]
Why was this treated as resolved?
A click event should contain the MouseEvent, shouldn't it?
In this case, in my select handler, I want to call the `MouseEvent.stopPropagation()` method to ensure that it does not trigger the click of the underlying element, which is used to catch clicks outside of the graph.
