### ISSUE TITLE
tooltip not flipping when breaking out of window

### ISSUE THREAD

**Issue by krechtern** [swimlane/ngx-charts#1081]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
In the linechart component the tooltip-placement does not flip from 'right' to 'left' if breaking out of window width. I'm using a custom tooltip template. The following image shows the issue. Nearly 
a quarter of the tooltip is missing.

![s p3zio quql9jidm7 ewa_thumb_1](https://user-images.githubusercontent.com/6142193/51380696-984c2880-1b12-11e9-8511-42fab57be7a7.jpg)

**Expected behavior**
When the tooltip breaking out of the window, it should correctly flip to the other side.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Always full visible tooltips are awesome!

**Please tell us about your environment:**
macOS 10.14.2, VS Code, yarn

* **ngx-charts version:** 10.0.0

* **Angular version:** 7.2.1

* **Browser:** 
Chrome 71.0.3578.98 | Firefox 64.0.2

* **Language:**
TypeScript 3.1.6

**Comment by BoJIbFbI4** [comment]
the same here (need to be 60 rows...)
![tooltip_bug](https://user-images.githubusercontent.com/20932727/53799810-f3f83700-3f43-11e9-849e-17176baff566.png)
