### ISSUE TITLE
Dual x axis for line chart & area chart

### ISSUE THREAD

**Issue by PanwalaVandan** [swimlane/ngx-charts#1098]
With reference to [this](https://github.com/swimlane/ngx-charts/issues/397) issue which I guess is not answered properly.

I have a requirement where I need to create Dual X axis in a Line Chart & area Chart. Is there a way to do this with the existing Line & Area Chart?
I mean by passing the JSON in a certain format?
Or please advice on how to create such a Custom Chart. As there is no specific documentation on how to use components and create custom charts.

**Comment by marjan-georgiev** [comment]
Hi there. No, that is not supported by the area/line charts in the library. There are several examples of custom charts in the repository. The compo chart might give you an idea on how to add another axis:

https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

More on custom charts: https://github.com/swimlane/ngx-charts/blob/master/docs/custom-charts.md
