### ISSUE TITLE
Persistent hover gradient in line chart

### ISSUE THREAD

**Issue by pablosproject** [swimlane/ngx-charts#1103]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [x] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
On highlighting a point in the graph, a nice gradient background is added to the series. Is there a way to make it persistent?

![screenshot 2019-02-12 at 11 53 11](https://user-images.githubusercontent.com/1416964/52630827-8bc2b200-2ebd-11e9-807a-e408b4a9d76d.png)

**Please tell us about your environment:**
Mac OSX 10.14.2

* **ngx-charts version:** 
10.0.0

* **Angular version:** x.x.x
7.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
, Chrome 71.0.3578.98

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by KingDarBoja** [comment]
On your scss/css file, place this code:
```
.ngx-charts .line-highlight {
    display: block;
}
```
I highly recommend placing the chart inside a _.chart-container_ class to increase the selector specificity to override the default `display: none` property.

Cheers!

**Comment by MicMicMon** [comment]
Had to use `!important` to get it taken into account:

```css
.ngx-charts .line-highlight {
    display: block !important;
}
```
