### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by MarcoDeJong** [swimlane/ngx-charts#1107]
@marjan-georgiev At the time of writing there are 44 open pull request; do you need help on reviewing/merging/whatsover?

**Comment by MarcoDeJong** [comment]
@marjan-georgiev And we have 48 open pull requests and counting. Willing to help out. Otherwise we need to fork the project?

**Comment by marjan-georgiev** [comment]
Anyone interested to help, please reach out to me directly on gitter (link in readme). Thank you.
