### ISSUE TITLE
Charts are not responsive when there is more than one chart in grid layout

### ISSUE THREAD

**Issue by Ocean-Blue** [swimlane/ngx-charts#1119]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
I have 2 charts (area + pie grid) in a grid layout. The charts are not resized with screen size changes.
Plunker: https://plnkr.co/edit/reh6fKvZltSDPh1LLc5Z?p=info

But if I have only one chart (area only) in the grid, it works fine.
Plunker: https://plnkr.co/edit/HlstEqrmuIDKyF3edrRt?p=preview

**Expected behavior**
Both charts should be responsive when screen size changes.

**Reproduction of the problem**
Plunker: https://plnkr.co/edit/reh6fKvZltSDPh1LLc5Z?p=info

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **ngx-charts version:** x.x.x
10.0.0

* **Angular version:** x.x.x
7.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome: Version 72.0.3626.119

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 3.1.6

**Comment by aron9forever** [comment]
So, looking at the issue log clearly you'll be waiting a good while here for an answer.

 I'm having something vaguely similar on a production build, crazy responsiveness glitch when introducing 2nd chart into the same bootstrap grid. What's weird though is that I was not experiencing on Chrome 71, so if you don't mind and have the time, would you please test whether your issue gets resolved by reverting to chrome 71? This could be a clear sign we're on the same issue and then we could start tracking it down.

**Comment by marjan-georgiev** [comment]
This can be achieved by making the grid divs position: relative, and adding a new wrapper div around the chart with position: absolute.

Here's an example stackblitz: https://stackblitz.com/edit/schedule-variance-jaq2x9?file=src/app/app.component.ts
