### ISSUE TITLE
StackedBarChart getValueDomain doesn't work as expected if values are string numbers("42").

### ISSUE THREAD

**Issue by sako9** [swimlane/ngx-charts#1127]
**I'm submitting a ...**  (check one with "x")

- [ x] bug report - search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

With StackedBarChart if the results passed into the chart have string numbers the getValueDomain() function that StackedBarChart uses to determine the scale with returns unexpected results.

**Expected behavior**

It should either take into account the possibility of string numbers or explicitly throw an error when the result values are strings numbers instead of numbers. The former is preferable because as far as i can tell most if not all the other graphs work with string numbers.

**Reproduction of the problem**

using stacked bar chart uses this as the result data
```[
  {
    "name": "Germany",
    "series": [
      {
        "name": "2010",
        "value": "40632"
      },
      {
        "name": "2000",
        "value": "36953"
      },
      {
        "name": "1990",
        "value": "31476"
      }
    ]
  },
  {
    "name": "United States",
    "series": [
      {
        "name": "2010",
        "value": "49737"
      },
      {
        "name": "2000",
        "value": "45986"
      },
      {
        "name": "1990",
        "value": "37060"
      }
    ]
  },
  {
    "name": "France",
    "series": [
      {
        "name": "2010",
        "value": "36745"
      },
      {
        "name": "2000",
        "value": "34774"
      },
      {
        "name": "1990",
        "value": "29476"
      }
    ]
  },
  {
    "name": "United Kingdom",
    "series": [
      {
        "name": "2010",
        "value": "36240"
      },
      {
        "name": "2000",
        "value":  "32543"
      },
      {
        "name": "1990",
        "value":  "26424"
      }
    ]
  },
  {
    "name": "Dominica",
    "series": [
      {
        "name": "1990",
        "value": "58135"
      },
      {
        "name": "2000",
        "value":  "43453"
      },
      {
        "name": "2010",
        "value":  "53039"
      }
    ]
  },
  {
    "name": "Chile",
    "series": [
      {
        "name": "1990",
        "value": "35557"
      },
      {
        "name": "2000",
        "value":  "36991"
      },
      {
        "name": "2010",
        "value":  "28419"
      }
    ]
  },
  {
    "name": "Dominica",
    "series": [
      {
        "name": "1990",
        "value":  "17865"
      },
      {
        "name": "2000",
        "value": "50465"
      },
      {
        "name": "2010",
        "value":  "53131"
      }
    ]
  },
  {
    "name": "Chad",
    "series": [
      {
        "name": "1990",
        "value":  "19735"
      },
      {
        "name": "2000",
        "value":  "33275"
      },
      {
        "name": "2010",
        "value":  "16166"
      }
    ]
  }
]
```

**What is the motivation / use case for changing the behavior?**

To have consistent behavior for all the graphs. 

**Please tell us about your environment:**

Windows 10
Visual Studio Code
npm 6.4.1

* **ngx-charts version:** x.x.x

10.1.0
* **Angular version:** x.x.x

7.1.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 3.2.2

https://github.com/swimlane/ngx-charts/blob/f75a87ce65d053b255a50ecc07d23f54bf14db08/src/bar-chart/bar-horizontal-stacked.component.ts#L220

Due to the wonkiness that is javascript, if a user tries to use a stackedbarchart and has values like "45", "25, "39" the getValueDomain function when searching for the smallestSum/Biggestsum will actually concatenate the string numbers so biggestsum could end up being "452539" which would become the max later on because the Math.max/min function allows you to compare a number to a string number.

**Comment by marjan-georgiev** [comment]
Strings are not a valid value for the stacked bar chart. I suggest validating and parsing them into numbers before passing them to the chart.
