### ISSUE TITLE
Error when using ngx-charts-line-chart- Getting platform-browser.js:1094 Error: <rect> attribute x: Expected length, "NaN".

### ISSUE THREAD

**Issue by Mazi10987** [swimlane/ngx-charts#1135]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

I am Using below Data format to bind Ngx Line chart

[
{
"name": "CPU Time",
"series": [
{
"name": "2019-03-24T05:14:00Z",
"value": "0.031"
},
{
"name": "2019-03-24T05:19:00Z",
"value": "0.015"
}

**Comment by marjan-georgiev** [comment]
Could you provide a stackblitz where this can be reproduced please?

**Comment by priskz** [comment]
I just ran into this exact issue (Line Chart in Safari). Upon further review nothing was wrong with the library, it was other js code that was incompatible with Safari that I was using to determine my [results], specifically it was related to parsing a Date string.

**Comment by priskz** [comment]
Also, just noticed your value is a string (has double quotes), have you tried removing those?

**Comment by Mazi10987** [comment]
Yes I tried and its working

Thanks for guiding me.

Regards,
Mazhar

**Comment by b-mi** [comment]
I have the same problem. What is bad with this data?
    [
  {
    "name": "Zvolen",
    "series": [
      {
        "value": 48.72,
        "name": "01.01"
      },
      {
        "value": 34.12,
        "name": "02.01"
      },
      {
        "value": 24.19,
        "name": "03.01"
      },
      {
        "value": 14.05,
        "name": "04.01"
      },
      {
        "value": 24.9,
        "name": "05.01"
      },
      {
        "value": 15.83,
        "name": "06.01"
      },
      {
        "value": 14.81,
        "name": "07.01"
      },
      {
        "value": 12.57,
        "name": "08.01"
      },
      {
        "value": 18,
        "name": "09.01"
      },
      {
        "value": 17.39,
        "name": "10.01"
      }
    ]
  }
]
