### ISSUE TITLE
Tooltip label for horizontal barchart is not escaped

### ISSUE THREAD

**Issue by sanisoclem** [swimlane/ngx-charts#1137]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
Tooltip labels of the barchart is not escaped

**Expected behavior**
Tooltip labels are escaped

**Reproduction of the problem**
1. add a barchart
1. use data that has html reserved characters in the `name`

https://plnkr.co/edit/zinyIIB8YGEcDydSbuMJ
hover over Germany

**What is the motivation / use case for changing the behavior?**
Legend and axis labels are escaped already. If the data comes from the user, they could then inject code to my site.

* **ngx-charts version:** 
```
"@swimlane/ngx-charts@^10.0.0":
  version "10.1.0"
  resolved "https://registry.yarnpkg.com/@swimlane/ngx-charts/-/ngx-charts-10.1.0.tgz#be139b770b85eda609961cc08dba815c4a0d0b32"
  dependencies:
    d3 "^4.10.2"
    d3-array "^1.2.1"
    d3-brush "^1.0.4"
    d3-color "^1.0.3"
    d3-force "^1.1.0"
    d3-format "^1.2.0"
    d3-hierarchy "^1.1.5"
    d3-interpolate "^1.1.5"
    d3-scale "^1.0.6"
    d3-selection "^1.1.0"
    d3-shape "^1.2.0"
    d3-time-format "^2.1.0"
```

* **Angular version:** 7.x

* **Browser:** all

**Comment by marjan-georgiev** [comment]
Accepting PR's on this. As a workaround, you can override the tooltip templates and escape the values yourself for the time being.
