### ISSUE TITLE
Polar/radar Chart example

### ISSUE THREAD

**Issue by itzhak91** [swimlane/ngx-charts#1138]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ X ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

hey, i wanted to ask for Polar/radar Chart example, in the docs its in TBD status, thanks.

**Comment by marjan-georgiev** [comment]
There are a couple examples of it in the interactive demo: https://swimlane.github.io/ngx-charts/#/ngx-charts/polar-chart

Here's the code: https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.html#L359
