### ISSUE TITLE
Override functionality given by CircleSeriesComponent

### ISSUE THREAD

**Issue by a18garje** [swimlane/ngx-charts#1141]
**I'm submitting a ...**  (check one with "x")

- [x] support request - to override functionality given by CircleSeriesComponent

**Current behavior**
CircleSeriesComponent have defined below function:
var CircleSeriesComponent = /** @class */ (function () {
                CircleSeriesComponent.prototype.mapDataPointToCircle = function (d, i) {

                    // Implementation
                }
}

I want to override this CircleSeriesComponent.prototype.mapDataPointToCircle function in my class.

So when NGX chart calls function CircleSeriesComponent.prototype.mapDataPointToCircle, function overridden in my class should get called.

First of all is it allow to override functionality given by NGX chart.
If yes then what approach i should follow to override this.

* **Browser:** [all | Chrome XX | Firefox XX 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by riley2200** [comment]
implement your own based on custom chart, cp the component and implement your own

**Comment by marjan-georgiev** [comment]
Yes, as @riley2200 points out, a custom chart would be the best approach here.
