### ISSUE TITLE
[Feature] Possibility to disable x axis rotation

### ISSUE THREAD

**Issue by riede** [swimlane/ngx-charts#1143]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
The x axis ticks begin to rotate if there is not enough space to place them horizontally. 

**Expected behavior**
An additional field to disable the rotation would be great so the x axis ticks can be displayed always horizontal. There is already a PR (#1139). Please take a look at this.

**What is the motivation / use case for changing the behavior?**
I've added a second x axis tick line to display other important information. Each of them rotate in a different way. Instead of rotating the x axis ticks some of them should be hidden.  In the picture below you can see the described behaviour:

![image](https://user-images.githubusercontent.com/37865880/56079760-c206aa00-5df8-11e9-965f-51c1a93081df.png)

**Comment by marjan-georgiev** [comment]
#1139 was merged, so this should be addressed now.
