### ISSUE TITLE
404 Not Found @swimlane/ngx-charts when installing the library

### ISSUE THREAD

**Issue by petikosa** [swimlane/ngx-charts#1144]
Hi guys,

while following the official docs and installing the lib with` npm install @swimlane/ngx-charts --save` I get this `npm ERR! 404 Not Found: @swimlane/ngx-charts@latest`. Using ng7.

Any help appreciated.
Peter

**Comment by marjan-georgiev** [comment]
It seems to be working fine for me, using npm v6.4.1.

**Comment by petikosa** [comment]
Found the issue. In my company we have .npmrc file where we define available install registries. There I was missing @swimlane.
