### ISSUE TITLE
Polar Chart "ERROR TypeError: Invalid calling object"

### ISSUE THREAD

**Issue by abinthaha** [swimlane/ngx-charts#1148]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
In polar chart, am getting an error "ERROR TypeError: Invalid calling object". The error is happening only in IE11 or below. The issue seems to be happening in the [demo page](https://swimlane.github.io/ngx-charts/#/ngx-charts/polar-chart) also.

Due to this error, my page getting stuck.

![image](https://user-images.githubusercontent.com/13361483/56341101-9e18df00-61d1-11e9-9e26-36fac5f81215.png)

**Expected behavior**
The graph should be loaded without any error.

**Reproduction of the problem**
Open this in IE11 and check console.
https://swimlane.github.io/ngx-charts/#/ngx-charts/polar-chart

**Please tell us about your environment:**
Angular 7, Windows, IE11

* **ngx-charts version:** 10.1.0

* **Angular version:** 7.0.4

* **Browser:** IE11 or below

**Comment by marjan-georgiev** [comment]
Hi @abinthaha, IE is not a supported browser on ngx-charts. There are too many SVG features that are not supported by IE to make the effort worth it.
