### ISSUE TITLE
Peer dependency 7x | 8x is invalid

### ISSUE THREAD

**Issue by anantoghosh** [swimlane/ngx-charts#1160]
It should be `7x || 8x`   (double | )

Verify here: https://semver.npmjs.com/

Error from `ng update`
`Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/common" (requires "7.x | 8.x", would install "7.2.15")`

**Comment by marjan-georgiev** [comment]
Fixed in 11.1.0. Thanks for catching that.

**Comment by anantoghosh** [comment]
Thank you for your prompt action 👍
