### ISSUE TITLE
Grouped vertical bar chart legend too short

### ISSUE THREAD

**Issue by jesusmariocalleja** [swimlane/ngx-charts#1163]
I have a grouped vertical bar chart with the legend on the right position, but it's too short and the group titles are not showing.
![image](https://user-images.githubusercontent.com/10001795/57508606-32beba80-7302-11e9-964e-c232ace16d69.png)

**Comment by sebastiangug** [comment]
Add more info, show your markup/container and the css for those.

**Comment by manolait** [comment]
Hola, has solucionado el problema?

**Comment by jesusmariocalleja** [comment]
> Hola, has solucionado el problema?

Que va, al final opté por quitar la leyenda :(

**Comment by manolait** [comment]
Puf vaya ruina, yo la necesito... Al final voy a cambiar todo por la librería highcharts

**Comment by LukasSefcik** [comment]
I have same issue.

`
<ngx-charts-bar-vertical [animations]="false" [view]="view4" [results]="single4" [xAxis]="false" [yAxis]="true"       [showDataLabel]="true" [showGridLines]="false" [legend]="true" [legendTitle]="''">
</ngx-charts-bar-vertical>`

![ngx-charts-legend](https://user-images.githubusercontent.com/24602626/98664876-38f48380-234b-11eb-8d3c-387856b763a8.png)

In css i have nothing.
