### ISSUE TITLE
X-axis ticks cut-off in ngx-charts-area-chart

### ISSUE THREAD

**Issue by amarendar12** [swimlane/ngx-charts#1164]
Hi ,

We are using ngx charts area to plot memory usage of different servers of different applications. However for few graphs, the x-axis starting or the ending ticks getting cut-off. Is this a bug? If any solution, can someone please suggest.

I tried to rotate the ticks to vertical to avoid this issue but has thrown below error.
﻿
compiler.js:2196 Uncaught Error: Template parse errors:
Can't bind to 'rotateTicks' since it isn't a known property of 'ngx-charts-area-chart'.
1. If 'ngx-charts-area-chart' is an Angular component and it has 'rotateTicks' input, then verify that it is part of this module.
2. If 'ngx-charts-area-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("                            [autoScale]="areaChartAutoScale" (select)="onAreaChartSelect($event)"   [ERROR ->][rotateTicks]="rotateXAxisTicks">
        <ng-template #tooltipTemplate let-model="model">
          "): ng:///AppModule/SolarwindApplicationComponent.html@10:102
    at syntaxError (compiler.js:2196)

Is there a fix for this without rotating the tick labels? can someone please help.

Attached the code snippet and the screenshot
<ngx-charts-area-chart *ngIf="areaChartMulti.length > 0" [scheme]="areaChartColorScheme" [results]="areaChartMulti" [gradient]="areaChartGradient" [xAxis]="areaChartShowXAxis"
                              [yAxis]="areaChartShowYAxis" [legend]="areaChartShowLegend" [showXAxisLabel]="areaChartShowXAxisLabel"
                              [showYAxisLabel]="areaChartShowYAxisLabel" [xAxisLabel]="areaChartXAxisLabel" [yAxisLabel]="areaChartYAxisLabel"
                              [autoScale]="areaChartAutoScale" (select)="onAreaChartSelect($event)" >

**Comment by marjan-georgiev** [comment]
Could you create a stackblitz where this can be reproduced please?

**Comment by rooby** [comment]
This is happening for me also, on a line chart.
My last tick is "10,000" and it gets cut off.

**Comment by rooby** [comment]
I found the problem in my case.
I was using with bootstrap and bootstrap was adding overflow: hidden on svgs, which was overriding the .ngx-charts overflow: visible.
