### ISSUE TITLE
Turn showXAxis and showYAxis false cause black chart until resize

### ISSUE THREAD

**Issue by furevor** [swimlane/ngx-charts#1165]
**Describe the bug**
Just add on your page chart area and set showXAxis and showYAxis to false

**To Reproduce**
1. Go to my demo
2. Change 'showYAxis' to false
3. See error

**Screenshots**
1. Here is screen without bug
![withoutBug](https://user-images.githubusercontent.com/24428435/57786388-92332500-775d-11e9-84fd-c5aaf00fbdc1.png)
2. Screen with bug
![withBug](https://user-images.githubusercontent.com/24428435/57786387-919a8e80-775d-11e9-9620-afd876f8f0c6.png)

With bug](https://monosnap.com/file/6kmBn92zBhoFGrqY9hfEsTMfAdqM8W)

**Expected behavior**
There should be a normal display of chart with color

**Demo**
Just try this on [stackblitz](https://stackblitz.com/edit/ngx-charts-23hwvv)

**ngx-charts version**
latest 11.1.0

**Additional context**
Unfortunately, I even have no workaround, please help!

P.S.  After resizing the browser colors appearing!

**Comment by marjan-georgiev** [comment]
Thanks for reporting this. A short-term workaround for this would be setting the `gradient` input to false.

This is a bug that needs fixing though.

**Comment by RuneHanssens** [comment]
A quick workaround for this issue is to wrap the chart in a div with display: grid.

**Comment by bobbyg603** [comment]
We have published a mirrored version ngx-charts that should fix this issue via [@bugsplat/ngx-charts](https://www.npmjs.com/package/@bugsplat/ngx-charts) and opened PR #1637
