### ISSUE TITLE
Horizontal scroll bar charts for huge datasets

### ISSUE THREAD

**Issue by JeromeDesseaux** [swimlane/ngx-charts#1169]
Hi,

First of all : thanks for your work! This is really huge and awesome.

I just miss a thing : I'm using a huge dataset (data every day, for some years). My client needs to see the whole dataset that (obviously) don't fit a single page width.

Is there a way adding horizontal scroll bar to stacked bar charts ?

Thanks

**Comment by marjan-georgiev** [comment]
No, not at the moment. You could set the width of the chart big enough, and then add a scrollbar to the chart's parent container, but that will also scroll the y axis, which might not be a good enough of a solution.

**Comment by marjan-georgiev** [comment]
Something like this, perhaps? https://stackblitz.com/edit/schedule-variance-wmdnvr?file=src/app/app.component.css

**Comment by JeromeDesseaux** [comment]
Thanks, this is quite what I am expected. Trying to find a way to fixe bar width and its perfect! :)

**Comment by marjan-georgiev** [comment]
Great, glad that helped.
