### ISSUE TITLE
Can i set the margins between two chart?

### ISSUE THREAD

**Issue by israelKusayev** [swimlane/ngx-charts#1170]
I Want to set the margin after every two bars.

I am using in bar-vertical-stacked.

my goal is actually to make this like the "grouped-bars "

**Comment by marjan-georgiev** [comment]
That seems like a very specific use case, so we don't plan to support it. I would suggest forking the vertical stacked chart and customising it to fit your needs.

https://github.com/swimlane/ngx-charts/blob/master/docs/custom-charts.md
