### ISSUE TITLE
Cannot find module '@angular/core'

### ISSUE THREAD

**Issue by nijanthan0** [swimlane/ngx-charts#1176]
ERROR in ../node_modules/@swimlane/ngx-charts/release/area-chart/area-chart-normalized.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/area-chart/area-chart-stacked.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/area-chart/area-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/area-chart/area-series.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-2d.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-normalized.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-stacked.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-label.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-2d.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-normalized.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-stacked.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/bar.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/series-horizontal.component.d.ts(1,69): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bar-chart/series-vertical.component.d.ts(1,54): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bubble-chart/bubble-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/bubble-chart/bubble-series.component.d.ts(1,69): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/area.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/axes/axis-label.component.d.ts(1,54): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/axes/x-axis-ticks.component.d.ts(1,83): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/axes/x-axis.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/axes/y-axis-ticks.component.d.ts(1,83): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/axes/y-axis.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/base-chart.component.d.ts(1,121): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/charts/chart.component.d.ts(1,74): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/circle-series.component.d.ts(1,77): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/circle.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/count/count.directive.d.ts(1,72): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/grid-panel-series.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/legend/advanced-legend.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/legend/legend-entry.component.d.ts(1,30): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/legend/legend.component.d.ts(1,75): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/legend/scale-legend.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/legend/scale-legend.component.d.ts(2,30): error TS2307: Cannot find module '@angular/platform-browser'.
../node_modules/@swimlane/ngx-charts/release/common/svg-linear-gradient.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/svg-radial-gradient.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/timeline/timeline.component.d.ts(1,87): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/tooltip-area.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/tooltip/injection-registery.service.d.ts(1,30): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/tooltip/injection.service.d.ts(1,88): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/tooltip/tooltip.component.d.ts(1,54): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/common/tooltip/tooltip.directive.d.ts(1,70): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/force-directed-graph/force-directed-graph.component.d.ts(1,55): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/gauge/gauge-arc.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/gauge/gauge.component.d.ts(1,70): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/gauge/linear-gauge.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/heat-map/heat-map-cell-series.component.d.ts(1,77): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/heat-map/heat-map-cell.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/heat-map/heat-map.component.d.ts(1,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/line-chart/line-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/line-chart/line-series.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/line-chart/line.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/number-card/card-series.component.d.ts(1,56): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/number-card/card.component.d.ts(1,106): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/advanced-pie-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-arc.component.d.ts(1,68): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-grid.component.d.ts(1,29): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-label.component.d.ts(1,42): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/pie-chart/pie-series.component.d.ts(1,69): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/polar-chart/polar-chart.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/polar-chart/polar-series.component.d.ts(1,55): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/tree-map/tree-map-cell-series.component.d.ts(1,69): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/tree-map/tree-map-cell.component.d.ts(1,53): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/tree-map/tree-map.component.d.ts(1,43): error TS2307: Cannot find module '@angular/core'.
../node_modules/@swimlane/ngx-charts/release/utils/visibility-observer.d.ts(1,38): error TS2307: Cannot find module '@angular/core'.

**Comment by marjan-georgiev** [comment]
Please provide a repository where this can be reproduced.

**Comment by nijanthan0** [comment]
I resolved it, thank you

**Comment by marjan-georgiev** [comment]
Would you care to say what the issue was and how you resolved it, so other people in the future can benefit from it?

**Comment by sudhirpanier** [comment]
@nijanthan0 I am facing this exact same issue, could you please share how you resolved it? I would appreciate it SO MUCH
