### ISSUE TITLE
Line chart in Firefox: Layout defect if legend property is true

### ISSUE THREAD

**Issue by KlausHans** [swimlane/ngx-charts#1181]
**Describe the bug**
If i use a line chart as provided in the stackblitz the layout is as follows in Firefox:
![grafik](https://user-images.githubusercontent.com/9212982/58469655-39419480-8140-11e9-853e-e89958aea645.png)

**To Reproduce**
Use a line chart with [legend]="true" and open it in Firefox.

**Expected behavior**
It should look like this (Screenshot taken from Chrome)
![grafik](https://user-images.githubusercontent.com/9212982/58469521-f2539f00-813f-11e9-8f2a-fb5feccec3e8.png)

**Screenshots**
See above

**Demo**
https://stackblitz.com/edit/angular-material-nfd6ua?file=app%2Fapp.component.ts

**ngx-charts version**
11.1.0

Any suggestions are appreciated.
Thank you.

**Comment by marjan-georgiev** [comment]
Looks like a bug. As a workaround, you can wrap the chart in a parent container with a set height: 

https://stackblitz.com/edit/angular-material-wj6nnq?file=app%2Fapp.component.html
