### ISSUE TITLE
Update zone.js to version 0.9.1 to allow upgrade to Angular 8

### ISSUE THREAD

**Issue by rogerg93** [swimlane/ngx-charts#1186]
Please update zone.js package to version 0.9.1 to allow an upgrade to Angular 8.

**Comment by ismcagdas** [comment]
Hi @rogerg93 are you planning to release this anytime soon ?

**Comment by rogerg93** [comment]
@ismcagdas I created a pull request, now it's on maintainers to merge it and decide when to release a new version.

**Comment by marjan-georgiev** [comment]
Merged the PR, will be in the next release. Thanks!

**Comment by Enngage** [comment]
@marjan-georgiev awesome, thanks! Do you have any ideas when the next release might be?

**Comment by marjan-georgiev** [comment]
@Enngage see my comment here please: https://github.com/swimlane/ngx-charts/issues/1168#issuecomment-498867770

**Comment by marjan-georgiev** [comment]
Released in 11.2.0
