### ISSUE TITLE
Internet Explorer - TypeError Cannot read property "add" of undefined

### ISSUE THREAD

**Issue by aubane** [swimlane/ngx-charts#1191]
**Describe the bug**
After the first loading of a chart (tested on pie chart, vertical bar chart & stacked horizontal bar chart) and when hovering on a bar, the following errors appear in the console of IE11.
These errors appear (also) when hovering over the charts on the Ngx-Chart Swimlane Page
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical

When entering the hover area of a bar:
"Error: TypeError: Cannot read property "add" of undefined"
After loading and when leaving the hover area of a bar:
"Error: TypeError: Cannot read property "remove" of undefined"
"Error: TypeError: This object doen't support the property or method "matches"

**ngx-charts version**
10.0.0

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported.
