### ISSUE TITLE
extra minor ticks in ngx-charts-gauge

### ISSUE THREAD

**Issue by eslankitachandratreya** [swimlane/ngx-charts#1196]
Hi,
Facing issue where minor tick exceeds sometime as show in screenshot.

![img](https://user-images.githubusercontent.com/51444341/59031412-4584ca80-8881-11e9-85c5-8572e6d437c7.png)

**ngx-charts version**
9.0.0

**Comment by marjan-georgiev** [comment]
Can you create a stackblitz? I can not reproduce this.

**Comment by eslankitachandratreya** [comment]
As this issue doesn't emerged each time. unable to produce stackblitz, also unable to debug.

**Comment by marjan-georgiev** [comment]
I see. I will close this issue in that case. If you figure out how to reproduce and capture in a stackblitz, please open another one. Thanks.

**Comment by LS64** [comment]
Since I faced the same problem, here is my finding. Maybe, this helps someone in the future:
In my case I erroneously passed a string instead of a number to the [min] and [max] properties of the chart. This seems to work in terms of all other aspects but the smallSegements.
