### ISSUE TITLE
Arrow on y axis when no data is present on chart.

### ISSUE THREAD

**Issue by mohddanish211** [swimlane/ngx-charts#1197]
A black arrow appears on the y axis on the chart when there is no data present in the chart. Most of the time it appears in the middle.

The bug is present in ngx-chart version 10.1.0

There should be no arrow present on the y axis if no data is present.
It appears when hover over the chart y axis.

![Arrow_NgxChart](https://user-images.githubusercontent.com/16339561/59036669-069a4900-8870-11e9-88ce-a86218922e1f.PNG)

Please let me know if its really a bug or I have to disable /enable any particular class.

Regards 
Mohd Danish

**Comment by marjan-georgiev** [comment]
Could you provide a stackblitz? Also, please fill out the issue template properly.

**Comment by mohddanish211** [comment]
Hello Marjan,

Please find the link below for stackblitz:

https://stackblitz.com/edit/sample-ngx-charts-combo-1-bwftbp

The problem is when you hover the mouse on y axis(near the middle or near by region) a arrow appears. It will move if you scroll the mouse while putting the tip of mouse on arrow.

The issues is when there is no data present from the server the charts shows nothing that is correct. But. when I move the mouse over chart an arrow appears on the y-axis which moves with the scroll bar. I want to disable that arrow or remove it when no data is present to show on the chart.

I hope you understand my issue. Please provide your inputs.

**Comment by marjan-georgiev** [comment]
Thanks for the demo. That arrow is the empty tooltip. You can disable it when your data is not yet defined by setting the [tooltipDisabled] input to true:

```
<ngx-charts-area-chart [results]="dateData" [xAxis]="true" [yAxis]="true" [tooltipDisabled]="!dateData || dateData.length === 0">
```

Example stackblitz: https://stackblitz.com/edit/sample-ngx-charts-combo-1-5wevai?file=src/app/combo-chart/combo-chart.component.html

**Comment by mohddanish211** [comment]
Hello Marjan,

Thank you so much for the quick response. Really appreciate it. 

Regards,
Danish
