### ISSUE TITLE
Grouped horizontal/Vertical charts are breaking with some negative values

### ISSUE THREAD

**Issue by AlluNandaKishore** [swimlane/ngx-charts#1199]
Hi there..
I have a grid from which i'm loading chart on each record's view mode.
Charts are displayed correctly for one data(record) and for other data(record) it is not displaying.
A kind of dance it is doing with console errors on few types of data(Mostly I've negative values in my data).

Data is:
```typescript
 {
    "name": "sales",
    "series": 
   [ 
      {"name": "budget",  "value": 180000  }, { "name": "estimated", "value": 231426.3 },
      { "name": "variance", "value": -51426.29999999999 }
   ]
  }
```

Thanks in advance...
Please guide me to fix the issue.

**Comment by marjan-georgiev** [comment]
Please provide more details by filling the issue template, and create a stackblitz project where this can be reproduced.
