### ISSUE TITLE
Errors with templates during production build

### ISSUE THREAD

**Issue by SergioV85** [swimlane/ngx-charts#1202]
**Describe the bug**
After updating the project to the latest version of Angular, and updating ngx-charts to v.12, I can't build the project in production mode due to next errors:

> ERROR in node_modules\@swimlane\ngx-charts\release\heat-map\heat-map.component.d.ts.HeatMapComponent.html(58,11): : Expected 2-3 arguments, but got 1.
node_modules\@swimlane\ngx-charts\release\heat-map\heat-map.component.d.ts.HeatMapComponent.html(59,11): : Expected 2-3 arguments, but got 1.
node_modules\@swimlane\ngx-charts\release\pie-chart\advanced-pie-chart.component.d.ts.AdvancedPieChartComponent.html(36,11): : Expected 1-2 arguments, but got 3.
node_modules\@swimlane\ngx-charts\release\pie-chart\advanced-pie-chart.component.d.ts.AdvancedPieChartComponent.html(37,11): : Expected 1-2 arguments, but got 3.

In non-production mode project built successfully, as well it works normally in development mode.

**ngx-charts version**
v. 12.0.0

**Comment by gary-holland** [comment]
Have the same issue here when running `ng build --prod`.  

Version 11.2 with Angular 8 seems ok, so I've dropped back to that for now.

**Comment by Enngage** [comment]
Yeah, same here

**Comment by marjan-georgiev** [comment]
Released a fix in 12.0.1. Please verify.

**Comment by BernhardRode** [comment]
Works for me, thank you!
