### ISSUE TITLE
Why use d3 v4 when v5 has been out for some time

### ISSUE THREAD

**Issue by rbirkgit** [swimlane/ngx-charts#1207]
**Describe the bug**

Any reason swimlane still uses 4.x instead of 5.x?

Second question, if you are adding the main d3 package, why do you also need to add the individual sub-packages? Seems redundant.

**Comment by marjan-georgiev** [comment]
Removed d3 as a dependency in v 13.0.0. Only individual d3 libraries are dependencies now. Closing as fixed.
