### ISSUE TITLE
Negative Values with rounded corners

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#121]
Negative values on bar charts, show the wrong rounded corner direction. 

![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/00961d2d-1d1e-462b-bb1e-eee052e502bd/2016-12-07_08-30-17.png)

**Comment by alyahmedaly** [comment]
it will be greet if you provide an option to enable or disable the edges

**Comment by zubair-io** [comment]
@alyahmedaly  one of my team members just submited a pull request to enable or disable rounded edges #408

**Comment by webcat12345** [comment]
Still not available for this option?

**Comment by marjan-georgiev** [comment]
@webcat12345 this should be working fine:

https://stackblitz.com/edit/vertical-bar-chart-8ysbzm?file=app%2Fdata.ts
