### ISSUE TITLE
Number Cards - card color overflows the size mentioned in 'view' attribute

### ISSUE THREAD

**Issue by school-coder** [swimlane/ngx-charts#1216]
`<ngx-charts-number-card [results]="data" [cardColor]="'#FAFAFA'" [view]="[1200, 200]"></ngx-charts-number-card>`

**Screenshots**
![image](https://user-images.githubusercontent.com/644749/60013698-b9560e00-969c-11e9-941f-24dd8bccdef3.png)

**ngx-charts version**
12.0.1

**Comment by marjan-georgiev** [comment]
I'm not sure I understand this. Could you elaborate? Also, please provide a stackblitz.

**Comment by school-coder** [comment]
This is my error. I have a class 

`.card {
 height: 450px;
}`

which resulted in this issue. Closing the issue now.

**Comment by school-coder** [comment]
d

**Comment by school-coder** [comment]
d
