### ISSUE TITLE
Decimals in Gauge Charts

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#122]
Decimals in gauge charts do not show up... 

![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/534a7f88-99c7-4b48-be6d-20a65f791d77/2016-12-07_08-48-15.png)

**Comment by marjan-georgiev** [comment]
This can be now fixed by specifying the `axisTickFormatting`, but let's handle the default case too.
