### ISSUE TITLE
Threshold lines for bar chart

### ISSUE THREAD

**Issue by HuyNVuong** [swimlane/ngx-charts#1222]
I am trying to add some threshold lines (ex: High, average...) into bar chart, this is what I have currently: 
![image](https://user-images.githubusercontent.com/35347897/60733477-959f8d00-9f12-11e9-91c8-c7efb6b223d8.png)
This is what I wanted it to be
![image](https://user-images.githubusercontent.com/35347897/60733412-64bf5800-9f12-11e9-880f-ad23beab1a62.png)
I have tried to overwrite some certain gridline like this but it is not working:
```
::ng-deep .ngx-charts { 
	.gridline-path:nth-child-last() {
		stroke: rgb(151, 34, 34);
	}
}
```
Can it be done with some scss overwriting or do I need to use combo charts?

**Comment by sab9900** [comment]
how does it work?
