### ISSUE TITLE
Mixed Chart Types - Bar graph & Line graph

### ISSUE THREAD

**Issue by medinarodel** [swimlane/ngx-charts#1223]
Is it possible to achieve Mixed Chart Types - Bar graph & Line graph? I just can't see on any examples you have.

https://www.chartjs.org/docs/latest/charts/mixed.html

Thanks!

**Comment by marjan-georgiev** [comment]
You are looking for custom charts. See example here:
https://swimlane.github.io/ngx-charts/#/ngx-charts/combo-chart

More info: 
https://github.com/swimlane/ngx-charts/blob/master/docs/custom-charts.md
