### ISSUE TITLE
Calendar Heatmap cell coloring is not working

### ISSUE THREAD

**Issue by wendellestradairely** [swimlane/ngx-charts#1225]
**Describe the bug**
I copied all the source code that are related to the calendar heatmap. I was able to display the chart, but all the cell colors are the same even though they have different values.

**To Reproduce**

Take a look at this StackBlitz: https://stackblitz.com/edit/angular-642xtv

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50942719/61341423-c8ce0e80-a878-11e9-8b63-6e70b995015e.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

Take a look at this StackBlitz: https://stackblitz.com/edit/angular-642xtv

**ngx-charts version**
Specify the version of ngx-charts where this bug is present
12.0.1

**Additional context**

**Comment by marjan-georgiev** [comment]
Your `[max]` input on the heatmap component is set to 50,000, while the max value in your data is 12. This is why all the colors you get are from the very beginning of your color scale, and they all end up similar.

If you change the `max` input to the maximum value of your data, your colors will span the full range of the color scale. Example:

https://stackblitz.com/edit/angular-il9lf4?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/8687/61629617-b2afbc00-ac85-11e9-8e12-3381230e5ace.png)
