### ISSUE TITLE
 @swimlane/ngx-charts@12.0.1 requires a peer of @angular/cdk@7.x || 8.x but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by school-coder** [swimlane/ngx-charts#1243]
**Describe the bug**
on NPM install, we are seeing the warning, 
 @swimlane/ngx-charts@12.0.1 requires a peer of @angular/cdk@7.x || 8.x but none is installed. You must install peer dependencies yourself.

**Expected behavior**
No Warning needs to be shown

**ngx-charts version**
12.0.1

**Comment by Hypercubed** [comment]
`@angular/cdk` is peer dep, if you are installing ngx-charts into a project you will need to install peer dependencies yourself.

If you are using the demo project here you don't have to worry because `@angular/cdk` is also a dev dep.
