### ISSUE TITLE
Different scaling for multiple series

### ISSUE THREAD

**Issue by 27leaves** [swimlane/ngx-charts#1252]
Hello!

I need to make a line chart with time on the X axis and multiple series with different units (temperature, humidity, CO2, ...) on the Y axis. Right now, due to the different min/max values of the different series, the chart is not really informative.

<img width="600" alt="Screenshot 2019-08-26 17 23 32" src="https://user-images.githubusercontent.com/999419/63702013-69bfca00-c826-11e9-9ae9-8f8c64174761.png">

Is there a way to set different scalings to the different series?

Thank you!

**Comment by manolait** [comment]
I need to
