### ISSUE TITLE
Chart responsiveness cannot shrink in flexbox

### ISSUE THREAD

**Issue by andrewv86** [swimlane/ngx-charts#1263]
**Describe the bug**
The responsive layout of the chart cannot shrink when the parent element is a flexbox, it can only grow to the size of the window.

**To Reproduce**
1. Go to [https://ngxchart-flexbox-issue.stackblitz.io](https://ngxchart-flexbox-issue.stackblitz.io)
2. Resize the window to make it smaller
3. Reload page
4. Resize the window to make it larger

**Expected behavior**
The chart should resize within its container accordingly when made larger or smaller.

**Demo**
[https://stackblitz.com/edit/ngxchart-flexbox-issue](https://stackblitz.com/edit/ngxchart-flexbox-issue)

**ngx-charts version**
12.0.1

**Comment by KingDarBoja** [comment]
Hello @andrewv86,

I think you should check marjan comment at #451 as workaround.

Cheers!

**Comment by andrewv86** [comment]
> Hello @andrewv86,
> 
> I think you should check marjan comment at #451 as workaround.
> 
> Cheers!
> 
> **EDIT:** I just saved you some time: [forked flexbox issue demo](https://stackblitz.com/edit/ngxchart-flexbox-issue-3tx2fl).

Perfect! Thank you very much, closing this now.

**Comment by boonzeet** [comment]
I encountered this issue and found it was due to a confusing aspect of flexboxes - the container will overflow unless min-width is set to 0.

I've reproduced the fix here (giving the div.main a min-width):
https://stackblitz.com/edit/ngxchart-flexbox-issue-gwve16

**Comment by Alarid** [comment]
> I encountered this issue and found it was due to a confusing aspect of flexboxes - the container will overflow unless min-width is set to 0.
> 
> I've reproduced the fix here (giving the div.main a min-width): https://stackblitz.com/edit/ngxchart-flexbox-issue-gwve16

min-width set to 0 is exactly the solution I was looking after, thanks ! Works like a charm
