### ISSUE TITLE
Clicking on a bar/piece should emit more than name/value

### ISSUE THREAD

**Issue by lanierhall** [swimlane/ngx-charts#1269]
**Is your feature request related to a problem? Please describe.**
If you click on a bar/piece it only returns the name/value. 

**Describe the solution you'd like**
It should also return userData that has been attached when the user passed in the data. For instance the id of the entity or some link value that the user wants to use to navigate somewhere.

**Describe alternatives you've considered**

**Additional context**

**Comment by marjan-georgiev** [comment]
It emits anything you add to the `extra` object on the data item. See 
https://github.com/swimlane/ngx-charts/blob/master/demo/data.ts#L8

**Comment by lanierhall** [comment]
Thanks, I noticed that after creating this and hadn't closed this yet.

**Comment by KaranTrivedi** [comment]
link not found. can we get some docs on this please?

**Comment by Zoraiyo** [comment]
Hi @KaranTrivedi  
Working link: [https://github.com/swimlane/ngx-charts/blob/master/src/app/data.ts#L15](https://github.com/swimlane/ngx-charts/blob/master/src/app/data.ts#L15)
Each bar chart (and all other charts that extend `BaseChartComponent`) has the `select` EventEmitter that emits the bar data including the `extra` object when the bar is clicked.
1. Open the [Demo](https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical) 
2. Open the developer console
3. Click on a bar
4. See the log entry with all data including `extra` object
