### ISSUE TITLE
In paged tables, automatically navigate to page of selected row

### ISSUE THREAD

**Issue by granttchart** [swimlane/ngx-charts#1283]
**Is your feature request related to a problem? Please describe.**
I'm using pagination on a table inside a modal and allowing a user to select a row. Once the selection is made, the selection is saved in state. The user can re-open the modal and edit their selection.

Upon re-open, I set the chart's `[selected]` to the selected row's corresponding object, but if this selection is not on the first page, it isn't visible to the user that their previous selection persists.

**Describe the solution you'd like**
When a selection is set and the selection is not visible, the library should navigate to the selection's page.

**Describe alternatives you've considered**
There could be a method that accepts a row ID and returns its page. I could then set the page offset myself.

**Comment by Hypercubed** [comment]
Do you have the right repo here... ngx-datatable maybe?
