### ISSUE TITLE
TypeError: s is not a function

### ISSUE THREAD

**Issue by AScarberry** [swimlane/ngx-charts#1288]
**Describe the bug**
Line chart breaks and will not load.
`TypeError: s is not a function`
followed by 
`TypeError: Cannot read property 'getColor' of undefined`

**To Reproduce**
Upgrade `"d3-time-format"` to version `2.2.1`

**Expected behavior**
Line chart should load with no related console errors

**ngx-charts version**
12.0.1

**Additional context**
Downgrading `"d3-time-format"` to version `2.1.3` fixes the issue

**Comment by wangju1111** [comment]
The downgrading of d3-time-format, works for me, thank you

**Comment by oliveirabc** [comment]
Has anyone figured out why downgrading the d3-time-format version fixes the issue? We're also having this prolem but not using d3-time-format.

**Comment by cunderwood-va** [comment]
See also https://github.com/swimlane/ngx-charts/issues/1291; if updating @angular-devkit/build-angular fixes it, that's probably the better outcome rather than pinning a library

**Comment by pantonis** [comment]
@wangju1111 or anyone else post a working packages.config please?
