### ISSUE TITLE
Data Series points with duplicate names are dropped in the rendered chart

### ISSUE THREAD

**Issue by ahmadakra** [swimlane/ngx-charts#1295]
**Describe the bug**
In any chart, when you supply a series of data with duplicated names, the chart drops the duplicated values.

**To Reproduce**
(1) Create any chart e.g. bar chart
(2) Add a data series where at least two points have identical point.name.toString()
(3) Observe how the chart does not render one of the two

**Expected behavior**
Every point in the data series needs to be treated as a distinct value.
I would have overridden toString() to return some form of Id value to make all the names unique, but the problem is that that same name is displayed in the tool-tip when the user hovers over the bar or the pie wedge. so it needs to be human-readable, and the human readable values may not necessarily be unique in some cases.

**Screenshots**
Data:
![image](https://user-images.githubusercontent.com/43896758/68071885-44a08800-fd90-11e9-8184-0a37aac5623c.png)

Result:
![image](https://user-images.githubusercontent.com/43896758/68071887-597d1b80-fd90-11e9-9be3-d6c5c9b5c28c.png)

**ngx-charts version**
^12.0.1
Angular 8

**Comment by GretchenGit** [comment]
Dealing with the same issue on a single horizontal chart right now. It stacks the data with same name on top of the other. I want to display each data, keep the name, but want to display a bar for each with it's own unique value.
![ngx_bug](https://user-images.githubusercontent.com/58035612/70217699-f5a89280-1741-11ea-86de-95082e2b5b87.jpg)

**Comment by ahmadakra** [comment]
ngx-charts is an amazing charting library for Angular but it seems like it is no longer maintained or supported unfortunately.
I wonder if there is a fork somewhere with an active community still, it would be such a waste to see a masterpiece like this go away. I am not aware of any alternative library with similar features.

**Comment by Hypercubed** [comment]
ngx-charts is actively maintained and continuously improved.  As with any OS project contributions are voluntary and resources are limited.

**Comment by Hypercubed** [comment]
@ahmadakra I don't think this is a bug.  If you want to show separate values for "Germany" create a separate name ("Germany 1990" for example).  This is how scales work.

**Comment by Hypercubed** [comment]
Value names must be a unique value, use `xAxisTickFormatting` if you wish to change the way the name is displayed in the axis.
