### ISSUE TITLE
Adding horizontal threshold lines on a line-chart ?

### ISSUE THREAD

**Issue by NikhilNanjappa** [swimlane/ngx-charts#1306]
**Is your feature request related to a problem? Please describe.**
I wanted the user viewing the chart to know a particular expected limit (red line) that he/she needs to reach. I've plotted a basic line-chart, but didn't find a capability to provide a threshold like horizontal line(s).

Basically something like this (uses chart.js annotations) - https://codepen.io/jordanwillis/pen/qrXJLW

**Describe the solution you'd like**
The capability to add one of more horizontal line(s) on top of a line-graph as shown in the image below.
<img width="526" alt="Screenshot 2019-11-20 at 15 54 32" src="https://user-images.githubusercontent.com/5576981/69254733-9af23100-0bae-11ea-9cdb-2623ab647c05.png">
 
**Describe alternatives you've considered**
- I've considered using a bar-chart as I heard bar-chart has a capability of a threshold line but didn't want to go down that lane as I wanted a line-chart.
- I also tried adding a `div` and manually placing it over the chart using `position: absolute` etc but thats too ugly imo.

**Additional context**
If such a feature already exists, apologies and please help me out by pointing me in the right direction!

**Comment by NikhilNanjappa** [comment]
Found out that line-chart supports reference lines - https://swimlane.github.io/ngx-charts/#/ngx-charts/line-reference-lines. Hence, closing this issue.

**Comment by Ten2az** [comment]
can we make solid reference lines
