### ISSUE TITLE
How I must pass the date with '2019-11-25T00:00:00.000Z' format as name?

### ISSUE THREAD

**Issue by fpichlou** [swimlane/ngx-charts#1316]
Hi all
I have an object of data with date format of `2019-11-25T00:00:00.000Z`, How I must pass it as the name property of chart data?
I did it by `New Date('2019-11-25T00:00:00.000Z')`, but I had the following error in the console!
```Getting platform-browser.js:1094 Error: <rect> attribute x: Expected length, "NaN"```

**Comment by marjan-georgiev** [comment]
That looks right. The issue could be something else with your data.

In the future, please post questions like this on StackOverflow. The github issue board is only for bugs and feature requests.
