### ISSUE TITLE
TypeError: this.xScale is not a function     at BarVerticalStackedComponent.push.

### ISSUE THREAD

**Issue by pantonis** [swimlane/ngx-charts#1318]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3295086/70134203-48297680-1690-11ea-95cb-658b77c6cadf.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
Specify the version of ngx-charts where this bug is present
12.1.0

**Additional context**

**Comment by Hypercubed** [comment]
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced
