### ISSUE TITLE
Ngx-charts Xaxis label position is wrong

### ISSUE THREAD

**Issue by disha-hegde** [swimlane/ngx-charts#1322]
Typically, the xaxis label is below the xaxis ticks. But here label position is on the xaxis. How do I solve this?
![ngx](https://user-images.githubusercontent.com/58779820/70630653-e6e64200-1c51-11ea-985b-5f879254fb32.PNG)

**Comment by marjan-georgiev** [comment]
Could you post a stackblitz where this can be reproduced? Thanks

**Comment by disha-hegde** [comment]
https://stackblitz.com/edit/angular-wnoetc

**Comment by tdhulster** [comment]
> https://stackblitz.com/edit/angular-wnoetc

Looks like Stackblitz has some issues to load the ngx-charts dependency, tried to reproduce myself but each time I try to install ngx-charts, Stackblitz blocks and fails to render the application. Can't seem to find Stackblitz errors though..
