### ISSUE TITLE
[vr13.0.0] Can't build in production mode

### ISSUE THREAD

**Issue by MDzyga** [swimlane/ngx-charts#1323]
Hi,
I can't build my application in production mode after updating @swimlane/ngx-charts package to latest version. I got an error:
ERROR in Unexpected value 'undefined' imported by the module 'ɵa in ../node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'.
When I build my application on previous version (12.1.0), build is succesfull.

Angular cdk: 8.2.3
Angular CLI: 8.3.20
Swimlane/ngx-charts: 13.0.0

**Comment by luismurua7** [comment]
I got the same issue. I updated the package in my application to 13.0.0 version to fix of a bug related to d3 dependencies, but not i have _ERROR in Unexpected value 'undefined' imported by the module 'ɵa in ../node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'_

**Comment by jritchie** [comment]
Duplicate of #1324

**Comment by MDzyga** [comment]
fixed in version 13.0.1

**Comment by rvtiwari98** [comment]
same issue with me not resolved in 13.0.1
