### ISSUE TITLE
Can't bind to 'tooltipDisabled' since it isn't a known property of ':svg:rect'.

### ISSUE THREAD

**Issue by smile2014** [swimlane/ngx-charts#1330]
ERROR in Unexpected value 'undefined' imported by the module 'ɵa in E:/ApesERP/yyerp2.0/myapp/node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'
Unexpected value 'undefined' exported by the module 'ɵa in E:/ApesERP/yyerp2.0/myapp/node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'
Unexpected value 'undefined' declared by the module 'ɵa in E:/ApesERP/yyerp2.0/myapp/node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'
Unexpected value 'undefined' imported by the module 'ɵcc in E:/ApesERP/yyerp2.0/myapp/node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts'
Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
Can't resolve all parameters for ɵm in E:/ApesERP/yyerp2.0/myapp/node_modules/@swimlane/ngx-charts/swimlane-ngx-charts.d.ts: ([object Object], ?).
Can't bind to 'tooltipDisabled' since it isn't a known property of ':svg:rect'. ("

**Comment by shubham-khanna** [comment]
Why this issue is closed?
