### ISSUE TITLE
13.0.0 IE support

### ISSUE THREAD

**Issue by qbouchat** [swimlane/ngx-charts#1333]
The latest version, 13.0.0, doesn't support IE anymore. This issue come from the upgrade of the d3-array dependency.

`"d3-array": "^2.4.0"`

D3 Array 2.* doesn't support IE considering the following link : [https://github.com/d3/d3-array/issues/87](url)
Is it possible to downgrade the version to the latest 1.* ?

**Comment by NaderAbbasi** [comment]
We have also encountered this error. How should we resolve it? 
We use the version 14.0.0 and angular version 9

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported.
