### ISSUE TITLE
Error when installing v13.0.0

### ISSUE THREAD

**Issue by whizkidwwe1217** [swimlane/ngx-charts#1335]
**Describe the bug**
Got an error when installing version 13.0.0.

`
ERROR in ./node_modules/@swimlane/ngx-charts/fesm2015/swimlane-ngx-charts.js
Module not found: Error: Can't resolve '@angular/cdk/portal' in 'C:\myproj\node_modules\@swimlane\ngx-charts\fesm2015'
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
13.0.0

**Additional context**
ng --version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.21
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.803.21
@angular-devkit/build-ng-packagr   0.800.1
@angular-devkit/build-optimizer    0.803.21
@angular-devkit/build-webpack      0.803.21
@angular-devkit/core               8.0.1
@angular-devkit/schematics         8.3.21
@angular/cli                       8.3.21
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.3.21
@schematics/angular                8.3.21
@schematics/update                 0.803.21
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.4
webpack                            4.39.2

**Comment by lyubomirv** [comment]
I have the same issue. The only differences seem to be I'm using Node 10.13 on Linux.

**Comment by marjan-georgiev** [comment]
try adding `@angular/cdk`v9.0.0-rc.7  to your dependencies. We'll add it by default in the next version.

**Comment by lioneltolosa** [comment]
npm install @angular/cdk --save :)

**Comment by vexap** [comment]
Very good, this help me

**Comment by TonyGLL** [comment]
thanks, very useful

**Comment by prophet-99** [comment]
Thanks

**Comment by Osanllet** [comment]
Very useful, thanks.

**Comment by Pluplu881210** [comment]
Thanks a lot! it solves the problem :)
