### ISSUE TITLE
Dead link on ngx-charts/docs/custom-charts.md

### ISSUE THREAD

**Issue by bar9** [swimlane/ngx-charts#1341]
**Describe the bug**
A dead link in the documentation

**To Reproduce**
1. Go to 'ngx-charts/docs/custom-charts.md' https://github.com/swimlane/ngx-charts/blob/master/docs/custom-charts.md
2. Click on 'Bar/Line Combo Chart' https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart
3. 404 Error

**Comment by marjan-georgiev** [comment]
Updated them, thanks!
