### ISSUE TITLE
im new to the ngx-chart.can i have full example for spark-line chart?

### ISSUE THREAD

**Issue by thanushiya13** [swimlane/ngx-charts#1345]
i got following error

Can't bind to 'view' since it isn't a known property of 'ngxchartschart'. ("<ngxchartschart [ERROR ->][view]="[width, height]" [showLegend]="false"[animations]="animations">

**Comment by marjan-georgiev** [comment]
The sparkline is a custom chart. You would need to copy the component into your project and then use it:

https://github.com/swimlane/ngx-charts/tree/master/src/app/custom-charts/sparkline
