### ISSUE TITLE
v13 cannot compile with ivy

### ISSUE THREAD

**Issue by cfremgen** [swimlane/ngx-charts#1347]
ERROR in No suitable injection token for parameter 'element' of class 'TooltipContentComponent'. no type or decorator

**Describe the bug**
Getting this error when compiling with "enableIvy": true

**Demo**
Can't create an ivy project on stackblitz

**ngx-charts version**
13.0.0, 13.0.1, 13.0.2

Also tried 12.0.x and got the same as this issue: https://github.com/swimlane/ngx-charts/issues/1217

**Additional context**
Removing enableIvy flag works

**Comment by garethflowers** [comment]
We're getting exactly the same issue (ngx-charts v13.02, angular v8.2.14).

**Comment by marjan-georgiev** [comment]
Have you tried upgrading to angular 9?

**Comment by cfremgen** [comment]
Upgrading to Angular 9.0.0-rc.9 has fixed the issue.

Closing since enableIvy flag is an experimental flag anyway.
