### ISSUE TITLE
Chart Width Out of container

### ISSUE THREAD

**Issue by xyrintech** [swimlane/ngx-charts#1349]
**Describe the bug**
Please see attached file. The chart goes out of container, the container has 100% - `col-12` inside `row` 

![image](https://user-images.githubusercontent.com/7784136/72736159-36118200-3bc3-11ea-9f21-5f3851abfe69.png)

Please see the 11PM above, it goes out of container. 

**To Reproduce**
Attached the screenshot for the same. Please lemme know if you still need more info on this. 

**Expected behavior**
Chart to obey the container width and stays within it. 

**ngx-charts version**
12.0.1

**Comment by marjan-georgiev** [comment]
Please provide a stackblitz where this can be reproduced.
