### ISSUE TITLE
How to set width of bars in a Grouped Vertical Bar Chart?

### ISSUE THREAD

**Issue by Oxyrus** [swimlane/ngx-charts#1351]
For some reason, I am not able to get a clean looking vertical bar chart. Currently it presents two issues:

1. The items are not centered within the group.
2. The width of the bars is super small for some reason.

![image](https://user-images.githubusercontent.com/11398826/72826671-453a1380-3c47-11ea-9240-1a42c061b18a.png)

Is it possible to modify the width and alignment somehow?

**Comment by lautarobock** [comment]
did you figure out how to do it? @Oxyrus

**Comment by gihanmu** [comment]
Any workaround for this ?
