### ISSUE TITLE
Upgraded to angular version 9 and can't run and build application

### ISSUE THREAD

**Issue by NakedFool** [swimlane/ngx-charts#1370]
**Describe the bug**
I'm trying to upgrade my whole application to latest version of angular.

Can't run and also build my application due to error that @swimline/ngx-charts has missing dependency : @angular/cdk/portal

**To Reproduce**

Just upgrade ngx-charts and angular to latest versions and try to run.

**Screenshots**

![image](https://user-images.githubusercontent.com/18723426/74323650-2500fe80-4d86-11ea-8593-b22a251d3c8a.png)

 
**ngx-charts version**
    ngx-charts": "^13.0.2",

**Comment by lala81996** [comment]
Same problem here! I tried compiling in a project with Angular CLI V 8.3.23 & ngx-charts V 13.0.2 and got following:
`Module not found: Error: Can't resolve '@angular/cdk/portal' in 'C:\PATH\node_modules\@swimlane\ngx-charts\fesm2015'`

**Comment by marjan-georgiev** [comment]
Try installing the `@angular/cdk` package. It's a peer dependency of the project.

https://github.com/swimlane/ngx-charts/blob/master/projects/swimlane/ngx-charts/package.json#L39

**Comment by stifff94** [comment]
witch command i have to use to upgrade

**Comment by TheAhmadSharif** [comment]
> Try installing the `@angular/cdk` package. It's a peer dependency of the project.
> 
> https://github.com/swimlane/ngx-charts/blob/master/projects/swimlane/ngx-charts/package.json#L39

It worked to me. I just added this line ""@angular/cdk": "^9.2.0"," in dependencies and then write npm install

**Comment by Jcamposlozano** [comment]
A mi me funcion con este comando. npm install @angular/cdk --save

**Comment by muhammadibrar1** [comment]
You need to install @angular/cdk. Just run this command 'npm i @angular/cdk'

**Comment by sudarshansb143** [comment]
I was getting `Peer Dependency Error` while installing `@angular/cdk` then I matched the version of `@angular/cdk` and `@angular/common` it worked for me
