### ISSUE TITLE
Bar chart : Increase Y range beyond maximum and minimum by some margins

### ISSUE THREAD

**Issue by gopinathshiva** [swimlane/ngx-charts#138]
**I'm submitting a ...**  (check one with "x")
```
[ ] feature request
```

**Current behavior**
Y domain is limited to maximum and minimum

**Expected behavior**
Would be great if an input option is provided to component to increase Y range by certain %.

**Comment by marjan-georgiev** [comment]
Good idea. We'll add this post 3.0.0. PR welcome.

**Comment by marjan-georgiev** [comment]
This has already been added. Closing.
