### ISSUE TITLE
Broken with Angular 9.1

### ISSUE THREAD

**Issue by sebrojas14** [swimlane/ngx-charts#1397]
**Describe the bug**
Broken after Angular 9.1 upgrade

**Screenshots**
![image](https://user-images.githubusercontent.com/1771574/77683842-0c7c2a80-6f67-11ea-8757-993d1e0f10b3.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
13.0.2

**Comment by StefanKoenigMUC** [comment]
can confirm that.

**Comment by blogcraft** [comment]
Strange, it didn't happened to me.

Have you tried deleting node_modules?

**Comment by linjie997** [comment]
Angular 9.1 works for me
Try to delete @swimlane folder and run npm install once again

**Comment by StefanKoenigMUC** [comment]
indeed, helped for me.

**Comment by aacebo** [comment]
We updated to ng9.1 recently so this should be working now, can someone confirm?

**Comment by linjie997** [comment]
This has never been broken in the first place. My guess is that ivy compiler had something dirty and it was easily fixable by deleting @swimlane folder under node_modules and run `npm install` once again.
I have used v13.0.2 with Angular 9.1 without issues.
By the way, I have now updated to v13.0.3 and it seems to be working as before.
