### ISSUE TITLE
Add ability to scale bar chart based on time

### ISSUE THREAD

**Issue by elliott-davis** [swimlane/ngx-charts#141]
```
[x] feature request
```
Currently the area and line charts accept x-domain data on a time scale but the bar chart treats it like linear string data. It would be awesome to allow the bar charts to accept time based scaling data.

**Comment by marjan-georgiev** [comment]
How would that work? If the x axis is a time scale, how much time would each bar represent?

This is possible, but would require additional inputs, like defining the bar range. And if you are going to do that, it would probably be easier to just wrangle your data and use an ordinal scale with the existing bar charts.

**Comment by elliott-davis** [comment]
The way I have solved for this with D3 is to set the width of the bar equal to the total width of the chat divided by the total data-sets in the array. I suppose that assumes that each data-set has a uniform time distribution for each bar (which I think would be the case for most charts). 

A snippet from my D3 example:
```
this.xScale = d3.scaleTime().rangeRound([0, this.width]);
this.xScale.domain([data[0].time_bucket, data.slice(-1).pop().time_bucket]);
this.svg.selectAll('.converge')
      .data(data)
      .enter().append('g')
      .selectAll('.rekt')
      .data((d) => { return this.stack.keys(['success', 'failure'])(d); })
      .enter().append('g')
        .attr('class', (d) => { return `converge-${d.key}` })
        .attr('fill', (d) => { return this.color(d.key); })
      .selectAll('rect')
      .data((d) => { return d; })
      .enter().append('rect')
        .attr('y', (d) => { return this.yScale(d[1]); })
        .attr('x', (d) => { return this.xScale(d.data.time_bucket); })
        .attr('height', (d) => { return this.yScale(d[0]) - this.yScale(d[1]); })
        .attr('width', this.width / data.length)
        .attr('transform', `translate(-${this.margin.left}, 0)`);
```

**Comment by marjan-georgiev** [comment]
Right, but that's a bad assumption to make if you want the chart to work for all types of time data. What if I have two dates that are very close to each other? The bars would overlap in that case. 

To solve this, you would have to divide the domain into buckets, and then wrangle the data to calculate the values for each bar. The chart could handle this, but it requires an extra input - either number of buckets, or the span of a bucket.

**Comment by elliott-davis** [comment]
I don't think this is feasible for the generic use case. I'll close and just extend the BaseChartComponent to fit my needs. Thanks for the input!
