### ISSUE TITLE
Please, add [yScaleMax] property to Line & Bar combo chart component 

### ISSUE THREAD

**Issue by sungwoongpyeon** [swimlane/ngx-charts#1414]
Now, I'm using Line & Bar combo chart component and I want to make the same y scale value for both line and bar chart. Is there any way that I can add [yScaleMax] to Combo chart?  

I saw there is the [yScaleMax] property in the single line chart.

Thanks,

**Comment by tphat2616** [comment]
i have the same situation . Hope some one help us :))

**Comment by ecenigiz** [comment]
Hi, 
I also had the same problem of not making line and bar combo chart with the same scale values. And I couldn't solve it with set to [yScaleMax]. My solution is as follows

combo-chart.component.ts
  **@Input() yScaleMax;**

getYDomainLine(): any[] {
    const domain = [];

    for (const results of this.lineChart) {
      for (const d of results.series) {
        if (domain.indexOf(d.value) < 0) {
          domain.push(d.value);
        }
        if (d.min !== undefined) {
          if (domain.indexOf(d.min) < 0) {
            domain.push(d.min);
          }
        }
        if (d.max !== undefined) {
          if (domain.indexOf(d.max) < 0) {
            domain.push(d.max);
          }
        }
      }
    }

    let min = Math.min(...domain);
    const max = Math.max(...domain);
    if (this.yRightAxisScaleFactor) {
      const minMax = this.yRightAxisScaleFactor(min, max);
      return [Math.min(0, minMax.min), minMax.max];
    } else {
      min = Math.min(0, min);
      return [min, **this.yScaleMax**];
  }
  }

  getYDomain() {
    const values = this.results.map(d => d.value);
    const min = Math.min(0, ...values);
    **const max = Math.max(...values, this.yScaleMax);**
    if (this.yLeftAxisScaleFactor) {
      const minMax = this.yLeftAxisScaleFactor(min, max);
      return [Math.min(0, minMax.min), minMax.max];
    } else {
      return [min, max];
    }
  }
