### ISSUE TITLE
Error while building project : An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by pranavghate30** [swimlane/ngx-charts#1416]
**First of all Thank you for a great plugin, really appropriate it.**
I had an issue with 13.0.2 Version where I was getting  `Kind of undefined` as an error while trying prod build. 
So I checked for it and found a new version released. I Updated the project and got a new error as below.

**Error in Console**
`ERROR in node_modules/@swimlane/ngx-charts/lib/bar-chart/bar.component.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/legend/legend-entry.component.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(30,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(31,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/number-card/number-card.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.
`

Would really appreciate if I get solution on it 👍 

**ngx-charts version**
13.0.3
![ERROR IN BUILDING CHARTS](https://user-images.githubusercontent.com/16238828/79353005-22727f00-7f58-11ea-9088-8533ad68910d.jpg)

**Comment by pabloppizarro** [comment]
My team and I are having the same issue , waiting for any solution.

**Comment by antleypk** [comment]
my team and I are having same issue;
Issue was created from following this tutorial:https://medium.com/@swathisprasad/building-data-visualization-with-angular-and-ngx-charts-375942d49fd6

**Comment by vikre** [comment]
12.1.0 Works fine with angular 8 if you guys are running 8 :) Had the same problem installing latest 13.0.3, but downgrading to 12.1.0 did the trick for now.

**Comment by antleypk** [comment]
i re-installed everything. I went down a rabbit hole; but got it to work in the end. htanks friend/

**Comment by pranavghate30** [comment]
Can you guys help me get the Stable version for angular 7? as I am using 7 in my project.

**Comment by vikre** [comment]
@pranavghate30 Try specifying the version to be `11.2.0` - since in the changelog it says that >= 12 is angular 8, and >= 13 is angular 9.

**Comment by Hypercubed** [comment]
@pranavghate30 @pabloppizarro  @antleypk 
I created a new angular cli app, installed ngx-charts, and setup a basic visualization as shown here: https://medium.com/@swathisprasad/building-data-visualization-with-angular-and-ngx-charts-375942d49fd6

I am no able to repo this issues.  Does anyone have a broken example?

**Comment by Hypercubed** [comment]
Here is my demo created using the cli and follwing the medium post: https://github.com/Hypercubed/ngx-charts-demo

**Comment by Hypercubed** [comment]
I just republished 13.0.2 as 13.0.4. Please "upgrade" to 13.0.4 for angular versions <9. Otherwise please use 14.0.0.

**Comment by pranavghate30** [comment]
Hi, Guys Sorry to reply late.

@vikre I tried with version 11.2.0 and then trying **"ng build --prod"** and still I get below error
![image](https://user-images.githubusercontent.com/16238828/80722043-8ed6ac00-8b1c-11ea-89a9-a0206b110a77.png)

Here is my package.json
![image](https://user-images.githubusercontent.com/16238828/80722118-a57d0300-8b1c-11ea-9413-f1ea8d2b3479.png)

@Hypercubed Even with Version **13.0.4** I get below error when I do **ng build --prod**
![image](https://user-images.githubusercontent.com/16238828/80722334-e2e19080-8b1c-11ea-98e6-c18a1707a726.png)

I am sorry I am new to angular framework.

**Comment by pranavghate30** [comment]
I tried Increasing the Heap Size by running below command 
`node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod
`
and I got this error
![image](https://user-images.githubusercontent.com/16238828/80724404-6dc38a80-8b1f-11ea-9ff9-8fae30207eb0.png)

**Comment by Berkay-Cubuk** [comment]
Hi there 👋 
I'm getting the same issue. Here is my versions:
- Angular => 9
- ngx-charts => 14.0.0
- IDE => VsCode
- package-manager => npm 6.14.5
- node => 12.16.3
- OS => Windows 10

I followed the official example: [https://stackblitz.com/edit/swimlane-line-chart](https://stackblitz.com/edit/swimlane-line-chart)

There is the error:
```
ERROR in node_modules/@swimlane/ngx-charts/lib/bar-chart/bar.component.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/legend/legend-entry.component.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(30,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(31,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/number-card/number-card.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.

i ｢wdm｣: Failed to compile.
```

Have a good & healthy day ❤️

**Comment by mariomurrent-softwaresolutions** [comment]
Any updates on this? Not resolved for me until now

**Comment by Pawansharma0044** [comment]
getting the same error while i try to implement 
I had an issue with npm i @swimlane/ngx-graph., where I was getting Kind of undefined as an error while trying prod build.

Error in Console
ERROR in node_modules/@swimlane/ngx-charts/lib/bar-chart/bar.component.d.ts(39,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/legend/legend-entry.component.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(30,17): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/tooltip/tooltip.directive.d.ts(31,17): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(17,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(18,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/count/count.directive.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/common/svg-radial-gradient.component.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/number-card/number-card.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context. node_modules/@swimlane/ngx-charts/lib/pie-chart/pie-label.component.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.

![image](https://user-images.githubusercontent.com/21026696/147914510-bc23a0af-9399-48a2-b911-0c179a6fd5b1.png)

**Comment by Pawansharma0044** [comment]
does anyone have solution, for above error

**Comment by JStw** [comment]
I fixed it by installed the **@swimlane/ngx-graph** version **7.2.0** and also adding the **"skipLibCheck": true** in my tsconfig.json in the **compilerOptions**.

I'm using this one in a standalone project so I don't care about skipping the lib check however I don't recommend this solution for a serious/professional project.

I'm working with Angular 8 on this project.
