### ISSUE TITLE
Error: View Container not found! ngUpgrade needs to manually set this via setRootViewContainer or setGlobalRootViewContainer.

### ISSUE THREAD

**Issue by Franziskus1988** [swimlane/ngx-charts#1428]
**Describe the bug**
If have an angular 9 app running with ngUpgrade in usage. Since the upgrade from angular 8.2.14 to 9.1.2 and ngx-charts 12.0.1 to 14.0.0  the error
`Error: View Container not found! ngUpgrade needs to manually set this via setRootViewContainer or setGlobalRootViewContainer.`
is thrown, when hovering over a line chart. 

**Expected behavior**
The chart shall not throw an exception. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5774027/80489455-23e07600-8960-11ea-8e71-c2808444b9ce.png)

**ngx-charts version**
14.0.0

**Additional context**
If this is not a bug a description of how to fix this would be really helpful.

**Comment by tamsrud** [comment]
Having same error on a Angular 9.1.3 app, but not using ngUpgrade.
But the app is exported and used as a Web Component.

**Comment by scarlin-symphony** [comment]
I have the same issue as above when exporting as a web component

**Comment by jcaroyanez** [comment]
I'm also trying to export an application to web component and I get the same error

**Comment by findly-naveenpatil** [comment]
Any solution to this issue ? I have same issue when exporting as web component

**Comment by medi6** [comment]
Hi, after spending a little time on it, I've got a solution.

1/ inject TooltipService to your component
`import {TooltipService} from '@swimlane/ngx-charts';`
2/ In component's constructor add :
` private chartToolTipService : TooltipService,
    private viewContainerRef: ViewContainerRef`   
3/ set the ViewContainerRef in ngOnInit. You can use the ViewContainerRef of your component, but It's best to use your root ViewContainerRef because of superpositions errors. In my case (ngUpgrade) It's a little more complicated :
'this.chartToolTipService.injectionService.setRootViewContainer(this.parentContainer||this.coreServicesProvider.mainViewService.mainViewContainer||this.viewContainerRef);'

And it works.

**Comment by mvandenbrink** [comment]
Thanks @medi6 , this removes the error indeed. Working with a base component, it was enough to only pass the viewContainerRef.

```
import { TooltipService } from '@swimlane/ngx-charts';

export class BaseComponent implements OnChanges, OnInit {
...
  private chartToolTipService : TooltipService;
  readonly viewContainerRef: ViewContainerRef;

  constructor(
    private injectorObj: Injector,
  ) {
    this.chartToolTipService = this.injectorObj.get(TooltipService);
    this.viewContainerRef = this.injectorObj.get(ViewContainerRef);
  }

  ngOnInit(): void {
    this.chartToolTipService.injectionService.setRootViewContainer(this.viewContainerRef);
    ...
  }
  
  ...
}

export class MyChartComponent extends BaseComponent {
  constructor(
    public injector: Injector,
  ) {
    super(injector);
  }
}
```

**Comment by ChristianKohler** [comment]
Why was this issue closed @Franziskus1988? Was the issue fixed?

**Comment by sechel** [comment]
I still have this issue. Would appreciate a thorough fix.

**Comment by abijithjohn** [comment]
I'm still facing the issue. It would be great if anyone can help me to overcome the issue.

![image](https://user-images.githubusercontent.com/51698635/119023498-9e42c480-b9bf-11eb-8d23-886dab688aeb.png)
