### ISSUE TITLE
Question: How to change grid color / theme 

### ISSUE THREAD

**Issue by labsnoir** [swimlane/ngx-charts#1433]
I have a <ngx-charts-line-chart> in an angular application and an angular material dark theme, but the grid of the line chart remains white. A dark grey would look nicer but I dont't know how to change it.
The label font color of the chart could be changed by adding simply
`fill: white;`
to the css.

I guess I'm missing something very obvious - shouldn't the label font color and grid color adjust automatically to the angular theme? And if not: how can I change the grid color for a line chart?

**Comment by heyteacher** [comment]
Try this (with and without `!important`)

```
.ngx-charts .gridline-path {
    stroke: #455066 !important;
}
```

**Comment by labsnoir** [comment]
Thank you, this works (even without "!important"). I did try this before, but only directly in my own angular component.
The lines above work in my global scss file.

**Comment by btxtiger** [comment]
I needed 
```css
::ng-deep .ngx-charts .gridline-path {
    stroke: var(--gray-default-rgba) !important;
}
```
to get it working.
