### ISSUE TITLE
Angular 9 Error: Expecting instance of DOM Element

### ISSUE THREAD

**Issue by elmoyeldo** [swimlane/ngx-charts#1447]
**Describe the bug**
After Angular 9 Update, whenever mouse is hovered over the graph, getting the error:
Error: Expecting instance of DOM Element.

**Screenshots**
![image](https://user-images.githubusercontent.com/6438308/82516196-1149fe80-9b12-11ea-99b2-caa39ec11ea4.png)

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
14.0.0

**Additional context**
Getting same error in Chrome & Safari

**Comment by elmoyeldo** [comment]
The issue has resolved when I removed aot:true in angular.json.

**Comment by saidsoualhi** [comment]
I have also this issue and I don't want to remove the aot option from my angular.json, any solution for this ?

**Comment by elmoyeldo** [comment]
> I have also this issue and I don't want to remove the aot option from my angular.json, any solution for this ?

Need to disable the Ivy in tsconfig.app.json:

```
  "angularCompilerOptions": {
    "enableIvy": false
  }
```

**Comment by saidsoualhi** [comment]
> > I have also this issue and I don't want to remove the aot option from my angular.json, any solution for this ?
> 
> Need to disable the Ivy in tsconfig.app.json:
> 
> ```
>   "angularCompilerOptions": {
>     "enableIvy": false
>   }
> ```

Already disabled because we was having an issue with localize translation :/

**Comment by quanghv991** [comment]
Same issue after upgrade to angular 10

**Comment by saidsoualhi** [comment]
Any news about this issue?

**Comment by samy-blake** [comment]
same error on version 16.0.0 :/

**Comment by fahadjabbar8** [comment]
any update on this

**Comment by sanchito59** [comment]
Bump. Still having this issue with the latest version of this package and Angular `v 10.1.6` and rxjs `v 6.6.7`, @elmoyeldo's solutions don't work for me either.
