### ISSUE TITLE
RealTime data: Display is incorrect when splicing series at high frequency (twice per second)

### ISSUE THREAD

**Issue by thibserot** [swimlane/ngx-charts#1461]
**Describe the bug**
I want to display some real time data which are refresh several time per seconds (let's say twice per seconds). When I keep all data, the display is perfect and accurate.

For performance and display constraint, I only want to keep a fix number of points since the graph can be displayed during dozens of minutes and it becomes pretty unresponsive to display a graph with several thousands of points. In order to keep the number of points constant, I apply a splice(1) on my series. When I do, the graph start to behave erratic and the y axis isn't render properly: The curve starts to shrink. When I stop adding data point, the curve is displayed properly.

Bug is present at least on Chrome and Firefox on Ubuntu

**To Reproduce**

Append points every 1/10th of second and keep only the last N points in your curve

```
data: any[] = [
  {
    "name": "Germany",
    "series": [
    ]
  },

    this.data[0].series.push({
        name: this.index,
        value: this.index % 2
      });
    this.index ++;
    this.data[0].series = this.data[0].series.splice(1);
    this.data = this.data.splice(0);
```

This is the case which doesn't work (when I apply splices): https://plnkr.co/edit/ZQFa1zmF3YYkZgBi
This is the case where the curve is properly displayed when i keep all points: https://plnkr.co/edit/ZB0UGX228EBG5GXq

The only difference between those two is line 79 which is commented out.

If I decrease the refresh frequency to once per second, the graph is displayed properly (but then the display isn't very nice as you see the new point coming every second and I want near realtime display)

**Expected behavior**
Graph should be displayed properly even when I splice the serie

**Screenshots**
No splice:
![image](https://user-images.githubusercontent.com/386572/84497585-70a2c500-acf2-11ea-9d71-89566dc819da.png)

Splice:
![image](https://user-images.githubusercontent.com/386572/84497650-916b1a80-acf2-11ea-9dfa-d9a8026ff075.png)

**Demo**

This is the case which doesn't work (when I apply splices): https://plnkr.co/edit/ZQFa1zmF3YYkZgBi
This is the case where the curve is properly displayed when i keep all points: https://plnkr.co/edit/ZB0UGX228EBG5GXq

**ngx-charts version**

All

**Additional context**

I tried to recreate the data object completely between each interactions but it makes the display even worse

**Comment by Zoraiyo** [comment]
Hello, 

I think this shrinking process depends on the slow or the delayed animation. The animation resets because of the new data before it has finished. I don't have a real solution for this, but I found a work around. If you disable the animation, your graph will look normal: [Plunker](https://plnkr.co/edit/sIsiEZYhU1M5aWpf) 

**Workaround**
Add `[animations]="false"` to your html.

**Comment by thibserot** [comment]
Hello,
Thanks for the workaround! I thought I had tried this flag...probably not properly.

Will resolve the issue as it seems the proper way to do it.
