### ISSUE TITLE
Math.random() usage is giving "Insecure-Randomness" vulnerability during security scan by Fortify

### ISSUE THREAD

**Issue by KrishnamoorthySundar** [swimlane/ngx-charts#1480]
Scan the whole code-base using Fortify 20 version.

**Comment by bbarry** [comment]
Why would it matter?

`Math.random()` is used in 2 places in this repository:

1. in the process of generating mock data in the demo application (src/app/app.component.ts and src/app/data.ts)
2. to generate ids for chart clipping paths (projects/swimlane/ngx-charts/src/lib/utils/id.ts)

I'd argue #2 shouldn't use random but simply a global increasing integer every time it is called, but in neither case does the fact that Math.random having security weaknesses apply to anything.

**Comment by KrishnamoorthySundar** [comment]
Thanks @bbarry for your time.
Clarity has been provided that this is not a security vulnerability. Hence, closing the issue. Thanks again.
