### ISSUE TITLE
 node_modules/ngx-echarts/lib/ngx-echarts.module.d.ts:5:47 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by LuoSven** [swimlane/ngx-charts#1481]
I use ngx-echarts^5.1.0  in ng 10.0.4
It's happen when ng server 
![image](https://user-images.githubusercontent.com/14365712/88998476-b5c39a80-d324-11ea-87c9-81e6c412318c.png)
5.1.0 worked successfully  in  ng  8.3.25 .

**Comment by linjie997** [comment]
This is likely because Angular 10 requires a generic with the ModuleWithProvider.
I suggest you to try this to fix the issue:
- Delete `@swimlane` folder under node_modules and `package-lock.json`
- Add under `angular.json`, under scripts, ngcc as postinstall
    ```
    {
      "scripts": {
        "postinstall": "ngcc"
      }
    }
    ```
    For more information see: https://angular.io/guide/ivy#ivy-and-universalapp-shell
- Run npm install again

**Comment by paulrobello** [comment]
Added postinstall ngcc and removed package-lock.json file and removed and reinstalled entire node_modules folder. 
Still get same error.

**Comment by paulrobello** [comment]
I got ng serve to work by removing the ngcc_bak files from the ngx-echarts folder and subfolders so it would recompile the lib.
The ngcc that runs postinstall for some reason does not do the ModuleWithProvider generic migration then when you run ng serve it see's the bak files and refuses to recompile the lib properly.

**Comment by linjie997** [comment]
> I got ng serve to work by removing the ngcc_bak files from the ngx-echarts folder and subfolders so it would recompile the lib.
> The ngcc that runs postinstall for some reason does not do the ModuleWithProvider generic migration then when you run ng serve it see's the bak files and refuses to recompile the lib properly.

Happy to know it helped!

**Comment by xtealer** [comment]
> > I got ng serve to work by removing the ngcc_bak files from the ngx-echarts folder and subfolders so it would recompile the lib.
> > The ngcc that runs postinstall for some reason does not do the ModuleWithProvider generic migration then when you run ng serve it see's the bak files and refuses to recompile the lib properly.
> 
> Happy to know it helped!

Having the same issue, could not get it working with the steps provides.

I added the script as suggested by angular documentation to package.json and deleted package-lock.json before re installing

**Comment by fchiumeo** [comment]
> ngx-echarts

I think you are in the wrong repo
I think this correct repo = https://github.com/xieziyu/ngx-echarts
https://github.com/xieziyu/ngx-echarts/issues/250

**Comment by xtealer** [comment]
Yeah I just noticed, thanks for the correction!
