### ISSUE TITLE
[Typo] ngx-charts-circle-ceries

### ISSUE THREAD

**Issue by kyleledbetter** [swimlane/ngx-charts#149]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

https://github.com/swimlane/ngx-charts/search?utf8=%E2%9C%93&q=ceries

`ngx-charts-circle-ceries` should be `ngx-charts-circle-series` right?

* **ngx-charts version:** 3.0.5

**Comment by amcdnl** [comment]
@kyleledbetter - can u pr that?
