### ISSUE TITLE
npm install error!

### ISSUE THREAD

**Issue by NixesGithub** [swimlane/ngx-charts#1535]
i cant install the library!

$ npm install @swimlane/ngx-charts --save
npm ERR! Unexpected token
npm ERR!  in JSON at position 19737 while parsing '{"maintainers":[{"email":"mike@ocks.org"'

npm ERR! A complete log of this run can be found in:

LOGS:
...
1 silly saveTree +-- typescript@4.0.3
51 silly saveTree `-- zone.js@0.10.3
52 verbose stack SyntaxError: Unexpected token
52 verbose stack  in JSON at position 19737 while parsing '{"maintainers":[{"email":"mike@ocks.org"'
52 verbose stack     at JSON.parse (<anonymous>)
52 verbose stack     at parseJson (C:\Users\gkolberg\Desktop\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
52 verbose stack     at C:\Users\gkolberg\Desktop\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
52 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
53 verbose cwd C:\Workspace\sib-reload-ui
54 verbose Windows_NT 10.0.18363
55 verbose argv "C:\\Users\\gkolberg\\Desktop\\nodejs\\node.exe" "C:\\Users\\gkolberg\\Desktop\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@swimlane/ngx-charts" "--save"
56 verbose node v12.18.3
57 verbose npm  v6.14.6
58 error Unexpected token
58 error  in JSON at position 19737 while parsing '{"maintainers":[{"email":"mike@ocks.org"'
59 verbose exit [ 1, true ]

**Comment by SandeepBalachandran** [comment]
I have installed  successfully  recently. Is this issue still exists in your side?

**Comment by NixesGithub** [comment]
i didn't prove it again. I can't remember what I reported. Could you send
me a screenshot please?

**Comment by SandeepBalachandran** [comment]
What kind of screenshot are you looking for?
