### ISSUE TITLE
Support Angular 11

### ISSUE THREAD

**Issue by Artik-Man** [swimlane/ngx-charts#1540]
```
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "~9.1.1" (ext
ended), would install "11.0.0").
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/common" (requires "~9.1.1" (extende
d), would install "11.0.0").
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/core" (requires "~9.1.1" (extended)
, would install "11.0.0").
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/forms" (requires "~9.1.1" (extended
), would install "11.0.0").
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/platform-browser" (requires "~9.1.1
" (extended), would install "11.0.0").
Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires
 "~9.1.1" (extended), would install "11.0.0").
```
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the `--force` option to ignore incompatible peer dependencies and instead address these warnings later.

**Comment by Tea-Ice** [comment]
Once again I can't upgrade our project because of this package. Maybe we'll get the update on this within the next 12 months, but I doubt it.

**Comment by acoroian** [comment]
I need this as well. I guess the fastest way to do that would be to contribute it if possible

**Comment by Tea-Ice** [comment]
@acoroian Doubtful, last time someone just upped the peer dependency versions and made a PR for the team to review. Took 3 months for it to be merged in by the @swimlane team.

**Comment by Tea-Ice** [comment]
I see that a PR was merged in that gave it Angular 11 support, but still no release for some reason. @marjan-georgiev Any chance for the release soon?

**Comment by jzzfs** [comment]
I'm waiting on the release too but in the meantime I'm using the slightly unsafe
```
 npm install --save https://github.com/swimlane/ngx-charts/tarball/master
```
and it works with angular 11.

**Comment by gexclaude** [comment]
According to the https://swimlane.gitbook.io/ngx-charts/changelog version 17.0.0 is out and supports angular 11
