### ISSUE TITLE
Area Chart color turns black when Gradient is On and X & Y axis are off

### ISSUE THREAD

**Issue by blogcraft** [swimlane/ngx-charts#1562]
**Describe the bug**
I wanted an area chart with nothing except the graph. So that means, no labels, no axis, no titles, no legend, etc. 

But when I turn off both axis, the gradient turns the graph black.

If you resize anything it gets painted again (except the timeline if you have it activated)

**Expected behavior**
Just maintain the gradient no matter what.

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 
https://stackblitz.com/edit/swimlane-area-chart-mehq3x?embed=1&file=app/app.component.ts

**ngx-charts version**
16.0.0

**Comment by egorkel-da14** [comment]
Have the same issue. As a workaround I extended directive from this issue https://github.com/swimlane/ngx-charts/issues/514

```typescript
@Directive({
  selector: '[appNgxChartsZeroMargin]'
})
export class NgxChartsZeroMarginDirective implements AfterViewInit {
  constructor(@Optional() @Self() private areaChart: AreaChartComponent) {
    if (this.areaChart) {
      this.areaChart.margin = [0, 0, 0, 0];
    }
  }

  public ngAfterViewInit(): void {
    setTimeout(() => {
      this.areaChart?.update();
    });
  }
}
```

**Comment by bobbyg603** [comment]
We have published a mirrored version ngx-charts that should fix this issue via [@bugsplat/ngx-charts](https://www.npmjs.com/package/@bugsplat/ngx-charts) and opened PR #1637
