### ISSUE TITLE
Timeline not working on version 17.0.0

### ISSUE THREAD

**Issue by MihailTrunov** [swimlane/ngx-charts#1575]
**Describe the bug**
For line or area charts timeline does not work

**To Reproduce**
1. Create a line chart using version 17.0.0. Use temporal data type for X axis.
2. Set "timeline" to "true"
3. as chart is rendered interact with timeline to zoom in on particular area of the chart
4. The appearance of the main chart does not change

**Expected behavior**
The main area of the chart should update accordingly

**ngx-charts version**
"@swimlane/ngx-charts": "17.0.0"

**Comment by MMLino** [comment]
Hello,
I have the same issue. In the latest version (v17.0.0) the timeline isn't working as expected.
Here a sample stackblitz project to replicate it: https://angular11-swimlane-linechart-v17.stackblitz.io/

**Comment by westlakem** [comment]
Same issue

**Comment by Zoraiyo** [comment]
Hello

I looked a bit into it and I found a solution. See PR #1593. 
Problem were the changes that were done in #1555. There was a change in the event handling of the d3-brush on the timeline. 
The event property of the 'brush end' event   must be `{selection}` instead of `{d3selection}`

**Comment by laksan1** [comment]
I have a project with charts in which there is a timeline, but it doesn't work. Please,  tell me when it will be fixed ?

**Comment by Zoraiyo** [comment]
Hi @laksan1, 
I have a project where I want to use that feature too. I can't tell you how often those pull requests are merged. If you look at the commit history, it is unfortunately very irregular. But I hope the merge and the release of hotfix 17.0.2 is done soon. 

@marjan-georgiev could you please look into it? 
Thanks a lot

**Comment by laksan1** [comment]
Thanks a lot for your feedback. Any news about the timeline?

> Hi @laksan1,
> I have a project where I want to use that feature too. I can't tell you how often those pull requests are merged. If you look at the commit history, it is unfortunately very irregular. But I hope the merge and the release of hotfix 17.0.2 is done soon.
> 
> @marjan-georgiev could you please look into it?
> Thanks a lot
Thanks a lot for your feedback. Any news about the timeline?

**Comment by ecospecifier** [comment]
![image](https://user-images.githubusercontent.com/71065956/116806701-16d80300-ab2f-11eb-887e-cf5ba403c098.png)

**Comment by Zoraiyo** [comment]
Yeah, it's a pity that this small bugfix is not integrated. The timeline is such a small feature, but it adds a much value for the usability. 

@haeminn, @nelsonGuti, @Hypercubed Could somebody please look into it? 
Thanks a lot

**Comment by ozkoidi** [comment]
Good to see this issue assigned to someone :) This bug is the only thing preventing us from upgrading to v17

**Comment by Skuriles** [comment]
Should be fixed with version 18 (at least it is on my side)
