### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'd3-shape'. Version 18.0.0

### ISSUE THREAD

**Issue by jlquijada** [swimlane/ngx-charts#1620]
**Describe the bug**
I updated my project to use the version 18.0.0, and now I get this build error:

√ Browser application bundle generation complete.

Error: node_modules/@swimlane/ngx-charts/lib/area-chart/area-chart.component.d.ts:2:29 - error TS7016: Could not find a declaration file for module 'd3-shape'. './node_modules/d3-shape/dist/d3-shape.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/d3-shape` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-shape';`

2 import { CurveLinear } from 'd3-shape';

**ngx-charts version**
18.0.0

**Additional context**
when I revert to version 17.0.1, everything works again.

**Comment by Hypercubed** [comment]
Fixed in v18.0.1

**Comment by jlquijada** [comment]
Thank you very much!

**Comment by carlosascari** [comment]
Well v20 has the same issue, using v18.0.1 fixed it
