### ISSUE TITLE
Plotted stacked area line chart with dates as x-coordinates throws an error;

### ISSUE THREAD

**Issue by weirdyang** [swimlane/ngx-charts#1634]
**Describe the bug**
I wish to plot this [set](https://gist.githubusercontent.com/weirdyang/556a4cfcf010738ed894b1dc712a2c4a/raw/726e1b664826e046eb7f5f5596e815d1631543bd/dump.json) of data.

Using the `insertedTimestamp` property as the series name for each series in the multi series
Here is the plunkr; https://plnkr.co/edit/IBdF2S8e8i4AkASR

```
  multi: MultiSeries = [
    {
      name: 'Green',
      series: []
    },
    {
      name: 'Amber',
      series: []
    },
    {
      name: 'Red',
      series: []
    }
  ]
```

```
        const multi = [
          {
            name: 'Green',
            series: []
          },
          {
            name: 'Amber',
            series: []
          },
          {
            name: 'Red',
            series: []
          }
        ] as MultiSeries;
        for (const signal of items) {

          const { greenSeries, redSeries, amberSeries } = this.constructEntry(signal);
          console.log(greenSeries, redSeries, amberSeries, 'testing!!')
          multi.find(x => x.name === "Green")?.series.push(greenSeries);
          multi.find(x => x.name === "Red")?.series.push(redSeries);
          multi.find(x => x.name === "Amber")?.series.push(amberSeries);
        }
        return multi;
```
```
  constructEntry(signal: SignalInfo) {
    let green = signal.green === 0 ? 0 : 1;
    let red = signal.red === 0 ? 0 : 1;
    let amber = signal.amber === 0 ? 0 : 1;
    let total = green + red + amber;
    let date = signal.insertedTimestamp //<<-this line will cause an error
    let greenSeries = {
      name: date,
      value: signal.green === 0 ? 0 : +(1 / total)
    };
    let redSeries = {
      name: date,
      value: signal.red === 0 ? 0 : +(1 / total)
    };
    let amberSeries = {
      name: date,
      value: signal.amber === 0 ? 0 : +(1 / total)
    };
    return {
      greenSeries,
      redSeries,
      amberSeries
    }
  }
```
When I use the `insertedTimestamp` property;

Sometimes it works:

![image](https://user-images.githubusercontent.com/25576022/121246496-ce50f980-c8d3-11eb-91a1-8ee5dca74f7e.png)

Sometimes it throws this error:
```
attrTween.js:5 Error: <path> attribute d: Expected number, "…3.7253436042904,NaNL296.16184717…".
```
![image](https://user-images.githubusercontent.com/25576022/121246660-fd676b00-c8d3-11eb-91a7-92c13ebba81e.png)

If I use the `id` property, it works fine;

![image](https://user-images.githubusercontent.com/25576022/121246157-6ef2e980-c8d3-11eb-867a-ad54675d3153.png)

Here is the repro link:
https://plnkr.co/edit/IBdF2S8e8i4AkASR

**Comment by weirdyang** [comment]
```
  constructEntry(signal: SignalInfo) {
    let green = signal.green === 0 ? 0 : 1;
    let red = signal.red === 0 ? 0 : 1;
    let amber = signal.amber === 0 ? 0 : 1;
    let total = green + red + amber;
    let date = new Date(signal.insertedTimestamp);
    let greenSeries = {
      name: date,
      value: signal.green === 0 ? 0 : +(1 / total)
    };
    let redSeries = {
      name: date,
      value: signal.red === 0 ? 0 : +(1 / total)
    };
    let amberSeries = {
      name: date,
      value: signal.amber === 0 ? 0 : +(1 / total)
    };
    return {
      greenSeries,
      redSeries,
      amberSeries
    }
  }
```
I've also tried to cast each data to a javascript data object, but it still throws an error.

**Comment by abhinabamitra** [comment]
Hi, @weirdyang , been facing the same issue, where I was trying to implement stacked area chart where the data updates every 30 seconds, the chart is loading when the data is initiated but the graph disappears when data updates, and the above mentioned  error is shown (i.e., `Error: <path> attribute d: Expected number, "…9.0037822674639,NaNL259.26173299…".`)

As you mentioned,

> If I use the id property, it works fine; 

can you please elaborate if you obtained a successful result, or on what is the `id` attribute?
Thanks in advance.

**Comment by weirdyang** [comment]
The data is in my comment. Id is an integer
