### ISSUE TITLE
Bar chart not working after upgrading to Angular v12.2.4

### ISSUE THREAD

**Issue by bobanmarkovic** [swimlane/ngx-charts#1674]
**Describe the bug**
After upgrading to Angular v12.2.4, Bar Chart stopped working with error:

```
core.js:6479 ERROR TypeError: node.transition is not a function
    at BarComponent.updatePathEl (swimlane-ngx-charts.js:8473)
    at BarComponent.update (swimlane-ngx-charts.js:8462)
    at timer (zone.js:2561)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at invokeTask (zone.js:487)
    at ZoneTask.invoke (zone.js:476)
    at data.args.<computed> (zone.js:2541)
```

This problem is visible only when animations are on - if I set [animations]="false" error is not happening.

With Angular v12.2.0 everything works fine (even with [animations]="true").

**To Reproduce**
1. Add Vertical Bar chart
2. Use Angular v12.2.4
3. Don't set animations property or set it to true

**Expected behavior**
There is no console error and chart is working

**Screenshots**
![error](https://user-images.githubusercontent.com/67064925/131972943-89aba2ed-b514-499f-bbc6-6230012e4aa0.png)

**ngx-charts version**
Tried v18.0.1 and v19.0.1

**Comment by iSachin007** [comment]
Getting same ERROR in "@angular/cli": "^10.2.0", for version 19

**Comment by AleonFS** [comment]
Same ERROR for another component. Probably is not caused by the upgrade to Angular v12.x.x because i use v11

![image](https://user-images.githubusercontent.com/28017467/132904788-c73b39e3-222b-4e13-9ba6-848155f21f62.png)

ngx-chart versions that i tried:

- ^18.0.1
- 18.0.0
- 17.0.1

Probably is caused by internal dependency?

**Comment by AleonFS** [comment]
In my case is solved changing "d3-selection" version from ^1.1.0 to ^2.0.0

**Comment by FadiNouh1** [comment]
Installation of latest versions of d3 libraries will solve the issue 

`npm install d3 d3-array d3-brush d3-color d3-force d3-format d3-hierarchy d3-interpolate d3-scale d3-selection d3-shape d3-time-format --save-dev`

**Comment by jarodsmk** [comment]
While adding the latest versions of the dependencies manually fixes it, the targeted versions of these peer-dependencies should be corrected in the @swimlane/ngx-charts package itself
