### ISSUE TITLE
Chart rendering problems in PrimeNG tab

### ISSUE THREAD

**Issue by matteson** [swimlane/ngx-charts#170]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I'm using PrimeNG tab components. A chart is in one tab. 
<img width="533" alt="screen shot 2017-01-20 at 2 38 47 pm" src="https://cloud.githubusercontent.com/assets/585221/22163198/dcc71a14-df1f-11e6-902b-038327039b62.png">
I switch to a different tab and make a change that results in a change to the data being plotted through a call to a server. I return to the tab with the charts, and the charts are not rendered.
<img width="482" alt="screen shot 2017-01-20 at 2 39 00 pm" src="https://cloud.githubusercontent.com/assets/585221/22163199/dcca9612-df1f-11e6-942b-55bc5cbbdd7a.png">
Either when I do a resize of the browser, or directly call the update() method on the LineChartComponent, the plot renders without its y axis.
<img width="522" alt="screen shot 2017-01-20 at 2 39 05 pm" src="https://cloud.githubusercontent.com/assets/585221/22163197/dcc6d6da-df1f-11e6-899d-23ca469d6646.png">

**Expected behavior**

Ideally the chart would be rendered when I return to the other tab.
It would also be acceptable if calling the update() method rendered a chart with the y axis as it originally was. 

**Reproduction of the problem**

I've not yet been able to produce a minimally working example. I've changed the series being plotted under the following conditions for the container wrapping the chart:
- [style.hidden] = true
- *ngIf = false

I have not yet tried:
- chart in ng-content
- Data being updated through a subscription on an observable

I could try the last two things if for some reason you think that's the likely cause. But, other than that I'm blocked on investigating the underlying cause.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OSX, Webstorm, NPM, Webpack Dev Server (via angular-cli beta 25.5)

* **ngx-charts version:** 3.1.2

* **Angular version:** 2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.2

**Comment by marjan-georgiev** [comment]
Could you set up a plunker or a github repo where this is reproducible please? Never worked with PrimeNG before so I'd like to investigate.

**Comment by matteson** [comment]
Repro: https://github.com/matteson/ngx-charts-view-bug-repro

In building the reproduction, I developed some more insight. The bug is driven by having an undefined view. When the tab with the chart is hidden, the chart gets mangled when the data is updated.

Coming back to the tab with the chart, a call to update() seems to be required for it to render. Unfortunately, the y-axis doesn't get fixed.

**Comment by marjan-georgiev** [comment]
Thanks! The problem here is that switching tabs in PrimeNG sets `display: none` to the tab with the chart. The chart measures its parent container dimensions in order to resize itself to fit the parent on every update. 
But when you change the data from the other tab and you trigger the update, the chart's parent container has a `display: none` CSS, so its dimensions can not be measured. If PrimeNG used a different way of hiding the tabs (either `*ngIf` or the `visibility` css property), it should be working.

To work around this, I modified the chart to keep its previous dimensions if the new ones can not be measured. This is in master and will come with the next release.

Alternatively, you can use fixed dimensions by defining the `view` property.

**Comment by amcdnl** [comment]
@marjan-georgiev - Implement something like this -> https://github.com/swimlane/ngx-datatable/blob/master/src/directives/visibility.directive.ts

**Comment by amcdnl** [comment]
Fixed :)

**Comment by mareknovotny** [comment]
it seems a bit broken for pie chart when I don't specify view attribute even I don't have it in hiding container.
