### ISSUE TITLE
support Angular 12

### ISSUE THREAD

**Issue by HDaghash** [swimlane/ngx-charts#1705]
**Is your feature request related to a problem? Please describe.**
Support Angular 12
**Describe the solution you'd like**
upgrading to angular 12 show error:

 Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "7.x || 8.x || 9.x" (extended), would install "12.2.13").

**Comment by ehealthexperts-rk** [comment]
Please update ngx-charts. The current version is 19.

Even version 16 did already support angular >= 10.
```"peerDependencies": {
    "@angular/animations": ">=10.0.0",
    "@angular/cdk": ">=10.0.0",
    "@angular/core": ">=10.0.0",
    "@angular/common": ">=10.0.0",
    "@angular/forms": ">=10.0.0",
    "@angular/platform-browser": ">=10.0.0",
    "@angular/platform-browser-dynamic": ">=10.0.0",
    "rxjs": "6.x"
  }
  ```

**Comment by marjan-georgiev** [comment]
Latest version of ngx-charts supports angular 12
