### ISSUE TITLE
could you upgrade npm to the latest code release version please? Thanks

### ISSUE THREAD

**Issue by vladimir-ivanov** [swimlane/ngx-charts#175]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
The npm package is up to date with the latest code release, which is 3.1.2. 

As for the new features in master, we will add a couple more fixed and release 3.2.0.
