### ISSUE TITLE
Unable to resolve dependency tree after v14 release of Angular

### ISSUE THREAD

**Issue by miguellira** [swimlane/ngx-charts#1757]
**Describe the bug**
Now that Angular v14 is out and all corresponding components have been bumped, ngx-charts fails to properly install on a v13 CLI built app.

**To Reproduce**
1. Download the latest v13 Angular CLI (v13.3.7 as of this post)
2. Create a new Angular application using `ng new`
3. Try to install the latest ngx-charts (v20.1.0 as of this post)
4. An npm error is throw because of incompatibility with v14 of @angular/common and/or @angular/cdk

**Expected behavior**
The npm package installs successfully on a v13 Angular app

**Screenshots**

**Demo**
Provide an online demo (stackblitz, codesandbox, or similar) where the issue can be reproduced 

**ngx-charts version**
20.1.0

**Additional context**
Below is the error you will get:
```console
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ngx-charts-test@0.0.0
npm ERR! Found: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.3.0" from the root project
npm ERR!   peer @angular/common@">=12.0.0" from @swimlane/ngx-charts@20.1.0
npm ERR!   node_modules/@swimlane/ngx-charts
npm ERR!     @swimlane/ngx-charts@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.0.0
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@">=12.0.0" from @swimlane/ngx-charts@20.1.0
npm ERR!   node_modules/@swimlane/ngx-charts
npm ERR!     @swimlane/ngx-charts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Workaround**
For now I have specified an override for the `@angular/cdk` to ensure the latest v13 of this transient dependency is used during an `npm install`
```json
  "overrides": {
    "@angular/cdk": "13.3.9"
  }
```

**Comment by miguellira** [comment]
@leoffx  Have you tried my suggested workaround? Pinning the transient dependency to a version that is compatible with v13? Your CI/CD may require a version of npm that supports the overrides setting

**Comment by leoffx** [comment]
@miguellira I did, but I was getting a different error from 'npm ci' saying that `package.json` and `package-lock.json` were diverging. In the end I changed `npm ci` to `npm i`, which is unfortunate but it works for now. Thank you so much!

**Comment by Hypercubed** [comment]
For now running with `legacy-peer-deps` is the only option.  Consider adding a .npmrc file to your repo like this: https://github.com/swimlane/ngx-charts/blob/master/.npmrc
