### ISSUE TITLE
Unable to serve using Angular 14

### ISSUE THREAD

**Issue by bryanrideshark** [swimlane/ngx-charts#1762]
**Describe the bug**

When doing ng serve on Angular 14, the following error is reported.

```

Warning: node_modules\@swimlane\ngx-charts\fesm2015\swimlane-ngx-charts.mjs depends on 'clone-deep'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

./node_modules/clone-deep/utils.js:11:0-38 - Error: Cannot statically analyse 'require(…, …)' in line 11

./node_modules/clone-deep/utils.js:13:0-33 - Error: Cannot statically analyse 'require(…, …)' in line 13

./node_modules/clone-deep/utils.js:15:0-28 - Error: Cannot statically analyse 'require(…, …)' in line 15

```

This error only appeared after upgrading to Angular 14.

I've checked the source - clone-deep is only used once, by one chart type. Would it make sense to get rid of this dependency, and just write a custom clone function? It would be faster, as well as making it possible to upgrade.

**ngx-charts version**
20.1.0

**Comment by Hypercubed** [comment]
Hi everyone... I understand your concerns.  We would love to upgrade but, at this moment, we're not in a position to consume Angular modules beyond v12.  We will as soon as possible.

**Comment by JoshuaWalsh** [comment]
For anyone else encountering this issue, a workaround is to add `unlazy-loader` to your Webpack configuration.

**Comment by Majed93** [comment]
Workaround for me was 
`npm install clone-deep --save`
