### ISSUE TITLE
Bundle size not reduced when only using one module

### ISSUE THREAD

**Issue by ge65cer** [swimlane/ngx-charts#1765]
**Describe the bug**
The bundle size of this project is quite big (60 KB gzipped). Importing only certain modules does not reduce the bundle size.
This was already [marked as fixed in #699](https://github.com/swimlane/ngx-charts/issues/699#issuecomment-583588652), but since then multiple users commented that the issue persists.
An analysis over at [bundlephobia](https://bundlephobia.com/package/@swimlane/ngx-charts@20.1.0) seems to confirm this issue, all exported modules have the same size (136.5 kB).

**To Reproduce**
1. Create a new Angular project with ngx-charts as dependency
2. Import the whole library `import { NgxChartsModule } from '@swimlane/ngx-charts';` in a component
3. Use webpack-bundle-analyzer to check the bundle size of the dependency
4. Import only a single module like so `import { LineChartModule } from '@swimlane/ngx-charts';`
5. Again use webpack-bundle-analyzer to check the bundle size
6. Observe that it has not changed

**Expected behavior**
The bundle size should have drastically reduced if a user only imports a single chart module (Angular Ivy should be able to tree-shake the unused modules of this library).

**Screenshots**
<img width="300" alt="Screenshot 2022-07-01 at 16 26 59" src="https://user-images.githubusercontent.com/102237363/176913806-f5d91f3d-9531-4587-beaf-77fec5d03dea.png">

**Versions**
ngx-charts: 20.1.0
angular: 13.3.11

**Comment by billyjov** [comment]
Same issue here

**Comment by Hypercubed** [comment]
We don't currently support SCAM in this library.  We hope to in the future.

**Comment by ge65cer** [comment]
@Hypercubed Is this a 'won't fix' or can we leave the issue open if it's planned to be introduced? 🙂
