### ISSUE TITLE
Series Data Compile Error

### ISSUE THREAD

**Issue by ccocker** [swimlane/ngx-charts#1768]
**Describe the bug**
Hi guys, I am new to ngx-charts and have installed it and is working in my Angular 13 project.

When i do a simple graph all works fine, however when i try to add in a graph with grouped series, I get a compile error in the browser console and the graph displays but with no data.

**To Reproduce**
https://stackblitz.com/edit/angular-ivy-554x7e?file=src/app/app.component.ts
`    
### Simple Data Template - Working
<ngx-charts-bar-vertical
      [view]="[1000, 200]"
      [results]="simpleData"
      [xAxisLabel]="'Category'"
      [yAxisLabel]="'Frequency'"
      [legend]="true"
      [legendTitle]="'Odd/Even Analysis'"
      [showXAxisLabel]="true"
      [showYAxisLabel]="true"
      [xAxis]="true"
      [yAxis]="true"
      [gradient]="true"
    >
    </ngx-charts-bar-vertical>

### Series Data Template - Not Working
    <ngx-charts-bar-vertical
      [view]="[1000, 200]"
      [results]="seriesData"
      [xAxisLabel]="'Category'"
      [yAxisLabel]="'Frequency'"
      [legend]="true"
      [legendTitle]="'Country Analysis'"
      [showXAxisLabel]="true"
      [showYAxisLabel]="true"
      [xAxis]="true"
      [yAxis]="true"
      [gradient]="true"
    >
    </ngx-charts-bar-vertical>`

`
### Simple Data Object - Working
simpleData = [
    { name: '3 Odd', value: 277 },
    { name: '3 Even', value: 256 },
    { name: '4 Odd', value: 208 },
    { name: '2 Even', value: 229 },
    { name: '2 Odd', value: 188 },
    { name: '4 Even', value: 193 },
    { name: '5 Odd', value: 75 },
    { name: '1 Even', value: 69 },
    { name: '1 Odd', value: 61 },
    { name: '5 Even', value: 65 },
    { name: '6 Odd', value: 10 },
    { name: '0 Even', value: 7 },
    { name: '0 Odd', value: 8 },
    { name: '6 Even', value: 8 },
  ];
### Series Data Object - Not Working
  seriesData = [
    {
      name: 'Germany',
      series: [
        {
          name: 'Predicted',
          value: 277,
          extra: {
            code: 'de',
          },
        },
        {
          name: 'Actual',
          value: 256,
          extra: {
            code: 'de',
          },
        },
      ],
    },
    {
      name: 'United States',
      series: [
        {
          name: 'Predicted',
          value: 208,
          extra: {
            code: 'us',
          },
        },
        {
          name: 'Actual',
          value: 229,
          extra: {
            code: 'us',
          },
        },
      ],
    },
    {
      name: 'France',
      series: [
        {
          name: 'Predicted',
          value: 108,
          extra: {
            code: 'fr',
          },
        },
        {
          name: 'Actual',
          value: 193,
          extra: {
            code: 'fr',
          },
        },
      ],
    },
    {
      name: 'United Kingdom',
      series: [
        {
          name: 'Predicted',
          value: 75,
          extra: {
            code: 'uk',
          },
        },
        {
          name: 'Actual',
          value: 69,
          extra: {
            code: 'uk',
          },
        },
      ],
    },
  ];`

**Expected behavior**
Expecting the graph data in the second graph to display the same as the demo https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical-2d

**Screenshots**
Attached
![graphs](https://user-images.githubusercontent.com/7856024/177917841-6e69e6b9-c888-409c-a97a-cf0d86f7fe2c.png)
![browser-error](https://user-images.githubusercontent.com/7856024/177917851-246fc444-379e-4ff1-948e-8b8ff4259a2e.png)

**ngx-charts version**
20.1.0

**Comment by Hypercubed** [comment]
For grouped data use `ngx-charts-bar-vertical-2d`

**Comment by Rlcolli4** [comment]
For what it was worth, I forked your stackblitz and was able to get it working:
1. I started by adding `BrowserAnimationsModule` to the imports in the app module to help with some of the errors I saw on load.
2. I converted the `ngx-charts-vertical` to `ngx-charts-vertical-2d` (just as @Hypercubed just posted) and it worked perfectly.
This worked in Angular 13 and 14 ([Here is my stackblitz of it in 13](https://stackblitz.com/edit/angular-ivy-catxjg?file=package.json,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts))

**Comment by Rlcolli4** [comment]
Also [here is their documentation](https://swimlane.gitbook.io/ngx-charts/examples/bar-charts/grouped-horizontal-bar-chart) on how to do any of their charts (this link will take you the grouped horizontal bar chart)

**Comment by ccocker** [comment]
> For grouped data use `ngx-charts-bar-vertical-2d`

Thank you - much appreciated

**Comment by ccocker** [comment]
> For what it was worth, I forked your stackblitz and was able to get it working:
> 
> 1. I started by adding `BrowserAnimationsModule` to the imports in the app module to help with some of the errors I saw on load.
> 2. I converted the `ngx-charts-vertical` to `ngx-charts-vertical-2d` (just as @Hypercubed just posted) and it worked perfectly.
>    This worked in Angular 13 and 14 ([Here is my stackblitz of it in 13](https://stackblitz.com/edit/angular-ivy-catxjg?file=package.json,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts))

@Rlcolli4 Thanks very much appreciated, working like a charm
