### ISSUE TITLE
Export Chart(s) as Image, SVG or base64 string

### ISSUE THREAD

**Issue by bvercelli99** [swimlane/ngx-charts#1773]
**Is your feature request related to a problem? Please describe.**
This would be a new feature request, no existing issue. 

**Describe the solution you'd like**
We were required to export out the charts as an image. I was able to get the SVG(s) from DOM, add my custom styles, write to canvas and export to PNG file.  I would be interested in doing a PR for it, but wanted to gauge interest first.

**Describe alternatives you've considered**
An alternative would be not exporting to PNG and so no need for a canvas element, and just allowing to export the SVG/Chart as base64 string for user? That would minimize using any extra elements and allow the user to create png/jpg etc of their choosing.

**Additional context**
Attached is a sample Line Chart Export with some custom styling
![SampleChartExport](https://user-images.githubusercontent.com/5415138/180503409-dd6db99d-20e3-489f-be49-5b7e13f0ced8.png)

**Comment by Hypercubed** [comment]
I don't feel this belongs in the charting library.  There are a few solutions out there for example: https://www.npmjs.com/package/svgsaver and perhaps some angular wrappers.
