### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#18]

**Comment by ocombe** [comment]
This is dependent on https://github.com/swimlane/ng2d3/issues/8

**Comment by jschwarty** [comment]
Is this still in the works? Getting the following error when trying to use a component in code that is run through server side rendering:

```
import { Input, Component, ElementRef, ViewEncapsulation, HostListener, ViewChild, HostBinding, Renderer } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by amcdnl** [comment]
@jschwarty - can you provide a demo env?

**Comment by zvirja** [comment]
As a workaround you can add the following code to your `package.json`:
```json
{
  "scripts": {
    "postinstall": "npm run fix-ngx-charts",
    "fix-ngx-charts": "babel node_modules/@swimlane/ngx-charts -d node_modules/@swimlane/ngx-charts --presets es2015",
  }
}
```

It helped on my local environment.

**Comment by wbhob** [comment]
I can confirm that this is still an issue. @zvirja 's fix works, but it is a hack and we need a more permanent solution. This seems to be an issue with how the library is packaged, targeting ES5. Complying with angular package format should solve this issue.

cc @scottwyatt

**Comment by wbhob** [comment]
well #8 has been closed

**Comment by scott-wyatt** [comment]
@maintainers, would you accept a PR with Ng-packagr?
