### ISSUE TITLE
Update vulnerable d3-color package and other d3 packages

### ISSUE THREAD

**Issue by moritz89** [swimlane/ngx-charts#1805]
**Describe the bug**
The package d3-color <3.1.0 has a known vulnerability to ReDoS

**To Reproduce**
1. npm audit

**Expected behavior**
ngx-charts not depending on vulnerable packages

**ngx-charts version**
20.1.0

**Additional context**
Additionally packages such as
- d3-interpolate
- d3-scale
- d3-transition
- d3-brush

should also be updated as they also have dependencies on d3-color

**Comment by drk-mtr** [comment]
Duplicate of https://github.com/swimlane/ngx-charts/issues/1799, except your issue contains useful info about these other packages which is probably worth copying there.

**Comment by moritz89** [comment]
Copied over additional info
