### ISSUE TITLE
Latest version suffering from High transitive security vulnerabilities 

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [swimlane/ngx-charts#1830]
**Describe the bug**
While a fix for the security vulnerability in `d3-color` was released - that same package is still causing transitive security vulnerabilities as the vulnerable version is pulled in by other `d3` packages (specifically `d3-brush`, `d3-interpolate`, `d3-scale`, and `d3-transition`) which were not updated.  

**Screenshots**
![image](https://user-images.githubusercontent.com/19909569/208761900-284149f4-7bbd-49cb-be39-1c0bc5962b18.png)

**ngx-charts version**
20.1.2

**Additional context**
First reported on issue #1809 by @uap-universe after it was closed

**Comment by jlquijada** [comment]
I fixed them in my project by manually editing the packages-lock.json file, updating the d3-dependencies versions to use the latest:

```json
        "node_modules/@swimlane/ngx-charts": {
            "version": "20.1.2",
            "resolved": "https://registry.npmjs.org/@swimlane/ngx-charts/-/ngx-charts-20.1.2.tgz",
            "integrity": "sha512-9uetDtBg++v96R9Nwgf8mvSu+6149FMQEm/jlpbcquUozfC5l+hO9i88tG3REOxnkGS10snGOCVUcPPY03nbxQ==",
            "dependencies": {
                "d3-array": "latest",
                "d3-brush": "latest",
                "d3-color": "latest",
                "d3-format": "latest",
                "d3-hierarchy": "latest",
                "d3-interpolate": "latest",
                "d3-scale": "latest",
                "d3-selection": "latest",
                "d3-shape": "latest",
                "d3-time-format": "latest",
                "d3-transition": "latest",
                "rfdc": "^1.3.0",
                "tslib": "^2.0.0"
            },
```

This is a bad situation, as [#1686](https://github.com/swimlane/ngx-charts/issues/1686), that is the reason why I intend to phase-out this package in favor of "chart.js": "^4.0.1", ASAP (much simpler, no dependencies, and does the same job for my project without problems)

**Comment by surenlancer7** [comment]
The above solution has too many changes. Was it working fine in all use cases.

**Comment by uap-universe** [comment]
@marjan-georgiev can you please prioritize this? Plus also fixing any other problems reported by npm audit?

**Comment by daiscog** [comment]
https://github.com/swimlane/ngx-charts/pull/1836 should fix this

**Comment by 3MR1T00** [comment]
> I fixed them in my project by manually editing the packages-lock.json file, updating the d3-dependencies versions to use the latest:
> 
> ```json
>         "node_modules/@swimlane/ngx-charts": {
>             "version": "20.1.2",
>             "resolved": "https://registry.npmjs.org/@swimlane/ngx-charts/-/ngx-charts-20.1.2.tgz",
>             "integrity": "sha512-9uetDtBg++v96R9Nwgf8mvSu+6149FMQEm/jlpbcquUozfC5l+hO9i88tG3REOxnkGS10snGOCVUcPPY03nbxQ==",
>             "dependencies": {
>                 "d3-array": "latest",
>                 "d3-brush": "latest",
>                 "d3-color": "latest",
>                 "d3-format": "latest",
>                 "d3-hierarchy": "latest",
>                 "d3-interpolate": "latest",
>                 "d3-scale": "latest",
>                 "d3-selection": "latest",
>                 "d3-shape": "latest",
>                 "d3-time-format": "latest",
>                 "d3-transition": "latest",
>                 "rfdc": "^1.3.0",
>                 "tslib": "^2.0.0"
>             },
> ```
> 
> After the edition, run `npm audit fix`, and the messages are gone.
> 
> This is a bad situation, as [#1686](https://github.com/swimlane/ngx-charts/issues/1686), that is the reason why I intend to phase-out this package in favor of `"chart.js": "^4.0.1",` ASAP (much simpler, no dependencies, and does the same job for my project without problems)

Not sure how you did this... 

In idea this can not work, as `npm audit fix` can not install latest for all the dependencies.

It would be a dependency mismatch. Ex: `swimlane v.20.1.2` does not allow `d3-brush v.3.0.0`, nor many others. The only  ones which are allowed to be major updated, are I think `d3-color` `d3-scale` and `d3-time-format`. 

For the other, they can only be minor or patch updated, they can't go up from `v.2.x.x` to `v.3.x.x`

Normally if you run `npm audit fix` in this situation, what happens is that dependencies go back from `latest` to previous state,  which would leave it just like it was.

Would you mind elaborating about the whole process in your case?

**Comment by sushmeex** [comment]
Facing similar issue in our project, we are the latest ngx charts and d3 versions

<img width="445" alt="image" src="https://user-images.githubusercontent.com/123559443/228130231-28beb29c-9556-4ad6-beb8-d0f0eeb01fa3.png">

**Comment by queejie** [comment]
I'm getting a sense that this package is possibly no longer in active development, since fixes were posted in Feb but not merged?

**Comment by daiscog** [comment]
@surya-pabbineedi thanks for merging #1836 

Unfortunately it does not fix the issue as [the dependencies declared in the lib's individual package.json](https://github.com/swimlane/ngx-charts/blob/20.4.0/projects/swimlane/ngx-charts/package.json#L47-L61) were not updated, so npm is still pulling in the old d3 deps:

<img width="452" alt="Screenshot 2023-06-14 at 10 41 42" src="https://github.com/swimlane/ngx-charts/assets/5968668/aa60c08f-ed51-49ad-b458-f7127c768088">

I've created #1874 to fix that.  Can you please look to merge this ASAP?

Thanks.

**Comment by surya-pabbineedi** [comment]
v20.4.1 has been published to address the vulnerabilities. Thanks!

<img width="618" alt="Screenshot 2023-06-14 at 6 34 11 PM" src="https://github.com/swimlane/ngx-charts/assets/98421392/ce75f82c-0c47-41c3-b7b9-b9000f97422b">
