### ISSUE TITLE
Module Import statement in samples

### ISSUE THREAD

**Issue by 72gm** [swimlane/ngx-charts#186]
Not a bug as such but didn't know where else to put this!

The demo samples all have the following import statement: **import {NgxChartsModule} from 'ngx-charts';**

I had to use: **import {NgxChartsModule} from '@swimlane/ngx-charts';** to get mine to work.

I'm using the latest angular cli.

Is this right or have i just frigged it luckily?

**Comment by marjan-georgiev** [comment]
`@swimlane/ngx-charts` is correct if you're using angular CLI.

In the plunkr demos we use system.js and that is just how the package is mapped in config.js. We should change that to prevent confusion.
