### ISSUE TITLE
ngx-charts componentscss overriding labels (.label)

### ISSUE THREAD

**Issue by DeezCashews** [swimlane/ngx-charts#188]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Ionic2 labels effected by ngx-charts css

**Expected behavior**
All non ngx-charts components remain untouched by ngx-charts css

**Reproduction of the problem**
Create a css with:
.label {
  font-size: 20px;
}

Add any ngx-charts-xxxx component

font-size will chant to 12px because of the following in ngx-charts/release/index.css
.label {
  font-size: 12px;
  font-weight: normal; }

**What is the motivation / use case for changing the behavior?**
Ionic2 adds .label to all ion-label components.  When a ngx-chart-xxx component is used, its .label css overrides the ion-label

**Please tell us about your environment:**
Win7Pro, VS Code, npm, ionic serve

* **ngx-charts version:** 4.0.1

* **Angular version:** 2.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by marjan-georgiev** [comment]
Fixed, coming in next release. Thanks for reporting!

**Comment by DeezCashews** [comment]
You're the man @marjan-georgiev !
