### ISSUE TITLE
Documentation Examples broken

### ISSUE THREAD

**Issue by 72gm** [swimlane/ngx-charts#189]
None of your examples in the documentation are working today

![2017-01-26](https://cloud.githubusercontent.com/assets/12847881/22326562/211ec90c-e3ab-11e6-9614-5344bc134f27.png)

**Comment by marjan-georgiev** [comment]
There seems to be a bug in plunker's embedded view. It does that to all plunks at the moment.

Here's a list to the edit views of all plunks:

Vertical Bar Chart
https://plnkr.co/edit/IPhMUjOHEhzncDzxRgRm?p=preview

Grouped Vertical Bar Chart
https://plnkr.co/edit/HJBUlMEUl3eJotj6YCdZ?p=preview

Stacked Vertical Bar Chart
https://plnkr.co/edit/THIN2SfIIjSXB1ICJUnu?p=preview

Normalized Vertical Bar Chart
https://plnkr.co/edit/t1bnsDjigPxFEAYihPZt?p=preview

Horizontal Bar Chart
https://plnkr.co/edit/H066vULzE6EOLipIjOt9?p=preview

Grouped Horizontal Bar Chart
https://plnkr.co/edit/2eQ9jheOTm8i74vp2EmP?p=preview

Stacked Horizontal Bar Chart
https://plnkr.co/edit/UHQVvMUmxsieiYITMVPq?p=preview

Normalized Horizontal Bar Chart
https://plnkr.co/edit/m57WQViqVcTPfroiLGQm?p=preview

Area Chart
https://plnkr.co/edit/HOXr8K?p=preview

Stacked Area Chart
https://plnkr.co/edit/qQXu19QRUhPtIQoGd8ru?p=preview

Normalized Area Chart
https://plnkr.co/edit/ULbzY7ZmdugBRrb8SgdQ?p=preview

Line Chart
https://plnkr.co/edit/7SqwjBi1hGcN2q6Ox1GU?p=preview

Pie Chart
https://plnkr.co/edit/BooZfKJz0nLATpTe1SwH?p=preview

Pie Grid Chart
https://plnkr.co/edit/1wyoTPr38ajgzUmOhMHi?p=preview

Advanced Pie Chart
https://plnkr.co/edit/732px9P6WMqDeirILWox?p=preview

Heat Map Chart
https://plnkr.co/edit/iyvvzBrEIayRWG5BcQ7e?p=preview

Tree Map Chart
https://plnkr.co/edit/VvVTLXOOsMGfYtT9c1CX?p=preview

Number Card Chart
https://plnkr.co/edit/c9Kb4DhRuj2MP1Cjgzl7?p=preview

Gauge Chart
https://plnkr.co/edit/MylIDCFIpzg1oH5tatDs?p=preview

Linear Gauge Chart
https://plnkr.co/edit/yIm5sYQEXdJ8ThIxg0gM?p=preview
