### ISSUE TITLE
Bug with `scss` reference during `aot` build

### ISSUE THREAD

**Issue by emoralesb05** [swimlane/ngx-charts#194]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

With the `SCSS` refactor https://github.com/swimlane/ngx-charts/commit/034d9774f86abfe9b64678dbaf6876fadb7a9665, lots of `scss` files were created and referenced in the `ts` files (which is fine).

But when the module is published, that reference is still there and no `scss` file released.

https://github.com/swimlane/ngx-charts/blob/master/release/common/tooltip/tooltip.component.js#L72

So its giving the following errors:

<img width="757" alt="screen shot 2017-01-28 at 10 16 09 am" src="https://cloud.githubusercontent.com/assets/5846742/22398714/e543707e-e542-11e6-92bb-c2b2dbb75213.png">

**Expected behavior**

`scss` files should be `compiled` and the `css` should be `inlined` during the build / publishing process in both `component.js` and `umd` files. (ideally)

OR

`scss` files should be released too (i think this would work also but it would be a workaround, since if somebody gets a hold of just the `umd` file, it still holds references in it)

**Reproduction of the problem**

Happens when trying to use `aot` with the `angular-cli`. (Didnt use to happen on previous releases since `css` was added differently)

**Please tell us about your environment:**
* **angular-cli:** 1.0.0-beta.26

* **ngx-charts version:** 4.0.1

* **Angular version:** 2.4.5

**Comment by antoineabourjeilycme** [comment]
I'm facing the same issue!

**Comment by dhcdata** [comment]
same. my workaround is to simply copy 

src/common/base-chart.component.scss
src/common/legend/advanced-legend.component.scss
src/common/legend/legend.component.scss
src/common/legend/scale-legend.component.scss
src/common/timeline/timeline.component.scss
src/common/tooltip/tooltip.component.scss
src/force-directed-graph/force-directed-graph.component.scss
src/gauge/gauge.component.scss
src/gauge/linear-gauge.component.scss
src/pie-chart/advanced-pie-chart.component.scss
src/pie-chart/pie-chart.component.scss
src/pie-chart/pie-grid.component.scss
src/tree-map/tree-map.component.scss

over to release

**Comment by antoineabourjeilycme** [comment]
I agree, I did that and it works like a charm.

**Comment by dhcdata** [comment]
It's obviously a build issue, but I can't for the life of me figure out what is creating the extension `*.scss.ngstyle.ts `
in the build process

**Comment by amcdnl** [comment]
I'm looking into it...only happens for aot

**Comment by marjan-georgiev** [comment]
I added the scss files to the release folder. This should fixes these problems.

Try it with 4.0.2

**Comment by emoralesb05** [comment]
Cool thanks! will start trying it soon.

**Comment by dhcdata** [comment]
This works for the immediate issue. Is there a reason why there is some build stuff within webpack and some outside?  Is it lack of resources to fully transition or by design?  If the former, it seems these types of issues will continue to pop up.

Thank you for all the work moving this project forward, it's great.

**Comment by amcdnl** [comment]
Packaging libraries for external usage in Angular2 is nearly impossible right now.

- Webpack -> Handles complex steps and packages but AoT doesn't work well and doesn't produce Type Defs
- CLI -> No packaging support
- TypeScript -> Handles Type Defs but not scsc/html build steps
- Rollup -> Same issues as Webpack.
