### ISSUE TITLE
Add valueFormatting parameter for Line Area charts

### ISSUE THREAD

**Issue by atoyansk** [swimlane/ngx-charts#1941]
**Is your feature request related to a problem? Please describe.**
It's not possible to format values as currencies using these types of charts.

**Describe the solution you'd like**
Add valueFormatting parameter for Line Area charts, where it would be possible to include a currency format to values.

**Comment by Rlcolli4** [comment]
According to the [documentation](https://swimlane.gitbook.io/ngx-charts/examples/line-area-charts/area-chart), you should be able to provide your own tooltip using `tooltipTemplate` or `seriesTooltipTemplate`, with a little formatting and CSS you could provide your own tool tips that show the colors and formatted values you are looking for.
