### ISSUE TITLE
LineChart example repro issue

### ISSUE THREAD

**Issue by athalay** [swimlane/ngx-charts#199]
I'm trying to use this library in my project, set up mostly everything as described in this example:

[https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html](https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html)

In my app.component.template I copied the chart from the example also:

```
<ngx-charts-line-chart
      [view]="view"
      [scheme]="colorScheme"
      [results]="multi"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [legend]="showLegend"
      [showXAxisLabel]="showXAxisLabel"
      [showYAxisLabel]="showYAxisLabel"
      [xAxisLabel]="xAxisLabel"
      [yAxisLabel]="yAxisLabel"
      [autoScale]="autoScale"
      (select)="onSelect($event)">
    </ngx-charts-line-chart>
```
    
, and I copied every property too, including data (though not using Object.assign, just setting the single/multi arrays in the constructor).

**When I run the app, the chart's 'frame' (including the gridlines) appear, though the chart not, and I get the following error in the console**:

```
Unhandled Promise rejection: Error in ./LineSeriesComponent class LineSeriesComponent - inline template:19:8 caused by: Unable to get property 'remove' of undefined or null reference ; Zone: <root> ; Task: Promise.then ; Value: Error: Error in ./LineSeriesComponent class LineSeriesComponent - inline template:19:8 caused by: Unable to get property 'remove' of undefined or null reference Error: Error in ./LineSeriesComponent class LineSeriesComponent - inline template:19:8 caused by: Unable to get property 'remove' of undefined or null reference
   at DebugAppView.prototype._rethrowWithContext (eval code:12915:21)
   at DebugAppView.prototype.detectChanges (eval code:12888:17)
   at AppView.prototype.internalDetectChanges (eval code:12723:17)
   at View_LineChartComponent3.prototype.detectChangesInternal (Function code:212:3)
   at AppView.prototype.detectChanges (eval code:12738:13)
   at DebugAppView.prototype.detectChanges (eval code:12885:17)
   at ViewContainer.prototype.detectChangesInNestedViews (eval co
```

**Comment by marjan-georgiev** [comment]
What browser are you getting this on?

**Comment by athalay** [comment]
IE 11

On Chrome (latest) it works!

What shall I do to make it work on IE 11 too?

**Comment by marjan-georgiev** [comment]
We do not actively support IE 11. It seems that the error is caused by angular using classList.remove, which IE 11 does not support.

Try adding this polyfill for it: https://github.com/yola/classlist-polyfill

**Comment by marjan-georgiev** [comment]
Also, read this page for other polyfills you may need to include: https://angular.io/docs/ts/latest/guide/browser-support.html

This is an angular issue, not ngx-charts issue.

**Comment by athalay** [comment]
Thanks Marjan, I added
es6-shim
classlist
, now the diagram appears, though for tooltips the following error comes up:

`JavaScript runtime error: Error: Error in ./AreaTooltip class AreaTooltip - inline template:4:6 caused by: Object doesn't support this action`

I got it, that you mentioned you don't actively support IE 11, though is there a chance to solve this issue?

I need to use IE because that allows proper debugging with Visual Studio only :(

**Comment by marjan-georgiev** [comment]
This too would need to be fixed through a polyfill. I'm not sure which one though - the error is not very descriptive. 

Can you find what function call breaks it?

**Comment by athalay** [comment]
Unfortunately I can't really find out :( The highest-level of the error-call stack give this error:

`stack = "Error: Error in ./AreaTooltip class AreaTooltip - inline template:4:6 caused by: Object doesn't support this action\n   at DebugAppView.prototype._rethrowWithContext (eval code:12915:21)\n   at Anonymous function (eval code:12932:21)\n   at Anonymous funct...`
