### ISSUE TITLE
Heat Map: Adjust label width

### ISSUE THREAD

**Issue by mariuspruski** [swimlane/ngx-charts#203]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
The labels of the heat map's y axis are cut off when they are too long.

**Expected behavior**
Would be great if the width of the labels dynamically increased with the length of the labels.

**Reproduction of the problem**
Add a heat map with long y labels.

**Comment by marjan-georgiev** [comment]
We could probably add a `maxAxisTickLabelLength` input to the charts that have axes.

**Comment by mariuspruski** [comment]
I noticed the same issue with the legend of the force directed graph. Perhaps it's the case with other legends, too.

**Comment by khan4019** [comment]
Does anyone know any temporary work-around to give more width to the tick labels. Perhaps something to the .tick class
![image](https://cloud.githubusercontent.com/assets/1848375/25296750/7586e280-26af-11e7-8e10-23e99c2a9798.png)

**Comment by markobalogh2** [comment]
[This function](https://github.com/swimlane/ngx-charts/blob/master/src/common/trim-label.helper.ts) is responsible for trimming the tick labels. By commenting out the last if/else block and replacing it with `return s;` you should be able to prevent trimming. However, it seems editing it directly in your `node_modules` has no effect...this has something to do with how npm compiles typescript into javascript that is beyond my knowledge. I think you might have to fork this repo and edit the typescript source.

**Comment by markobalogh2** [comment]
Can someone help me figure out how to meaningfully edit trim-label.helper.js? I know this file is compiled from typescript during the build process but it still doesn't make sense that if I directly edit the js it doesn't have any effect on the behavior of the module. Does angular cache the javascript or something?

**Comment by marjan-georgiev** [comment]
@markobalogh2 you need to edit index.js. That is the file that is imported in your application:
https://github.com/swimlane/ngx-charts/blob/master/release/index.js#L10988

**Comment by markobalogh2** [comment]
@marjan-georgiev perfect, thank you!

**Comment by marjan-georgiev** [comment]
This should be addressed by https://github.com/swimlane/ngx-charts/pull/870 and will be in the next release. Closing.
