### ISSUE TITLE
Some charts do not display on Microsoft Edge (Also examples not working https://swimlane.gitbooks.io/ngx-charts/)

### ISSUE THREAD

**Issue by eanna-mul** [swimlane/ngx-charts#205]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Charts are not displaying in Microsoft Edge

**Expected behavior**

Charts should display in Microsoft Edge browser

**Reproduction of the problem**

These examples do not display on Microsoft Edge:
https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical-stacked.html
https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html

**What is the motivation / use case for changing the behavior?**

We are using this library in a large multinational company. We will demo these charts in Microsoft edge.

**Please tell us about your environment:**

windows 10 
Intellij IDEA
npm

* **ngx-charts version:** x.x.x

ngx-charts version: 3.0.7

* **Angular version:** 2.x.x

Angular version: 2.4.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Microsoft Edge

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by eanna-mul** [comment]
The error being thrown by Microsoft Edge is "Object doesn't support property or method 'includes'". I think this could be an issue with using includes() as it is not supported in all browsers. As the stackoverflow article suggests, a possible fix could be to replace includes() with indexOf() or to use a pollyfill. What do you guys think?

**Comment by marjan-georgiev** [comment]
I would suggest using a polyfill for `includes`.

**Comment by marjan-georgiev** [comment]
Additionally, here's a list of polyfills to use with angular 2 for various browsers https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by eanna-mul** [comment]
Hey guys, got it fixed. I used the core-js polyfill for array which has the includes() fix: https://github.com/zloirock/core-js

Also for anyone else having similar issues, make sure in your tsconfig that: `"lib": ["es7", "dom"]`

Thanks for the fast feedback @marjan-georgiev
