### ISSUE TITLE
Change X and Y axis color.

### ISSUE THREAD

**Issue by MateenKadwaikar** [swimlane/ngx-charts#207]
**I'm submitting a .....**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request => Please do not submit support request here
```

How can I change the color for X and Y axis data.  I have to change the font color of the underline data.

![image](https://cloud.githubusercontent.com/assets/6949959/22589107/90e264a4-ea2e-11e6-87c6-a9a5dd45c9ea.png)

**Comment by marjan-georgiev** [comment]
I'm not sure I understand this. What are you trying to change the color of?

**Comment by MateenKadwaikar** [comment]
@marjan-georgiev  I have a black background and I want to change the color for the text which show 8,500,000 etc.

**Comment by marjan-georgiev** [comment]
You can override the CSS of any element like here:

https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.scss#L218

**Comment by MateenKadwaikar** [comment]
@marjan-georgiev it is changing for all the others too . I just want to change for the particular text. Not all

**Comment by marjan-georgiev** [comment]
You want the color changed only for the text saying 8,500,000 but not the others? That is not possible to do through the library.

**Comment by MateenKadwaikar** [comment]
Ohh okay so there is no way other way do that right ?

**Comment by ChrisGrigg** [comment]
@MateenKadwaikar I managed to do this through selecting the CSS child. The following code will change the colour of the '2010' label.

`::ng-deep .ngx-charts {
    .x {
        .tick {
            &:first-child {
                text {
                    fill: #fff;
                }
            }
        }
    }
}`
