### ISSUE TITLE
Percentages wrong in Pie Grid

### ISSUE THREAD

**Issue by 72gm** [swimlane/ngx-charts#208]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
![2017-02-03 2](https://cloud.githubusercontent.com/assets/12847881/22589702/80f3f9ac-ea03-11e6-8a28-73ca8ddf3441.png)

Both charts using the same data collection but the Pie Grid is displaying the wrong pecentages. I'm not sure how this is even possible as this data is correct in the Pie Grid just the % that is wrong??

* **ngx-charts version:** 4.0.1, Angular2 cli and all browsers

**Comment by amcdnl** [comment]
Can you make a demo of this plz?

**Comment by 72gm** [comment]
if I make a plunkr based on one of your examples and copy the code directly into it then it works. So my code is fine.

I've taken the code and created a new test html and component with just the minimum chart code and I still get the same error when doing it in my angular cli project....  if i use any more than 2 items in the data collection the percentages are wrong in the Pie Grid????

**Comment by 72gm** [comment]
actually the bit about anymore than 2 data items is wrong... the calcs are wrong regardless (just adds up to 100 when there are 2 items...

its almost like its rounding to the nearest 10%

**Comment by marjan-georgiev** [comment]
this should be fixed in 4.1.0. Have you tried that?

**Comment by 72gm** [comment]
it is rounding to the nearest 10 %... i'll try the latest version

**Comment by 72gm** [comment]
works in 4.1.0

**Comment by marjan-georgiev** [comment]
👍
