### ISSUE TITLE
External Legend Styling

### ISSUE THREAD

**Issue by DeezCashews** [swimlane/ngx-charts#211]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
While it's obviously not intended to be used so, I am manually using ngx-charts-legend so I can place where I would like without effecting chart itself.  I do so my manually creating the appropriate data to feed in like so:
`<ngx-charts-legend [data]="domain" [colors]="colors"></ngx-charts-legend>`
instead of letting the chart do it for me.  However, the styling does not take effect because the css expects it to be wrapped in .chart-legend.  I easily work around by surrounding like so:
`<div *ngIf="domain" class="chart-legend">` but would be nice if ngx-charts-legend contained everything it needed for its own styling instead of relying on a parent container to provide the class.

**Expected behavior**
Legend would style correctly by just specifying its selector.

**Reproduction of the problem**
```
// JS
let domain = ['Label1', 'Label2'];
let colors = new ColorHelper('cool', 'ordinal', domain, null);

// Template
<ngx-charts-legend [data]="domain" [colors]="colors"></ngx-charts-legend>
```

**What is the motivation / use case for changing the behavior?**
Allow user to use legend outside of chart without having to dig into internals of css to get displaying properly.

**Comment by marjan-georgiev** [comment]
You can assign the class when you use the component - there's no need to wrap it in a container. 

Like this:
https://github.com/swimlane/ngx-charts/blob/master/src/common/charts/chart.component.ts#L32

But I agree, it's probably better to assign that class to the root div of the legend component.

**Comment by DeezCashews** [comment]
@marjan-georgiev correct, I just wrapped in a div to illustrate what normally happens when used in a chart, pointing out that the chart component is partially responsible for the styling of the legend component and it would be nice if legend component could work outside of that context without knowing the CSS internals.  I'll look into submitting a PR if I get some free time this week.

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
