### ISSUE TITLE
SystemJS issues

### ISSUE THREAD

**Issue by Jannaro** [swimlane/ngx-charts#212]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I am trying to run the demo with SystemJS instead of Webpack and found some issues:

1. The browser displays information about missing files (that really do not exist):
GET http://localhost:3000/src/common/legend.js 404 (Not Found)
GET http://localhost:3000/src/common/tooltip.js 404 (Not Found)
...

2. The browser displays information about missing files (that do exist, but in a different directory):
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/legend.component.scss 
...

3. After above issues are fixes messages about undefined variables start to appear. Examination shows that BaseChartComponent constructor gets all its arguments undefined.

**Expected behavior**
All the issues may be fixed in a simple way:

1. Import statements should consistently use name of the module, so for instance 
import { TooltipModule } from './tooltip'; 
should be substituted by
import { TooltipModule } from './tooltip/tooltip.module';

2. It is a well known issue, if a component includes a template or style in a separate file it should contain moduleId property:
moduleId: module.id.
The module variable needs to be declared, the simple declaration will do:
declare var module: {
   id: string;
};

3. To fix it I added constructors to all classes derived from BaseChartComponent. The constructors are trivial: 
  constructor(chartElement: ElementRef, zone: NgZone, cd: ChangeDetectorRef, location: Location) {
      super(chartElement, zone, cd, location);
  }
however it is necessary to add missing imports to the files.
 
A complete list of changes to fix point 1:
chart-common.module.ts
import { TooltipModule } from './tooltip/tooltip.module';
import { LegendComponent } from './legend/legend.component';
import { ScaleLegendComponent } from './legend/scale-legend.component';
import { LegendEntryComponent } from './legend/legend-entry.component';
import { AdvancedLegendComponent } from './legend/advanced-legend.component';
import { Timeline } from './timeline/timeline.component';
import { CountUpDirective } from './count/count.directive';

card.component.ts
import { count, decimalChecker } from '../common/count/count.helper';

tooltip.module.ts
import { InjectionService } from '../../services/injection.service';

tooltip.component
import { PlacementTypes } from './position/placement.type';
import { PositionHelper } from './position/position';

tooltip.directive
import { PlacementTypes } from './position/placement.type';

tooltip.service
import { InjectionRegistery } from '../../services/injection-registery.service';
import { InjectionService } from '../../services/injection.service';
import { TooltipContentComponent } from './tooltip.component';

injection-registery.service.ts
import { InjectionService } from './injection.service';

base-chart.component.ts 
import { VisibilityObserver } from '../utils/visibility-observer';

chart.component.ts
import { TooltipService } from '../tooltip/tooltip.service';

timeline.component.ts
import { id } from '../../utils/id';

**Reproduction of the problem**
Use SystemJS.

**What is the motivation / use case for changing the behavior?**
I suppose that the library should work with SystemJS. The changes described above will work with Webpack as well.

**Please tell us about your environment:**
Windows

* **ngx-charts version:** x.x.x
4.1.0

* **Angular version:** 2.x.x
2.4.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.1.5

**Comment by Jannaro** [comment]
I have created GitHub repo Jannaro/ngx-system as a demo.
I made it hastily, so first manually copy demo/app.component.html to dist/demo.
Run:
npm install
gulp sass
gulp sassdemo
npm start.
I made all my suggested changes so it works. Now you can reverse the changes one by one and see the consequences.
I have added the following files to the root directory:
Index.html
package.json
systemjs.config.js
gulpfile.js
and made minimal changes to made it working (using Index.html, substituting .scss with .css) that should be irrelevant to the issues.

**Comment by Jannaro** [comment]
There are 2 more issues that I overlooked before.

4. It seems that DOMContentLoaded event is not fired. It is necessary to uncomment two lines in bootstrap.ts to make the program running.

5. The reference at the beginning of d3.ts seems to be dependent on Webpack:
/// <reference path="../node_modules/awesome-typescript-loader/lib/runtime.d.ts" />
Awesome TypeScript loader is designed for Webpack.
The line may be substitute for instance with:

declare function require(name: string);

**Comment by Jannaro** [comment]
@marjan-georgiev 
I would like to withdraw point 2 (moduleId). The issue mat be handled using Gulp (gulp-inline-ng2-template).
I have updated my demo, it uses Gulp 4 now.

**Comment by tehZeno** [comment]
Any updates on this issue?

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
