### ISSUE TITLE
DAG Tree

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#218]
## Requirements
Tree component to visualize workflows

- Custom Styling on Nodes and Edges (shapes/logos/text/colors)
- Expand Collapse on Edges
- Multiple edges from a single node
- Drag/Drop
- Ordering
- Zoom?
- Circular paths?

## Examples
![ana](https://d13yacurqjgara.cloudfront.net/users/142356/screenshots/3016326/artboard_1.png)

![flow](https://d13yacurqjgara.cloudfront.net/users/180062/screenshots/2712965/dribbble.png)

![dribble](https://d13yacurqjgara.cloudfront.net/users/18730/screenshots/3271768/attachments/703523/dth_8-full-1.png)

![d3](http://jssolichin.com/blog/wp-content/uploads/2013/10/31.png)

![ss](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/d1217495-684e-430a-8bf4-101d42295122/2017-02-10_08-56-30.png)

![o](http://senseable.mit.edu/datadrivesvisualsg/img/site_banner_02.jpg)

![d](https://d13yacurqjgara.cloudfront.net/users/207046/screenshots/3215632/crmcampaign.jpg)

**Comment by marjan-georgiev** [comment]
This is being implement as a custom chart in a separate repo: https://github.com/swimlane/ngx-charts-dag
