### ISSUE TITLE
Real Data usage Bar Chart

### ISSUE THREAD

**Issue by DaMair** [swimlane/ngx-charts#219]
Hi,

i am using the ngx charts Bar Chart in my Angular2 Application. I am getting my historical Json Data via REST and store it in the Component as a List of JSON Objects. I got 2 Problems and i can't find any documenation about it. 

1)
If the List chances (using MQTT for real life DATA), the chart isnt updating (Covalent Teradata DataTable does).

2) How can the "filter" field on which the Chart is filtering  be changed (at the moment there is just one bar with the last data in it) -> i got a list with elements with the same name but different values.

code used: 

Main.ts:

 view: any[] = [700, 400];
  showXAxis = true;
  showYAxis = true;
  gradient = false;
  showLegend = true;
  showXAxisLabel = true;
  xAxisLabel = 'Nummer';
  showYAxisLabel = true;
  yAxisLabel = 'Value';
  colorScheme = {
    domain: ['#5AA454', '#A10A28', '#C7B42C', '#AAAAAA']
  };

Main.html:

<ngx-charts-bar-vertical
      [view]="view"
      [scheme]="colorScheme"
      [results]="sensors"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [legend]="showLegend"
      [showXAxisLabel]="showXAxisLabel"
      [showYAxisLabel]="showYAxisLabel"
      [xAxisLabel]="xAxisLabel"
      [yAxisLabel]="yAxisLabel"
  >
    </ngx-charts-bar-vertical>

(sensors=list of Json values)

I will include two screenshots with the needed data and the chart result!
Thx for any help and your charts look awesome!

Greetings,
David/ hopeless student
![unbenannt](https://cloud.githubusercontent.com/assets/23579976/22832539/af8b6128-efae-11e6-96f9-312f72f47177.JPG)
![unbenannt2](https://cloud.githubusercontent.com/assets/23579976/22832541/b238a9c6-efae-11e6-984d-e49973c02401.JPG)

**Comment by marjan-georgiev** [comment]
The results property needs to be passed an immutable array for it to detect changes.

As for the other issue, can you create a plunker or a github repo where it can be reproduced?

**Comment by byunru** [comment]
I need a historial bar which the data is not evenly distributed on time series, for example:
http://plnkr.co/edit/w9LnjVxWFCSkU3Vxs7pU?p=preview
I hope ngx charts can provide an easy way to achieve this, Thanks.

**Comment by Phota16** [comment]
I am facing similar kind of issue. I got data from rest api and convert to name value format. It generated the bar chart correctly. I have a refresh button, on click event  get the data again from server and refresh the result. It too generate the bar chart with new result set. But i got some error in the F12(attched below)
**code sample:**
export class GraphDataFormat {
    name: string;
    value: number =0;
}
single: GraphDataFormat[] = [];
 ngOnInit() {
    this._rowsSubscriber = this.comService.getCommunications("4/29/2015", "4/29/2016", 3)
      .subscribe(data => {       
        this.single = [];        
        data.forEach((item, i, data) => { this.single.push({ name: (item.eventType), value: (item.total) }) });
      });
  }
refreshWidget() {
let obj = this.comService.getCommunications("4/29/2015", "4/29/2016", 1)
    this._subscription = obj.subscribe(result => {
    this.single = [];
    result .forEach((item, i, data) => { this.single.push({ name: (item.eventType), value: (item.total) }) });
});
}
Error****
![image](https://user-images.githubusercontent.com/20189130/29379974-cf4da322-8289-11e7-98ce-52634017f57d.png)

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
