### ISSUE TITLE
Radar Charts

### ISSUE THREAD

**Issue by areed829** [swimlane/ngx-charts#222]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

Are you guys planning on adding a radar chart to this project at some point?
https://en.wikipedia.org/wiki/Radar_chart#/media/File:Spider_Chart2.jpg

**Comment by marjan-georgiev** [comment]
Absolutely, it's on the road map.

We have an open issue already about it, so I'm going to be closing this one: https://github.com/swimlane/ngx-charts/issues/91

**Comment by marjan-georgiev** [comment]
Added in 5.2 https://swimlane.github.io/ngx-charts/#/ngx-charts/polar-chart
