### ISSUE TITLE
Is Chart using available space properly in responsive mode

### ISSUE THREAD

**Issue by 72gm** [swimlane/ngx-charts#224]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
**Current behavior**
Charts in responsive mode (no view set) not using up available parent space (Marjan asked to raise from gitter)

**Expected behavior**
Charts would use up more of the available space

**Reproduction of the problem**
 <div class="col-12">
      <div class="card">
        <div class="card-header"> State Of The Parties </div>
        <div class="card-block" style="min-height: 400px;width:100%">
              <ngx-charts-pie-chart [scheme]="colorScheme" [results]="partyTotals" [legend]="false" [explodeSlices]="false" [labels]="true"
                [doughnut]="false" [gradient]="gradient" (select)="onSelect($event)">
                </ngx-charts-pie-chart>
        </div>
      </div>
    </div>

**What is the motivation / use case for changing the behavior?**
Charts would be better responsive if they used the space available better on smaller viewports

Windows 10
* **ngx-charts version:** 4.1.2
* **Angular version:** 2.4.7
* **Browser:** all

![2017-02-14 1](https://cloud.githubusercontent.com/assets/12847881/22934402/b798424e-f2c6-11e6-825d-1b609252be78.gif)

**Comment by StanFisher** [comment]
Since this bug is a high priority, is there a known workaround? If not, is there a timeframe for when this issue is targeted to be fixed? Thanks!

**Comment by marjan-georgiev** [comment]
This should be fixed in the latest release. We probably missed closing this issue as there was a duplicate one. Please let me know if you still see it.

![image](https://user-images.githubusercontent.com/8687/30085327-298c3738-9296-11e7-9d96-8c3c465e155e.png)

**Comment by StanFisher** [comment]
@marjan-georgiev Thank you for the quick response. I'm still seeing the issue. It looks like the drawing of the pie graph always takes into account the space the labels would take up, even if they aren't shown. You can see the large amount of padding that is included when I make the size of the view port 175 x 175. I'm seeing the same thing when I select _Fit Container_.

![image](https://user-images.githubusercontent.com/35271/30134982-c8936e40-931e-11e7-9172-2a80173c6f38.png)

**Comment by StanFisher** [comment]
@marjan-georgiev I see the problem. If you take a look at [PieChartComponent starting at line 87](https://github.com/swimlane/ngx-charts/blob/20fc3e2d22c467793b3db2323754e122ef94c30e/src/pie-chart/pie-chart.component.ts#L87), you will see that when deselecting **Show Labels**, margins still contains `[30, 80, 30, 80]`. The update needs to reset the margins to the intended default of `[20, 20, 20, 20]`. This brings up another question though. Why are the margins being set at all? I would think that when I want to fit to the container, there should be no margins. Do you agree?

**Comment by PiiSmith** [comment]
Exactly the problems mentioned by StanFisher above, are addressed by this pull request https://github.com/swimlane/ngx-charts/pull/759 , which makes this hard coded "border" of ```20, 20, 20, 20``` or ```30, 80, 30, 80``` optional.

**Comment by furevor** [comment]
Hello! Still no one solution for now from developers? It looks like [this workaround](https://github.com/swimlane/ngx-charts/issues/514) has broken, because of hardcoded margins inside 'update()' method. Looks like there is only one solution - reimplement chart with zero margins?

**Comment by PiiSmith** [comment]
Well my pull request and the solution I proposed was ignored, so we moved one and used something different to display a pie-chart in a very limited space. The pull request is now older than a year.

**Comment by furevor** [comment]
> Well my pull request and the solution I proposed was ignored, so we moved one and used something different to display a pie-chart in a very limited space. The pull request is now older than a year.

Thanks for replay, is there any possibility to look at your PR? It seems that workaround shouldn't be complex, I have copy/pasted code from BarVerticalComponent and changed margins to zero..

**Comment by marjan-georgiev** [comment]
Hi all, just merged the PR, will be in the next release. Would need to add the `margins` input to all charts before we release, so they are all consistent. If anyone is interested in working on that, please let me know.

Thanks!

**Comment by furevor** [comment]
> Hi all, just merged the PR, will be in the next release. Would need to add the `margins` input to all charts before we release, so they are all consistent. If anyone is interested in working on that, please let me know.
> 
> Thanks!

Hello! Sounds great! Sorry, have no idea how to contact you, but I have noticed one important thing in PieGridComponent. There is no ability for hiding label and also there is hardcoded padding and baseline in `getSeries()`, `const baselineLabelHeight = 20;`, `const padding = 10;`.
I have added a new input parameter 'showLabel' and wrapped svg text label with it, using <ng-container *ngIf>, but I am not sure I am ready for PR now, maybe I can try to do that after your next release with customizable margins, or you know better way how to customize also 'hide/show' label functionality with correct padding of PieGridComponent.
Thank you very much!

**Comment by marjan-georgiev** [comment]
@furevor could you check whether this PR solve all of that for you, please? https://github.com/swimlane/ngx-charts/pull/1000

**Comment by furevor** [comment]
> @furevor could you check whether this PR solve all of that for you, please? #1000

I have added some comments to this PR, this all are important changes which I also have implemented in my copy component previously, but not exactly all I was talking about. I need to hide [this](https://monosnap.com/file/ePNCksbxU37fGRzgvMQPjALNfWQLUm)'Total' label, but when I just hide or delete it, I am getting extra margins like [this](https://monosnap.com/file/DAOJRpHrA0iXLYOGQ00En0lbVnM34a)

And for now I don't know how to fix it properly
