### ISSUE TITLE
Gauge Chart Label w/o Units Text

### ISSUE THREAD

**Issue by theHellyar** [swimlane/ngx-charts#230]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When the gauge chart does not have a units label the value label is not centered.

**Expected behavior**

If the units label is removed then the remaining value label should center in the gauge.

**Reproduction of the problem**

Set the gauge chart to 360 degree gauge and remove the text for the unit label notice the uncenters value label. This can be seen on the demo page or plunker.

**What is the motivation / use case for changing the behavior?**

I am using the gauge chart at 360 degree for a circular progress bar with only the number int he center

**Please tell us about your environment:**

VS Code
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 3.1.1 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.2 Build version 8C38

* **ngx-charts version:** 4.1.2

* **Angular version:** 2.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Ionic 2 - Safari and Android

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
2.0.9

**Comment by gnomeontherun** [comment]
I just wrote some CSS to hide that text element, but it would be nice to be able to disable this as an option.

**Comment by vgreddyrontala** [comment]
I had a solution for hiding the Gauge chart middle text.

<ngx-charts-gauge
[view]="view" *ngIf="radioData else noradioData"
[scheme]="colorScheme"
[results]="radioData"
[min]="0"
[max]="100"
[angleSpan]="240"
[startAngle]="-120"
[margin]="margin"
[bigSegments]="10"
[smallSegments]="5"
[tooltipDisabled]="false"
[valueFormatting]="hideShowText"
[animations]="animations" >

By using [valueFormatting]="hideShowText", in component part we need to write below function

hideShowText(showText){
//console.log(showText)
}

That's it data will hide

**Comment by Joydip-Paul** [comment]
Add a custom function "hideNumber()" and bind it to the chart in HTML. Example: [valueFormatting]="hideNumber"

<ngx-charts-gauge [results]="data" [legend]="legend" 
    [valueFormatting]="hideNumber">
</ngx-charts-gauge>

 hideNumber(data: any) {
    return '';
  }
