### ISSUE TITLE
Stacked bar chart negative values issue

### ISSUE THREAD

**Issue by ForteUnited** [swimlane/ngx-charts#233]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Negative values when using the stacked bar charts causes strange behavior and the rendering with regards to the axis is incorrect. In the plunkr example you will see that the x-axis labels are not visible when there are negative values. Furthermore, the stack colors are incorrect. The negative values are for Cash Flow which should be yellow, yet they are red which is incorrect.

**Expected behavior**
The expected behavior is to have no visual strangeness as related to the portions of the stacked bars (incorrect coloring) and correct axis label placement. 

**Reproduction of the problem**
https://plnkr.co/edit/mucm31?p=preview

**What is the motivation / use case for changing the behavior?**
So that the chart does what it is designed and intended to do.

**Please tell us about your environment:**
See plunkr demo of problem.

* **ngx-charts version:** x.x.x
See plunkr demo of problem.

* **Angular version:** 2.x.x
See plunkr demo of problem.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tested in Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Interesting case - we want to stack two positive values and a negative one. How would you expect that to look like? Stack the positive ones above the zero, and negative ones in the opposite direction below it?

We currently sum the values, which is why it looks like that when you try to stack a negative value.

**Comment by ForteUnited** [comment]
Yes, I was expecting the positive ones to be above zero, and the negative ones to be below zero also stacked but going down if there are multiple negative segments. This is for a cash flow projection so the "cash flow" series in Year 1 when financing is generally considered an outflow/negative value due to the cost of acquiring the asset. If you've acquired a good asset, cash flow should start to turn positive soon thereafter.

**Comment by marjan-georgiev** [comment]
Great, thanks for the explanation.

**Comment by cipri-p** [comment]
I can see that there is a PR for this one. Any timelines when this would be available?

**Comment by marjan-georgiev** [comment]
The PR has been merged, this will be in the next release.
