### ISSUE TITLE
LineChart: Condensed axis values with fit-container setting are not restored on resize.

### ISSUE THREAD

**Issue by HitomiTenshi** [swimlane/ngx-charts#236]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When resizing the window height or width, the line-chart component reduces the amount of values displayed on the axis if the window gets too small.

Those values are not restored when the window height / width gets bigger again, leaving the line-chart without a Y-Axis / X-Axis. **(Happens only with `number` type values)**

All axis values that were condensed during resize are lost. This is really a problem for us, because we are also shipping an electron version of our app, which does get resized a lot.

**Expected behavior**
Axis values get restored when height / width changes.

**Reproduction of the problem**
- Visit your demo site: https://swimlane.github.io/ngx-charts/
- Enable: Dimensions -> Fit Container
- Open up the line chart type
- Resize the window height, make it so small, that the chart is forced to condense all Y-Axis values
- Restore the window height
- **Result: The Y-Axis is missing.**

You could also try and make it just small enough to condense a few values, then make the height bigger again. You will see that all condensed Y-Axis values are gone.

**What is the motivation / use case for changing the behavior?**
We are shipping an electron app, which gets resized a lot, making those axis values disappear.

**Please tell us about your environment:**
OS: Windows 10 Pro x64
IDE: Atom
Node: 7.5.0

* **ngx-charts version:** 4.1.2

* **Angular version:** 2.4.8

* **Browser:** Chrome 56 | Firefox 51

* **Language:** TypeScript 2.0.10

**Comment by HitomiTenshi** [comment]
I just noticed that when using numbers for X-Axis values, then they disappear as well if the width gets too small.

**Comment by marjan-georgiev** [comment]
Disappearing is by design, to prevent overlap. However, they should appear again when you resize it back, which is a bug.

**Comment by HitomiTenshi** [comment]
Yeah, sorry if I wasn't clear enough. That's what I was trying to say.
