### ISSUE TITLE
ngx-charts doesn't work with IE 11

### ISSUE THREAD

**Issue by HitomiTenshi** [swimlane/ngx-charts#237]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Crashes when trying to load the library.

![iexplore_2017-02-22_12-50-17](https://cloud.githubusercontent.com/assets/7304212/23210362/85ee99a4-f8fd-11e6-8391-377b21bf039a.png)

**Expected behavior**
Does not crash.

**Reproduction of the problem**
Visit your demo site with IE 11: https://swimlane.github.io/ngx-charts/

**Please tell us about your environment:**
OS: Windows 10 Pro x64
IDE: Atom
Node: 7.5.0

* **ngx-charts version:** 4.1.2

* **Angular version:** 2.4.8

* **Browser:** IE 11

* **Language:** TypeScript 2.0.10

**Comment by amcdnl** [comment]
Angular2 doesn't support IE11. See https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by marjan-georgiev** [comment]
Include the classList polyfill referenced here:
https://angular.io/docs/ts/latest/guide/browser-support.html#!#classlist

**Comment by HitomiTenshi** [comment]
Oh thanks, I will do that on my site.

The bug I showed there happened on your [demo site](https://swimlane.github.io/ngx-charts/) though. So I was assuming that it wasn't working.

**Comment by marjan-georgiev** [comment]
@HitomiTenshi did that work for you?

**Comment by HitomiTenshi** [comment]
@marjan-georgiev Including es6 shims and after that the classList polyfill worked! At least the the line chart.

**Comment by benitocyrille** [comment]
sorry but i have a similar issue wit IE11, my chart displays well on Chrome and Mozilla some advises please

import { BrowserAnimationsModule } from '/animations';
import { NgxChartsModule } from '@swimlane/ngx-charts';

ERROR Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'contains'
TypeError: Object doesn't support property or method 'contains'

<ngx-charts-line-chart [scheme]="colorScheme" [(results)]="data" [gradient]="gradient" [xAxis]="showXAxis" [yAxis]="showYAxis"
[legend]="showLegend" [autoScale]="autoScale" [timeline]="timeline" [roundDomains]="roundDomains" (select)="onSelect($event)">

**Comment by yodamad** [comment]
this polyfill.ts works for me

`
import 'core-js/es6';
import 'core-js/es7/array';
import 'core-js/es7/reflect';
import 'core-js/client/shim';
import 'classlist.js';
import 'intl';
require('zone.js/dist/zone');

// IE11 fix
if (typeof SVGElement.prototype.contains == 'undefined') {
  SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}
`

require yarn add classlist.js intl
