### ISSUE TITLE
LineChart: Gradients on hovered points not visible when using hash location strategy.

### ISSUE THREAD

**Issue by HitomiTenshi** [swimlane/ngx-charts#238]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
With hash location strategy (bug):
![chrome_2017-02-22_16-14-18](https://cloud.githubusercontent.com/assets/7304212/23217627/400f1e50-f91a-11e6-8deb-390d86061aa6.png)

Without hash location strategy:
![chrome_2017-02-22_16-11-10](https://cloud.githubusercontent.com/assets/7304212/23217639/45c91990-f91a-11e6-94c9-c5fe0f373f50.png)

**Expected behavior**
Gradients should show on both strategies.

**Reproduction of the problem**
- Enable hash location strategy
- Put a line chart on a url that isn't the root / url.
- Visit that url and hover over a point

**What is the motivation / use case for changing the behavior?**
When using electron, we are required to use the hash location strategy.

**Please tell us about your environment:**
OS: Windows 10 Pro x64
IDE: Atom
Node: 7.5.0

* **ngx-charts version:** 4.1.2

* **Angular version:** 2.4.8

* **Browser:** Chrome 56 | Firefox 51

* **Language:** TypeScript 2.0.10

**Comment by HitomiTenshi** [comment]
I just tried to fix the problem by removing `${pageUrl}` from `url()` references, but that doesn't quite fix it.

Removing `${pageUrl}` makes gradients work with the hash location strategy on every browser (duh).

But when it's removed, the gradients on the non hash location strategy stop working with **Firefox 51**.

Chrome on the other hand has no problems with that.

Is there a way to exclude the `pageUrl` when the main app is using a hash location strategy?

**Comment by marjan-georgiev** [comment]
Yes, this is a problem with referencing the gradients. We use absolute paths to reference them. You can't exclude them at the moment, but it might be possible to generate the correct absolute path when using hash location strategy.

The way we do that now is 
``
    const pageUrl = this.location.path();
    this.gradientId = 'grad' + id().toString();
    this.gradientFill = `url(${pageUrl}#${this.gradientId})`;
```
