### ISSUE TITLE
ngx line chart height issue in angular 2 tab component!

### ISSUE THREAD

**Issue by siddhantfulzele** [swimlane/ngx-charts#241]
ngx line chart height issue when first time plot in angular 2 tab component! any idea guys?
and if Im in active tab then plot will correctly plotted
![ngx line chart issue](https://cloud.githubusercontent.com/assets/13316739/23257085/344a42c4-f9e8-11e6-8f68-333c93a8be29.jpg)

**Comment by marjan-georgiev** [comment]
Could you provide a plunkr or a github repo where we can reproduce this?

**Comment by siddhantfulzele** [comment]
sorry! unable to provide plunkr!
Angular 2- how to add an event listener to the charts that can manually trigger update() from outside

**Comment by marjan-georgiev** [comment]
I am going to close this until we are able to reproduce it. If you can provide a reproducible example (plunkr or a github repo) I'd be happy to reopen and take a look.
