### ISSUE TITLE
line chart with different time stamps is not shown as expected

### ISSUE THREAD

**Issue by mburger81** [swimlane/ngx-charts#242]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Using this simple result object for my line-chart:
```
[{
    "name": "Armenia",
    "series": [
      {
        "value": 4300,
        "name": "2016-09-20T06:52:31.057Z"
      },
      {
        "value": 4527,
        "name": "2016-09-22T06:52:31.057Z"
      },
      {
        "value": 2053,
        "name": "2016-09-24T06:52:31.057Z"
      }
    ]
  },
  {
    "name": "Guatemala",
    "series": [
      {
        "value": 5212,
        "name": "2016-09-20T06:52:31.057Z"
      },
      {
        "value": 5622,
        "name": "2016-09-21T06:52:31.057Z"
      },
      {
        "value": 6351,
        "name": "2016-09-24T06:52:31.057Z"
      }
    ]
  },
  {
    "name": "Laos",
    "series": [
      {
        "value": 4000,
        "name": "2016-09-20T06:52:31.057Z"
      },
      {
        "value": 5867,
        "name": "2016-09-23T06:52:31.057Z"
      },
      {
        "value": 6045,
        "name": "2016-09-24T06:52:31.057Z"
      }
    ]
  }
];
```
Draws me a front line chart. The x-axis is not a time line, as you can see at first there is day 2016-09-20 on second there is 2016-09-22 and then 2016-09-24 and then the 2016-09-21 and 2016-09-23.

![image](https://cloud.githubusercontent.com/assets/3778892/23266351/d6ceb10c-f9e7-11e6-99b5-a1e42fe64954.png)

**Expected behavior**
I think this is working if value is a simple number as 1, 2, 3, 4, 5. But for a date this is not workind, I don't know if we have to format the date, but the result array is copied from your demo.

working and expected result for numbers

![image](https://cloud.githubusercontent.com/assets/3778892/23266627/a02f52ae-f9e8-11e6-937b-8907171f348b.png)

* **ngx-charts version:** **4.1.3**

* **Angular version:** **2.4.8**

**Comment by marjan-georgiev** [comment]
The dates need to be actual date objects. If you look at how we generate that data, you will see that these are javascript date objects: https://github.com/swimlane/ngx-charts/blob/master/demo/data.ts#L269

**Comment by mburger81** [comment]
Yea sorry, showing your example data I assumed the string is passed and recognized as Date automatically by the lib!
So anything is working as expected thx a lot!
