### ISSUE TITLE
Grouped charts with different types

### ISSUE THREAD

**Issue by mareknovotny** [swimlane/ngx-charts#243]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[] support request => Please do not submit support request here
```

**Current behavior**
I can use Grouped Bar charts (horizontal/vertical) to show multiset data, but this is more for data of the same type

**Expected behavior**
What I need is to show multi set data of different types like population numbers and related counts of sex for instance. This could be nice to use bar chart and line chart together

**What is the motivation / use case for changing the behavior?**
I can reduce the place i need in the page with combined charts, this could be probably documented as a demo or example how to quickly combine two or more types of charts. It doesn't require to be implemented as a new chart type in ngx-charts, but it could be helpful too. I haven't found any guidance on this type of customization and would appreciate the help and contribute it back if it works.

* **ngx-charts version:** 4.1.3

* **Angular version:** 2.4.5

* **Language:** [TypeScript 2.1.x | ES5]

**Comment by marjan-georgiev** [comment]
A combination of bar and line chart has been implemented as a demo and can be seen here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

The code for the custom chart can be found here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart
