### ISSUE TITLE
Not set VIEW attribute doesn't fit container and render chart with height and width = 0 

### ISSUE THREAD

**Issue by mareknovotny** [swimlane/ngx-charts#244]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I found the issue #170 which reported problem with rendering chart in hidden element/container
The fix seems break the case when the view attribute is not set at all in html template. It effectively renders chart with 0 for height and width. The workaround is to set view always to a value of width and height.

**Expected behavior**
a chart still fits the container in which is placed even without set view from html template element.  

**Reproduction of the problem**
it is reproducable on https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical.html when you remove line with view attribute

* **ngx-charts version:** 4.1.3
* **Angular version:** 2.4.5

**Comment by marjan-georgiev** [comment]
Try setting height (or min-height) to the parent container.

**Comment by marjan-georgiev** [comment]
Here's a modified plunkr which works fine:

https://plnkr.co/edit/XJSkWpIupqTRC2eJalUP?p=preview

**Comment by jsight** [comment]
I think in previous releases, we had only set width. It seems strange to me that height would be required, but not width. Are the behaviors around this documented?

**Comment by marjan-georgiev** [comment]
It's always been the height. If you add an empty div to a page, it will have height 0, but the width will fit its parent width.

When you add a chart inside that div, the chart will measure the dimensions of the div, and it will see that the height is 0, so it won't render itself. That is why you need to set the height of the parent div.

**Comment by jsight** [comment]
You can say "always", but our previous (working with 3.x) style for the parent was:

    .chartBoundary {
        width: 500px;
        margin: 20px auto;
    }

I'm not sure what changed to cause the parent div to measure zero, but it seems like something did. Maybe it was some new CSS in ngx-charts.

**Comment by marjan-georgiev** [comment]
@jsight if you remove the chart from that container, what is its width?

Also, can you tell me the exact version of ngx-charts that this worked in?

**Comment by mareknovotny** [comment]
we upgraded from 3.0.2

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
