### ISSUE TITLE
request time series (historical) bar chart

### ISSUE THREAD

**Issue by byunru** [swimlane/ngx-charts#264]
link to 
https://github.com/swimlane/ngx-charts/issues/219

Need a historical bar which the data is not evenly distributed on time series, for example:
http://plnkr.co/edit/w9LnjVxWFCSkU3Vxs7pU?p=preview
I hope ngx charts can provide an easy way to achieve the above chart,
not like this: https://plnkr.co/edit/1k0QicwypV4aZNabisTM?p=preview
although the line chart looks good for time series:
https://plnkr.co/edit/NQu9XUigb8ffRimkp8Fu?p=preview

**Comment by marjan-georgiev** [comment]
The x scale on the bar charts is ordinal. To get what you want, you would need to fork the bar chart you want to use and modify the xScale to be a timeScale instead of ordinal.

**Comment by byunru** [comment]
Can't bind to 'xScale' since it isn't a known property of 'ngx-charts-bar-vertical'. ?

**Comment by marjan-georgiev** [comment]
Correct, you can't pass this as an input. You would need to implement a custom bar chart and change the xScale yourself.

**Comment by byunru** [comment]
Is it possible to add a baseline chart component for this senario to the demo site?
https://swimlane.github.io/ngx-charts

**Comment by byunru** [comment]
@marjan-georgiev 

follow up with the above request "add a baseline chart component for time series (historical) bar chart to the demo site"
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical

Thanks

**Comment by SRozdobudko** [comment]
hi, how i can use:

customColors | object |   | custom colors for the chart. Used to override a color for a specific value

i have: 
    <ngx-charts-line-chart *ngIf="params?.replaceFilter"
      [view]="view"
      [scheme]="colorScheme"
      [results]="multi"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [xAxisLabel]="xAxisLabel"
      (select)="onSelect($event)">
    </ngx-charts-line-chart>

Your documentation mentions only the custom color. But no more, I want to change the color of the line after some value, I hope you can help me with this. It will be nice if you show an example code

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
