### ISSUE TITLE
Problem Running npm runScript "package"

### ISSUE THREAD

**Issue by lvanngo** [swimlane/ngx-charts#265]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I get the following error when updating release folder for my forked version: Error: Cannot find module '../dist'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/linhvanngo/cpi/nos2/ngx-charts/node_modules/cross-env/dist/bin/cross-env.js:4:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/Users/linhvanngo/.npm-packages/lib/node_modules/npm/bin/npm-cli.js" "run" "build:package"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! @swimlane/ngx-charts@4.2.0 build:package: `cross-env NODE_ENV=package npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @swimlane/ngx-charts@4.2.0 build:package script 'cross-env NODE_ENV=package npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @swimlane/ngx-charts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=package npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @swimlane/ngx-charts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @swimlane/ngx-charts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/linhvanngo/cpi/nos2/ngx-charts/npm-debug.log
ERROR: "build:package" exited with 1.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/Users/linhvanngo/.npm-packages/bin/npm" "runScript" "package"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! @swimlane/ngx-charts@4.2.0 package: `npm-run-all -s clean copy:build build:sass package:replace-scss package:aot build:package package:replace package:minify copy:styles clean:build`
npm ERR! Exit status 1
**Expected behavior**

Could you please let me know if it's my node and npm version?
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

I am blocked from releasing a needed feature.
**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by lvanngo** [comment]
I think it's just a lock down of cross-env version.  Will try this.

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
