### ISSUE TITLE
Ticks are rotated based on original tick value rather than formatted tick value

### ISSUE THREAD

**Issue by harshithkashyap** [swimlane/ngx-charts#267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Ticks rotated by angle based on https://github.com/swimlane/ngx-charts/commit/6a67e4e8fce242f6bdcbb862d96ef2e42b63c872

**Expected behavior**
When `xAxisTickFormatting` function is passed, ticks are rotated based on original tick value rather than the value returned from the function passed by user to `xAxisTickFormatting`
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Ticks are rotated even when they are run through a formatting function and the text doesn't overflow.

* **ngx-charts version:** 4.2.0

* **Angular version:** 2.4

* **Browser:** [all]

* **Language:** [all]

**Comment by williangd** [comment]
I have this problem too.. 
Value: 1521555799 (Time in seconds)
Formatted Value: Domingo 10:33:20

When i pass the value in seconds (1521555799), tick don't rotate.
![no rotate](https://user-images.githubusercontent.com/16259047/37673242-7a34f2ae-2c4e-11e8-88b6-b904ccdc8435.png)

If I pass the value with more characters (time in milliseconds 1521555799000) tick rotate correctly.
![rotate](https://user-images.githubusercontent.com/16259047/37673241-7a09a68a-2c4e-11e8-9d3c-1ddb513ce1f6.png)


.

**Comment by marjan-georgiev** [comment]
This should be resolved in the latest version.
