### ISSUE TITLE
Which version of D3 needs to installed?

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-charts#268]
**I'm submitting a ...**  

[x ] bug report
[ ] feature request
[ ] support request

**Current behavior**
I've installed D3 using "npm install d3 --save" which install version 4.7.1
When I installed ngx-charts, I'm observing error in resolving D3.

```
c:\my-git-ws\heat-map-demo>npm install @swimlane/ngx-charts --save
heat-map-demo@0.0.0 C:\rahul-singhai\my-git-ws\heat-map-demo
+-- @swimlane/ngx-charts@4.2.0
+-- UNMET PEER DEPENDENCY d3@4.7.1
`-- UNMET PEER DEPENDENCY rxjs@5.2.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @swimlane/ngx-charts@4.2.0 requires a peer of d3@4.4.0 but none was installed.
npm WARN @swimlane/ngx-charts@4.2.0 requires a peer of rxjs@5.0.3 but none was installed.

```

This clearly indicates something is not right

**Expected behavior**
Please help me to resolve D3. Which version of D3 I need to install.

**Reproduction of the problem**
Need information on D3 supported version

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Node version : 6.9.1

* **ngx-charts version:** 4.2.1

* **Angular version:** 2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web 
NA

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

Kindly let me know if you need more information

Thanks. Rahul

**Comment by marjan-georgiev** [comment]
The current version has been built and tested with d3 version 4.2.x

We will be upgrading the d3 version in the next major release, because it introduces breaking changes.
