### ISSUE TITLE
Ngx-Charts 4.2.1 Not showing any result

### ISSUE THREAD

**Issue by WebTalentTop** [swimlane/ngx-charts#275]
Help me. Why can't I see any result with ngx-charts?
I tried to refer to its demo but failed.
Could please guide me?

**Comment by marjan-georgiev** [comment]
Please ask questions like this in the gitter chat.

**Comment by WebTalentTop** [comment]
I am sorry for my rough description.
Now I am trying to integrate ngx-charts to my pages.
I have imported NgxChartModule on top of my ts file.
And Do I have to generate module.ts, bootstrap.ts as the demo shown?
For now, I am not what I should do.
Please give me a guidance.
