### ISSUE TITLE
Ngx-charts integration

### ISSUE THREAD

**Issue by WebTalentTop** [swimlane/ngx-charts#276]
Now I am trying to integrate ngx-charts to my pages.
I have imported NgxChartModule on top of my ts file.
And Do I have to generate module.ts, bootstrap.ts and follow all as the demo shown?
I have wrote ngx-chart directive on html file like as demo.

When I inspect the page, I can see its inner code at demo.
<div class="ngx-charts-outer" style="width: 700px;">
      <svg class="ngx-charts" width="583.3333333333334" height="300">
        .....

But on my page, I can't see any generated code.
So, there is no chart result on my page.
For now, I am not sure what I should do.
Please give me a guidance.

Is it possible to integrate this ngx-charts to the system which doesn't support webpack?
This is very important question, I think.

**Comment by marjan-georgiev** [comment]
Again, questions like these should be asked on the gitter chat, not here. Please use this board for reporting bugs and feature requests.

Yes, ngx-charts does work with system.js, as show here: https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical.html
