### ISSUE TITLE
Need a Single Pie Grid Using % or allow total for creating the percentage

### ISSUE THREAD

**Issue by RPbarfield** [swimlane/ngx-charts#289]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
With the Pie Grid, a single grid displays at 100% no matter what the value is. 

**Expected behavior**
I would like to provide a percent value (or a total value to create the percentage) that will allow the single chart to show the correct percentage.

**Reproduction of the problem**
Just create the pie grid with a single data entry.

**What is the motivation / use case for changing the behavior?**
More flexibility to show the pie grid as a single visualization, along with the ability to show it in groups.

**Please tell us about your environment:**
OSX, Angular 2, TypeScript 2, WebPack 2

* **ngx-charts version:**
4.2.0

* **Angular version:** 
2.4.2

* **Browser:** 
All

* **Language:**
TypeScript 2.1.5

**Comment by marjan-georgiev** [comment]
You can achieve something like that with a gauge chart:

https://plnkr.co/edit/6CcmoSwce3v3vIjdyRkb?p=preview

**Comment by RPbarfield** [comment]
Perfect! Thanks.
