### ISSUE TITLE
legendTitle should be configurable.

### ISSUE THREAD

**Issue by PolarbearDK** [swimlane/ngx-charts#290]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
ChartComponent (ngx-charts-chart) has:
@Input() legendTitle = 'Legend';
but the component is embedded inside other chart components without the abillity to configure this input.

**Expected behavior**
All charts with legends should have an @Input() legendTitle that is forwarded to ChartComponent

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Use other language than english.

**Please tell us about your environment:**
all

* **ngx-charts version:** x.x.x
4.2.1

* **Angular version:** 2.x.x
2.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

**Comment by marjan-georgiev** [comment]
I agree. We should add that as an input to all charts that have a legend.

**Comment by PolarbearDK** [comment]
This has been fixed! Thanks!
