### ISSUE TITLE
Support for Angular 4

### ISSUE THREAD

**Issue by jvbianchi** [swimlane/ngx-charts#299]
Does this library has support for Angular 4?

**Comment by marjan-georgiev** [comment]
Not yet. It will be added in version 5.0.0

**Comment by Opticsponge** [comment]
it works now with angular 4 but you have to turn off aot

**Comment by marjan-georgiev** [comment]
Version 5.0.0 should work with angular 4. Please let me know if you see any problems.

**Comment by metavurt** [comment]
I know it's closed, but rock n roll, it's all a go for me! **Thank you!**
