### ISSUE TITLE
Make animation timeout and duration configurable

### ISSUE THREAD

**Issue by zheffie** [swimlane/ngx-charts#300]
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Animation timeouts and durations are hardcoded. 

**Expected behavior**
Make them configurable

**Comment by marjan-georgiev** [comment]
This is a valid request. We can implement turning animations on/off, but I'm not sure if it's possible to configure duration of animations in angular's animation framework.
