### ISSUE TITLE
Ability to set a custom tick format for tooltips

### ISSUE THREAD

**Issue by Pennywise83** [swimlane/ngx-charts#308]
Hi,
I think that introduce the ability to set a custom tick format for tooltips would be a very useful feature .

Actually I have a dataset with all the keys in epoch timestamp. Through xAxisTickFormatting i convert it to human readable date, but the tooltip shows the raw timestamp.

**Comment by marjan-georgiev** [comment]
This is a valid request. There was also a suggestion to allow passing an angular template as the tooltip body, which would be even better and allow bigger customization of tooltips.

**Comment by marjan-georgiev** [comment]
Going to close this as it is covered by https://github.com/swimlane/ngx-charts/issues/65
