### ISSUE TITLE
New lines in xAxisTickFormatting and yAxisTickFormatting

### ISSUE THREAD

**Issue by Pennywise83** [swimlane/ngx-charts#309]
Is it possible to return a string value in two or more lines through xAxisTickFormatting and yAxisTickFormatting? 

Actually if I try to return 

> return '<tspan x="0" dy="0">' + moment(new Date(parseInt(a))).format('DD/MM/YYYY') + ' < /tspan>' + '<tspan x="0" dy="1em">' + moment(new Date(parseInt(a))).format('HH:mm:ss') + '</tspan > ';

All the value is converted to string and I'm not able to write the labels in new lines.

**Comment by marjan-georgiev** [comment]
Not possible at the moment. Axis labels are all single lines. Allowing multi-line tick labels would make it much harder to prevent axis label overlap, so I don't think it is a great idea to do that.

**Comment by josechifflet** [comment]
Is the issue still unsolved? @marjan-georgiev @Pennywise83
