### ISSUE TITLE
Charts behaving erratically populated dynamically or in loop

### ISSUE THREAD

**Issue by WillNye** [swimlane/ngx-charts#316]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When attempting to redefine the chart data or creating multiple charts with unique data the chart has issues with animation, plot points, and color scheme. I observed this on both area and line chart.

**Reproduction of the problem**
GIf of issue: http://imgur.com/a/VN5XJ

Code:
```
  <div *ngFor="let graph of graphData">
    <!--<div *ngIf="graph.name === graphForm.value.groupBy">-->
      <div class="col s12 m8 z-depth-3 offset-m2"
         style="margin-top: 3em; padding-bottom: 2.5vw; padding-top: 2.5vw"
         *ngIf="!isLoading">
          <ngx-charts-area-chart
            class="chart-container"
            [scheme]="graph.settings.colorScheme"
            [schemeType]="graph.settings.schemeType"
            [results]="graph.settings.data"
            [legend]="graph.settings.showLegend"
            [gradient]="graph.settings.gradient"
            [xAxis]="graph.settings.showXAxis"
            [yAxis]="graph.settings.showYAxis"
            [showXAxisLabel]="graph.settings.showXAxisLabel"
            [showYAxisLabel]="graph.settings.showYAxisLabel"
            [xAxisLabel]="graph.settings.xAxisLabel"
            [yAxisLabel]="graph.settings.yAxisLabel"
            [autoScale]="graph.settings.autoScale"
            [timeline]="graph.settings.timeline"
            [showGridLines]="graph.settings.showGridLines"
            [curve]="graph.settings.curve"
            [roundDomains]="graph.settings.roundDomains"
            [tooltipDisabled]="graph.settings.tooltipDisabled"
            style="min-height: 100vw">
          </ngx-charts-area-chart>
      </div>
    <!--</div>-->
  </div>
```

**Please tell us about your environment:**
Ubuntu 16.04

* **ngx-charts version:** x.x.x
4.4.0

* **Angular version:** 2.x.x
2.3.1

* **Browser:** 
Chrome Version 57.0.2987.133 (64-bit)

**Comment by marjan-georgiev** [comment]
It looks like the domain got resorted. Could you try using a date scale instead of an ordinal one?

Try making your dates in the data actual javascript date objects, instead of strings (as they are now).

**Comment by WillNye** [comment]
@marjan-georgiev 
Thanks for the quick response! I converted to date objects instead but I'm still getting the same issue. Here's the code and I logged date_as_object to verify it correctly converted.

```
            let date_split = a['the_date'].split('-');
            const the_date = date_split[0] + '/' + date_split[1] + '/' + date_split[2];
            const date_as_object = new Date(the_date);
```

Console:
`Sat Dec 03 2016 00:00:00 GMT-0600 (CST)`

**Comment by WillNye** [comment]
@marjan-georgiev 
As a follow up test I used the day (int 1-31) and subsequent charts still displaying incorrectly. Could charts of the same type be using a global var that is causing collisions? I'll throw the gif and code up on here in a couple minutes!

**Comment by marjan-georgiev** [comment]
Any chance you can reproduce this in plunkr? Would help a lot to identify the issue.

**Comment by WillNye** [comment]
@marjan-georgiev 
No problem!
This is a smaller dataset so the issue isn't as pronounced but you can see that the upper graphs appear to lose data in the chart but not the lower as was the issue in mine. 

https://plnkr.co/edit/eOwpsj?p=preview

**Comment by marjan-georgiev** [comment]
The differences between the data points on the top chart are too big, so two of the areas are near the bottom. I updated the data to make them closer to each other, and it is rendering fine:

https://plnkr.co/edit/50sjQgnKlr5ubQVAqR1I?p=preview

**Comment by WillNye** [comment]
It turns out that there was an issue with the incoming data that was causing this issue occasionally.
