### ISSUE TITLE
Number charts with any array length

### ISSUE THREAD

**Issue by calebeaires** [swimlane/ngx-charts#318]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
With an array length by 10, charts goes as this image.

**Expected behavior**
Just show 10 boxes

![captura de tela 2017-04-10 as 15 09 34](https://cloud.githubusercontent.com/assets/794195/24875914/179626de-1e00-11e7-88f5-419b0d840253.png)

**Comment by Hypercubed** [comment]
That is by design.  The number cards are always displayed in a grid.  You can change the color of the empty card using the `[emptyColor]` input.

**Comment by calebeaires** [comment]
That`s it. Thanks!
