### ISSUE TITLE
Feature Request: A way to disable circle creation for all the data items on a line chart

### ISSUE THREAD

**Issue by richavyas** [swimlane/ngx-charts#319]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When hovered on a line chart, it shows all the data points as hovered. I tried adding the following CSS:
```
.circle {
       visibility: hidden;
}

.circle:hover {
       visibility: visible;
}

```
these styles just hide the circles but still create `g tags` and attach them to DOM. It is a performance hit in case of huge data set.

**Expected behavior**

Only the data point hovered should be hovered and not all the points on the line.

**Reproduction of the problem**
Create a line chart with 100 data points and check.

**What is the motivation / use case for changing the behavior?**
There should be a way that a flag can be passed through the template `ngx-charts-line-chart` e.g. 
```
circleHoverDisabled = true/false
```
and based on this variable, data entries should be set.

***Please let me know if this approach looks fine to you. I'll create a PR for this.***

**Please tell us about your environment:**

- OS - MAC
- IDE - Code
- NPM
- Node

* **ngx-charts version:** x.x.x
5.0.0

* **Angular version:** 2.x.x
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
This should be addressed in 6.0.0.
