### ISSUE TITLE
Are there compound charts available? Or ways in which we can make one? Combine two or more charts?

### ISSUE THREAD

**Issue by shivkumarganesh** [swimlane/ngx-charts#322]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

Is there a way to make a compound chart of combine two charts together? I am not able to find this. Please assist.

**Comment by Hypercubed** [comment]
Most (perhaps all) ngx charts are composed of angular components that may be combined to create custom charts.

**Comment by amcdnl** [comment]
Not out of the box, but you can easily compose multiples to accomplish this. Its on our roadmap for out of the box support.
