### ISSUE TITLE
Number cards don't resize when value changes.

### ISSUE THREAD

**Issue by Hypercubed** [swimlane/ngx-charts#326]
**I'm submitting a ...**  (check one with "x")
bug report

**Current behavior**
The text in number cards are scaled based on the original value.  If the value changes the text is not properly scaled.

**Expected behavior**
If the value in a number changes it should set the font scale to match.

**Reproduction of the problem**

See https://plnkr.co/edit/30SEeg

![image](https://cloud.githubusercontent.com/assets/509946/25014326/82df1c8a-2034-11e7-9b2c-dfbb15bf8c2d.png)

**Comment by Hypercubed** [comment]
#330

**Comment by tqthong0911** [comment]
why it not working in my code ?
I change "get view" to "get view()" because error expected.
I copy code here.
![image](https://cloud.githubusercontent.com/assets/17449785/25313165/b7930b40-2853-11e7-9c57-96421d3255b7.png)
