### ISSUE TITLE
Using "ngx-charts-number-card" no free memory.

### ISSUE THREAD

**Issue by tqthong0911** [swimlane/ngx-charts#344]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I think it not free memory.
It takes too much ram and CPU.
it error when i copy thís code to angular CLI project.
**Expected behavior**

**Reproduction of the problem**

I copy code in example here
 ----> https://plnkr.co/edit/30SEeg?p=preview
and add to example 
https://github.com/marjan-georgiev/Angular-CLI-NG2D3-Demo/blob/master/src/app/custom-chart/custom.component.html

**What is the motivation / use case for changing the behavior?**

this ís picture i run issue 
https://github.com/swimlane/ngx-charts/pull/330

![image](https://cloud.githubusercontent.com/assets/17449785/25314041/115fcbd8-2866-11e7-8144-320ac5607267.png)

**Please tell us about your environment:**

Ubuntu 16.04

* **ngx-charts version:** 5.1.2

* **Angular version:** 4.1.0

* **Browser:** [all | Chrome 58.0.3029.81 (64-bit)

* **Language:** [all | TypeScript 2.2.0]

PS:
Why i can using "Fit Container" or button "APPLY DIMENSIONS" in my code ??
![image](https://cloud.githubusercontent.com/assets/17449785/25314791/b01f0fc8-2874-11e7-8372-3b7e9b785d3b.png)

**Comment by Hypercubed** [comment]
The memory issue was my bad code in the plunker, it is fixed now.  For your other issues can you please create separate tickets with more details.

**Comment by aleho70** [comment]
What was wrong? I had same problem that ngx-charts-number-card when was periodically refreshed then it has memory leak and stack was exhoused. Also other charts (not yet exactly detected which one) have same problem. I have big dashboard for 4k monitor with many charts, so it is not easy detect where is reason of the memory leak. I am using 7.3.0 version.

**Comment by leandromsa** [comment]
@aleho70 did you find what's causing the memory leak, if a send the array empty in the results everything works ok, but if i add one value, the memory usage just go up without stopping
