### ISSUE TITLE
tooltipText for Bar Charts and Line Charts

### ISSUE THREAD

**Issue by thormentor** [swimlane/ngx-charts#345]
There is some functionality like tooltipText, already implemented, for Bar and Line Charts. 
I really need something like this!

**Comment by JoshSchoen** [comment]
I agree this would be nice. We have use cases where we want to show actuals and % particularly in stack bar charts when not using the normalized version. Mentioned this briefly here #320.

**Comment by Hypercubed** [comment]
Yes, it is planned.  We implement this as needed.  If this is needed for bar and line charts, PRs are welcome.

**Comment by JoshSchoen** [comment]
Will do, wasn't sure if a PR was the route to take here. Happy to contribute!

**Comment by samaxes** [comment]
Can't we use the same functions used in `xAxisTickFormatting` and `yAxisTickFormatting` to format the tooltip text?

**Comment by marjan-georgiev** [comment]
The plan for tooltips is to allow passing a whole template, since there is room to be able to allow more customization for them. Please refer to this issue:

https://github.com/swimlane/ngx-charts/issues/65

**Comment by marjan-georgiev** [comment]
This was implemented in https://github.com/swimlane/ngx-charts/pull/399.
