### ISSUE TITLE
Format Text in the Legend, Word Wrapper?

### ISSUE THREAD

**Issue by thormentor** [swimlane/ngx-charts#346]
My problem is that sometimes my Legends are too big to fit the Legend container. 
Is there any way to wrap words, so that I can read all the text?

**Comment by marjan-georgiev** [comment]
You can override the css like this: https://plnkr.co/edit/uJiJYlDhLAWWueNFF6Mb?p=preview

**Comment by cb1544** [comment]
Hello,

Did you find a way to wrap your text ?
Can you share please ?

Thanks,
CB
