### ISSUE TITLE
Question: How to add more space for y axis label

### ISSUE THREAD

**Issue by khan4019** [swimlane/ngx-charts#351]
I need to increase the left side spacing to show the names. 

So that i can display full names in the following chart
![image](https://cloud.githubusercontent.com/assets/1848375/25393773/f77c580c-29a1-11e7-9d65-e19ab9ef3b02.png)

https://plnkr.co/edit/zNuT9JrmSHJIYCy0qNBb?p=preview

* **ngx-charts version:** 5.1.1

* **Angular version:** 4.0.2

.y.axis is a svg group and hence it doesn't take a width. Is there any work around to increase label spacing...

**Comment by marjan-georgiev** [comment]
This is not possible at the moment. The axis labels are truncated automatically.

**Comment by khan4019** [comment]
Thanks @marjan-georgiev  for your reply. I needed it for my project. Is there any plan to add this capability? If yes, please let me know the expected time so that i can inform my manager.

**Comment by marjan-georgiev** [comment]
This isn't planned for yet. We are open for discussion on whether it should be part of the charting library.

You can build a custom chart with the available components and modify the axis to enable it though.

**Comment by khan4019** [comment]
Thanks for the response... I will go with the custom chart option
