### ISSUE TITLE
Horizontal bar chart, Option to render Y axis values on the bars

### ISSUE THREAD

**Issue by dipcore** [swimlane/ngx-charts#354]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The only available option is to show|hide Y axis values. It's always rendered on the left and bars on the right. 

**Expected behavior**
A boolean option to enable rendering Y axis values right on the bars. 
[Optional] The format of values could be "{y_axis_value} - {x_axis_value}" ie "USA - 20.300"

Something like:
```
----------------------------------------------
| USA - 20.300                                |
----------------------------------------------
| Canada - 10.900     |
---------------------------------------
| UK - 19.000                         |
---------------------------------------
```

**Comment by GPranali** [comment]
Hello, any update on this ? I am using same feature to show values on bar.

**Comment by marjan-georgiev** [comment]
This is done.
