### ISSUE TITLE
Xaxis and Yaxis fix range values

### ISSUE THREAD

**Issue by castri1** [swimlane/ngx-charts#357]
Is it possible to set the X or Y axis to fixed lengths?

For example can I set the X axis to be in the range [-50, 100]
![image](https://cloud.githubusercontent.com/assets/11744035/25485455/9ecffe4c-2b23-11e7-8a89-827e86f8ec52.png)

**Comment by taimoor99** [comment]
any solution?

**Comment by marjan-georgiev** [comment]
This is supported by the `yScaleMax` and `yScaleMin` inputs.
