### ISSUE TITLE
[BUG] Dimension rounding causes wrong placement of the legend

### ISSUE THREAD

**Issue by HitomiTenshi** [swimlane/ngx-charts#360]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Commit 1eeddd2fe96686514810d216404026a681bfba70 causes line charts with the `fit container` setting to display their legend below the chart. The legend keeps swapping positions when data changes.

This only happens at certain window sizes.

![chrome_2017-04-28_16-50-15](https://cloud.githubusercontent.com/assets/7304212/25534332/bb6502c6-2c33-11e7-8cf2-f2809b36ec13.png)

I've testet undoing that commit and the legend then stays where it should be on all the window sizes that had this issue with this commit.

Is there any reason why rounding is necessary?

**Expected behavior**

Legend stays on the top right side of the line chart.

**Reproduction of the problem**

- run `npm start` with the latest code
- select line chart
- enable `fit container`
- now resize the window around, mine started jumping around at 1409x1279 window size, although it happens at other sizes too. Seems to be rounding errors that cause it to go below the chart.

**Please tell us about your environment:**
Windows 10 x64 Pro
node 7.9.0

* **ngx-charts version:** Current code from master branch
* **Angular version:** 4.1.0
* **Browser:** Chrome 58
* **Language:** TypeScript 2.2

**Comment by HitomiTenshi** [comment]
@Hypercubed The bug still happens with the fix you posted.

Commit 1eeddd2fe96686514810d216404026a681bfba70 also added rounding on file `src/common/charts/chart.component.ts`. I tested truncating these 2 lines as well instead of rounding and that seems to fix it.

Did you miss this change or does this need rounding on purpose?

**Comment by Hypercubed** [comment]
Not rounded on purpose.  I changed the minimum I thought necessary to fix the bug.  If you are able to submit a PR we would welcome it.
