### ISSUE TITLE
ng-template' is not a known element

### ISSUE THREAD

**Issue by JosephSKh** [swimlane/ngx-charts#363]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I run I get this:
```
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): TooltipContentComponent@9:10 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): TooltipContentComponent@9:10
```

**Expected behavior**
no console error logs

**Reproduction of the problem**
just initial implementation

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
latest

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment]
Latest version only works with Angular 4. See readme for info on 2.x version.

**Comment by JosephSKh** [comment]
@amcdnl thx for your reply, so which version shall I install? i'm installing 5.0.0 for now
and maybe you can create another one for V4? I think this is confusing. Thank you

**Comment by marjan-georgiev** [comment]
The readme clearly states to use version 4.x for angular 2.x

**Comment by JosephSKh** [comment]
thx
