### ISSUE TITLE
Number Card Chart throws error more than 10 items have 0 value

### ISSUE THREAD

**Issue by gnomeontherun** [swimlane/ngx-charts#365]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
It appears that the number card component doesn't like it if you have  11+ items in the `results` with a value of `0`. It works fine with 10 or fewer. The number of values with > 0 doesn't seem to matter.

Get error

```
NumberCardComponent.ngfactory.js:17 ERROR TypeError: Cannot read property 'replace' of undefined
    at hexToRgb (http://localhost:4200/vendor.bundle.js:97747:21)
    at invertColor (http://localhost:4200/vendor.bundle.js:97765:14)
    at http://localhost:4200/vendor.bundle.js:95450:141
    at Array.map (native)
    at CardSeriesComponent../src/number-card/card-series.component.ts.CardSeriesComponent.getCards (http://localhost:4200/vendor.bundle.js:95431:14)
    at CardSeriesComponent../src/number-card/card-series.component.ts.CardSeriesComponent.update (http://localhost:4200/vendor.bundle.js:95418:26)
    at CardSeriesComponent../src/number-card/card-series.component.ts.CardSeriesComponent.ngOnChanges (http://localhost:4200/vendor.bundle.js:95399:14)
    at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:10913:19)
//...down the rabbit hole
```

**Expected behavior**
I would expect it to not throw an error and render the items happily. Its sad enough that there are 11 cards with a 0 value.

**Reproduction of the problem**
https://plnkr.co/edit/PkZklOu0hqxNcd4OV5Uy?p=preview

Be sure to open console log.

**What is the motivation / use case for changing the behavior?**
No errors are cool.

**Please tell us about your environment:**
This is plunkr, but was using ngcli v1, OSX 10.12.4, Node 6.9.2, Chrome 58

* **ngx-charts version:** x.x.x
5.1.2

* **Angular version:** 2.x.x
4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by Hypercubed** [comment]
@gnomeontherun Thank you for reporting this.  I believe I have identified the bug and should have a fix soon.  For the moment you can work around this by adding an `emptyColor` input to the number-card component.  For example:

```
    <ngx-charts-number-card
      [scheme]="colorScheme"
      [results]="single"
      [emptyColor]="'#000'">
    </ngx-charts-number-card>
```

**Comment by gnomeontherun** [comment]
Thanks @Hypercubed that seems to workaround nicely!

**Comment by marjan-georgiev** [comment]
This should be fixed by https://github.com/swimlane/ngx-charts/pull/366
