### ISSUE TITLE
Does ngx-charts support mixed types in a single chart?

### ISSUE THREAD

**Issue by qiluo** [swimlane/ngx-charts#367]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
From the documentation, I didn't find any clue would ngx-charts support or not, looks like it doesn't

**Expected behavior**
I want a single chart can contains line chart and bar chart, or more

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
You would need to build a custom chart to do this. All of the components that you can use are exposed through the NgxChartsModule.

**Comment by qiluo** [comment]
Thanks for reply, but any idea how to build custom chart by using ngx-charts

**Comment by sjdemoor** [comment]
I would also like to see some example code which builds custom charts.  

I followed your example (https://medium.com/@amcdnl/charts-with-svgs-in-angular2-1d08a0e635ea), and was able to build a simple bar-chart.  But (using this repo to see how charts are assembled from base components), I was not able to get x/y axes to render, and got somewhat lost trying to add a line-chart to a bar-chart.

**Comment by marjan-georgiev** [comment]
This has been implemented as a demo and can be seen here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

The code for the custom chart can be found here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

**Comment by ChristofferArnlund** [comment]
Is there a possibility to see the code of the example "Line charts with reference lines"? https://swimlane.github.io/ngx-charts/#/ngx-charts/line-reference-lines

**Comment by DmitryEfimenko** [comment]
I really like the philosophy behind this charting library, but the API needs to be enhanced so that a consumer of the library doesn't need to bring in so much custom code into the repository. I mean, look at the https://github.com/swimlane/ngx-charts/blob/master/demo/combo-chart/combo-chart.component.ts. That does not look easy
