### ISSUE TITLE
Expect text and unit font size could be customised in gauge chart

### ISSUE THREAD

**Issue by qiluo** [swimlane/ngx-charts#371]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**
Hopefully user can customise font size for these two labels, thanks

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
The text and unit fonts automatically scale with the chart, so we can not allow overriding those without breaking responsiveness.

**Comment by qiluo** [comment]
But if set showAxis=false, the inner texts (value and unit) would be very large

**Comment by pmadhavan** [comment]
Yes, I agree with @qiluo  this is how my gauge looks if I set showAxis=false
![image](https://user-images.githubusercontent.com/22695227/32118403-7423dc7c-bb06-11e7-9e7e-7fb46abc595e.png)

```
<ngx-charts-gauge
  [results]="base"
  [min]="0"
  [max]="100"
  [units]="'%'"
  [angleSpan]="180"
  [startAngle]="-90"
  [showAxis]="false"
  (select)="onSelect($event)">
```

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.

**Comment by mokhz** [comment]
Hello. I have this issue as well. I'm using the gauge chart to display my state of charge. Is there any way to just display the value with a % sign next to it?

**Comment by mokhz** [comment]
> Hello. I have this issue as well. I'm using the gauge chart to display my state of charge. Is there any way to just display the value with a % sign next to it? https://i.gyazo.com/95c75c7b15bab799fe840595ffc32e05.png
> This is how it looks currently.

Hello again. I solved this issue by using valueFormatting. However, when I first used a valueFormatting function it started to kill the performance since I hadn't changed my ChangeDetectionStrategy, so make sure you use 

changeDetection: ChangeDetectionStrategy.OnPush

**Comment by vgreddyrontala** [comment]
I had a solution for hiding the Gauge chart middle text.

<ngx-charts-gauge
[view]="view" 
[scheme]="colorScheme"
[results]="radioData"
[min]="0"
[max]="100"
[angleSpan]="240"
[startAngle]="-120"
[bigSegments]="10"
[smallSegments]="5"
[tooltipDisabled]="false"
[valueFormatting]="hideShowText"
[animations]="animations" >

By using [valueFormatting]="hideShowText", in component part we need to write below function

hideShowText(showText){
//console.log(showText)
}

That's it data will hide
![noLabel](https://user-images.githubusercontent.com/5131391/95172120-7efe7a80-07d4-11eb-83fa-f25dbbcc0f4a.png)
