### ISSUE TITLE
Real Time Data Integration with AngularFire2 Observables

### ISSUE THREAD

**Issue by kacase** [swimlane/ngx-charts#379]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I connected a chart from ngx chart to an observable from AngularFire2, which allows real-time data updates through a web socket.

Updated Data gets recongnized correctly and the chart does display it. However a full rerender of the chart happens, with all bars/pie segments animating from 0 and not from the previous value.

**Expected behavior**
When data updates, the graph should not animate from 0 but from the previous value.

Otherwise there should be no animation.

**Please tell us about your environment:**
OSX 10.12.5 Sierra
HTTP Server

* **ngx-charts version:**
5.1.2

* **Angular version:**
4.1

* **Browser:** 
Chrome 57
Safari 10.2, WebKit 12604.1.19.0.1, TP 29
IE 11

* **Language:** 
Typescript

**Comment by marjan-georgiev** [comment]
Can you provide a demo? If you go to the ngx-charts demo page, and select the `Real-time` option under `data`, you can see that the bars and pie segments animate properly. They are not being redrawn

https://swimlane.github.io/ngx-charts/

**Comment by julianshaw2000** [comment]
The charts work great with static data, however when I get real-time data from an observable the chart crashes the layout of my application.

**Comment by marjan-georgiev** [comment]
Closing this. If you still have the same problem and can provide an example, I would be happy to reopen.
