### ISSUE TITLE
Support for IE

### ISSUE THREAD

**Issue by tssobe** [swimlane/ngx-charts#386]
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Charts don't work at IE edge/11/10

Hi,
I am very impressed of the work that has been done on this OS, and I would like to use it.
I have noticed that the charts don't work on IE.
Are you familiar with the issue? is it going to be fixed soon (is there ETA)?

Thanks a lot

**Comment by Hypercubed** [comment]
ngx-charts should work on edge (I just tested) if you find anything in particular not working please report it.

**Comment by tssobe** [comment]
Hi
Thanks, you are correct, it works on Edge.
Are you going to support IE11?
Thanks

**Comment by Ketec** [comment]
Indeed - it took me some time to find out that my app was broken because i used ngx charts in one of the cards.

IE11 specifically complains about:

```
TypeError: Unable to get property 'remove' of undefined or null reference
   at DefaultDomRenderer2.prototype.removeClass (https://localhost:3000/vendor.dll.js:18591:71)
   at DebugRenderer2.prototype.removeClass (https://localhost:3000/vendor.dll.js:14731:9)
   at setElementClass (https://localhost:3000/vendor.dll.js:10982:9)
   at checkAndUpdateElementValue (https://localhost:3000/vendor.dll.js:10933:13)
   at checkAndUpdateElementInline (https://localhost:3000/vendor.dll.js:10879:5)
   at checkAndUpdateNodeInline (https://localhost:3000/vendor.dll.js:13592:13)
   at checkAndUpdateNode (https://localhost:3000/vendor.dll.js:13567:9)
   at debugCheckAndUpdateNode (https://localhost:3000/vendor.dll.js:14197:5)
   at debugCheckRenderNodeFn (https://localhost:3000/vendor.dll.js:14176:13)
   at Anonymous function (Function code:150:5)
   at debugUpdateRenderer (https://localhost:3000/vendor.dll.js:14161:5)
```

**Comment by tssobe** [comment]
Any ETA?
We are in a croasroad if to use it or not.
But without the support to ie11 we won't able.
Thanks !!

**Comment by menix** [comment]
Add my voice for IE11+ support.
Thanks in advance!

**Comment by iamnyasha** [comment]
If you are using angular-cli you can add these polyfills ...
import 'core-js/es7/array';

import 'classlist.js';  // Run `npm install --save classlist.js`.

then in you index.html file add the MouseEvent polyfill
`
<script type="text/javascript">
    (function (window) {
      if (!!window.MSInputMethodContext && !!document.documentMode || document.documentMode === 10) {
        function MouseEvent(eventType, params) {
          params = params || { bubbles: false, cancelable: false };
          var mouseEvent = document.createEvent('MouseEvent');
          mouseEvent.initMouseEvent(eventType, params.bubbles, params.cancelable, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);

          return mouseEvent;
        }

        MouseEvent.prototype = Event.prototype;

        window.MouseEvent = MouseEvent;
      }
    })(window);
  </script>
`
source: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/MouseEvent#Polyfill

This effectively adds full support for ie10 and ie11

**Comment by Ketec** [comment]
I think it's part of the animation polyfills. Or because of it.

I had to add  the web-animations-js polyfill to add the support for animations in ie/edge and other unsupported browsers - and i just noticed i didn't get this fatal error anymore.

in my case - browser.polyfill.ts (angular 2 starter).

**Comment by garyforsterio** [comment]
Just added `import 'core-js'` and everything is working hunky-dory :slightly_smiling_face: 

Thanks @iamnyasha

**Comment by Hypercubed** [comment]
That:s great... we should add this to the demo and somewhere in the docs.

**Comment by Tyroche** [comment]
Any updates on this?

**Comment by Darshan-popin** [comment]
Tried all the above suggested methods ,.. Still no fruit . Any updates or ETA on the support ?? Even ran the Demo version on IE11 and 10 got the below errors 
![capture](https://user-images.githubusercontent.com/20539351/30210465-63ea4e30-94ba-11e7-8427-25b00a93db36.PNG)

**Comment by garyforsterio** [comment]
Is sounds like your polyfill isn't working correctly.
Provided you've setup core-js correctly it should be doing this, but just to identify if that's the issue try adding this to your html before any other scripts:
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.prototype.contains"></script>
```
This will polyfill the specific method which you're seeing errors for in your conole.

Let me know if that helps

**Comment by yodamad** [comment]
Make it works with this polyfills.ts

import 'core-js/es6';
import 'core-js/es7/array';
import 'core-js/es7/reflect';
import 'core-js/client/shim';
import 'classlist.js';
import 'intl';
require('zone.js/dist/zone');

// IE11 fix
if (typeof SVGElement.prototype.contains == 'undefined') {
SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}

**Comment by Darshan-popin** [comment]
@yodamad : Thanks man !! it worked smoothly

**Comment by CramericaIndustries** [comment]
Just updated ngx-charts to v6.1.0. Now Universal is throwing an exception on start up that is related to the polyfill.ts code:

```
npm info lifecycle p4-monitor-angular@0.0.0~postbuild:universal:server: p4-monitor-angular@0.0.0
npm info ok
npm info lifecycle p4-monitor-angular@0.0.0~postbuild:universal:prod: p4-monitor-angular@0.0.0
npm info ok
/workdir/p4-monitor-angular/dist/server/server.js:157204
if (typeof SVGElement.prototype.contains === 'undefined') {
           ^

ReferenceError: SVGElement is not defined
    at Object.defineProperty.value (/workdir/p4-monitor-angular/dist/server/server.js:157204:12)
    at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
    at Object.SVGElement.contains (/workdir/p4-monitor-angular/dist/server/server.js:157141:69)
    at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
    at Object.defineProperty.value (/workdir/p4-monitor-angular/dist/server/server.js:125824:11)
    at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
    at Object.hasOwn (/workdir/p4-monitor-angular/dist/server/server.js:79980:37)
    at __webpack_require__ (/workdir/p4-monitor-angular/dist/server/server.js:20:30)
    at Object.defineProperty.value (/workdir/p4-monitor-angular/dist/server/server.js:63:18)
    at Object.<anonymous> (/workdir/p4-monitor-angular/dist/server/server.js:66:10)
```

You should propably check first if 'SVGElement' is defined before accessing one of its properties.

**Comment by CramericaIndustries** [comment]
fixed it localy by modyfing the code in the compiled pollyfill.js file to:
```
// IE11 fix
// Ref: https://github.com/swimlane/ngx-charts/issues/386
if (typeof(SVGElement) !== "undefined" && typeof SVGElement.prototype.contains === 'undefined') {
    SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}
```

**Comment by marjan-georgiev** [comment]
@CramericaIndustries can you PR that please?

**Comment by CramericaIndustries** [comment]
#587 maybe some one should check if it doesn't break that IE fix

**Comment by HitomiTenshi** [comment]
@CramericaIndustries @marjan-georgiev 
I just opened up IE11 and typed your added line `typeof(SVGElement) !== "undefined"`, it returns `true`.

![iexplore_2017-10-13_12-46-32](https://user-images.githubusercontent.com/7304212/31543079-dce611fa-b014-11e7-80f6-40ab9ca8bf2b.png)

This change does not break the IE fix. I wonder though why Universal is getting problems with it.

**Comment by CramericaIndustries** [comment]
> I wonder though why Universal is getting problems without it.

From the Angular Universal docs:
> window, document, navigator, and other browser types - do not exist on the server - so using them, or any library that uses them (jQuery for example) will not work.
I guess that SVGElement is one of those browser types.

**Comment by Adondriel** [comment]
Is there a polyfill for the SVGElement, to try to fake the server into knowing what that item is?

**Comment by harsoon** [comment]
@yodamad : Thanks! a sub-set of your solution works well for me, intl doesn't seem to be necessary for this and I already had an import 'zone.js/dist/zone';:

import 'core-js/es6';
import 'core-js/es7/array';
import 'core-js/es7/reflect';
import 'core-js/client/shim';
import 'classlist.js';

// IE11 fix
if (typeof SVGElement.prototype.contains == 'undefined') {
SVGElement.prototype.contains = HTMLDivElement.prototype.contains;
}

**Comment by juliandavidmr** [comment]
Run:
`npm install --save classlist.js`

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
`import 'classlist.js';`
