### ISSUE TITLE
Optmization for date display

### ISSUE THREAD

**Issue by lordmos** [swimlane/ngx-charts#392]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**

I'm a user from China and I got a problem here . I need to display the localeString in the tooltips and xAxis then try some ways , but didn't work for me.

1. Just use time stamp as name and format xAxis :
xAxis seens good to me , but tooltips still display as time stamp .

2. Use a Date object as name :
xAxis and tooltips show the date string ,not a locale string .

3. User a Locale string as name:
There has a bug : "2017-4-22 20:36:04" is after "2017-5-11 14:58:57"
My test data and you can try in a line chart : 
[{"name":"冷冻水进水温度","series":[{"name":"2017-4-19 14:07:47","value":-0.1},{"name":"2017-4-19 14:12:51","value":-0.1},{"name":"2017-4-19 14:17:53","value":1.6},{"name":"2017-4-22 04:10:07","value":6553.5},{"name":"2017-4-22 04:15:08","value":1.6},{"name":"2017-4-22 17:50:25","value":6553.5},{"name":"2017-4-22 17:55:26","value":1.6},{"name":"2017-4-26 14:35:40","value":6553.5},{"name":"2017-4-26 14:40:41","value":1.6},{"name":"2017-5-2 14:07:23","value":6553.5},{"name":"2017-5-3 14:10:50","value":6553.5},{"name":"2017-5-4 14:14:27","value":6553.5},{"name":"2017-5-5 14:18:25","value":6553.5},{"name":"2017-5-6 14:22:16","value":6553.5},{"name":"2017-5-7 14:25:48","value":6553.5},{"name":"2017-5-8 14:28:58","value":6553.5},{"name":"2017-5-9 14:32:12","value":6553.5},{"name":"2017-5-11 14:58:57","value":6553.5}]},{"name":"冷冻水出水温度","series":[{"name":"2017-4-19 14:07:47","value":-0.1},{"name":"2017-4-19 14:12:51","value":-0.1},{"name":"2017-4-19 14:17:53","value":10.9},{"name":"2017-4-30 10:27:20","value":6553.5},{"name":"2017-4-30 10:32:21","value":10.9},{"name":"2017-5-2 14:07:23","value":6553.5},{"name":"2017-5-3 14:10:50","value":6553.5},{"name":"2017-5-4 14:14:27","value":6553.5},{"name":"2017-5-5 14:18:25","value":6553.5},{"name":"2017-5-6 14:22:16","value":6553.5},{"name":"2017-5-7 14:25:48","value":6553.5},{"name":"2017-5-8 14:28:58","value":6553.5},{"name":"2017-5-9 14:32:12","value":6553.5},{"name":"2017-5-11 14:58:57","value":6553.5}]},{"name":"1#冷却水进水温度","series":[{"name":"2017-4-19 14:07:47","value":-0.1},{"name":"2017-4-19 14:12:51","value":-0.1},{"name":"2017-4-19 14:17:53","value":9},{"name":"2017-5-2 14:07:23","value":6553.5},{"name":"2017-5-3 14:10:50","value":6553.5},{"name":"2017-5-4 14:14:27","value":6553.5},{"name":"2017-5-5 14:18:25","value":6553.5},{"name":"2017-5-6 14:22:16","value":6553.5},{"name":"2017-5-7 14:25:48","value":6553.5},{"name":"2017-5-8 14:28:58","value":6553.5},{"name":"2017-5-9 14:32:12","value":6553.5},{"name":"2017-5-11 14:58:57","value":6553.5}]},{"name":"1#冷却水出水温度","series":[{"name":"2017-4-19 14:07:47","value":-0.1},{"name":"2017-4-19 14:12:51","value":-0.1},{"name":"2017-4-19 14:17:53","value":6.8},{"name":"2017-4-22 20:36:04","value":6553.5},{"name":"2017-4-22 20:41:05","value":6.8},{"name":"2017-4-27 18:31:33","value":6553.5},{"name":"2017-4-27 18:36:34","value":6.8},{"name":"2017-5-2 14:07:23","value":6553.5},{"name":"2017-5-3 14:10:50","value":6553.5},{"name":"2017-5-4 14:14:27","value":6553.5},{"name":"2017-5-5 14:18:25","value":6553.5},{"name":"2017-5-6 14:22:16","value":6553.5},{"name":"2017-5-7 14:25:48","value":6553.5},{"name":"2017-5-8 14:28:58","value":6553.5},{"name":"2017-5-9 14:32:12","value":6553.5},{"name":"2017-5-11 14:58:57","value":6553.5}]}]

I need some help .

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

VSCode , ng-cli

* **ngx-charts version:** 5.x.x

* **Angular version:** 4.x.x

* **Browser:** [all]

* **Language:** [TypeScript 2.X]

**Comment by marjan-georgiev** [comment]
You can format the axis ticks with the `xAxisTickFormatting` and `yAxisTickFormatting` inputs, and you can pass custom templates for the tooltips.
