### ISSUE TITLE
TS transpile error

### ISSUE THREAD

**Issue by qiluo** [swimlane/ngx-charts#393]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I have an Ionic app using ngx-chart, during build, I got 
```
[15:17:23]  transpile started ...
[15:17:28]  typescript: node_modules/@swimlane/ngx-charts/release/utils/color-utils.d.ts, line: 9
            Cannot find name 'RGBColor'.

       L9:  export declare function hexToRgb(value: string): RGBColor;

[15:17:28]  ionic-app-script task: "build"
[15:17:28]  Error: Failed to transpile program
```

**Expected behavior**

**Please tell us about your environment:**

OSX, NPM

* **ngx-charts version:** 5.2.0

* **Angular version:** 4.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "~2.2.1"

**Comment by Hypercubed** [comment]
Thanks for the report... I just fixed this in #394
