### ISSUE TITLE
Bubble Chart view width/height defaults to 400x400

### ISSUE THREAD

**Issue by alecrosenbaum** [swimlane/ngx-charts#395]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If no view parameter is specified, the chart defaults to 400x400. These constants can be seen in [ngx-charts/src/bubble-chart/bubble-chart.component.ts](https://github.com/swimlane/ngx-charts/blob/master/src/bubble-chart/bubble-chart.component.ts) on line 87
`@Input() view: number[] = [400, 400];`

If a view input of `null` in pass in, everything works as expected.
ex: 
`<ngx-charts-bubble-chart
            [view]="null"
            [results]="calibrationGraphs[name].data"
            ...
        </ngx-charts-bubble-chart>
`

**Expected behavior**
View should expand/shrink with the view dimensions (like the other charts)

**Reproduction of the problem**

Don't specify the view parameter when creating a bubble chart.

**What is the motivation / use case for changing the behavior?**

be consistent with other charts.

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** 
tested on Chrome 57.0.2987.133

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
If the view parameter is omitted, it should default to undefined, so it fits the container.

**Comment by marjan-georgiev** [comment]
Fixed

**Comment by abhilash0301** [comment]
Related to bubble - chart i have one question ,what is the solution when two or more than two bubble overlap means  x and y axis have same value . 
The Problem is that when we hover the bubble it shows the last value of the array . 
Please suggest any solution .

Thanks
