### ISSUE TITLE
Replace 'NaN' with 0% in Legend

### ISSUE THREAD

**Issue by vforvasquez** [swimlane/ngx-charts#398]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Right now my advanced pie chart uses data that is updated by user selection, if the user selects a combination that does not have data assigned to it the legend will display "NaN" because in ngx-charts/release/index.js line 10560 percentage is set to value / _this.total * 100; 

So we added a check to replace NaN with 0 right underneath that:
            // Prevent NaN from being displayed
            if(isNaN(percentage)){
              percentage = 0;
            }

I was thinking this might something that people would prefer to have instead of the way that it is currently done but also realize there might be a very good reason for having it display NaN.

**Comment by Pritoj** [comment]
Would it be better to give a value getter hook so the user can provide values for the ticks?

**Comment by milleraundra** [comment]
+1
