### ISSUE TITLE
Pie Chart Resizing issue

### ISSUE THREAD

**Issue by rishi-ios** [swimlane/ngx-charts#400]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Pie Chart Labels goes out of container window.

**Expected behavior**
It should remain inside container window.

**Reproduction of the problem**
1. Create a multiple div containers to hold a charts
2. Add Pie chart in one div container.

**What is the motivation / use case for changing the behavior?**
We've been trying to implement a dashboard kind view, where we are showing multiple charts in a page. We have removed view attribute and it fits to container. When we make the widget big chart renders as expected and fit to div but when we make the div small, by resizing the window(W:320, H:280), the label's of Pie Chart goes out of div's content area.

Windows 7
Display - 1366 x 768

    ngx-charts version: 5.1.2
    d3: 4.8.0

    Angular version: 4.0.2

    Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 58.0.3029.81

    Language: [all | TypeScript X.X | ES6/7 | ES5]
    Typescript 2.2.0
![pie_chart](https://cloud.githubusercontent.com/assets/5341784/26205226/be5a35c0-3bfe-11e7-9da8-c8a501c7c48a.png)

**Comment by marjan-georgiev** [comment]
This should be resolved. Please let me know if it's still an issue.
