### ISSUE TITLE
Make `totalLabel` in advanced-legend component a `@Input()`

### ISSUE THREAD

**Issue by SamVerschueren** [swimlane/ngx-charts#401]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently, it is not possible to use a custom word (translated string for instance) as `totalLabel` in the [advanced-legend.component](https://github.com/swimlane/ngx-charts/blob/master/src/common/legend/advanced-legend.component.ts). I'm using the advanced pie chart but want to translate the `total` label.

**Expected behavior**
To make it possible to use a custom total label when the `advanced-legend.component` is being used, for instance in the advanced pie chart.

My suggestion would be the following
1. Make [totalLabel](https://github.com/swimlane/ngx-charts/blob/master/src/common/legend/advanced-legend.component.ts#L72) an `@Input() totalLabel = 'total';`
2. Every component using the `advanced-legend.component` should have `@Input() totalLabel` which sends that value downstream to the legend component.

This way the legend is fully translateable.

I would be happy to create a PR for this but wanted to discuss things first.

**Reproduction of the problem**
/

**What is the motivation / use case for changing the behavior?**
When working with `ngx-charts` in an environment where you need translated labels, currently it is not possible to do that for the `totalLabel` in the advanced legend. I don't want to hack around this issue and it would just be nice if it was supported out of the box.

**Please tell us about your environment:**
macOS Sierra, VS Code, yarn

* **ngx-charts version:** 5.x

* **Angular version:** 4.x

* **Browser:** all

* **Language:** TypeScript

**Comment by marjan-georgiev** [comment]
Added in master. The input is called `label`

**Comment by SamVerschueren** [comment]
Nice, thanks for the fast response!
