### ISSUE TITLE
turn off transition (live data)

### ISSUE THREAD

**Issue by ptrblgh** [swimlane/ngx-charts#403]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
plunkr: [https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp](https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp)

**Expected behavior**
Shift the points + area left (previous position) without transition. (Only the new point and the corresponding area would use transition or simply appear).

**Reproduction of the problem**
[https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp](https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp)

**What is the motivation / use case for changing the behavior?**
As shown in the plunkr, it looks strange when the result set is updated with the new value. There is a transition between every point + area. Would be handy if this transition was optional.

**Please tell us about your environment:**
Windows, npm

* **Angular version:** 2.x.x
4.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 57.0.2987.133 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 TypeScript 2.3.2

**Comment by marjan-georgiev** [comment]
This effect is being described here: https://bost.ocks.org/mike/path/

We will add a disableAnimations input to all chart in one of the upcoming releases.
