### ISSUE TITLE
is this possible ? grouped bar combined with stack chart ?

### ISSUE THREAD

**Issue by yaronmil** [swimlane/ngx-charts#404]

**Comment by marjan-georgiev** [comment]
A combination of bar and line chart has been implemented as a demo and can be seen here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

The code for the custom chart can be found here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

**Comment by montananyto-dev** [comment]
Hi @yaronmil ,

I was wondering if you managed to implement it ? Would be nice if you could share if you did it.

Thank you
