### ISSUE TITLE
Bar Chart Animations are Choppy (All Types)

### ISSUE THREAD

**Issue by ianzimmerman** [swimlane/ngx-charts#406]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Bar Chart Animations are choppy (Vertical, Horizontal, Grouped, Stacked, Normalized)
Affects other charts if on same view. 

**Expected behavior**
Animations should be smooth. Compare with any pie chart.

**Reproduction of the problem**
https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-horizontal-2d
> switch between bar charts
Compare with switching between pie charts.
Solved by downgrading to ~5.1.2 and ~5.2.1

**What is the motivation / use case for changing the behavior?**
Bar chart animations cause all other charts to render poorly and slowly.

**Please tell us about your environment:**
macOS 10.12, Chrome Version 58.0.3029.110 (64-bit), 

* **ngx-charts version:** 
5.3

* **Angular version:** 
4.0.1

* **Browser:** 
Chrome Version 58.0.3029.110 (64-bit)

* **Language:**
TS 2.2.0

**Comment by stanvanheumen** [comment]
I am experiencing the same problem with all types. Downgrading to ~5.1.2 fixed the problem for me. Is there any timeframe on when this will be fixed?

**Comment by dweitz43** [comment]
seems like it is a result of this commit https://github.com/swimlane/ngx-charts/pull/402/commits/fc42a80ae6aac5e0132af5b7f6a731bc61671e7d

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.

**Comment by matheusdavidson** [comment]
still a problema, animation is very buggy and it throw tween errors
