### ISSUE TITLE
Chart is not rendered after data is changed

### ISSUE THREAD

**Issue by kakalos12** [swimlane/ngx-charts#407]
Hi, 
I'm having the problem when rendering chart from the ajax resource. It render blank. How can I fix this  ? 

Thanks, 
Dong Nguyen

**Comment by huiguang-liang** [comment]
Did you try including a force refresh data changing `data`?

`data = [...data];`

**Comment by kakalos12** [comment]
I fixed this by setting the result variable and calling the update method explicitly.

**Comment by huiguang-liang** [comment]
Guess you can consider closing the thread, my personal opinion is that this doesn't constitute an issue per se.

**Comment by GO3LIN** [comment]
How did you called the update method plz ?  thanks !
