### ISSUE TITLE
Feature Request:  echo all [results] parameters in (select) event

### ISSUE THREAD

**Issue by sjdemoor** [swimlane/ngx-charts#409]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Sample input json includes an embedded 'data' object, in addition to required `name`, `value`, `series`, etc:

```json
[
  {
    name: 'January',
    series: [
      {
        name: 'Color',
        value: 29476,
        data: {
          routePath: 'this/is/the/path/to/Jan/Color',
          payload: 'payload%20info...'
        }
      }
...
]
```
For a `ngx-charts-bar-vertical-2d` (or any `2d` bar chart type), the (select) event echoes not only the relevant {name:, series:, value:}, but also the embedded `data` object:

Example implementation of (select)="onSelect($event)" == console.log($event):
![image](https://cloud.githubusercontent.com/assets/16191409/26407589/96684cd6-4069-11e7-8bc9-99b3f5f93662.png)

**Expected behavior**
For all other graph/chart types, the embedded data object is not echoed into the (select) event.

Similar json with embedded `data` object, fed into `ngx-charts-line-chart`
![image](https://cloud.githubusercontent.com/assets/16191409/26407896/5cf01794-406a-11e7-98aa-e85c1153f806.png)

`data` object is not echoed to the $event.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Echoing all available fields from the json is extremely useful, as it allows the app to add arbitrary embedded data into the existing {name: value:} structure. For example; enabling routing from the `(select)="onSelect($event)"` function, or linking multiple chart components on a dashboard using an 'id:' field, etc.

**Please tell us about your environment:**

* **ngx-charts version:** 5.2.0

* **Angular version:** 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X 
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS

**Comment by marjan-georgiev** [comment]
This is captured by https://github.com/swimlane/ngx-charts/issues/506. Closing as duplicate.

**Comment by nicole-ge** [comment]
I havent understand the work around. Can you please explain it with a more detailled example.
