### ISSUE TITLE
ERROR TypeError: Cannot read property 'map' of undefined     at BarVerticalComponent../src/bar-chart/bar-vertical.component.ts.BarVerticalComponent.getXDomain

### ISSUE THREAD

**Issue by edyrkaj** [swimlane/ngx-charts#410]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Load data from angular service with http.get and retrieve them on constructor method
Graphics are displayed ok but console shows these logs of errors. Also it breaks angular routes.

**Expected behavior**
Should skip this error and stay on same route url.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jotatoledo** [comment]
Could you provide a small reproduction of this problem?

**Comment by huysamen** [comment]
This happens when the data (in their examples called `single` and `multi`) you bind to the chart is undefined (at least it did for us).  Just initialize your data with an empty array and see if it still happens.

**Comment by maxencefrenette** [comment]
I still think ngx-charts should provide a better error message when one of the input is undefined
