### ISSUE TITLE
Request for Count shown on Bar chart/Pie Chart/Stacked Bar

### ISSUE THREAD

**Issue by pratikpanchal4472** [swimlane/ngx-charts#418]
Hi Team,

Is it possible to show numbers on Bar Chart graph on each bar and for Pie the numbers on  slices?

**Comment by huiguang-liang** [comment]
Would love this too, seconded!

**Comment by viziocruze** [comment]
Hi Team,

Is there any updates on this

**Comment by marjan-georgiev** [comment]
This was added to bar charts via the `showDataLabel` input.
