### ISSUE TITLE
I cannot see the bar graph - the data is logging in the expected format

### ISSUE THREAD

**Issue by kittycatbytes** [swimlane/ngx-charts#421]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request => Please do not submit support request here
```

**Current behavior**
I am pulling the data in via an observable, then pushing the properties from the observable into the single array, and the output {{single | json}} produces the correct format for the chart data:
`[ { "name": "5 - Dormant", "value": 1 }, { "name": "Draft", "value": 9 }, { "name": "2 - Active in DRIVE", "value": 2 }, { "name": "4 - Assigned to Section", "value": 1 }, { "name": "1 - Pending DRIVE Review", "value": 25 }, { "name": "6 - Out of Scope", "value": 1 }, { "name": "3 - Officer Review", "value": 1 } ]`
However, I cannot see the chart - there are no errors.  I see the text labels and "Legend" but no chart.  I have tried fiddling a lot with the css/sass but it appears no graph is there.  Within the chart bindings in dev tools I see the following:
```
<!--bindings={
  "ng-reflect-ng-if": "false"
}-->
```
I assume that means it is not getting the data?  Please help!

**Expected behavior**
For the chart to display.

**Reproduction of the problem**
As described above.

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
VS 2017, Angular 4, TypeScript

* **ngx-charts version:** x.x.x
"@swimlane/ngx-charts": "^5.3.1",

* **Angular version:** 2.x.x
4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript ES6

**Comment by jotatoledo** [comment]
Hey, could you provide a small reproduction of your problem? You could use one of the plnkrs in the documentation. Example: https://plnkr.co/edit/KaouGHPQwRskr6HB9XGf

**Comment by kittycatbytes** [comment]
(1)When I pull the data in as a string, then create an observable of it - it works no problem.  However, when I (2) hit is as a REST API, then push the values using an interface into an array, it does not work.  So if I were to work off your plunkr, it would not exactly recreate my problem.  And the REST API call hits a URL behind a firewall.  Even though the output {{single | json}} yields the exact same string, (1) outputs the bar graph perfectly and (2) does not.

**Comment by kittycatbytes** [comment]
So I am looking at the difference between (1) and (2).  When I console.log in each case, (1) returns the Objects as individual line items in the console.  (2) returns [ ], which you can then go into and see the individual objects.  I assume this is likely the key to why it is not working.

**Comment by jotatoledo** [comment]
May I see how are u mapping the returned items from your webapi into the charting format? Most likely there is something weird there

**Comment by kittycatbytes** [comment]
Here is my service function:
```
          getData() {
              return this.http.get(this.url, this.options)
                  .map(res => res.json().d.results)
                  .concatMap(data => data)
                  .groupBy(item => (item as any).Status)
                  .mergeMap(group => group
                      .count(item => group.key == group.key)
                      .map(total => ({ name: group.key, value: total }))
                  )
                  .toArray();
```

Here is my component code: 
```
    constructor(spservice: SharePointService) {
        super();
        this.xAxisLabel = "Status";
        this.yAxisLabel = "Count";
        this.tracdata = spservice.getData();
        this.tracdata.subscribe(data => data
            .forEach((item, i, data) => { this.single.push({ name: (item.name), value: (item.value) }) })
            );
            //.forEach(data => { this.single.push({ data }) }));

        this.single.map(data => data)
        this.single.map(data => console.log(data));
        Object.assign(this,  this.single ); 

        
    }
```

**Comment by kittycatbytes** [comment]
sorry I have a duplicate    this.single.map(data => data) in there, that shouldnt be in there

**Comment by kittycatbytes** [comment]
also component template:
```
<div class="{{colmdVal}} {{colsmVal}} {{colxsVal}} gizmo">
  <md-card>
    <md-card-header>
      <md-card-title>{{title}}</md-card-title>
    </md-card-header>
    <md-card-content class="trac">
      {{single | json}}
      
      <ngx-charts-bar-vertical 
                               [view]="view"
                               [scheme]="colorScheme"
                               [results]="single"
                               [gradient]="gradient"
                               [xAxis]="showXAxis"
                               [yAxis]="showYAxis"
                               [legend]="showLegend"
                               [showXAxisLabel]="showXAxisLabel"
                               [showYAxisLabel]="showYAxisLabel"
                               [xAxisLabel]="single.name"
                               [yAxisLabel]="single.value"
                               (select)="onSelect($event)">
      </ngx-charts-bar-vertical>
      
    </md-card-content>
  </md-card>
</div>
```

**Comment by jotatoledo** [comment]
Yup the problem is definetly on the service function :smile: 
Could you give me an interface definition of what is the web api returning? Specially what is the type of `results`. 

My next question would be, what do you want to archieve with `concatMap(data => data)`? As far as I understand, if results is a plain object, `concatMap(data => data) `will create a dictionary of its members. If its an array, `concatMap(data => data) `will emit singular values for every element.

On the other hand, I would strongly recommend you to set the return type of getData to `Observable<DataInterface[]>,` where `DataInterface` is just made of name and value. 

Furthermore, you use `single.name` and `single.value` in your template. If single is an array, what do you expect to get by accesing properties like that?

**Comment by kittycatbytes** [comment]
The interface I am using is:
```
export interface thisData {
    name: string;
    value: number;
}
```
But that is not the interface of what is being returned.  I am just using that to define what is being returned by the service.  If I were to have what was being returned by the API it would be something like:

d: {
     results:{
           FieldValuesAsText:{
                   Status: string;
           }
     }
}

But it is a much more complicated data set than that, but those are the ones that I care about.

Really I am just trying to get to .groupBy, because without it, I am unable to access the Status field because it nested a few layers deep within the object.  I am open to suggestions on a better way to achieve that.

I am currently trying to return results as a function now.

**Comment by kittycatbytes** [comment]
I got it working finally.  I did not change my service function.  I updated the template results to: [results]="data | async" as follows:
```
      <ngx-charts-bar-vertical 
                               [view]="view"
                               [scheme]="colorScheme"
                               **[results]="tracdata | async"**
                               [gradient]="gradient"
                               [xAxis]="showXAxis"
                               [yAxis]="showYAxis"
                               [legend]="showLegend"
                               [showXAxisLabel]="showXAxisLabel"
                               [showYAxisLabel]="showYAxisLabel"
                               (select)="onSelect($event)">
      </ngx-charts-bar-vertical>
```
And my constructor to:
```
    constructor(spservice: SharePointService) {
        super();
        this.tracdata = spservice.getDriveTrac();

    }
```

**Comment by kittycatbytes** [comment]
Although it displays I still get many errors such as "TypeError: Cannot read property 'map' of null"

**Comment by johanchouquet** [comment]
Just had the same issue, finding the same solution (i.e. `data | async`), ans still have the same errors (TypeError: Cannot read property 'map' of null).

Any news about these ?

**Comment by aleksvidak** [comment]
@johanchouquet Did you find any solution for the error (TypeError: Cannot read property 'map' of null)?
