### ISSUE TITLE
seriesTooltipTemplate format

### ISSUE THREAD

**Issue by mrv777** [swimlane/ngx-charts#424]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request => Please do not submit support request here
```

I know it says not to support support requests here, but I couldn't find where you are supposed to 😞 
This should be an easy question though:  What is the proper format for `seriesTooltipTemplate`?  I couldn't find an example anywhere.  I know the other template is like this:
```
<ng-template #tooltipTemplate let-model="model">
		    <h1>
		      Title
		    </h1>
		    <h2>{{model.name}}--{{model.value}}</h2>
	  </ng-template>
```
That doesn't work for this one though if I just switch `tooltipTemplate` to `seriesTooltipTemplate`.  It shows `Title` and the 2 dashes, but that's it.  I'm guessing you can specify the x and y values for that point, but I'm not sure how.  Any help would be appreciated and thank you in advance

**Comment by marjan-georgiev** [comment]
You can do this:

```
<ng-template #tooltipTemplate let-model="model">
  {{model | json}}
</ng-template>
```

Which will show you what the model looks like.

**Comment by mrv777** [comment]
Thank you!  That is very helpful.
For anyone else wondering, it seems the difference with `seriesTooltipTemplate` is just that it is an array of one element.  So `model.name` becomes `model[0].name` and then it displays 😄

**Comment by marjan-georgiev** [comment]
Correct, the seriesTooltipTemplate lists all series for that x value.

**Comment by JLLproduction** [comment]
you should just run an ngfor on model

<ng-template #seriesTooltipTemplate let-model="model">
                    <div *ngFor="let mod of model; let i = index">
                        <h1 class="ds-h6" style="margin: 2px; font-weight: normal; color: white">{{mod.name}}-{{ mod.series }}</h1>
                        <h3 class="ds-h4" style="margin: 2px; font-weight: normal">{{ mod.value | graphToolTip }}</h3>
                    </div>
                </ng-template>

**Comment by JLLproduction** [comment]
Also what did you use to get the color thats applied to it
