### ISSUE TITLE
Timeline is broken with ngx-charts 5.3.1

### ISSUE THREAD

**Issue by tobigit** [swimlane/ngx-charts#425]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I have a Line-Chart with multiple series and a timeline below. Today after I upgraded ngx-charts from 5.1.2 to 5.3.1 the timeline is broken. Selecting a time range is not possible or very very slow. The chrome tab hangs and no interaction is possible.

**Reproduction of the problem**
Here is a sample of a line Chart with ngx-charts 5.1.2:
https://plnkr.co/edit/s76Sdr3dqz68BWEl6gjf?p=preview

And here is the same sample with ngx-charts 5.3.1:
https://plnkr.co/edit/mzrIbNuCMwm0zTsRuUtJ?p=preview

**Please tell us about your environment:**

* **ngx-charts version:** 5.3.1

* **Angular version:** 4.0.1

* **Browser:** Chrome 58.0.3029.110

* **Language:** TypeScript 2.2.0

**Comment by maxencefrenette** [comment]
It doesn't seem to be broken on 5.2.1 either, if that can help.

**Comment by Papamilo** [comment]
I've got exactly the same issue..it completely freeze the screen and the mouse icon "cross" keep displaying

**Comment by EduJGURJC** [comment]
Same issue

**Comment by marjan-georgiev** [comment]
Fixed in master. Gonna be in next release.
