### ISSUE TITLE
Changing arc line on gauge chart

### ISSUE THREAD

**Issue by Papamilo** [swimlane/ngx-charts#428]
**Current behavior**
I would change the width of a gauge chart...I tried with CSS class "arc" but that change nothing...if anyone could help? I'll have others charts to modify in the future..is that possible? thanks in advance 

**Expected behavior**
 Gauge Chart with lines larger, I expect something a bit like that : http://www.presentation-process.com/wp-content/uploads/powerpoint-gauge.jpg 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
 If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/TLx2vYlCTLsqcLwvWafd). 

**Please tell us about your environment:**
 Xubuntu Linux 

* **ngx-charts version:** x.x.x
 Latest 

* **Angular version:** 2.x.x
 Angular 4

* **Browser:**  Chrome XX

* **Language:** 
 TypeScript ES6/7

**Comment by Papamilo** [comment]
I hope it's clear enough, otherelse feel free to ask me..thanks :+1:

**Comment by marjan-georgiev** [comment]
The width of the arcs is defined by the chart's size and can not be overridden. We do not plan to add support for that in the near future. The example you provided looks like a completely different chart than our gauge chart. I would suggest building a custom chart.

**Comment by Papamilo** [comment]
Ahright many thanks for your quick answear Marjan, is there possible to build cutom chart using ngx-chart styles? If yes, is there somewere I could find a tutorial or exemple?

**Comment by marjan-georgiev** [comment]
It's possible to use the pie-arc component to build something similar, although there is no tutorial on how to do the exact same thing. I would suggest looking into the implementation of the gauge and pie charts and see how you can use the building blocks to achieve what you need. 

I will close this issue for now.

**Comment by Papamilo** [comment]
Ahright then thanks mylord !
