### ISSUE TITLE
Line chart reference Lines

### ISSUE THREAD

**Issue by JoshSchoen** [swimlane/ngx-charts#430]
**I'm submitting a to add options for reference lines in line charts.*  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
You are not able to add reference lines to the line charts.

**Expected behavior**
Add up to 3 reference lines and range and labels to line charts. This is needed to indicate min, max, averages and show confidence levels.

**What is the motivation / use case for changing the behavior?**
Ability to add up to 3 reference lines and range and labels to line charts.

![reference-lines](https://user-images.githubusercontent.com/8234649/26974808-a32ca338-4ce2-11e7-8f8f-79373e84f715.gif) There is an open PR #422 

Please let me know if there is anything that needs to be done in order to move the PR forward.

**Comment by marjan-georgiev** [comment]
Merged into master.
