### ISSUE TITLE
LICENSE.md is missing

### ISSUE THREAD

**Issue by phra** [swimlane/ngx-charts#436]
hi,

cool library! but i cannot find the license anywhere.
can you please add it?

thanks.

**Comment by stephanrauh** [comment]
Just in case you're worrying about the license (as opposed to knowing the license while missing the file): https://swimlane.gitbooks.io/ngx-charts/content/license.html states the library is put under the MIT license.

**Comment by phra** [comment]
sent a PR to fix this. #437
