### ISSUE TITLE
Is it possible to provide data through node service?

### ISSUE THREAD

**Issue by kevinxia787** [swimlane/ngx-charts#438]
Hi, I'm writing an angular app where I need the node server  to require a json file and have angular perform a get request to that json and parse it, then display the data in the gauge chart. is this possible?

**Comment by marjan-georgiev** [comment]
Yes, it doesn't matter where the data comes from. The charts accept a javascript array, they don't care how you create it or where you get the data from. You need to do that outside the chart and pass it to it as an input.
