### ISSUE TITLE
Multi series line chart incorrectly handles complex values as names for x axis

### ISSUE THREAD

**Issue by achekh** [swimlane/ngx-charts#440]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The line chart has all values in one column, when I provide complex object for the name data property instead of string. I also provide the xAxisTickFormatting function that creates proper string representation. When debugging the xAxisTickFormatting function, I can see that it always receive the same value.

**Expected behavior**
The line chart should properly display x axis labels basing on the xAxisTickFormatting function result.

**Reproduction of the problem**
I provide an object with id and name for the name property, similar to 
```
[
  {
    "name": "Germany"
    "series": [
      {
        "name": { "name": "Two thousand ten", "id":"2010" },
        "value": 7300000
      },
      {
        "name": { "name": "Two thousand eleven", "id":"2011" },
        "value": 8940000
      }
    ]
  },
...
```
I also provide ` [xAxisTickFormatting]="formatXAxisTick"` configuration and the formatXAxisTick function
```
   formatXAxisTick(tick: any): string {
        return tick.name;
    }
```

**What is the motivation / use case for changing the behavior?**
In order to reliably determine the value I receive in onSelect event I want to receive identifier of the data piece, not (only) the formatted label.

**Please tell us about your environment:**
Windows 8.1, VisualStudio 2017, npm.

* **ngx-charts version:** 5.3.1
* **Angular version:** 4.1.0
* **Browser:** Chrome 59.0.3071.104 (Official Build) (64-bit)
* **Language:** TypeScript 2.2.2.0

**Comment by marjan-georgiev** [comment]
The name property is expected to be a string. There is a different feature request for the use cases, allowing passing custom data that will be emitted during onSelect: https://github.com/swimlane/ngx-charts/issues/506
