### ISSUE TITLE
A module cannot import itself (AOT with NGC and Rollup)

### ISSUE THREAD

**Issue by RichMartel** [swimlane/ngx-charts#446]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Trying to follow:
https://angular.io/guide/aot-compiler

using ngc and rollup, rollup is returning the following error on the ngx-charts module:

**Expected behavior**

Error: A module cannot import itself
webtmp/node_modules/@swimlane/ngx-charts/release/common/tooltip/tooltip.component.ngfactory.js (5:0)
3: import * as i2 from '@angular/common';
4: import * as i3 from '@swimlane/ngx-charts/release/common/tooltip/tooltip.component';
5: import * as i4 from './tooltip.component.ngfactory';
   ^
6: var styles_TooltipContentComponent = [i0.styles];
7: export var RenderType_TooltipContentComponent = i1.ɵcrt({ encapsulation: 2,

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

Trying to get aot compiling / tree-shaking / and bundling working in my build process

**Please tell us about your environment:**

Ubuntu 17.04, Sublime, npm, node/express
nothing unusual

* **ngx-charts version:** x.x.x

5.3.1

* **Angular version:** 2.x.x

4.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

n/a

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.4.0

**Comment by marjan-georgiev** [comment]
This should be fixed. Please let me know if it is still an issue.
