### ISSUE TITLE
Chart CSS Files Not in AOT Build

### ISSUE THREAD

**Issue by jboothe** [swimlane/ngx-charts#448]
**I'm submitting a ...** Bug
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When creating an Angular 4 AOT build, ngx-charts CSS styles are not pulled into the build. A specific example would be `.gridpanel`. The image below shows a black background (presumably the default fill) for the bar chart. Upon inspection of the compiled source, there is no instance of `.gridpanel` class. 

![black-gridpanel](https://user-images.githubusercontent.com/3723481/27410121-5573590e-56b3-11e7-9d99-58469a6375e6.png)

**Expected behavior**
Expect ngx-charts css classes to be part of the AOT build. 

**Reproduction of the problem**
Using the Angular Class [angular-starter](https://github.com/AngularClass/angular-starter) seed app, place a bar chart on a page and create an AOT build. 

**Please tell us about your environment:**

Mac OSX 10.12.5
Node 6.8.1
Npm 3.10.8
Typescript 2.3.4
Angular 4.1.3
webpack : 2.6.1
webpack-dev-server : 2.4.2

* **ngx-charts version:** 
5.3.1

* **Browser:** 
ALL

**Comment by Luukschoen** [comment]
Is this still happening in 6.0.0? I've tested it out myself and it seems to be working fine.

**Comment by marjan-georgiev** [comment]
This should be fixed.
