### ISSUE TITLE
ngx-charts-tree-map IE 11 error

### ISSUE THREAD

**Issue by yuveliremil** [swimlane/ngx-charts#449]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
when I add  **ngx-charts-tree-map**  I get following error on **IE-11** (_on other browsers work fine_) :

**ERROR TypeError:** Failed to set the "**pointer-events**" property of a reference whose value is not defined or is NULL

**Expected behavior**
Display ngx-charts-tree-map

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7 (8, 10), node.js

* **ngx-charts version:** x.x.x
5.3.1

* **Angular version:** 2.x.x
angular 4.1.3 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript

**Comment by tpeter29** [comment]
I ran into this same issue a few days ago.  If you launch the treemap demo provided by swimlane in IE11 it doesn't show the labels (ERROR TypeError: Unable to set property 'pointer-events' of undefined or null reference). 

Demo:  https://swimlane.github.io/ngx-charts/#/ngx-charts/tree-map-demo

Please note that the treemap was working in IE11 prior to last week.

**Comment by jclancy93** [comment]
I've noticed a lot of issues with this new lib and ie11. Was using v4 and angularv2.4 and since I have upgraded to v5 and angularv4 both bar charts and pie charts are throwing a huge amount of errors. Even downgrading the library to v4 does not seem to fix the issue.

**Comment by akaztp** [comment]
The problem seems to be on the tree-map component HTML template:
```
    <svg:foreignObject
        *ngIf="width >= 70 && height >= 35"
        [attr.x]="x"
        [attr.y]="y"
        [attr.width]="width"
        [attr.height]="height"
        class="label"
        [style.pointer-events]="'none'">
```
On IE11 the foreignObject does not have the style property.
Still seeking some solution without having to change the component's code.

**Comment by atapas** [comment]
Is there a work-around possible for this issue?

**Comment by atapas** [comment]
![image](https://user-images.githubusercontent.com/3633137/41536429-36acdee0-7323-11e8-9981-cd68b8392bf9.png)

**Comment by davemcmanus** [comment]
This is still happening in IE 11/Edge with @swimlane/ngx-charts version 12.0.1 

My Polyfills.ts file:

/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es7/array';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';


/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

 // (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 // (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 // (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
// (window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

**Comment by LeParadoxHD** [comment]
Same here, 2019...

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported.
