### ISSUE TITLE
Interactive Tree Chart

### ISSUE THREAD

**Issue by JoshSchoen** [swimlane/ngx-charts#454]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Interactive tree/path chart not available.

**Expected behavior**
Reusable Interactive Tree Chart component. This is a simple example https://bl.ocks.org/mbostock/4339083
I would like to know if there are any plans to create such a chart. If not I am more than happy to create a PR and work with you on the various options to expose.

A few that come to mind are:
- Node size
- Node spacing
- Font size
- Start view (collapsed, not collapsed)
- Node color
- Path color
- Node stroke color
- Path tooltip using `ng-template`
- Node tooltip using `ng-template`
- Node click events
- Path click events

**What is the motivation / use case for changing the behavior?**
Need to show parent, child path relationships. A good example is various customer paths to a transition in e-commerce.

**Comment by dpineiden** [comment]
Ey! I need also something like that.

I updated that example with a resize function.

I hope that will be usefull to implement that new branch


https://gist.github.com/dpineiden/8e21e2773824f69fabfff35a01e76ba8

**Comment by dpineiden** [comment]
And you can try with that example

https://gist.github.com/dpineiden/bb4b8dc7e231d0bbdda036c3fa14c72c

**Comment by dpineiden** [comment]
Wel i started a project ngx-tree, but i need help to build in the correct way the chart....

https://github.com/dpineiden/ngx-tree

**Comment by marjan-georgiev** [comment]
@JoshSchoen take a look at https://github.com/swimlane/ngx-charts-dag
We are planning to extend that to handle different types of graphs (including trees)

**Comment by JoshSchoen** [comment]
@marjan-georgiev that's great! I've been playing with the tree a little and where I'm falling short is how to deal with the enter, update and exit methods that D3 uses which you don't seem to use much. Guessing this is due to server side rendering so it might have to be done differently to handle the parent child relationship events. If you have thoughts on this I'd be interested, would love to help with this effort, we have some other charts that the folks over at [covalent](https://github.com/Teradata/covalent) and I have been discussing and want to contribute where we can. Perhaps we can combined our efforts?

**Comment by marjan-georgiev** [comment]
We are not using the d3 lifecycle events. We only plan to use d3 for the layout, and let angular take care of the DOM and animations. That is how ngx-charts work too. Absolutely, lets work on this together. We can start by planning to abstract the graph vis library (it currently supports Dagre layout) and implement the d3 tree layout.

**Comment by JoshSchoen** [comment]
Ok great I'll start looking at the dag code and continue the conversation on that repo. For what is worth a couple other charts that we are targeting mind is the Sankey and sunburst.

**Comment by Lakston** [comment]
As anyone managed to implement . a tree chart with ngx-charts ? Do I need to look into https://github.com/swimlane/ngx-charts-dag as mentioned and furthermore, do I need both ngx-charts and dag to achieve this ?

Thanks for your help everyone !

**Comment by marjan-georgiev** [comment]
@Lakston you can visualize a tree chart with ngx-charts-dag, but it uses the dagre layout, not the d3 tree layout.

**Comment by marjan-georgiev** [comment]
Closing. Please use https://github.com/swimlane/ngx-graph for graph visualisation.

**Comment by jsonsystems** [comment]
@marjan-georgiev Is there an example for creating a hierarchical tree structure? I can't see anything on https://github.com/swimlane/ngx-graph.

**Comment by marjan-georgiev** [comment]
@jsonsystems see https://swimlane.github.io/ngx-graph/demos/examples#organization-tree

**Comment by Lonli-Lokli** [comment]
@JoshSchoen did you manage to create sankey diagram?
