### ISSUE TITLE
Display single point in line chart

### ISSUE THREAD

**Issue by walfen** [swimlane/ngx-charts#462]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Current behavior**
How can I display a single point in a line chart? Sorry if this isn't the correct place for this question but I can't find another one.

**Expected behavior**

Improve documentation with this topic.

**Please tell us about your environment:**

* **ngx-charts version:** 5.3.1

* **Angular version:** 4.2.5

* **Browser:** [all]

* **Language:** [TypeScript]

**Comment by metodribic** [comment]
It seem this is a bug, because point does get rendered, but the grid for some reason is not, and since you can not display points in lines by default, you can not see it. You can put the data in activeEntries and you'll se that point is there but everything else is missing. I'm not sure if one point "line" is event a viable line-chart, so this could potentially be expected behaviour.

**Comment by metodribic** [comment]
I noticed that if you set `autoScale=false` the grid does get rendered, but it is still a problem that the point is visible only if you put it in the `result`+ in `activeEntries` and it disappears once you hover it

**Comment by walfen** [comment]
See solution of #467

**Comment by joshigauravv** [comment]
I used solution of #467  but unable to get the result or persists circle

**Comment by FrankL-git** [comment]
I used stroke-width and stroke-linecap after the chart has been displayed. Assume the third line of your chart consists of a single data point. Then you can it display as follows:

`const el = document.querySelectorAll('g.line-series path')[2];`
`el.setAttribute('stroke-width', '5');`
`el.setAttribute('stroke-linecap', 'round');`

**Comment by chriszrc** [comment]
@FrankL-git that works great, thanks! I added that answer to the SO post here as well- https://stackoverflow.com/a/69193173/228369

**Comment by ppratikcr7** [comment]
I have posted a way simpler answer on the above SO post here: https://stackoverflow.com/a/75131314/9286991

**Comment by Mateusz19021996** [comment]
@ppratikcr7 this soultion does not work , could You please provide some more precise example?

**Comment by vivek-andani** [comment]
Can anyone suggest method to change color of dot for individual dot displayed in this ngx-line chart?
https://stackblitz.com/edit/swimlane-line-chart-pvyaj6?file=app%2Fcustom-liner-chart-service.service.ts
