### ISSUE TITLE
Horrible performance.

### ISSUE THREAD

**Issue by azarus** [swimlane/ngx-charts#470]
Overall performance is horrible. Not sure about what "server park" or machine you use but the simplest demo lags with delays like 1-2 seconds. This is quite huge performance issue, even with latest firefox + i7 4790k + gtx1070 card..

**Comment by marjan-georgiev** [comment]
Could you be a little bit more specific?

**Comment by azarus** [comment]
I assume youre joking. :) nice one

**Comment by marjan-georgiev** [comment]
I'm going to close this one as it provides no information at all. Feel free to open a new issue by properly filling out the issue template.

**Comment by azarus** [comment]
Surely will do as soon as i care more about your resource hungry project. Thanks for your time.
