### ISSUE TITLE
Why are the peer dependencies so strict 

### ISSUE THREAD

**Issue by vprasanth** [swimlane/ngx-charts#477]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
[x] discussion
```
Sorry I don't know where else to post this given I only have three choices above, I added my own.  

I was wondering why the peer dependencies are very strict right down to the patch release. Is it really that this library depends on some fix available in that patch or just there because that was the most recent version at the time? 

Locking down peer dependencies makes it very difficult (and annoying) for us consumers who may be using other libraries that share the same peer dependencies.  

Anyways was wondering thats the consensus on this?

**Comment by marjan-georgiev** [comment]
You are right, they don't have to be locked down to a patch version. Thanks for pointing it out.
