### ISSUE TITLE
Cant load charts as conflic on BrowserModule and BrowserAnimationsModule

### ISSUE THREAD

**Issue by vbenavidesa** [swimlane/ngx-charts#479]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Expected behavior**
show page with a small simple bar chart.

**Reproduction of the problem**
Barely installed ngx-charts and d3 from npm and put basic data for the simplest of charts.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10 professional, VS Code

* **ngx-charts version:** x.x.x
most recent one.

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
You're using angular 2. Only ngx-charts versions up to 4.x work with angular 2. Versions after 5 work with angular 4.

**Comment by vbenavidesa** [comment]
Hi marjan,

I am using angular 4. all my packages on package.json are 4.2.5 from @angular

**Comment by marjan-georgiev** [comment]
Then you filled the issue template wrong or didn't fill it out completely.

It looks like you are importing BrowserModule on two places in your app. It should only be imported once.

**Comment by vbenavidesa** [comment]
Hi Marjan,

Will check it out and will message you later today if sometimes goes wrong.

**Comment by vbenavidesa** [comment]
Hi Marjan,

Issue was solved thank you very much.
