### ISSUE TITLE
Question on ngx-charts usage

### ISSUE THREAD

**Issue by vbenavidesa** [swimlane/ngx-charts#480]
Hi.

This is more of a question than a bug or petition. For those of you who have worked with this before, how can you have multiple charts on the same page, and how can you input the properties on the html instead of the component.

Love **ngx-charts** but I find the documentation a bit lacking in some points. If you have the methods of doing this and are lacking the time to put a well done document for API usage, let me know I might be able to give a hand as to return something to the community.

**Comment by PolarbearDK** [comment]
Hi,

Yes, you can have multiple charts on the same page. Just use several <ngx-charts....> tags.
The questions on input parameters seems to indicate that you are new to Angular property binding. 
https://angular.io/guide/template-syntax#property-binding

I agree that the documentation is a bit lacking. I suggest you download the source code for the project, and play around with the demo project.

**Comment by eltimmo** [comment]
This had me puzzled as well, but it's pretty easy to do 

In your .ts

```typescript
  constructor()
  {
    Object.assign(this, {single})
    Object.assign(this, {serverTypes })
  }

} // outside initial class

export var serverTypes = 
[
  {
    "name": "Windows",
    "value": 10
  },
  {
    "name": "Linux",
    "value": 5
  },
];

export var single = 
[
  {
    "name": "Germany",
    "value": 8940000
  },
  {
    "name": "USA",
    "value": 5000000
  },
];
```

in your HTML
```html
    <ngx-charts-advanced-pie-chart
      [view]="view"
      [scheme]="colorScheme"
      [results]="single"
      [gradient]="gradient">
    </ngx-charts-advanced-pie-chart>

    <ngx-charts-bar-vertical
      [view]="view"
      [scheme]="colorScheme"
      [results]="serverTypes"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [legend]="showLegend"
      [showXAxisLabel]="showXAxisLabel"
      [showYAxisLabel]="showYAxisLabel"
      [xAxisLabel]="xAxisLabel"
      [yAxisLabel]="yAxisLabel">
    </ngx-charts-bar-vertical>
```

**Comment by marjan-georgiev** [comment]
@vbenavidesa does that answer your question?

**Comment by vbenavidesa** [comment]
@marjan-georgiev yes, thank you, i figured it out!
