### ISSUE TITLE
downgrade angular4 into angular 1.5

### ISSUE THREAD

**Issue by brusand** [swimlane/ngx-charts#484]
hi comunity,

it is more a question, but i don t where to post it.

i have an angular 1.5 app and i want to use your awersome framework. Is some one had already trid to downgrade ngx-chart into an anagular 1.5 app ?

Thanks 

Best regards
Bruno

**Comment by marjan-georgiev** [comment]
You can use the charts inside angular 1 if you are using a hybrid angular1/angular4 application with ngUpgrade. You can downgrade them as you would downgrade any other angular4 component.
