### ISSUE TITLE
Legend Text Overflow

### ISSUE THREAD

**Issue by dankrajnak** [swimlane/ngx-charts#486]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Long text in the legend component is cut off by the legend container without ellipsis.  The span element in which the text sits is set to 100% of the container and doesn't account for the color icon next to it.

**Expected behavior**

Long text that cannot fit in the legend box should end with an ellipsis.  The span element (selector is .legend-label-text) should have a width of `calc(100% - 15px)`, accounting for the color icon next to it.

**Reproduction of the problem**

Go to the [documentation for bar graphs](https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical.html) and change the data to create a long line of text in the legend.

* **ngx-charts version:** 6.0.0

* **Browser:** [ Chrome 59 | Firefox 54 | Edge 40 ]

**Comment by davidavdav** [comment]
I have the opposite: legend labels are always truncated to ellipsis.  No matter how wide the space for the graph is.

**Comment by MartinoMensio** [comment]
@roydekleijn I have the same issue. Did you manage to solve it in some ways?

**Comment by homj** [comment]
The fix causes issues with safari. Using `width: 100%` for legend labels fixes the safari issue.
