### ISSUE TITLE
Noob Q, 

### ISSUE THREAD

**Issue by dpineiden** [swimlane/ngx-charts#489]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

Hello, I'm creating a Tree Chart. I think it 's almost done but has some problems. 

https://github.com/dpineiden/ngx-tree

**Current behavior**
When i load the page, the system check the template first before calculate the nodes and links. And then borke websocket connection, and shows this error:

`Can't bind to 'r' since it isn't a known property of ':svg:circle'. ("eNodeId(node)" [attr.transform]="transform" (click)="onNodeClick(node)">
    <circle class="figure" [ERROR ->][r]="node.radius" [cursor]="node.cursor" [style]="node.styles" [transform]="node.transform" [cx]="nod"): ng:///TreeGraphModule/TreeGraphComponent.html@22:27
Can't bind to 'cursor' since it isn't a known property of ':svg:circle'. ("tr.transform]="transform" (click)="onNodeClick(node)">
`

**Expected behavior**

I expect that the nodes and paths are drawing on the svg, but nothing happens.

**Reproduction of the problem**

Clone the git, install npm, start server.

**What is the motivation / use case for changing the behavior?**

Check data structures in a graph.

**Please tell us about your environment:**

Gnu Linux, Debian.

* **ngx-charts version:** x.x.x
6.0.0

* **Angular version:** 2.x.x
4.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox and Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
ES6 i guess ....

**Comment by marjan-georgiev** [comment]
You need to use `<svg:circle [attr.r]="5" />`
