### ISSUE TITLE
I'm adding ngx-charts to my angular 4 app and getting an error 

### ISSUE THREAD

**Issue by jithin-jain** [swimlane/ngx-charts#490]
I am adding ngx-charts to my angular 4 app and getting error for @angular/animations.

The Error message is : 

_ERROR in ./~/@swimlane/ngx-charts/release/index.js
Module not found: Error: Can't resolve '@angular/animations' in 'D:\Latest proj\node_modules\@swimlane\ngx-charts\release'
 @ ./~/@swimlane/ngx-charts/release/index.js 8:225-255
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts_

older version of ngx-charts works with angular2 but am getting error with angular4. So i updated ngx-charts to 5.0.0 version and respective d3 version required but yet getting error for @angular/animations. 

My package.json file now looks like -

"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@swimlane/ngx-charts": "^5.0.0",
    "core-js": "^2.4.1",
    "d3": "^4.9.0",
    "dateformat": "^2.0.0",
    "rxjs": "^5.2.0",
    "zone.js": "^0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.1",
    "@types/jasmine": "^2.5.53",
    "@types/node": "^6.0.60",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.4",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "2.0.0-beta.5",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.16.1",
    "jasmine-core": "^2.4.1",
    "null-loader": "^0.1.1",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "style-loader": "^0.13.1",
    "typescript": "^2.2.2",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.4.1",
    "webpack-merge": "^3.0.0"
  }

**Comment by dpineiden** [comment]
Try this:

`{
  "name": "ngx-tree",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/core": "^4.2.5",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/router": "^4.2.5",
    "@swimlane/ngx-charts": "^6.0.0",
    "@swimlane/ngx-ui": "^17.2.9",
    "core-js": "^2.4.1",
    "d3": "^4.10.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.4",
    "@angular/compiler-cli": "^4.2.5",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by jithin-jain** [comment]
Thanks dpineiden!!!
It was versions issue and is resolved.

**Comment by Famalis** [comment]
Hello, sorry for asking this on a closed issue, but didn't want to clone. I am having a similar problem

`ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-normalized.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/legend/legend.component.d.ts (1,83): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/legend/scale-legend.component.d.ts (2,30): Cannot find module '@angular/platform-browser'
.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/legend/legend-entry.component.d.ts (1,30): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/legend/advanced-legend.component.d.ts (1,56): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/tooltip/injection.service.d.ts (1,88): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/tooltip/injection-registery.service.d.ts (1,30): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/tooltip/tooltip.component.d.ts (1,53): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/tooltip/tooltip.directive.d.ts (1,89): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/count/count.directive.d.ts (1,80): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/timeline/timeline.component.d.ts (1,95): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/timeline/timeline.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/charts/chart.component.d.ts (1,74): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/area.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/area.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/base-chart.component.d.ts (1,121): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/base-chart.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/utils/visibility-observer.d.ts (1,38): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/circle.component.d.ts (1,56): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/circle-series.component.d.ts (1,77): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/circle-series.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/grid-panel-series.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/svg-linear-gradient.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/svg-radial-gradient.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/tooltip-area.component.d.ts (1,53): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/area-chart/area-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/area-chart/area-chart-normalized.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/area-chart/area-chart-stacked.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/area-chart/area-series.component.d.ts (1,56): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-2d.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-normalized.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-horizontal-stacked.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-2d.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/common/legend/scale-legend.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/bar-vertical-stacked.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/series-horizontal.component.d.ts (1,69): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bar-chart/series-vertical.component.d.ts (1,54): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bubble-chart/bubble-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/bubble-chart/bubble-series.component.d.ts (1,69): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/force-directed-graph/force-directed-graph.component.d.ts (1,55): Cannot find module '@angular/co
re'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/heat-map/heat-map-cell.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/heat-map/heat-map-cell.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/heat-map/heat-map-cell-series.component.d.ts (1,77): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/heat-map/heat-map.component.d.ts (1,29): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/line-chart/line.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/line-chart/line-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/line-chart/line-series.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/line-chart/line-series.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/polar-chart/polar-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/polar-chart/polar-series.component.d.ts (1,55): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/polar-chart/polar-series.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/number-card/card.component.d.ts (1,106): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/number-card/card-series.component.d.ts (1,64): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/advanced-pie-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-label.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-arc.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-arc.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-chart.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-grid.component.d.ts (1,29): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-grid-series.component.d.ts (1,68): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/pie-chart/pie-series.component.d.ts (1,69): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/tree-map/tree-map-cell.component.d.ts (1,53): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/tree-map/tree-map-cell.component.d.ts (2,34): Cannot find module '@angular/common'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/tree-map/tree-map-cell-series.component.d.ts (1,69): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/tree-map/tree-map.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/gauge/linear-gauge.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/gauge/gauge.component.d.ts (1,70): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/gauge/gauge-arc.component.d.ts (1,43): Cannot find module '@angular/core'.
ERROR in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/gauge/gauge-axis.component.d.ts (1,42): Cannot find module '@angular/core'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve @angular/core relative to D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts
/release/ngx-charts.module.d.ts., resolving symbol NgxChartsModule in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/ngx-charts.module.d.ts, resolving s
ymbol NgxChartsModule in D:/Projekty/RemoteHeroes/Cubi/CubiFrontend/node_modules/@swimlane/ngx-charts/release/ngx-charts.module.d.ts
    at syntaxError (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:1725:34)
    at simplifyInContext (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24949:23)
    at StaticReflector.simplify (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24961:13)
    at StaticReflector.annotations (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24391:41)
    at _getNgModuleMetadata (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\Projekty\RemoteHeroes\Cubi\CubiFrontend\curb-frontend\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at <anonymous>`

Here is my package.json

`{
  "name": "curb-frontend",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json --host 127.0.0.1",
    "start-1": "ng serve --proxy-config proxy-test.config.json --host curb-test.copro.no",
    "build": "ng build",
    "build:prod": "ng build -prod -aot false",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.3.6",
    "@angular/core": "^4.3.6",
    "@angular/forms": "^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/platform-server": "^4.3.6",
    "@angular/router": "^4.3.6",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/lodash": "^4.14.72",
    "@types/moment": "^2.13.0",
    "@types/socket.io-client": "^1.4.29",
    "angular-progress-http": "^0.5.1",
    "angular-svg-round-progressbar": "^1.1.0",
    "angular2-moment": "^1.3.3",
    "angular2-recaptcha": "^0.6.0",
    "angular2-sails": "^0.2.8",
    "angular2-virtual-scroll": "^0.3.0",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.5.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "ng2-bootstrap": "^1.6.3",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-charts": "^1.5.0",
    "ng2-file-upload": "^1.2.1",
    "ngx-bootstrap": "^2.0.0-beta.5",
    "ngx-file-drop": "^1.0.10",
    "ngx-popper": "^1.1.0",
    "rxjs": "^5.1.0",
    "socket.io-client": "^1.7.3",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.2",
    "@angular/compiler-cli": "^4.3.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "^2.5.2",
    "webpack": "^3.4.1"
  }
}
`
