### ISSUE TITLE
Stacked Area Chart: [autoScale] not implemented.

### ISSUE THREAD

**Issue by sjdemoor** [swimlane/ngx-charts#492]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
```
Template parse errors:
Can't bind to 'autoScale' since it isn't a known property of 'ngx-charts-area-chart-stacked'.
```

**Expected behavior**
This is probably intentional, since it doesn't really make sense for 'autoScale' functionality on a stacked area chart.  With that said, either the documentation should be corrected, or the functionality should be added. 

**Reproduction of the problem**
```
<ngx-charts-area-chart-stacked
  ...
  [autoScale]="true"
  ...>
</ngx-charts-area-chart-stacked>  
```
**What is the motivation / use case for changing the behavior?**
Probably -- clean up documentation.

**Please tell us about your environment:**
any

* **ngx-charts version:** 6.0.0

* **Angular version:** 4.1.2

* **Browser:** [all]

* **Language:** [all]

**Comment by michaelfaisst** [comment]
This is also applies to the normalized area chart (and it also doesn't make sense to have autoScale for it, so it's only a documentation issue).
