### ISSUE TITLE
Ability to add labels on the bars for bar chart

### ISSUE THREAD

**Issue by limpep** [swimlane/ngx-charts#493]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request => Please do not submit support request here
```

**Expected behavior**

Hi I was wondering if it would be possible to add labels on the actual bars? similar to this.

https://ibb.co/iQQQ5Q

thanks

**Please tell us about your environment:**

Mac

* **ngx-charts version:** ^6.0.1

d3": "^4.10.0

```
@angular/cli: 1.2.6
node: 8.2.1
os: darwin x64
@angular/animations: 4.3.2
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/language-service: 4.3.2
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
```

**Comment by Phota16** [comment]
Please let me know or give some idea , how to print x-axis value on the bar 
exa 
![image](https://user-images.githubusercontent.com/20189130/30180244-d560596a-93d4-11e7-9469-d4528ac40ded.png)

**Comment by calebeaires** [comment]
@limpep have you achieved to do that? This will be a very usefull feature!

**Comment by limpep** [comment]
@calebeaires I found out that it what I needed could be achieved with CSS. Thanks

**Comment by pmadhavan** [comment]
@limpep Can you give an example of how did that using CSS?

**Comment by luoguibin** [comment]
ah, this is a question than I want to ask, but the answer....

**Comment by marjan-georgiev** [comment]
This is supported through the `showDataLabel` input.
