### ISSUE TITLE
Behaviour on remove element from list, doesn't remove from svg

### ISSUE THREAD

**Issue by dpineiden** [swimlane/ngx-charts#499]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

This is the project
https://github.com/dpineiden/ngx-tree

**Current behavior**

I have a list of nodes and links. When click on node with children the system splice the children nodes and link paths. But doesn't update the *ngFor on the svg section, so the children nodes don't dissapeard.

**Expected behavior**
Clean children nodes and links

**Reproduction of the problem**

Clone and run the project, it shows a test view with data example.

**What is the motivation / use case for changing the behavior?**

Be similar to traa graph from d3.

**Please tell us about your environment:**

Gnu Linux, Debian, etc

* **ngx-charts version:** x.x.x

last version-.-
* **Angular version:** 2.x.x

last version ..

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Mozilla, Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
You need to pass a new array to the `results` input, because the input is immutable.

```
this.results = [...this.results]`
```
