### ISSUE TITLE
Feature: Gauge Chart Additions

### ISSUE THREAD

**Issue by mtpultz** [swimlane/ngx-charts#500]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Feature Request**
Customization of the Gauge chart:  

1. Allow colour gradient for bar that indicates max value, or
1. Separated segments via breaks that allow use of different colors indicating segment level or priority
1. Gauge indicator showing current level versus the max value

An example image showing points, and a D3 example https://codepen.io/jaketrent/pen/eloGk showing segments and colours.  I've also been trying to play with this example http://bl.ocks.org/ameyms/9184728 showing segment on the end of indicator, which seemed like an interesting idea to show a gradient on instead of solid blue.

![image](https://user-images.githubusercontent.com/599498/28946802-4670a658-7861-11e7-959f-852ed2710098.png)

* **Angular version:** 4.x.x

**Comment by marjan-georgiev** [comment]
This looks like a good candidate for a custom chart. Extending the current gauge chart to also support these different styles and looks would make it very complicated. I suggest creating a custom chart by using the gauge chart code and modifying it.

**Comment by mtpultz** [comment]
@marjan-georgiev Do you have an example of customizing the gauge chart.  Just a single change to the chart, but a starting point to continue off that is good practice.  I'm only just learning D3 and I'm not overly confident after looking at your code I would start modifying it properly and in a clean way.  Just looking for what you would consider best practice for customizing a chart

**Comment by marjan-georgiev** [comment]
@mtpultz please take a look at this PR: https://github.com/swimlane/ngx-charts/pull/588 and comment there whether this covers your use case.

**Comment by mtpultz** [comment]
@marjan-georgiev wow that looks great!

I think my feature request was a bit too confusing with the picture, which was an over the top example of elements in the two linked examples that were the focus:

1. The block (http://bl.ocks.org/ameyms/9184728) that had a line that fills up to a value, is able to turn off the gauge pointer, and have a stacked value over unit similar to the centered value in the image or #78

1. The codepen (https://codepen.io/jaketrent/pen/eloGk) that shows divided colour segments, but instead similar to the image where out of 100 units yellow might be 40 units, orange 50 units, and red 10 units?  Seems all the gauges I've tried to use force even incremental colour segments instead of differing segment ranges

**Comment by marjan-georgiev** [comment]
Yes please, post that in the PR so we can make sure it's modified as needed.
