### ISSUE TITLE
Chart Tooltip does not work on touch devices

### ISSUE THREAD

**Issue by jboothe** [swimlane/ngx-charts#511]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Tap or long press on bar chart does not display a tooltip. A long press shows an unpopulated tooltip with incorrect css applied. 

**Expected behavior**

Tap on any chart bar (or pie slice) should display tooltip. 

**Reproduction of the problem**
Go to [demo page](https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-vertical.html) with a touch device and tap or long press on a bar.

**What is the motivation / use case for changing the behavior?**
Users of touch devices need access to tooltips that desktop users get on hover.

**Comment by Creiger** [comment]
I have a simiIar request. I am not sure which mobile OS are you using, but on iOS it is not a chart tooltip that shows up. Its an iOS text selection tool. So i think that we either need an option to select whitch event will be used for tooltip show or just add a tap input as another trigger for it.

**Comment by jboothe** [comment]
This behavior occurs on iOS 9, 10. 
Is this a known issue?

**Comment by Creiger** [comment]
That is exactly what i am talking about. This is a regular iOS text selection tool. It is not an unpopulated tooltip with wrong css. Tooltip just does not show. What should be the trigger is another question. I think adding an option selecting a trigger would be the best.

**Comment by marjan-georgiev** [comment]
The tap should be triggering the chart select output. We need to bind the tooltip to another event. Any suggestions?

**Comment by Creiger** [comment]
Maybe a longtap (taphold)?

**Comment by jboothe** [comment]
Are there any plans to address this one in the immediate future? Thanks.

**Comment by androidparth90** [comment]
Hi All,

Is this issue resolved?

**Comment by weisss123** [comment]
I am still facing the same issue in 8.1.0

**Comment by jhilscher** [comment]
Works fine on Android. Seems to be an iOs issue, (9.0.0)

**Comment by Benno007** [comment]
Interested in having this available as well :+1:

**Comment by aldred1314** [comment]
Currently it still broken, any other way to fix it?

**Comment by SmirnovM91** [comment]
+1, and tooltip shows up If I click 3 times on bar, how to fix it?

**Comment by BizzottoClaudio** [comment]
on a samsung tablet with the latest chrome (78.0.3904.62) the tooltip works flawlessly, but on ipad air with ios 12.4.2 it doesn't show at all

**Comment by marjan-georgiev** [comment]
Merged, will be in the next release.
