### ISSUE TITLE
how to change color schema in charts

### ISSUE THREAD

**Issue by ipula** [swimlane/ngx-charts#512]
i need to change color schema in line chart like demos in here https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart . Need example plz,plunker may be good

**Comment by marjan-georgiev** [comment]
You can look at the code of the demo page for that:

https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.ts#L408

The color schemes need to have the following format:
```
{
  domain: ['#000000', '#FF0000']
}
```

These are the built-in color schemes into the library:
https://github.com/swimlane/ngx-charts/blob/master/src/utils/color-sets.ts
You can also reference these by the name

**Comment by Stexxen** [comment]
> These are the built-in color schemes into the library:
> https://github.com/swimlane/ngx-charts/blob/master/src/utils/color-sets.ts
> You can also reference these by the name
> 

Could you explain how? i.e. I want to use the 'vivid' colorset, and setting [scheme] to 'vivid' just creates lots of errors about
`Cannot read property 'scaleType' of undefined`

**Comment by hariramesh9a** [comment]
> > > These are the built-in color schemes into the library:
> > > https://github.com/swimlane/ngx-charts/blob/master/src/utils/color-sets.ts
> > > You can also reference these by the name
> > 
> > 
> > Could you explain how? i.e. I want to use the 'vivid' colorset, and setting [scheme] to 'vivid' just creates lots of errors about
> > `Cannot read property 'scaleType' of undefined`
> 
> just say scheme="flame"

<ngx-charts-bar-vertical [view]="view" scheme="flame" [results]="single" [gradient]="gradient"
            [xAxis]="showXAxis" [yAxis]="showYAxis" [legend]="showLegend" [showXAxisLabel]="showXAxisLabel"
            [showYAxisLabel]="showYAxisLabel" [xAxisLabel]="xAxisLabel" [yAxisLabel]="yAxisLabel" (select)="onSelect($event)">
          </ngx-charts-bar-vertical>

**Comment by abhijitchikane-angularminds** [comment]
> You can look at the code of the demo page for that:
> 
> https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.ts#L408
> 
> The color schemes need to have the following format:
> 
> ```
> {
>   domain: ['#000000', '#FF0000']
> }
> ```
> 
> These are the built-in color schemes into the library:
> https://github.com/swimlane/ngx-charts/blob/master/src/utils/color-sets.ts
> You can also reference these by the name

Can you please share how to reference it by name
