### ISSUE TITLE
cut label in pie chart

### ISSUE THREAD

**Issue by mailok** [swimlane/ngx-charts#513]
Hi!, i have a problem using pie chart, my code is attached.
the label is not show complete, any suggestions?
![need show](https://user-images.githubusercontent.com/3769277/29213167-120580e0-7e70-11e7-8ec3-2040d86a7624.PNG)

My versions:
"@swimlane/ngx-charts": "^6.0.1"
"d3": "^4.10.0"
Angular: 4.2.6

![chart](https://user-images.githubusercontent.com/3769277/29176639-66311424-7dba-11e7-8978-d29d7451ac17.PNG)
![funtion](https://user-images.githubusercontent.com/3769277/29176640-6659cbee-7dba-11e7-90b7-6b4e037a86a4.PNG)
![html](https://user-images.githubusercontent.com/3769277/29176637-637daa1c-7dba-11e7-9a06-17b98a1536c1.PNG)

**Comment by ImranAhmed** [comment]
It's due to the fact that the library is trimming the label as follows.

[{{trimLabel(label, 10)}}](https://raw.githubusercontent.com/swimlane/ngx-charts/master/src/pie-chart/pie-label.component.ts)

There seems to be no easy way to display the full label plus value.

**Comment by marjan-georgiev** [comment]
This was added and released in 7.1.0
