### ISSUE TITLE
Grouped horizontal bar chart renders bar height and whitespace improperly when data sets contain items of different names

### ISSUE THREAD

**Issue by wakers01** [swimlane/ngx-charts#515]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When displaying a grouped horizontal bar chart, given the set of data below or some similar set, the chart renders in an odd way. There is a great amount of whitespace between the groups and the bars of the chart are very skinny and do not take up all available space within the chart. This appears to happen when multiple series of data have differing names, as if the chart wants to allow space for all sets from each group in every group rather just allowing space for sets only within the group they exist in.

**Expected behavior**
The excess whitespace in the chart should not exist, and the height of the bars in the chart should expand to fill the available space.

**Reproduction of the problem**
The issue is easy to reproduce using the example on the official example page located here:
https://swimlane.gitbooks.io/ngx-charts/content/charts/bar-horizontal-2d.html

Replace the data in the "multi" array in the data.ts file with the following series:
[
  {
    "name": "New Items",
    "series": [
      {name: "Item01", value: 13704},
      {name: "Item02", value: 15111},
      {name: "Item03", value: 205},
      {name: "Item04", value: 168}
    ]
  },
  {
    "name": "Old Items",
    "series": [
      {name: "ItemC1", value: 472},
      {name: "ItemC2", value: 396},
      {name: "Item1", value: 40242},
      {name: "Item2", value: 37193},
      {name: "Item3", value: 34208},
      {name: "Item4", value: 17665},
      {name: "Item5", value: 34199},
      {name: "Item6", value: 34336},
      {name: "Item7", value: 18},
      {name: "Item8", value: 11}
    ]
  }
];

**What is the motivation / use case for changing the behavior?**
Ideally I think most users would like a chart that renders evenly spaced and dimensioned bars in most / all cases

**Comment by marjan-georgiev** [comment]
This is because the barPadding and groupPadding options are currently in pixels, so they are absolute. We are planning to allow them to be relative (as a percentage of the bar width), so they scale proportionally when the chart is resized or more elements are added. There is a PR for it already:

https://github.com/swimlane/ngx-charts/pull/342
