### ISSUE TITLE
Add ability to change advanced pie chart font size

### ISSUE THREAD

**Issue by wakers01** [swimlane/ngx-charts#516]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The advanced pie chart does not provide a way to change the size of the font that renders percentages and totals. Because of this, if you shrink the pie chart, the chart itself shrinks, but the text remains the same size, so you get some very odd mismatches between chart size and font size (e.g. tiny chart and huge font).

**Expected behavior**
Ideally, changing the chart size using the view property would scale the font along with the chart, so the font size remains relative to the chart size.

**Reproduction of the problem**
Go to the official docs here:
https://swimlane.gitbooks.io/ngx-charts/content/charts/advanced-pie-chart.html

Change the view array values in app.ts from the default of [700, 400] to something like [700, 200] or [300, 400]. 

**What is the motivation / use case for changing the behavior?**
The current behavior makes it difficult to scale this chart to smaller sizes, and that presents a visualization problem for some applications of the chart depending on website size, scale.

**Comment by marjan-georgiev** [comment]
You can override the font size, spacing, padding by css
https://plnkr.co/edit/1JKS2CRy6EjL59JIqqCv?p=preview

**Comment by marjan-georgiev** [comment]
We may want to look into making the text sizes relative to the chart size.

**Comment by BearandYoon** [comment]
Hi @marjan-georgiev 

I am using advanced-pie-chart in my project and it works well but I need to change the chart layout.
https://stackblitz.com/edit/angular-k3wm1u
As you can see in this example, pie-chart is very small than the legend section.
I would like to make the pie chart bigger.
I tried to change the width of advanced-pie class and .advanced-pie-legend-wrapper class but it doesn't work for me.

**Comment by BearandYoon** [comment]
Hi @marjan-georgiev 

Did you check above post?

**Comment by marjan-georgiev** [comment]
@BearandYoon take a look at the changes I made:

https://stackblitz.com/edit/angular-tnctpx?file=app/table/table.component.scss

You shouldn't change the chart element's size, but the size of its container. I moved the pie-chart-container class to a div that wraps the chart, and added min-width to it.

**Comment by SkanderLassoued09** [comment]
How can i modify the css ngx admin
