### ISSUE TITLE
Ability to set min and max values for x axis - regardless of highest value in dataset

### ISSUE THREAD

**Issue by simonmlewis** [swimlane/ngx-charts#518]
I'm submitting a feature request

**Current behavior**
The x axis maximum value currently seems to be driven by the highest value in the dataset.

**Expected behavior**
It would be good to set a min and max value - something like [min]="0" [max]="100" or of course somewhere in the data object

**What is the motivation / use case for changing the behavior?**
We have a graph that shows percentages and we'd like to be able to have 0 - 100% along the x axis regardless of the highest value in the dataset. I'd have thought this is fairly standard functionality but I can't find anything in the documentation.

![image](https://user-images.githubusercontent.com/4834843/29265790-3d9cf1f4-80da-11e7-936b-82da8da81d25.png)

**Comment by marjan-georgiev** [comment]
This will be in the next version as part of https://github.com/swimlane/ngx-charts/pull/359
