### ISSUE TITLE
Stacked Horizontal Bar Chart renders VERY slowly with large dataset

### ISSUE THREAD

**Issue by PolarbearDK** [swimlane/ngx-charts#519]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Stacked Horizontal Bar Chart renders VERY slowly with large dataset (100 groups with up to ~50 series)

It takes up to 30 seconds in Chrome to fully render chart while browser fully utilize one CPU core. It is even slower in Edge.

I used to have a similar performance problems with time series Area Chart, but it was fixed in 6.0.0. 

**Expected behavior**

Faster renderingen.

**Reproduction of the problem**

Sorry, but I cant publish my data.

This is how it looks while it is waiting to render:
![firstrender](https://user-images.githubusercontent.com/5196920/29276401-d03049d8-810e-11e7-8dd1-6ae54a7415d4.png)

And this is how it looks when rendered.
![finalrender](https://user-images.githubusercontent.com/5196920/29276477-0c874e0e-810f-11e7-98c5-7a1ebb8c0028.png)

**What is the motivation / use case for changing the behavior?**

Better user experience.

**Please tell us about your environment:**

Windows, NG cli, yarn

* **ngx-charts version:** 6.0.1

* **Angular version:** 4.3.2 and 4.3.4

* **Browser:** Chrome 60, Edge.

* **Language:** TypeScript 2.4.2

**Comment by PolarbearDK** [comment]
Reproduce using: https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-horizontal-stacked
Check the following check boxes:
- Data > Real-Time
- Dimensions > Fit Container (or fixed height 2000-4000)
- Options > Use Gradients
Now sit back and watch the CPU usage increase as the dataset grows.

**Comment by kc7bfi** [comment]
I'm having a similar problem although I never see the horizontal stacked bar render.

**Comment by EricSmekens** [comment]
Did you try to switch off animations?
For 50 series with 100 datapoints, it is pretty quick for me without animations.

With animations it takes 10-15 seconds to complete the animations indeed.
