### ISSUE TITLE
Option for not changing x and y axis value ranges when updating values

### ISSUE THREAD

**Issue by matthias-herrmann** [swimlane/ngx-charts#520]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```
E.g. I used the line chart to display device counts for different locations. The user can deselect locations and the data is getting removed and the chart is getting updated but the range of the x and y axis change and so the user can't really compare how many devices that one location had.

**Comment by marjan-georgiev** [comment]
This is coming in the next version as part of https://github.com/swimlane/ngx-charts/pull/359
