### ISSUE TITLE
line and heat map chart issues

### ISSUE THREAD

**Issue by praveenrajkr** [swimlane/ngx-charts#521]
Hi ,
 facing this two errors when am trying to use LINE and HEATMAP charts .Help me with the following

------------------------------------------------------------------------------------------
ERROR TypeError: Cannot read property 'length' of undefined
    at LineChartComponent../src/line-chart/line-chart.component.ts.LineChartComponent.getXDomain (index.js:14887)
    at LineChartComponent../src/line-chart/line-chart.component.ts.LineChartComponent.update (index.js:14855)
    at LineChartComponent../src/common/base-chart.component.ts.BaseChartComponent.ngOnChanges (index.js:9160)
    at checkAndUpdateDirectiveDynamic (core.es5.js:10868)
    at checkAndUpdateNodeDynamic (core.es5.js:12366)
    at checkAndUpdateNode (core.es5.js:12281)
    at debugCheckAndUpdateNode (core.es5.js:13139)
    at debugCheckDirectivesFn (core.es5.js:13080)
    at Object.eval [as updateDirectives] (LineChartComponent.html:1)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13065)

ERROR CONTEXT:
---------------------------

View_LineChartComponent_0 | @ | LineChartComponent.html:1
-- | -- | --
  | proxyClass | @ | compiler.es5.js:14971
  | webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError | @ | core.es5.js:13405
  | webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError | @ | core.es5.js:1085
  | (anonymous) | @ | core.es5.js:4814
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run | @ | zone.js:141
  | webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular | @ | core.es5.js:3844
  | webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick | @ | core.es5.js:4814
  | (anonymous) | @ | core.es5.js:4684
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | onInvoke | @ | core.es5.js:3890
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:390
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run | @ | zone.js:141
  | webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run | @ | core.es5.js:3821
  | next | @ | core.es5.js:4684
  | schedulerFn | @ | core.es5.js:3635
  | webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:238
  | webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:185
  | webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next | @ | Subscriber.js:125
  | webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next | @ | Subscriber.js:89
  | webpackJsonp.../../../../rxjs/Subject.js.Subject.next | @ | Subject.js:55
  | webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit | @ | core.es5.js:3621
  | checkStable | @ | core.es5.js:3855
  | onHasTask | @ | core.es5.js:3903
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.hasTask | @ | zone.js:444
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate._updateTaskCount | @ | zone.js:464
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone._updateTaskCount | @ | zone.js:288
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask | @ | zone.js:208
  | drainMicroTaskQueue | @ | zone.js:595
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:502
  | invokeTask | @ | zone.js:1370
  | globalZoneAwareCallback | @ | zone.js:1388

--------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------

LineChartComponent.html:2 ERROR TypeError: Cannot read property 'scaleType' of undefined
    at ChartComponent../src/common/charts/chart.component.ts.ChartComponent.getLegendType (index.js:9465)
    at ChartComponent../src/common/charts/chart.component.ts.ChartComponent.update (index.js:9452)
    at ChartComponent../src/common/charts/chart.component.ts.ChartComponent.ngOnChanges (index.js:9447)
    at checkAndUpdateDirectiveInline (core.es5.js:10840)
    at checkAndUpdateNodeInline (core.es5.js:12339)
    at checkAndUpdateNode (core.es5.js:12278)
    at debugCheckAndUpdateNode (core.es5.js:13139)
    at debugCheckDirectivesFn (core.es5.js:13080)
    at Object.View_LineChartComponent_0._co [as updateDirectives] (LineChartComponent.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13065)

ERROR CONTEXT
--------------------------

View_LineChartComponent_0 | @ | LineChartComponent.html:2
-- | -- | --
  | proxyClass | @ | compiler.es5.js:14971
  | webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError | @ | core.es5.js:13405
  | webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError | @ | core.es5.js:1085
  | (anonymous) | @ | core.es5.js:4814
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run | @ | zone.js:141
  | webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular | @ | core.es5.js:3844
  | webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick | @ | core.es5.js:4814
  | (anonymous) | @ | core.es5.js:4684
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:391
  | onInvoke | @ | core.es5.js:3890
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke | @ | zone.js:390
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run | @ | zone.js:141
  | webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run | @ | core.es5.js:3821
  | next | @ | core.es5.js:4684
  | schedulerFn | @ | core.es5.js:3635
  | webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub | @ | Subscriber.js:238
  | webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next | @ | Subscriber.js:185
  | webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next | @ | Subscriber.js:125
  | webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next | @ | Subscriber.js:89
  | webpackJsonp.../../../../rxjs/Subject.js.Subject.next | @ | Subject.js:55
  | webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit | @ | core.es5.js:3621
  | checkStable | @ | core.es5.js:3855
  | onLeave | @ | core.es5.js:3934
  | onInvokeTask | @ | core.es5.js:3884
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask | @ | zone.js:423
  | webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask | @ | zone.js:191
  | webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask | @ | zone.js:498
  | invokeTask | @ | zone.js:1370
  | globalZoneAwareCallback | @ | zone.js:1388

**Comment by marjan-georgiev** [comment]
Are you passing the correct data?

Check the documentation on the data format those charts expect:
https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html
https://swimlane.gitbooks.io/ngx-charts/content/charts/heat-map.html

**Comment by marjan-georgiev** [comment]
Either that, or you are not passing any data at all (i.e. the chart is initialized while your data is still loading).

I am going to close this. If that is not the issue, please reply and we can reopen.
