### ISSUE TITLE
Pie Grid Issues

### ISSUE THREAD

**Issue by naxikoril** [swimlane/ngx-charts#524]
I need to use single Grid

**Eg:**
1. I have a Grid named My Contracts, total number of contacts is 100 my contracts is 10 so  the percentage is 10% and Total is 100 or I need to toggle Total label at bottom of the Pie Grid and toggle center percentage, 

may you please look into this?
Thanks.

**Comment by marjan-georgiev** [comment]
This will probably fix your use case: https://github.com/swimlane/ngx-charts/pull/554

It will be released in the next version.

**Comment by codesweetcat** [comment]
Thanks for sharing this great ng-chart framework. 
may I ask a query, I found seemly tool just supports 3XN rows format even I adjust view size. 
is it possible to set more than 3 columns ? 

 thanks in advance
