### ISSUE TITLE
Multiple charts in one diagram

### ISSUE THREAD

**Issue by achimha** [swimlane/ngx-charts#528]
**I'm submitting a ...** 
```
[X] feature request
```
From what I gathered, multiple series in one chart always use the same X/Y coordinate system. Is there a way to have multiple charts in one diagram with their own X/Y axes? The output should look like this.

![screen shot 2017-08-24 at 15 02 29](https://user-images.githubusercontent.com/6816140/29667634-6647bb24-88dd-11e7-9fb5-78ba2e4c39fb.png)

**Comment by marjan-georgiev** [comment]
This is only possible by writing a custom chart. You can find an example on how to combine the different components of ngx-charts here: 
https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

**Comment by anishgomez** [comment]
Please provide the example for combo chart.  Otherwise please remove that example from your demo. It leads to choose the wrong plugin. I choose this plugin after saw your demos. If one of that demo item is not supported means then why you still keep there. I am stuck in between the development.

**Comment by rsimpson2** [comment]
Almost 2 years later and the details of the implementation of "custom" charts is zero.
