### ISSUE TITLE
some charttypes throw TypeErrors on old WebView (30.0.0.0)

### ISSUE THREAD

**Issue by znegva** [swimlane/ngx-charts#529]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
I am not sure what the problem really is...
I am building an App using ionic and ngx-charts, targets are Browsers, Android and iOS.
At one point I am using a pie-chart and everything is fine, works on all testing devices, even on the old Android 4.4.2 with WebView Version/4.0 Chrome/30.0.0.0.

But when I try to use bar-charts they are not rendered at all and Errors are thrown on the old Webview. On other modern browsers and webviews everything works fine.
I think the first problem is:
```
Object [object Array] has no method 'includes'
```

Array.includes() is a **ES2016** (aka ES7) thing (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)) and only supported by WebView beginning from version 47.
So no surprise it is not working in WebView 30.0.0.0.

Buuut, as far as I understand the [tsconfig.json](https://github.com/swimlane/ngx-charts/blob/master/tsconfig.json) of the ngx-charts project targets ES5 , so all Array.includes() should be converted to something ES5 like.
Why are there Array.includes() left e.g. in [/release/bar-chart/bar-horizontal-2d.component.js](https://github.com/swimlane/ngx-charts/blob/master/release/bar-chart/bar-horizontal-2d.component.js) line 84?

So this is more a comprehension question than a real bug-report.

I would like to use ngx-charts for the App also on older Android phones, are there any suggestions on how to do it (how to get rid of Array.includes() in the "release" files)?

**Current behavior**
some charttypes throw TypeErrors on old Webview,  

**Expected behavior**
Charts should render :-/

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** 5.3.1

* **Angular version:** 4.1.3

* **Browser:** [Android 4.4.2 WebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Have you tried including a polyfill for it?

**Comment by znegva** [comment]
Indeed using a polyfill does make it work on the old WebView.

My concern was/is why do the JS files in _release_-folder use _Array.includes_ (supported as of ES2016 aka ES7<sup>1</sup>) despite the target of ngx-charts is ES5<sup>1</sup>.



---
<sup>1</sup> [ECMA Script Versions Overview](https://en.wikipedia.org/wiki/ECMAScript#Versions)

**Comment by LoveJuhee** [comment]
add "import 'core-js/es7/array';" to polyfills.ts 

https://github.com/angular/angular-cli/issues/4128#issuecomment-274053739
