### ISSUE TITLE
Errors with d3 4.10.0

### ISSUE THREAD

**Issue by juergenr** [swimlane/ngx-charts#537]
I get following errors using d3 version 4.10.0:
(With former d3 versions e.g. 4.9.1 all works fine)

```
in ./node_modules/@swimlane/ngx-charts/release/index.js
Module not found: Error: Can't resolve 'd3-hierarchy' in 'C:\Projects\dashboard\node_modules\@swimlane\ngx-charts\release'
 @ ./node_modules/@swimlane/ngx-charts/release/index.js 8:257-280
 @ ./ClientApp/app/app.module.shared.ts
 @ ./ClientApp/app/app.module.client.ts
 @ ./ClientApp/boot-client.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot-client.ts

in ./node_modules/@swimlane/ngx-charts/release/index.js
Module not found: Error: Can't resolve 'd3-shape' in 'C:\Projects\dashboard\node_modules\@swimlane\ngx-charts\release'
 @ ./node_modules/@swimlane/ngx-charts/release/index.js 8:355-374
 @ ./ClientApp/app/app.module.shared.ts
 @ ./ClientApp/app/app.module.client.ts
 @ ./ClientApp/boot-client.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot-client.ts
```

Versions I use:
ngx-charts: 6.0.2
angular: 4.3.6
rxjs: 5.4.3
d3:  -4.9.1 OK,   4.10.0 ERROR
typescript: 2.4.2

OS: Win 10
Browser: all

**Comment by jvieyra92** [comment]
I had a similar problem. In our project.config.ts we had to add those additional packages as well because index.js wasn't bringing them in for us. Not 100% sure its the correct way but it got it working. Code looks like this 

 {
      name: 'd3-hierarchy',
      path: `node_modules/d3-hierarchy/build`,
      packageMeta: {
        main: 'd3-hierarchy.js',
        defaultExtension: 'js'
      }
     },

**Comment by juergenr** [comment]
Through adding d3-hierachy and d3-shape to the package.json file its working.
```
        "d3": "4.10.2",
        "d3-hierarchy": "1.1.5",
        "d3-shape": "1.2.0",
```

**Comment by marjan-georgiev** [comment]
The charts have been tested and require d3 4.9.x. We will work on updating them to d3 4.10
