### ISSUE TITLE
A way to change the color for axis and ticks

### ISSUE THREAD

**Issue by medisoft** [swimlane/ngx-charts#540]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request => Please do not submit support request here
```

I'm trying to implement ngx-charts with a dark background, and I was unable to find a way to change the text color for ticks and axis. 

I tried changing with CSS but it is not working.

Is there a way to change that colors?

Thanks

**Comment by CDDelta** [comment]
I changed the text color on graphs by using this css: `.ngx-charts text {
    fill: #fff;
}`

**Comment by marjan-georgiev** [comment]
You should be able to change the axis and label colors using CSS. Make sure the CSS you write to override this is not loaded before the chart's CSS. Or use `!important`

**Comment by adacho-programista** [comment]
in angular dont forget to go deeper in sass using `::ng-deep`
```
::ng-deep .ngx-charts { 
    text{
        fill: #fff!important; 
    }
}
```

**Comment by hidayatarg** [comment]
> in angular dont forget to go deeper in sass using `::ng-deep`
> 
> ```
> ::ng-deep .ngx-charts { 
>     text{
>         fill: #fff!important; 
>     }
> }
> ```

It worked for me thanks

**Comment by Klerith** [comment]
Simplest way 
```
<ngx-charts-bar-horizontal
      [results]="results"
      [scheme]="colorScheme"
      [results]="single"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [legend]="showLegend"
      [showXAxisLabel]="showXAxisLabel"
      [showYAxisLabel]="showYAxisLabel"
      [xAxisLabel]="xAxisLabel"
      [yAxisLabel]="yAxisLabel"
      (select)="onSelect($event)"
      style="fill: grey;">   <----------------------- HERE
    </ngx-charts-bar-horizontal> 
```

**Comment by Ayaz1997** [comment]
This worked for me.. Thank You! :)

**Comment by anton-drant** [comment]
Hi all, is there a way to style the ticks programmatically and not via css?
