### ISSUE TITLE
plunkr examples in the documentation are offline

### ISSUE THREAD

**Issue by DGauggel** [swimlane/ngx-charts#543]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
All of the plunkr examples in the documentation (gitbooks) are offline.

**Comment by samhs-zonefox** [comment]
I'm also having this same problem, and because of the way the documentation is structured it seems the only place to get a reliable "sample" of operational code for each of the chart types.

**Comment by marjan-georgiev** [comment]
Looks like it's an issue with plunkr not showing typescript files:

https://plnkr.co/group?place=msg%2Fplunker%2FQZqmICLdSNE%2FpbXR91AxAQAJ

**Comment by marjan-georgiev** [comment]
I reached out and it has been fixed.
