### ISSUE TITLE
yaxis ticks positioning - bar charts

### ISSUE THREAD

**Issue by Sibiraj-S** [swimlane/ngx-charts#545]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
No tick positioning I guess 

**Expected behavior**
Something like here in this codepen https://codepen.io/subneo101/pen/JrjrGa.

Text inside the bar

![untitled](https://user-images.githubusercontent.com/20282546/30468407-c5787f16-9a08-11e7-9cd2-07e30e1ccdf3.png)

**Comment by marjan-georgiev** [comment]
This can be done as a custom chart. You can find an example on how to build custom charts using our components here: https://github.com/swimlane/ngx-charts/tree/master/demo/combo-chart

I would do this by using the bar-series-horizontal component without any axis, and would add a layer of labels on top of it.
