### ISSUE TITLE
awful documentation

### ISSUE THREAD

**Issue by rojasjandro89** [swimlane/ngx-charts#547]
anyone knows any kind of documentation for this framework? I mean actual documentation, not the demo examples. An awesome framework like this shouldn't have such a poor documentation...

**Comment by marjan-georgiev** [comment]
Do you mean this?

https://swimlane.gitbooks.io/ngx-charts/content/

**Comment by khoavn** [comment]
Yes, I agree with rojasjandro89, we need more examples. Currently I'm stuck with customizing labels, I know I should use **labelFormatting** but I don't know how to do that from template and component files. It will help with examples.

**Comment by amcdnl** [comment]
@rojasjandro89 - Thanks for the feedback. I'm sorry the documentation does not meet your expectations. This is a completely FREE open-source project written by passionate developers. We are developers not authors but open-source software needs all types of contributors, we are ALWAYS open to pull requests in general and if you want to contribute back with better documentation we would gladly accept it.

**Comment by rojasjandro89** [comment]
@marjan-georgiev - that's the poor documentation I was talking about, it's basically a collection of very basic examples. when it says an input property is an object it doesn't say the structure of the object, for example, the scheme, it takes an object but it's impossible to guess the structure of it, for all I know the structure shown in the example is just a specific case...is there more I can do with scheme? can the scheme change the color of the x and y axis? How to style the legend? How does the AxisTickFormatting function work? what kind of parameters it takes and what it should return? Can I use it to change the color of the axis?...and I'm only using line-chart, I'm pretty sure there are a lot of input properties for other chart types as well. 
@amcdnl - After reading my post I can see I sounded a little arrogant and imperative. I was frustrated after hours dissecting the examples provided in the demo section. Again... my apologies, we've developed a tendency to demand features to developers when we should be helping instead. I was just hoping there was a better documentation I didn't know about.

**Comment by rojasjandro89** [comment]
@khoavn -  I was able to change the overall color of the axes (including the label) by overriding the CSS of the text elements (SVG text).
`.ngx-charts text {
  fill: #a8b2c7 !important;
}`
I hope it helps

**Comment by JoshSchoen** [comment]
@rojasjandro89 Wanted to chime in here not pile on. I have been using NGX Charts for a number months now and have contributed to the the code. While documentation for almost all open source project could always be better I highly recommend you spend the some time with the library and learn. The team over there has put a lot of time into this and as consumers of the code we should appreciate their work and help make it better by collaborating and giving back to what they have graciously put out there for free to make our lives easier. I guarantee, if you spend the time to learn why and how they did what they did, it will make you better in the work that you do. Cheers!

**Comment by marjan-georgiev** [comment]
@rojasjandro89 I'm sure there is a better way to ask all of those questions than this. We have a gitter channel where you can ask any question not covered by the documentation: https://gitter.im/swimlane/ngx-charts

**Comment by marjan-georgiev** [comment]
I also hope that you will help us improve the documentation by submitting a pull request after getting the answers you are looking for. We encourage everyone to contribute with documentation and examples.

**Comment by drullo** [comment]
I am a new user of ngx-charts and I agree that the documentation, while helpful, could be better in explaining how to utilize all features.  I've had the same frustrations that @rojasjandro89 and other users have expressed.  I'm grateful to have this charting system in the open source community and it's very useful.  But most people don't want to (and shouldn't have to) dig through a project's source code just to figure out how to customize label color (for example).  If somebody on the development team gets an opportunity, those of us making use of this project would greatly appreciate some additional effort being put into enhancing the documentation.  Thank you to everyone involved!

**Comment by mdramos** [comment]
maybe I'm just whiffing it, but I have not seen any code examples in the docs

**Comment by red2678** [comment]
4 years later...

**Comment by blogcraft** [comment]
Docs are not very helpfull and some stackblits still use ngx-charts 10... I'm getting some issues now that there is no docs about it...
