### ISSUE TITLE
position tooltips horizontally/vertically

### ISSUE THREAD

**Issue by Sibiraj-S** [swimlane/ngx-charts#549]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] - feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Tooltip is automatically positioned vertically on the top or bottom

**Expected behavior**
Allow tooltip to be positioned horizontally. i.e., either on right or left

Something like

`toolTipPlacement/toolTipPosition`

 ```
 <ngx-charts-bar-horizontal [toolTipPlacement]="'horizontal'"> </ngx-charts-bar-horizontal>
```

**What is the motivation/use case for changing the behavior?**
While using custom templates I have added certain items that are hidden by page when positioned vertically but horizontally placing tooltips can avoid at certain case

* **ngx-charts version:** @latest

* **Angular version:** 4.x

* **Browser:** all

**Comment by marjan-georgiev** [comment]
The tooltip directive already has those inputs. They would need to be exposed through the charts though:

https://github.com/swimlane/ngx-charts/blob/master/src/common/tooltip/tooltip.directive.ts#L23

**Comment by Sibiraj-S** [comment]
@marjan-georgiev Any Update on this?

**Comment by qsphinx** [comment]
Hello. I see that this feature request was closed, but I couldn't find in code that it was added. Was this implemented? Or this is not in plan anymore? Thanks.

**Comment by term29** [comment]
I'm interested in this as well.  Wondering why it was closed without comment or resolution.

**Comment by sebastientromp** [comment]
Same here :)
