### ISSUE TITLE
Data provided to tooltip templates is not consistent

### ISSUE THREAD

**Issue by HitomiTenshi** [swimlane/ngx-charts#553]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When using tooltip templates on bar charts, I can use my custom defined `sourceValue` property from my chart data object:

![chrome_2017-09-19_16-48-01](https://user-images.githubusercontent.com/7304212/30598600-73a52ee6-9d5a-11e7-8a1c-f342c7397b44.png)

When using tooltip templates on polar charts, the data for tooltips is different:

![chrome_2017-09-19_16-15-34](https://user-images.githubusercontent.com/7304212/30598415-ea8a0a8c-9d59-11e7-839e-770f8dc1f244.png)

**Expected behavior**

My custom property should be always accessible.

**What is the motivation / use case for changing the behavior?**

I want to be able to use my custom properties in tooltip templates.

* **ngx-charts version:** 6.0.2 (current version from master @ 9/19/2017)

* **Angular version:** 4.4.1

* **Browser:** all

* **Language:** all

**Comment by NaughtyCodes** [comment]
any update on this, I also trying to provide custom data in tooltips

**Comment by HitomiTenshi** [comment]
I made a [PR](#555) for this. I have no idea if it makes it into ngx-charts though. I'm using the PR in my projects and it works and has been working for a long time now.

**Comment by artipixel** [comment]
I was breaking my head until I've found this piece of code:

https://github.com/swimlane/ngx-charts/blob/f344a1a2c12bc9e019c7fa8323e7cd3774c9bd1e/src/common/base-chart.component.ts#L180-L182

You can pass additional parameters using "extra" key on your item.

**Comment by HitomiTenshi** [comment]
This should be documented properly. If using the "extra" key on items is the way, why do bar charts keep their original item data and other chart types don't?

I also don't get why there is so much cloning involved. Why not just keep references intact?
