### ISSUE TITLE
TreeMap show label, even when data is small?

### ISSUE THREAD

**Issue by SamuelMarks** [swimlane/ngx-charts#557]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
<img width="684" alt="screen shot 2017-09-22 at 3 30 49 pm" src="https://user-images.githubusercontent.com/807580/30730521-10665f5a-9fab-11e7-94a6-9e103da838d1.png">

**Expected behavior**
Text should appear somewhere? - Maybe a legend, tooltip or similar.

**Reproduction of the problem**
https://plnkr.co/edit/bWO0TU8RGNl2BuBcaO3N?p=preview

**What is the motivation / use case for changing the behavior?**
Still useful to know what's insignificant

**Please tell us about your environment:**
All

* **ngx-charts version:** 6.0.2

* **Angular version:** 2.4.1

* **Browser:** all

* **Language:** all

**Comment by marjan-georgiev** [comment]
This is by design. There is still tooltip for the small areas, so you can hover over them to see their labels and values.

![image](https://user-images.githubusercontent.com/8687/30739107-9238230c-9f8c-11e7-95f2-2c957c5bc205.png)

**Comment by hbthanki** [comment]
Can we override this in any way?
