### ISSUE TITLE
How to use labelFormatting of PieChart

### ISSUE THREAD

**Issue by khoavn** [swimlane/ngx-charts#558]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```
I'm trying to show % numbers as labels of **pie chart**, my solution is including number into key (e.g: REALKEY (4)) and pass "formatLable" function to **labelFormatting**, below is formatLable function:

`formatLable(lable) {
        if(this.total == 0)
            return lable;

Extract number from lable as count
        
        let result = (count / this.total) * 100;

        return result.toFixed(2);
    }`

The problem is this function doesn't see **this.total** (total in component.ts), so I try to pass this total number into this function as param, but I don't know how to do that.

**Comment by marjan-georgiev** [comment]
try passing the function like this:
`[labelFormatting]="labelFormatting.bind(this)"`

Then you will have access to the local state of the component and `this.total`.
