### ISSUE TITLE
Advanced Pie Chart show / hide legend

### ISSUE THREAD

**Issue by dbartumeu** [swimlane/ngx-charts#564]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```
Is it possible to have a property to enable / disable  the legend on an advanced Pie Chart?

Thanks.

**Comment by marjan-georgiev** [comment]
But then it's just a donut chart without labels.

**Comment by lasya-sivalenka** [comment]
What are the ways to disable the legend, I don't think we have any option to do that. 
We have a requirement to display only the chart without legend or at least smaller legend which we could not establish, the legend is occupying most of the width and the chart is coming up smaller comparatively.

**Comment by marjan-georgiev** [comment]
@lasya-sivalenka see my reply above

You can use the regular pie chart and pass the following options:
```
[legend]="false"
[doughnut]="true"
[labels]="false"
```

**Comment by koddist** [comment]
I think `[noBarWhenZero]` could be very useful for `<ngx-charts-advanced-pie-chart>`

[Screenshot](https://i.ibb.co/55Z9tYv/Screenshot-2019-11-14-at-10-56-08.png)
