### ISSUE TITLE
New build to support Angular 5.0.0-rc.0 with replacing ngOutletContext

### ISSUE THREAD

**Issue by Tempus35** [swimlane/ngx-charts#566]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request => Please do not submit support request here
```

**Current behavior**

Angular 5.0.0-rc.0 requires replacing ngOutletContext, this seems to have been done in the code but there has been no release.

**Expected behavior**

A release to support the changes in the new Angular 5

**Reproduction of the problem**

Install Angular 5.0.0-rc.0 with the current release

**What is the motivation / use case for changing the behavior?**

Using Angular 5.0.0-rc.0

* **ngx-charts version:** x.x.x
6.0.2

* **Angular version:** 2.x.x
5.0.0.rc.0

**Comment by Tempus35** [comment]
Master code base works, using for now, since release sounds like it will be soon. I will be closing this.

**Comment by sandangel** [comment]
sorry but I tried yarn add https://github.com/swimlane/ngx-charts.git and yarn add https://github.com/swimlane/ngx-charts.git#master but it not worked. how to install from master code base?

**Comment by Tempus35** [comment]
@sandangel There is not a way to add from yarn that I know. I cloned the git, built it and moved the files over to the node_modules of my project manually.

**Comment by sandangel** [comment]
thanks @Tempus35 . I cloned the git, rename the src folder to ngx-charts and move it to my src/app. I just wonder is using the src instead of built increase my bundle size? The vendor bundle is 3MB now. Wow!

**Comment by Tempus35** [comment]
@sandangel What I did was clone the git, ran yarn, ran yarn run package, deleted the dist, demo, src, and node_modules in ngx_charts. Seemed to work fine.

**Comment by anvial** [comment]
It seems that     "@swimlane/ngx-charts": "6.1.0",
also have the same problem
```
Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <ng-template
            [ngTemplateOutlet]="template"
            [ERROR ->][ngOutletContext]="{ model: context }">
          </ng-template>
        </span>
"): ng:///TooltipModule/TooltipContentComponent.html@11:12
Property binding ngOutletContext not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): ng:///TooltipModule/TooltipContentComponent.html@9:10
```

Is the only solution is to build lib in node_modules manually?
