### ISSUE TITLE
How to put data numbers on the bar graph?

### ISSUE THREAD

**Issue by anavgale** [swimlane/ngx-charts#569]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I need a way to put data figures and series total on the stacked bar graph like this image.

![image](https://user-images.githubusercontent.com/1831491/31225072-fa99ebae-a9ed-11e7-8027-4b5706dac222.png)

**What is the motivation / use case for changing the behavior?**
Need more control on how graph is displayed. Tooltips are good, when single user is accessing the graph, but when graph is being presented on the screen on web page, its not possible to mouse-over and see the tooltip.

**Comment by marjan-georgiev** [comment]
This is supported by the `showDataLabel` input on bar charts.
