### ISSUE TITLE
Translation of displayed text

### ISSUE THREAD

**Issue by Nightapes** [swimlane/ngx-charts#570]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

In single series and multi series the `name` is displayed. When changing the language the data set needs to be modified and the id of a item is overwritten.

```
[
 name: 'English',
 series: [
                    { name: 'English item', value: 0 },
                    { name: 'English item 2', value: 2 }
            ]
]
```

```
[
 name: 'Deutsch',
 series: [
                    { name: 'Deutsch 1', value: 0 },
                    { name: 'Deutsch 2', value: 2 }
            ]
]
```

When using selected, the name changed and it's hard to get from the translation to the item id.

**Expected behavior**

Single series and multi series have at list a static id.

```
[
 name: 'English',
 id: 'group-0'
 series: [
                    { name: 'English item', value: 0, id: 'item-0 },
                    { name: 'English item 2', value: 2, id: 'item-1 }
            ]
]
```

```
{
 name: 'Deutsch',
 id: 'group-0'
 series: [
                    { name: 'Deutsch 1', value: 0, id: 'item-0 },
                    { name: 'Deutsch 2', value: 2 }, id: 'item-1 }
            ]
}
```

In single series and multi series the `name` is displayed, but also the id is returned. 

**What is the motivation / use case for changing the behavior?**

Use the library  with translations

**Please tell us about your environment:**

* **ngx-charts version:** 6.0.2

* **Angular version:** 4.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by cocoviper** [comment]
I would suggest to not go that route for translations. I've made on my project a translation for my graphs and the name is not updated once the graph is loaded. I'm forced to reload the graph for the names to change.

My suggestion would be to accept an observable for the name which would make it flexible and easier to implement with libraries such as ngx-translate.

``` javascript
[
 name: translateService.stream('language').asObservable(),
 series: [
                    { name: translateService.stream('item1').asObservable(), value: 0 },
                    { name: translateService.stream('item2').asObservable(), value: 2 }
            ]
]
```

This way there would be no needed code to handle all the ids

**Comment by Springrbua** [comment]
Any news on this?
Using the name as ID and for the display does not seem right to me.

**Comment by marjan-georgiev** [comment]
This will be enabled by https://github.com/swimlane/ngx-charts/issues/506

**Comment by MichaelChappell0117** [comment]
Can someone please explain to me how extra can be used for dynamic translations? I have the labels being translating via pipe directive; but, for instance, the pie chart names can be translated once but don't change whenever I switch languages
