### ISSUE TITLE
tickFormatting is not done using Intl

### ISSUE THREAD

**Issue by PolarbearDK** [swimlane/ngx-charts#571]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Some numbers (and dates) are formatted using Intl but others like ticks are not.

**Expected behavior**
All numbers and dates be formatted using Intl.

**Reproduction of the problem**
Example from https://swimlane.github.io/ngx-charts/#/ngx-charts/bar-vertical with Danish locale.
![ngx-chart-intl](https://user-images.githubusercontent.com/5196920/31234350-f935451e-a9ee-11e7-988a-30d28538f728.png)
Notice that the popup is formatted correctly (using dot as thousand separator which is correct ), but the tics are not (using "comma" as thousand separator). 

**What is the motivation / use case for changing the behavior?**
Correct formatting of numbers/dates using browsers current locale

**Please tell us about your environment:**
Windows 10, VS Code, Yarn, Chrome

* **ngx-charts version:** 6.0.1

* **Angular version:** 4.3.4

* **Browser:** [all ]

* **Language:** [all ]

**Comment by marjan-georgiev** [comment]
This should be consistent in the latest version. For custom formatting, please look at the `yAxisTickFormatting` tick formatting input and the tooltip templates feature.

**Comment by ChrTall** [comment]
@marjan-georgiev 
For me the issue is still present in the current version. Could you provide an example on the yAxisTickFormatting function for this problem?
