### ISSUE TITLE
Bug - line chart is displaying multiple tooltips when data is fetched from api

### ISSUE THREAD

**Issue by nukec** [swimlane/ngx-charts#576]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I load data from api into charts, tooltips do not disappear

![dra](https://user-images.githubusercontent.com/3589518/31313300-bd04ad70-abd6-11e7-9e71-3d7744d689f4.PNG)

**Expected behavior**
Tooltips should disappear.

**Reproduction of the problem**
Get some data set from api and assign as result to ngx-charts line chart

I am having a char initialised. Works good so configuration is properly set up and dependency installed. I followed example for line-chart and used data provided here: https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html

Works correctly.
Problem is when I load a data from API feed, my graph acts strange, tooltip is not disappearing and whatever route i click it loads in same window, aka something is broken:
[![https://user-images.githubusercontent.com/3589518/31313300-bd04ad70-abd6-11e7-9e71-3d7744d689f4.PNG][1]][1]

Now this is the data from feed:

    {
        "currentWeight": 80,
        "bodyMassIndex": 0,
        "exercisesProgress": [
            {
                "name": "Bench Press",
                "series": [
                    {
                        "name": "10/10/2017",
                        "value": 66
                    },
                    {
                        "name": "12/10/2017",
                        "value": 78
                    },
                    {
                        "name": "15/10/2017",
                        "value": 61
                    },
                    {
                        "name": "18/10/2017",
                        "value": 79
                    },
                    {
                        "name": "19/10/2017",
                        "value": 74
                    },
                    {
                        "name": "22/10/2017",
                        "value": 68
                    },
                    {
                        "name": "23/10/2017",
                        "value": 75
                    },
                    {
                        "name": "17/11/2017",
                        "value": 76
                    },
                    {
                        "name": "23/11/2017",
                        "value": 62
                    },
                    {
                        "name": "23/12/2017",
                        "value": 71
                    },
                    {
                        "name": "23/01/2018",
                        "value": 68
                    },
                    {
                        "name": "23/02/2018",
                        "value": 70
                    }
                ]
            }
        ]
    }

I then initialise data like this in graph:

    <ngx-charts-line-chart
          [view]="view"
          [scheme]="colorScheme"
          [results]="dashboardModel.exerciseProgress"
          [gradient]="gradient"
          [xAxis]="showXAxis"
          [yAxis]="showYAxis"
          [legend]="showLegend"
          [showXAxisLabel]="showXAxisLabel"
          [showYAxisLabel]="showYAxisLabel"
          [xAxisLabel]="xAxisLabel"
          [yAxisLabel]="yAxisLabel"
          [autoScale]="autoScale"
          (select)="onSelect($event)">
    </ngx-charts-line-chart>

Thing doesn't work.
When I put data directly into ts.file:

    export var multi = [
      {
          "name": "Bench Press",
          "series": [
              {
                  "name": "10/10/2017",
                  "value": 66
              },
              {
                  "name": "12/10/2017",
                  "value": 78
              },
              {
                  "name": "15/10/2017",
                  "value": 61
              },
              {
                  "name": "18/10/2017",
                  "value": 79
              },
              {
                  "name": "19/10/2017",
                  "value": 74
              },
              {
                  "name": "22/10/2017",
                  "value": 68
              },
              {
                  "name": "23/10/2017",
                  "value": 75
              },
              {
                  "name": "17/11/2017",
                  "value": 76
              },
              {
                  "name": "23/11/2017",
                  "value": 62
              },
              {
                  "name": "23/12/2017",
                  "value": 71
              },
              {
                  "name": "23/01/2018",
                  "value": 68
              },
              {
                  "name": "23/02/2018",
                  "value": 70
              }
          ]
      }
    ];

and then initialise it like:

    <ngx-charts-line-chart
          [view]="view"
          [scheme]="colorScheme"
          [results]="multi"
          [gradient]="gradient"
          [xAxis]="showXAxis"
          [yAxis]="showYAxis"
          [legend]="showLegend"
          [showXAxisLabel]="showXAxisLabel"
          [showYAxisLabel]="showYAxisLabel"
          [xAxisLabel]="xAxisLabel"
          [yAxisLabel]="yAxisLabel"
          [autoScale]="autoScale"
          (select)="onSelect($event)">
    </ngx-charts-line-chart>

Then it works.
I am not sure what is different:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/lrKFI.png
  [2]: https://i.stack.imgur.com/FwjcL.png

I am using angular 4.4.4 and latest ngx-charts versions.

**Comment by maxplayer3** [comment]
@nukec , I had same issue, fixed that when just wrapped "ngx-charts-line-chart" into <div> tag with `*ngIf="resultsFromApi"`. So basically show the chart when data is ready.

**Comment by marjan-georgiev** [comment]
Closing this as there hasn't been any activity in a while. Please let me know if it's still an issue.
