### ISSUE TITLE
can you please

### ISSUE THREAD

**Issue by itcozum** [swimlane/ngx-charts#585]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
Hi,

can you please include the "HEAT MAP  - CALENDAR"  sample as in your site to this component demo samples. I'm really curious how it was possibly done..

Thanks in advance.

Best Regards
Nelly

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
The code for the calendar is already in the demo page:
https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.html#L485

And here's how the data is generated:
https://github.com/swimlane/ngx-charts/blob/master/demo/app.component.ts#L422
