### ISSUE TITLE
[QUESTION] What I need release for version 2.4.5 Angular ?

### ISSUE THREAD

**Issue by ALPNP** [swimlane/ngx-charts#589]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ ] feature request
[x] support request
```

* **Angular version:** 2.4.5

* **Language:** [TypeScript 2.3.3 | ES6/7 | ES5]

What I need release for version 2.4.5 Angular ?

**Comment by marjan-georgiev** [comment]
Version 4 should be compatible with angular 2.
