### ISSUE TITLE
Base Chart component width only updating on window resize

### ISSUE THREAD

**Issue by JoshSchoen** [swimlane/ngx-charts#592]
**I'm submitting a ...**  (check one with "x")
```
[] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Base Chart component width only updating on window resize.

**Expected behavior**
Expect the base chart width to update when it's parent container width changes not just on window resize. I played with this a bit and one way I got it working was using an Observable in DoCheck but there is certainly performance considerations.

`ngDoCheck() {
    this.dimsSubject.next(
      {
        width: this.chartElement.nativeElement.offsetWidth,
        height: this.chartElement.nativeElement.offsetWidth
      });
    this.dimsSubject.debounceTime(200).subscribe(d => {
      this.dims = d;
      this.update();
    })
  }`

**Reproduction of the problem**
![ngx-width-issue](https://user-images.githubusercontent.com/8234649/31585516-9ac08c22-b188-11e7-9234-08429dea3a67.gif)
You can see it happen for yourself here. https://teradata.github.io/covalent/#/components/ngx-charts.

**What is the motivation / use case for changing the behavior?**
Ensure the charts are responsive when adjacent UI elements widths change.

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
5.3.1 + but has been an ongoing issue.

* **Angular version:** 2.x.x
4.4.3

* **Browser:** Chrome, Firefox, Safari, mobile Safari

* **Language:** all

**Comment by sandangel** [comment]
chart component  does not know that parent container is resized, you should have an event when parent container is resized, then add an ngIf on chart component for showing chart, e.g public show: boolean. When event is fired, show = false, setTimeout 300ms, show = true. Optionally in 300ms show = false you could add an loading component.

**Comment by JoshSchoen** [comment]
@sandangel thanks! This got me on the right track : ). I actually took it one step further and created a directive and a shared service that can be used in the component and directive to share state. I opted to use an Observable with debounceTime rather than a setTimeout as it made it a little more reusable and manageable. thanks again, we can close this issue now.

**Comment by gpit2286** [comment]
@JoshSchoen Can you share your code? I'm running into this same problem with fxFlex.
