### ISSUE TITLE
Interactive ngx-charts-tree-map with more than one top level element

### ISSUE THREAD

**Issue by raed667** [swimlane/ngx-charts#599]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

The interactive ngx-charts-tree-map "according to the demo" can only support one top level element.

**Expected behavior**

Have more than one element on the "Top" view.

**Reproduction of the problem**
Check demo 

**What is the motivation / use case for changing the behavior?**
More complete functionality.

**Please tell us about your environment:**
Windows 10

* **ngx-charts version:** x.x.x
6.1.0 

* **Angular version:** 2.x.x
4.2.4

* **Browser:** 
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

**Comment by sandangel** [comment]
I guess you can use Custom chart in the documentation to draw what ever you like
