### ISSUE TITLE
X axis and Y axis label not showing

### ISSUE THREAD

**Issue by nukec** [swimlane/ngx-charts#600]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
![weight](https://user-images.githubusercontent.com/3589518/31679920-97ff4bca-b36a-11e7-9e32-c15bea0e5edb.PNG)

**Expected behavior**
It should show x axis label and y axis label.

**Reproduction of the problem**
Use values inside of template instead of component for showXAxisLabel and showYAxisLabel.
```
      <ngx-charts-line-chart [scheme]="{domain: ['#5AA454', '#A10A28', '#C7B42C', '#AAAAAA']}" [results]="filterableData" [gradient]="true"
            [xAxis]="true" [yAxis]="true" [legend]="true" [showXAxisLabel]="true" [showYAxisLabel]="true" [xAxisLabel]="Date" [yAxisLabel]="Weight"
            [autoScale]="true" (select)="onSelect($event)">
      </ngx-charts-line-chart>
```

* **ngx-charts version:** latest

* **Angular version:** 4.4.4

**Comment by marjan-georgiev** [comment]
You are passing variables instead of strings.

Either do this:
`[xAxisLabel]="'Date'" [yAxisLabel]="'Weight'"`

or this:
`xAxisLabel="Date" yAxisLabel="Weight"`

**Comment by krishragu12395** [comment]
Still the lable is not visible. I have passed the values as an object. That carries the following data(animations:true
autoScale:false
gradient:false
legend:true
results: [LineChartDetails, LineChartDetails, LineChartDetails]
scheme:{domain: Array(9)}
showXAxisLable:trueshowYAxisLable:true
view: [600, 400]
xAxis:true
xAxisLable:"xAxis"
yAxis:true
yAxisLable:"yAxis")

But still the xAxis and yAxis lables are not visible in the UI.
