### ISSUE TITLE
add min/max for heatmap

### ISSUE THREAD

**Issue by zpydee** [swimlane/ngx-charts#602]
i am passing a series to this chart that needs to be heatmapped between 0 and 100% and be allocated colors accordingly. because the heatmap does not have a min or max input, it uses the min and max values passed in as series data. I believe heatmap hould work much like to gauge where the min and max values can optionally be specified.

**Comment by marjan-georgiev** [comment]
That's a valid request. Added to backlog and accepting PRs.

**Comment by aislingvasey** [comment]
+1
Is there any way to mimic or force the current version of heatmap to think the data is between 0 and 100% if the max value is less than 100%? 
@swimlane/ngx-charts: 6.1.0

Thanks very much

**Comment by abdullahsaleem93** [comment]
+1 for this... would be nice to have it in the next release

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev  I have added a PR with minimal changes

**Comment by abdullahsaleem93** [comment]
I want to merge it in 7x...is it possible?

**Comment by marjan-georgiev** [comment]
Merged the PR. This will be in the next release. Will see if can be cherry-picked into 7.x easily.

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev I'm more than happy to send a PR for 7.0.1 essentially to create a new tag i.e 7.0.2

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev I already have it for 7.0.1 tag here: https://github.com/abdullahsaleem93/ngx-charts/tree/heapmap-max-min-fix-7.0.1

**Comment by marjan-georgiev** [comment]
@abdullahsaleem93 I created a `7.x` branch. Please PR it to that branch. I will release it in 7.5.0

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev is it possible to have it as 7.0.2
nothing seems to work above that becuase of https://github.com/swimlane/ngx-charts/issues/834

**Comment by abdullahsaleem93** [comment]
I checkout the 7.0.1 tag and made changes to it so it would be nice to have a 7.0.2 tag and have it publish to npm

**Comment by marjan-georgiev** [comment]
#834 seems to be about 8.x not being compatible with angular 5, which it isn't. 7.4.0 should still be compatible to angular 5.

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev I tested the 7.4 branch but it didn't work. let me check again

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev nope the problem https://github.com/swimlane/ngx-charts/issues/834 exists in 7.4
![Uploading image.png…](issue) from what I have researched the problem doen't exist in 7.3 but I din't verify that so would it be possible to have a 7.0.2?

**Comment by marjan-georgiev** [comment]
It feels really weird that it would work in 7.3 and not 7.4.
But Ok, I created a 7.0.x branch. Submit the PR to that one and I'll release it in 7.0.2.

**Comment by marjan-georgiev** [comment]
Thank you for the contribution! Will cut the two releases today.

**Comment by abdullahsaleem93** [comment]
@marjan-georgiev there seems to be unused import hat I missed in https://github.com/swimlane/ngx-charts/pull/877 so i have removed it and sent a PR

**Comment by marjan-georgiev** [comment]
@abdullahsaleem93 published 7.0.2
