### ISSUE TITLE
xScaleMax not working on horizontal bar

### ISSUE THREAD

**Issue by kylawamg** [swimlane/ngx-charts#611]
Hi guys, 

Im trying to set the xScaleMax property to my horizontal bar chart, but im getting the following error message: 

_```
Error: Template parse errors:
Can't bind to 'xScaleMax' since it isn't a known property of 'ngx-charts-bar-horizontal'.
1. If 'ngx-charts-bar-horizontal' is an Angular component and it has 'xScaleMax' input, then verify that it is part of this module.
2. If 'ngx-charts-bar-horizontal' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        [xAxisLabel]="xAxisLabel"
        [yAxisLabel]="yAxisLabel"
        [ERROR ->][xScaleMax]="99">
      </ngx-charts-bar-horizontal>
  </div>
"): ng:///InteractiveMapModule/ControlIndicatorComponent.html@14:8
```_

When Im try the same on the plunkr example, no problems are find and all work at expected. I only have issues with this property, could u help me?

**Comment by marjan-georgiev** [comment]
What version of ngx-charts are you using? This feature was added in 6.1.0.

**Comment by kylawamg** [comment]
Thanks marjan-georgiev! The problem was resolved updating the version of the package. In addition to this, can I put a vertical bar chart with only top border? that is the background or fill with opacity to 0 and only top-border (which is the corresponding to value) colored...

Thanks in advance!

**Comment by Hypercubed** [comment]
@kylawamg You can set the opacity using CSS, but I can't think of a way to only show a top border of a path (ngx-chart's bars are paths not rects).
