### ISSUE TITLE
timeline not showing when enabled

### ISSUE THREAD

**Issue by Wesselfick** [swimlane/ngx-charts#614]
Hi 

I looked at the documentation and it states that to use the timeline that you need to have the x data as date. I replicated the line chart sample into a plunker and enabled timeline option with this data but i see the chart changing in size but not showing any timeline, 

[Plunker](https://plnkr.co/edit/0yRSbsCninEjFtRZrJT9?p=preview)

Regards

**Comment by Wesselfick** [comment]
i found my issue, i was setting the date as string

**Comment by shopsoy** [comment]
Hi,
Im having the same problem that I didn't got the reason why?
Can you please show in your Plunker link what you have performed?

Thanks in advance

**Comment by Wesselfick** [comment]
I was casting my date values as strings, make sure you set it to a valid DATE value
