### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by pantonis** [swimlane/ngx-charts#616]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Trying to build using angular-cli and webpack and getting

```
webpack-concat-plugin\index.js:54
                        throw err;
                        ^

Error: ENOENT: no such file or directory, open 'C:\SourceControl\src\MyProject\node_modules\d3\d3.js'
    at Error (native)
```

**Expected behavior**
Successful build

**What is the motivation / use case for changing the behavior?**
Bug

**Please tell us about your environment:**
Window 10, VS Code, npm, angular-cli

* **ngx-charts version:** x.x.x
6.1.0, d3: 4.11.0

* **Angular version:** 2.x.x
4.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by marjan-georgiev** [comment]
You need to add d3 as a dependency to your project.

**Comment by pantonis** [comment]
@marjan-gorgiev Added it in packages config and installed it

**Comment by marjan-georgiev** [comment]
Can you check if there is a file called `d3.js` in `C:\SourceControl\src\MyProject\node_modules\d3\`?

**Comment by pantonis** [comment]
No there isnt
Here is the content of this folder

![image](https://user-images.githubusercontent.com/3295086/32103734-5d60212a-bb2a-11e7-972b-597527f4f132.png)

**Comment by marjan-georgiev** [comment]
Can you try installing d3 4.9 instead of 4.11?

**Comment by pantonis** [comment]
Same problem.

d3.js is under ```node_modules\d3\build```

**Comment by marjan-georgiev** [comment]
@pantonis did you figure this out? I wasn't able to reproduce.

**Comment by pantonis** [comment]
No I manually copied paste d3.js into ```node_modules\d3\d3.js```
