### ISSUE TITLE
Pie chart not updating

### ISSUE THREAD

**Issue by pantonis** [swimlane/ngx-charts#618]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When I initialize data with some items when the component loads I see the data. After I update the data from a websocket connection the pie chart is not shown but only the legend. I have even try to set ```this.data = [...this.data]``` but still nothing

**Expected behavior**
It should render the new data

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
BUG

**Please tell us about your environment:**

Win 10, VS Code, npm, angular-cli 

* **ngx-charts version:** x.x.x
  "@swimlane/ngx-charts": "6.1.0",
        "d3": "^4.11.0"

* **Angular version:** 2.x.x
4.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by pantonis** [comment]
Think I found what was causing it. Was passing negative numbers as values. Would be good to have Math.abs inside the library to handle these.

**Comment by jkon** [comment]
So, @pantonis is right that we should be able to pass negative values to the pie chart too and they should be surrounded by a Math.abs(). I would add an extra bit to it that the label that is added to the legend and such reflect the negative. I am working on a FinTech app and the first chart I worked on with this package was a pie chart for displaying asset allocation of a portfolio (proportions of Cash, Bonds, Stocks and Real Assets). The reason I need the negative number to work is that bonds (and technically stocks or even cash) can be a negative number. In most people's cases, a mortgage or other loan would bring the bonds value down into the negative and that needs to be reflected in the pie chart, but even if I do the absolute value myself, I don't see a way to change the value label to be negative. If there is a way, please tell me . Thanks

**Comment by marjan-georgiev** [comment]
Does it really make sense to use the pie chart for negative values though? I am worried that doing Math.abs would be a misrepresentation of the data.

I'm not against it, just trying to understand why a pie chart would be used to represent that kind of data, over a bar chart, which does support negative values.

**Comment by pantonis** [comment]
I work for a FinTech as well. As jkon correctly mentioned some times you need to show asset allocation charts. e.g exposure of your assets can be Positive (long) or negative (Short).

**Comment by jkon** [comment]
Believe me, I have had the argument about it with colleagues enough times. It doesn’t make sense to me either that a pie chart would show a negative, but that is how it is displayed in most financial software. The other thing that might be helpful would be if we could pass in a percent value to the chart, but also formatted labels for the values, not just just the series label. That way you could represent the pie piece in a percent, but put in a dollar or percent value for the label. I know it sound ridiculous, but it would be helpful for anyone who works in FinTech
