### ISSUE TITLE
Labels not shown in pie chart

### ISSUE THREAD

**Issue by pantonis** [swimlane/ngx-charts#619]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
When having ten values but some of them are really smaller than the higher ones labels are not being drawn. Chartjs functionality here is the best. Is this supported in ngx-charts where you click on an item on the legend and only selected are drawn?
https://plnkr.co/edit/6VDMMAOtLQQgfZJtEx8Z?p=preview

**Expected behavior**
Labels should be shown or chart should be redrawed

**Reproduction of the problem**
https://plnkr.co/edit/sP4wDsbeBriSRpz2rynI?p=preview

**What is the motivation / use case for changing the behavior?**
BUG

**Please tell us about your environment:**

WIndows 10, Vs Code. npm, angular-cli

* **ngx-charts version:** x.x.x
6.1.0

* **Angular version:** 2.x.x
4.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by marjan-georgiev** [comment]
Yes, this is by design. Items below a certain threshold do not have labels in order to prevent label overlap.

We do not currently have filtering items based on legend clicking built into the charts. You could probably do this outside of the chart by building a custom legend and modifying the data input.
