### ISSUE TITLE
The style of bar chart can not be changed

### ISSUE THREAD

**Issue by doganugur** [swimlane/ngx-charts#621]
I am trying to change the style of bar chart, but the changes I have done on css file are not updating the bar chart.I couln't find a way to update the font of x-axis values

**Comment by marjan-georgiev** [comment]
You should be able to update the font on the axis via CSS. For further help, please use our gitter chat. Let's keep the github issues only for bugs and feature requests.

https://gitter.im/swimlane/ngx-charts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by Nabeel123** [comment]
You can try this example is for "**ngx-charts-pie-grid**"         
`$('.ng-star-inserted:eq(8)').attr("y", "95");
$('.ng-star-inserted:eq(8)').css({'font-weight': '600', 'font-size': '12.5pt' });`
