### ISSUE TITLE
IE11 activate and deactivate event duplication

### ISSUE THREAD

**Issue by ramuda** [swimlane/ngx-charts#625]
Valid for all chart types 
* **ngx-charts version** : 6.1.0

* **Angular version:** 4.x

* **Browser:** [IE11|Edge]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
In my opinion the best way to fix will be changing names of events to sth like:

chartActivate
chartDeactivate

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported
