### ISSUE TITLE
Can I create half Doughnut chart from pie chart.

### ISSUE THREAD

**Issue by yogesh-aloha** [swimlane/ngx-charts#630]
* **ngx-charts version:** 6.1.0

* **Angular version:** 4.2.0

I wanted to create half doughnut chart which have some value in the half circle.
I am also wanted to put total value in the doughnut chart so is that possible?

**Comment by marjan-georgiev** [comment]
Not by using the pie-chart component, but you can build a custom one that does that.
https://swimlane.gitbooks.io/ngx-charts/content/intro/custom-charts.html

**Comment by balajibadly** [comment]
this link is broken, can you share me the working link ?
