### ISSUE TITLE
yScaleMin = 0 no effect

### ISSUE THREAD

**Issue by akalitenya** [swimlane/ngx-charts#632]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

yScaleMin = 0 does not affect the chart (xScaleMin not tested)

**Expected behavior**

yScaleMin = 0 should affect chart

**Reproduction of the problem**

-
**What is the motivation / use case for changing the behavior?**

-
**Please tell us about your environment:**

-
* **ngx-charts version:** x.x.x

6.1.0

* **Angular version:** 2.x.x

4.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Version 61.0.3163.100 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
-

**Comment by marjan-georgiev** [comment]
Can you provide a demo please? A stackblitz or a plunkr example would do.

**Comment by akalitenya** [comment]
in this demo https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart
chart reacts if we set 
AutoScale = true
minimum Y-Scale = 1000

but if we set 
AutoScale = true
minimum Y-Scale = 0
chart is not reacts

**Comment by marjan-georgiev** [comment]
AutoScale needs to be set to false f you want to override the minimum Y scale.

**Comment by marjan-georgiev** [comment]
There seems to be a bug where yScaleMin is set to 0, because then it will evaluate to false on this line: https://github.com/swimlane/ngx-charts/blob/master/src/line-chart/line-chart.component.ts#L356

This is why you are seeing this behavior.

But yScaleMin = 0 is equal to AutoScale = false.

**Comment by akalitenya** [comment]
I agree that you found line causing bug. 
If yScaleMin = 0 (defined) then chart should behave same way as AutoScale = false.
