### ISSUE TITLE
Add id to data

### ISSUE THREAD

**Issue by Jacquers** [swimlane/ngx-charts#642]
**I'm submitting a ...**

[x ] feature request

**Current behavior**

Please add the ability to add an id to data and output it as part of the onSelect event. It would be very useful for filtering data based on the charts.

export let single = [
    {
        'id': 1,
        'name': 'Germany',
        'value': 8940000
    },
    {
        'id': 2,
        'name': 'USA',
        'value': 5000000
    },
    {
        'id': 2,
        'name': 'France',
        'value': 7200000
    }
];

**Comment by Nightapes** [comment]
#570

**Comment by marjan-georgiev** [comment]
Closing in favor of #570.

**Comment by sebastiangug** [comment]
@marjan-georgiev 
This is all fine and dandy but it's been over 2 years for a simple feature that takes 100 lines of code... 

Then there's pull requests with the modifications made that are just sitting there for months with no conflicts.
