### ISSUE TITLE
timline for ngx-charts-line-chart 

### ISSUE THREAD

**Issue by neo-xy** [swimlane/ngx-charts#647]
have been banging my head agains the walll for the last few houres with that one: can someone pls tell me how to implement  "timline" -bar seen in the exemple here [https://swimlane.github.io/ngx-charts/#/ngx-charts/line-chart](url) after one chose "timeline" under "options/GDP.." or provide me with some documentation for it  because I can not find a thing about it:s .preciate all the help(y)

**Comment by mikecabana** [comment]
I see you closed this issue which I assume means you've figured this out. 

For those looking through the issues for answers, to enable a proper timeline for the line chart you have to:

a. set the timeline option to true
b. provide a Date object as a 'name' value for each series dataset i.e 
    'series' : [ {'name' Date obj, 'value': 100} ]

This is defined in the documentation as 'Only available if x scale is date'.

**Comment by neo-xy** [comment]
@mikecabana yeap - I missed the part that it just works for "Date"-object - good that You put an explanation everyone in the future (y)

**Comment by marjan-georgiev** [comment]
Please feel free to submit PRs for the documentation. If there are features that you feel are not explained well in there, please submit a PR. We would be happy to accept them.

**Comment by mikecabana** [comment]
#662
