### ISSUE TITLE
Tooltip template as ContentChild on BaseChart

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ngx-charts#65]
I'd like to be able to customize the tooltip for any chart that extends BaseChart.

I'll make a PR if you like the idea.

Something like this:

```
<some-chart>
  <template #tooltipTemplate let-model>
    {{model.customValue}} and {{some.outside.value}}
  </template>
</some-chart>
```

BaseChart would register `@ContentChild('tooltipTemplate') tooltipTemplate: TemplateRef`

And each chart would be responsible for plugging `this.tooltipTemplate` into the `swui-template` directive.

**Note:** I haven't thought of a good way to override the area-tooltips.  I won't touch them in this PR.

Let me know what you think.

**Comment by amcdnl** [comment]
The tooltips are actually based on our other project: https://github.com/swimlane/swui/tree/master/src/components/tooltip

What if we let you pass a `TemplateRef` as an option for the tooltips?

**Comment by isaacplmann** [comment]
Something like this?

    <template #tooltipTemplate let-model>
      {{model.customValue}} and {{some.outside.value}}
    </template>
    <some-chart [tooltipTemplate]="tooltipTemplate"></some-chart>

That's fine with me.  I prefer the `ContentChild` style, but this is functionally equivalent.

Should I start on the PR?

**Comment by amcdnl** [comment]
What about both? I can see scenarios where I might want to have a global ref I pass in.

**Comment by isaacplmann** [comment]
What should happen if both are defined?  Which one takes precedence?  We could arbitrarily pick one or throw an error.

**Comment by isaacplmann** [comment]
If both are defined, what if we ignore the `ContentChild`, since it comes later in the life cycle but also send a `console.warn` to the developer.

**Comment by JoshSchoen** [comment]
Created a PR for more customizable tooltips for line, bar and area charts. https://github.com/swimlane/ngx-charts/pull/369

**Comment by marjan-georgiev** [comment]
This was implemented in https://github.com/swimlane/ngx-charts/pull/399.
