### ISSUE TITLE
Graph doesn't update after timeline selection is cleared

### ISSUE THREAD

**Issue by thetravis** [swimlane/ngx-charts#653]
Sorry for posting this in ngx-graph project first. My mistake.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```
**Current behavior**

I have function `getData()` updating `data` once every second, i.e. `this.data = this.getData()` and in html:
```
      <ngx-charts-line-chart-timeline [scheme]="scheme" [results]="data" [gradient]="gradient" [xAxis]="showXAxis" [yAxis]="showYAxis" [legend]="showLegend" [showXAxisLabel]="showXAxisLabel" [showYAxisLabel]="showYAxisLabel" [xAxisLabel]="xAxisLabel" [yAxisLabel]="yAxisLabel" [autoScale]="autoScale" [animations]="animations" [tooltipDisabled]="tooltipDisabled" [timeline]="timeline" (select)="onSelect($event)">
      </ngx-charts-line-chart-timeline>
```
It works as expected and the graphs "rolls" nicely showing last 200 (user selected number) points in the graph. Once I select area in timeline the graph stops as expected and shows only the selected values. When I click unselected area in timeline the selection clears and shows the last 200 points, but the graph doesn't update unless I manually update the gaph by clicking the timeline again. 

 

**Expected behavior**

If the selection is cleared graph should update automatically. 

**Reproduction of the problem**

As above

**What is the motivation / use case for changing the behavior?**

As above

* **ngx-charts version:** 6.1.0

* **Angular version:** 4.4.4

**Comment by thetravis** [comment]
I'm guessing it's this part of the `timeline.js` which is responsible for this behabiour:
```
    Timeline.prototype.addBrush = function () {
        var _this = this;
        if (this.brush)
            return;
        var height = this.height;
        var width = this.view[0];
        this.brush = brushX()
            .extent([[0, 0], [width, height]])
            .on('brush end', function () {
            var selection = d3event.selection || _this.xScale.range();
            var newDomain = selection.map(_this.xScale.invert);
            _this.onDomainChange.emit(newDomain);
            _this.cd.markForCheck();
        });
        select(this.element)
            .select('.brush')
            .call(this.brush);
    };
```
What does `_this.onDomainChange.emit(newDomain);` do if the `newDomain` is empty selection? 

Edit from original: As far as my investigations go, when clearing the selection, `onDomainChange.emit()` which calls `updateDomain(domain)`:

```
    LineChartComponent.prototype.updateDomain = function (domain) {
        this.filteredDomain = domain;
        this.xDomain = this.filteredDomain;
        this.xScale = this.getXScale(this.xDomain, this.dims.width);
    };
```

where `domain` is something like `[500, 1500]` which is the whole range of the `series` (=this.data) at that moment. But after that `this.xDomain` or `this.xScale` seems to stop updating, while timeline keeps rolling and showing the current status of the data.

**Comment by thetravis** [comment]
Aaaand this seems to fix the problem: in my modified `line-chart-timeline.component.ts`:
```
  updateDomain(domain): void {
    if (domain[0] == this.getXDomain()[0] && domain[domain.length - 1] == this.getXDomain()[this.getXDomain().length - 1]) {
      this.filteredDomain = null;
    } else {
      this.filteredDomain = domain;
      this.xDomain = this.filteredDomain;
      this.xScale = this.getXScale(this.xDomain, this.dims.width);
    }
  }
```
So I added check if the selection `domain` matches the `getXDomain()` and if it does, clear the `filteredDomain`. Else continue in old fashion.

**Comment by marjan-georgiev** [comment]
@thetravis if this has been resolved, I will close the issue. Please let me know if you still have issues.

**Comment by leolleocomp** [comment]
Got at this issue yesterday, when this discussion helped me a lot. I added the @thetravis changes on checking if the `domain` matches the `getXDomain()`, for me it didn't work as expected, so I've further changed it to the following code on https://github.com/leolleocomp/ngx-charts/commit/7e86f89b77c40b33129c6377607cecb5bef4c877 , just changing the way the javascript date comparisons are made, as exposed on https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript. I'm really grateful, thank you @thetravis !

```typescript
if (                                                                                                                                                                                                       
     domain[0].getTime() === this.getXDomain()[0].getTime() &&                                                                                                                                                
     domain[domain.length - 1].getTime() === this.getXDomain()[this.getXDomain().length - 1].getTime()                                                                                                        
) {                                                                                                                                                                                                        
    this.filteredDomain = null;                                                                                                                                                                              
} else {                                                                                                                                                                                                   
    this.filteredDomain = domain;                                                                                                                                                                            
    this.xDomain = this.filteredDomain;                                                                                                                                                                      
    this.xScale = this.getXScale(this.xDomain, this.dims.width);                                                                                                                                            
}
```
