### ISSUE TITLE
Error building the app with prod flag

### ISSUE THREAD

**Issue by jfalmoguera** [swimlane/ngx-charts#655]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Hi all,

When I built my app with the prod flag I recieve this error:

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Also I tried with --aot == false, and in this case I get this other error:
Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.

If I run the app with ng serve all going fine.

Any suggestions?

Regards,
Jose

**Comment by marjan-georgiev** [comment]
Can you provide a repository where this can be reproduced please?

**Comment by jfalmoguera** [comment]
Finally I could resolved the issue, and Im not sure if the problemn was related to the library or to angular cli. 

For solving it  I moved the project folder to the root path, I mean i reduce the path for the build proccess.

Regards,
Jose
