### ISSUE TITLE
Add valueFormatting parameter for advanced pie chart and possibly all other components

### ISSUE THREAD

**Issue by katafractari** [swimlane/ngx-charts#657]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Values in advanced pie chart are agressively rounded and prefix/postfix labels can only be added to values via css ::before.

**Expected behavior**
Ability to custom format values and add prefix/postfix labels via *valueFormatting*.

**What is the motivation / use case for changing the behavior?**
I need to show an advanced pie chart with currency values like *CHF 55,9* but I only get *56*.

* **ngx-charts version:** 7.0.1

* **Angular version:** 4.3.1

**Comment by marjan-georgiev** [comment]
This should be resolved by https://github.com/swimlane/ngx-charts/pull/719.
