### ISSUE TITLE
Changing pie chart label text size

### ISSUE THREAD

**Issue by AshrafGabesh** [swimlane/ngx-charts#658]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Tried several times using CSS to update the font size of the label text with no success.
used for example: 

/deep/ g > .pie-label {
    font-size: 14px !important;
}

and 

/deep/ .pie-label {
    font-size: 14px !important;
}

**Expected behavior**
To be able to set the label font size in a pie chart.

**Please tell us about your environment:**
Angular 2+ project

* **ngx-charts version:** x.x.x
6.1.0

* **Angular version:** 2.x.x
4.3.2

* **Browser:** [ Chrome ]

**Comment by marjan-georgiev** [comment]
Here's a plunkr demonstrating that: https://plnkr.co/edit/R859owBxqpZ9lpxNg0yJ?p=preview
