### ISSUE TITLE
Bug when tooltip is insert, remove quickly

### ISSUE THREAD

**Issue by sandangel** [swimlane/ngx-charts#661]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I have explain the issue [here](https://github.com/angular/angular/issues/19712) on angular repo but angular team seem like can not reproduce it. Could you please try to reproduce it on your end or propose another reproduce step so angular team can work on a test and do some fix. At this time the issue still happen on my end and I'm not sure everyone is the same.

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
I am not able to reproduce that using your stackblitz either. What browser are you using?

**Comment by sandangel** [comment]
I'm using chrome 62. hmm... I can easily reproduce the problem on my Mac as well as my Ubuntu 16.04. Don't know what is the different between my ends and yours.

**Comment by sandangel** [comment]
Ok I knew it. Please try to click on the 'graph' link, then when the chart start to appear, click refesh on the stackblitz preview (not browser refresh). And when stackblitz is bundling app, hit back button.

**Comment by Hypercubed** [comment]
Please reopen if this is still an issue.
