### ISSUE TITLE
Pie Grid Multi Option Error

### ISSUE THREAD

**Issue by jason111neo** [swimlane/ngx-charts#667]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
It only allows single data 

**Expected behavior**
upon changing the data to multi, it should work, instead having toLocaleString error

**Reproduction of the problem**
as expected

**What is the motivation / use case for changing the behavior?**
Multiple data sets in a pie grid

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
latest

* **Angular version:** 2.x.x
latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Could this be achieved with multiple pie charts?
