### ISSUE TITLE
Allow overriding spacing in heatmaps and bar charts

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-charts#67]
Add a spacing input property which would control the spacing between rectangles on heatmap charts, and spacing between bars on bar charts:

![image](https://cloud.githubusercontent.com/assets/8687/19807506/b4925a4a-9d20-11e6-8d1d-d0e623bc91ae.png)

**Comment by Hypercubed** [comment]
What do you think of `xInnerPadding` and `yInnerPadding` as the input properties?

**Comment by marjan-georgiev** [comment]
I'm thinking just call it `padding` and make it the same for both X and Y?

**Comment by marjan-georgiev** [comment]
Also, the paddingInner property used on the scale is relative to the range band. So a padding of `0.1` on the x axis is not the same as padding of `0.1` on the y axis (see image above). 

So I think we should make the padding input value absolute in px, and then calculate the relative values to pass to `paddingInner` in order to make the spacing equal.

**Comment by amcdnl** [comment]
`@angular/flex-layout` lets you pass offsets like `%, px, vw, vh` and does relative calculations. Might be interesting for here too https://github.com/angular/flex-layout/wiki/API-Overview

**Comment by Hypercubed** [comment]
@marjan-georgiev Got it.  The default right now is 0.1 (or 10%) in both X and Y, if we change that to `px` is that a breaking change?

@amcdnl Is there elsewhere in ngx-charts that uses `%, px, vw, vh` inputs?

**Comment by marjan-georgiev** [comment]
It won't be the same since it will change it from a relative to absolute value, but I would say that is the desired behavior here, not a breaking change.

We don't use that kind of input yet. There's an issue suggesting we add percentage inputs in addition to px to the chart width and height.

**Comment by Hypercubed** [comment]
I'll start with px input.  If and when % is added to width and height we can add it here.

Is there any president/objection to allowing the input to be `number` or `[number, number]`?  For example:

`padding=10` means 10px in both x and y.
`padding=[10,20]` means 10px in x, 20px in y.

**Comment by marjan-georgiev** [comment]
That looks good to me.

**Comment by Hypercubed** [comment]
If this looks good I can do the same to the bar graph.  https://github.com/swimlane/ngx-charts/compare/master...Hypercubed:feature/innerPadding
