### ISSUE TITLE
Image/vector overlay on chart

### ISSUE THREAD

**Issue by eddieedease** [swimlane/ngx-charts#670]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Feature request**
Is it possible to use an image/vector -overlay that in a area-chart? Also, can we make something like that clickable?

**What is the motivation / use case for changing the behavior?**
I want to remake the next chart using ngx-charts. It uses 3 axis to determinate a specific point. 2 out of 3 given entry's should mark a spot on the chart. All the yellow stuff on top is really an overlay to see in which catagory the result will be. (graph is intented for hospital workers) 
![alt text](https://cubestick.nl/needs/graph.png "graph")

* **ngx-charts version:** x.x.x
latest

**Comment by marjan-georgiev** [comment]
Achieving this would require writing a custom chart. Please take a look at our custom charts page in the docs: https://swimlane.gitbooks.io/ngx-charts/content/intro/custom-charts.html
