### ISSUE TITLE
Black chart on safari. Gradient dosnt work

### ISSUE THREAD

**Issue by KamilKmitaLasoft** [swimlane/ngx-charts#672]
[ x ] bug report 
[ ] feature request
[ ] support request 

On safari browser chart is black. All works fine , but color is black. 
When i change [gradient]="true" to false is ok but without gradient 👎 
```
  lineChartColorScheme = {
    domain: ['#C40536', '#6d6d6d']
  }
```
Angular 5.0.0
"d3": "^4.12.0",

**Comment by KamilKmitaLasoft** [comment]
some ideas ?

**Comment by oiricaud** [comment]
any solutions?

**Comment by oiricaud** [comment]
@KamilKmitaLasoft  how did you resolve this?

**Comment by KamilKmitaLasoft** [comment]
i didnt :(

**Comment by GerardoLSJ** [comment]
This issue es because you have to pass the absolute route of the linearGradient in Safari

Back in version 3.1.0 they were using this approach : 

https://github.com/swimlane/ngx-charts/blob/9b79199e909b0c4ea8959891fe63fa2835c2fb20/src/area-chart/area-chart.component.ts#L209

```jsx
      let pageUrl = window.location.href;
      this.clipPathId = 'clip' + id().toString();
      this.clipPath = `url(${pageUrl}#${this.clipPathId})`;
```

But now i cant figure out how they're passing the "base ref" to the charts

Now theyre using a variable called : **gradientUrl** but cant figure out how they link the base ref there.

**Comment by splatyourbugs** [comment]
If anyone has a solution here that would be awesome.  Love the gradient but the problem with it rendering on Safari and mobile is tough.

**Comment by jbaker-va** [comment]
Also looking for a fix here.

**Comment by splatyourbugs** [comment]
Agreed.  A fix here would be most valuable.

**Comment by honzagula** [comment]
Following...

**Comment by eleon479** [comment]
This may potentially be the same issue as #1062 where the gradient works just fine unless the xaxis and yaxis properties are BOTH set to false. Setting either of them to true brings the gradient back but of course this isn't desired behavior. (Seems to be occurring on Chrome as well)

**Comment by bop10** [comment]
This happens on Safari, and iOS Devices.

**Comment by perotom** [comment]
Nobody found a workaround?

**Comment by oiricaud** [comment]
Nope lol

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by koutsenko** [comment]
Lol... still no gradient.

**Comment by ngnkabylbai** [comment]
Any updates?

**Comment by TayyabKML** [comment]
Anybody found a way to solve this issue?

**Comment by Drake62610** [comment]
Hello this is my workaround for the problem, when i load my chart or change the data I just update gradient with a little delay : 
```ts
@ViewChild(AreaChartComponent, { static: true }) chart: AreaChartComponent;

public ngAfterViewInit() {

        setTimeout(() => {
            this.chart.gradient = true;
            this.chart.update();
        }, 10);
    }
```

Hope this will solve your issue.

**Comment by Meghana1991** [comment]
Hi @Drake62610 

I tried by setting timeout but still unable to render the gradient. Anything else I should be doing?

Thanks

**Comment by automagicxyz** [comment]
> This issue es because you have to pass the absolute route of the linearGradient in Safari
> 
> Back in version 3.1.0 they were using this approach :
> 
> https://github.com/swimlane/ngx-charts/blob/9b79199e909b0c4ea8959891fe63fa2835c2fb20/src/area-chart/area-chart.component.ts#L209
> 
> ```js-jsx
>       let pageUrl = window.location.href;
>       this.clipPathId = 'clip' + id().toString();
>       this.clipPath = `url(${pageUrl}#${this.clipPathId})`;
> ```
> 
> But now i cant figure out how they're passing the "base ref" to the charts
> 
> Now theyre using a variable called : **gradientUrl** but cant figure out how they link the base ref there.

This is the reason why gradient doesn't work in safari.  Safari needs to take absolute path. 
Workaround:

**Option 1:  Use HashLocationStrategy for angular route**
`RouterModule.forRoot(routes, { useHash: true }`

**Option 2: Keep using PathLocationStrategy but append current url to fill: url(#id) after view initialized**
```
ngAfterViewInit() {
    setTimeout(_ => {
      const areas = document.querySelectorAll('path.area');
      areas.forEach(area => {
        const fill = area.getAttribute('fill').slice(4, -1);
        area.setAttribute('fill', `url(${window.location.href + fill})`);
      });
    }, 100);
  }
```

**Comment by bobbyg603** [comment]
We have published a mirrored version ngx-charts that should fix this issue via [@bugsplat/ngx-charts](https://www.npmjs.com/package/@bugsplat/ngx-charts) and opened PR #1637
