### ISSUE TITLE
[IE-11]: errors on multiple components

### ISSUE THREAD

**Issue by sjdemoor** [swimlane/ngx-charts#673]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

- errors on all charts when (select) is hit.
- errors on line-chart, area, stacked-area, and normalized-area charts when (activate) and (deactivate) are hit.
- several charts do not behave normally. (bubble chart displays bubbles, then they immediately go away; tree-map generates `ERROR TypeError: Unable to set property 'pointer-events' of undefined or null reference` errors upon initial rendering, etc...)

**Expected behavior**
IE-11 should be supported.

**Reproduction of the problem**
cloned this repo, and ran on Windows-10 in IE-11.  

**What is the motivation / use case for changing the behavior?**
IE-11 should be supported.

**Please tell us about your environment:**

Windows-10, executing `npm run start` in Git Bash, $ npm -v 5.5.1, $ node -v v7.7.4

* **ngx-charts version:** 7.0.1
{
  "name": "@swimlane/ngx-charts",
  "version": "7.0.1",
  "description": "Declarative Charting Framework for Angular2 and beyond!",
...
}

* **Angular version:** 5.x

* **Browser:** [ IE 11 ]
IE 11

* **Language:** [all ]

Note:  the following file updates resolves many, but not all of the issues:

- demo/app.component.ts ==>  tooltipDisabled = true; (resolves activate/deactivate issue on line-charts and several others, but you still cannot (select) on a data point in a series.

- package.json ==> add `"classlist.js": "^1.1.20150312"` to dependencies.
-  src/polyfills.ts ==> add the following imports:
```
import 'classlist.js';
import 'web-animations-js';
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'zone.js/dist/zone'; 
```

**Comment by akaztp** [comment]
The error with "pointer-events" is also on #449

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported.
