### ISSUE TITLE
** I'm submitting a feature request**

### ISSUE THREAD

**Issue by jojoaddison** [swimlane/ngx-charts#676]
@marjan-georgiev 
Hi Marjan, 
Thanks for this great library!
I tried out the treemap widget and it works great.
My issue is for a way to color the cells based on values rather than names.
Here is my use case:
I want all values from  0-3 to have for instance yellow, 4 - 7 orange and 7 - 10 red.
Is there any such possibility?
Thanks for your kind response.

**Comment by marjan-georgiev** [comment]
This is a valid request. Accepting PRs.

The way I would do this is modify the customColors input to accept a function that would have the data point as a parameter and return a color. This way you can write a custom function that generates a color for the data.

**Comment by marjan-georgiev** [comment]
This was added and released in 7.1.0
