### ISSUE TITLE
Angular 5 chart animations extermely slow and taxing on memory

### ISSUE THREAD

**Issue by StefanErakovic** [swimlane/ngx-charts#678]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Import module and use charts with animations, resulting in slow animations and high impact on app performance.

**Expected behavior**

Animations are fast and work as demonstrated on the demo page.

**Reproduction of the problem**

Import module in angular 5 app and use any chart with animations turned on.

**Please tell us about your environment:**

Stack blitz example:

https://stackblitz.com/edit/angular-jchkhz

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.0.0 and higher

* **Browser:** [Chrome XX | Firefox XX ]

**Comment by marjan-georgiev** [comment]
You are passing a function call to both the `[view]` and `[results]` inputs. This runs those functions on every change detection cycle, and triggers the chart to redraw. That is a very bad practice.

Here's your stackblitz fixed: https://stackblitz.com/edit/angular-1f9e4u

**Comment by StefanErakovic** [comment]
Thanks for the quick reply, this seems like an issue that could occur quite often.
Could this information be written down somewhere on the docs for future reference?

Thanks again mate.

**Comment by marjan-georgiev** [comment]
I don't think that is an issue specific to the charts. Passing function calls as inputs reevaluates them on every change detection cycle, so you should avoid that in general if possible, especially in cases where those functions return the same values over and over.

**Comment by marjan-georgiev** [comment]
Also, please feel free to submit a PR against our documentation. We need help improving it, and we encourage people to contribute to them.
