### ISSUE TITLE
add yScaleMin to vertical bar charts

### ISSUE THREAD

**Issue by hoffm670** [swimlane/ngx-charts#680]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Right now there is an option to set the maximum scale value for the y-axis for vertical bar charts (yScaleMax) but no option to set the minimum.

**Expected behavior**

I am requesting that a y-axis minimum similar to yScaleMax be added.

**What is the motivation / use case for changing the behavior?**

I make performance testing tools and we graph normalized difference from baseline. Because of this our graphs have both positive and negative values. In order to make the graphs very easy to eyeball we usually lock in the axis max and min so that when you view the graph, any bars that approach the top or bottom are worth investigating. I've linked an image below as a quick example of what our graphs would look like.

![image](https://user-images.githubusercontent.com/7826305/34278165-dc1508c2-e66e-11e7-818c-7bfbf698f765.png)

**Comment by pascalgross** [comment]
I would really appreciate this. Line-Charts do have this feature as it seems.

**Comment by priyankaAnand** [comment]
Hi I am Using ngx bar chart vertical but still having the same issue. how to add yScaleMin to bar chart

**Comment by marjan-georgiev** [comment]
Merged the PR, this will be in the next release.
