### ISSUE TITLE
Zero based area chart

### ISSUE THREAD

**Issue by BatMen** [swimlane/ngx-charts#681]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Area charts are always based on the minimum value of Y axe

**Expected behavior**
We should have an *@Input* parameter of type `number | 'auto'` to be able to render an area chart based on a specific Y value. To be able to render something like this (forget the colors, just focus on the zero based area behaviour)

![Zero based area chart example](https://i.imgur.com/LW9PVuv.png)

**What is the motivation / use case for changing the behavior?**
Just being able to do this. I ask first, maybe I would dig into the code to make a pull request. I just want to know if I'm missing something somewhere. I did not find anything in the @input list which may provide this type of behaviour.

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.0.0

**Comment by BatMen** [comment]
I write a PR for this issue [here](https://github.com/swimlane/ngx-charts/pull/684)

**Comment by marjan-georgiev** [comment]
Merged the PR, will be in next release.

**Comment by frostchick** [comment]
how to change the color under baseValue? please :(
