### ISSUE TITLE
Use lettable rxjs operators

### ISSUE THREAD

**Issue by CDDelta** [swimlane/ngx-charts#682]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently, ngx-charts uses patch operators.

**Expected behavior**
ngx-charts to use lettable operators

**What is the motivation / use case for changing the behavior?**
Patch operators...
- are not tree-shakeable
- augment the Observable prototype for all consumers of the library

**Please tell us about your environment:**
-

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.1.0

* **Browser:** all

* **Language:** all

**Comment by amcdnl** [comment]
Merged
