### ISSUE TITLE
Custom Chart Hosting

### ISSUE THREAD

**Issue by sandangel** [swimlane/ngx-charts#686]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I believe that many people are using ngx-chart to build their own custom charts. And many of them are building same kind of chart.

**Expected behavior**

There should be a place where people can share charts they have built.

**What is the motivation / use case for changing the behavior?**

By hosting a place where people can share their own chart, We can extend ngx-chart library, increase reusable code and learn a lot from each other.

**Comment by marjan-georgiev** [comment]
That's a good idea.
I added a custom charts index section on our custom charts documentation page: https://github.com/swimlane/ngx-charts/blob/master/docs/intro/custom-charts.md

Feel free to submit a PR to that page and link to your custom chart implementations (those can be anything - a github repo, plunkr, stackblitz, or even a blog post with code samples).

**Comment by amcdnl** [comment]
You could use stackblitz and just provide links there.
