### ISSUE TITLE
help me guys! pieChart inside text

### ISSUE THREAD

**Issue by Kalaijagdai** [swimlane/ngx-charts#687]
![test](https://user-images.githubusercontent.com/24638874/34409963-4759c342-ebf7-11e7-9b22-375a3d32e05b.jpg)

hello guys! How do I make the texts of the tooltip have a ngx-charts-pie-chart ?

**Comment by jhonieldor** [comment]
I understood by the documentation that there is no such option in ngx-charts, I imagine it should have a flag (true or false) as input in the pie-chart component and internally in the d3 library would be appended calculating the percentages as seen in https://embed.plnkr.co/EoOdyCFGZZVHAFhYRA18/... But I also do not see why not repeat the behavior seen in the advanced-pie chart. Another libraries  normally display this feature in the pie-chart fractions...

**Comment by juergenr** [comment]
Any news on this issue?

**Comment by amirping** [comment]
+1

**Comment by HDaghash** [comment]
+1
