### ISSUE TITLE
unable to sort values in x-axis for line chart

### ISSUE THREAD

**Issue by adithyasai** [swimlane/ngx-charts#689]
When i am trying to replicate something like this : https://swimlane.gitbooks.io/ngx-charts/content/charts/line-chart.html

i am unable to sort the values on x - axis. the data is looking like 2000, 2001, 2002, 1999. but it should be 1999, 2000, 2001, 2002.

How to solve this?

**Comment by marjan-georgiev** [comment]
Are you passing those values as strings, or numbers?

Strings:
```
export const single = [
  {
    name: '2',
    value: 40632
  },
  {
    name: '1',
    value: 49737
  },
  {
    name: '3',
    value: 36745
  }
]
```

Numbers:
```
export const single = [
  {
    name: 2,
    value: 40632
  },
  {
    name: 1,
    value: 49737
  },
  {
    name: 3,
    value: 36745
  }
]
```

If you are passing them as numbers, the should be sorted.

**Comment by waterskier2007** [comment]
having a "name" property be the indicator of location on the x axis seems odd

**Comment by sebastiangug** [comment]
Any luck/ideas on affecting the order of any axis?

**Comment by austinthedeveloper** [comment]
To anyone who has run into sorting issues, the problem is easier than you think. Let's take this series for example:

[
  {name: 'series one', value: **5 values**},
  {name: 'series two', value: **10 values**}
]

This data will cause sorting issues because the array is a different length. Even if the first series has 5 values, **it needs all 10 to show correctly**.

**Comment by ddsultan** [comment]
> Are you passing those values as strings, or numbers?
> 
> Strings:
> 
> ```
> export const single = [
>   {
>     name: '2',
>     value: 40632
>   },
>   {
>     name: '1',
>     value: 49737
>   },
>   {
>     name: '3',
>     value: 36745
>   }
> ]
> ```
> 
> Numbers:
> 
> ```
> export const single = [
>   {
>     name: 2,
>     value: 40632
>   },
>   {
>     name: 1,
>     value: 49737
>   },
>   {
>     name: 3,
>     value: 36745
>   }
> ]
> ```
> 
> If you are passing them as numbers, the should be sorted.

What if I have formatted dates or something like that? How would one do the sorting?

**Comment by acgrama** [comment]
> To anyone who has run into sorting issues, the problem is easier than you think. Let's take this series for example:
> 
> [
> {name: 'series one', value: **5 values**},
> {name: 'series two', value: **10 values**}
> ]
> 
> This data will cause sorting issues because the array is a different length. Even if the first series has 5 values, **it needs all 10 to show correctly**.

In principle yes, but how do I deal with the situation where I don't have 10 values in the first series? i.e., I can't just set the missing values to zero, I actually do not have data for that series at that x value.
Is there a way in ngx-charts to specify that a value is missing?

**Comment by acgrama** [comment]
> > Are you passing those values as strings, or numbers?
> > Strings:
> > ```
> > export const single = [
> >   {
> >     name: '2',
> >     value: 40632
> >   },
> >   {
> >     name: '1',
> >     value: 49737
> >   },
> >   {
> >     name: '3',
> >     value: 36745
> >   }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Numbers:
> > ```
> > export const single = [
> >   {
> >     name: 2,
> >     value: 40632
> >   },
> >   {
> >     name: 1,
> >     value: 49737
> >   },
> >   {
> >     name: 3,
> >     value: 36745
> >   }
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you are passing them as numbers, the should be sorted.
> 
> What if I have formatted dates or something like that? How would one do the sorting?

Same case here, is there a way to deal with this gracefully via ngx-charts?

**Comment by acgrama** [comment]
OK, seems like the best way I can find is to use unix milliseconds as x axis values, since they are then sorted correctly, and use the xAxisTickFormatting function to format the milliseconds into human-readable timestamps shows as labels.

**Comment by borriej** [comment]
Any ideas on this?
I have a retrospective tool, and the x-axis are sprint names. eg: VT-1, VT-2, VT-3, VT-4, VT-5...
now, some team members do have values for a sprint, but others weren't in the retrospective.. so VT-2 might have a value for some team members, but for others they dont have a value. 

How do I set a fixed x-axis order? (I dont want to use date)

**Comment by JoshuaOndieki** [comment]
> Any ideas on this? I have a retrospective tool, and the x-axis are sprint names. eg: VT-1, VT-2, VT-3, VT-4, VT-5... now, some team members do have values for a sprint, but others weren't in the retrospective.. so VT-2 might have a value for some team members, but for others they dont have a value.
> 
> How do I set a fixed x-axis order? (I dont want to use date)

@robvaneck I resorted to using numbers.
- I would sort the sprint names or whichever strings would do. In the names key, I would use the index of the names. So it would be 1, 2, 3, 4, 5 in this case.
- Provide `xAxisTicks` as [1, 2, 3, 4, 5]
- Provide `xAxisTickFormatting` to find the actual name like VT-1 for value 1 from the sorted array.
