### ISSUE TITLE
What are the parameters for valueFormatting in Gauge?

### ISSUE THREAD

**Issue by timhuff5** [swimlane/ngx-charts#690]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```

**Current behavior**
I want the text in the middle of the Gauge to be smaller

**Expected behavior**
valueFormatting would allow me to have parameters to change the visual value in the middle of the gauge

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
UX

**Please tell us about your environment:**
Mac

* **ngx-charts version:** x.x.x
Latest

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
It's a function that accepts the value, and returns a string.
