### ISSUE TITLE
Do we have Grid based charts in NGX-CHARTS 7.0.1

### ISSUE THREAD

**Issue by gauravshri12** [swimlane/ngx-charts#695]
I have json data files which i need to showcase in tabular format & based on same table data chart gets displayed.

**Comment by jotatoledo** [comment]
Check the demos and see if something fits your needs?

**Comment by marjan-georgiev** [comment]
See if the number card matches your requirements. If not, you may want to build a custom chart: https://swimlane.gitbooks.io/ngx-charts/content/intro/custom-charts.html
