### ISSUE TITLE
Support fullTemplateTypeCheck

### ISSUE THREAD

**Issue by cfremgen** [swimlane/ngx-charts#696]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Can't AoT build using latest Angular compiler flag "fullTemplateTypeCheck": true

**Expected behavior**
Build without error

**Reproduction of the problem**
Build this repo with "fullTemplateTypeCheck": true

* **ngx-charts version:** x.x.x
7.0.1

* **Angular version:** 2.x.x
5.2.0

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript version 2.5.3

![image](https://user-images.githubusercontent.com/31008811/34927943-0b461074-f988-11e7-95ba-621a51b1605c.png)

**Comment by marjan-georgiev** [comment]
I believe this was fixed by https://github.com/swimlane/ngx-charts/pull/730

Please let me know if it's still an issue, and I will reopen.
