### ISSUE TITLE
Wrong total percentage in advanced pie chart

### ISSUE THREAD

**Issue by mmahmad** [swimlane/ngx-charts#700]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Incorrect percentage calculated in advanced pie chart.

**Expected behavior**
Individual percentages should add up to 100%.

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.2.0
![ngx-charts-miscalculation](https://user-images.githubusercontent.com/4930049/35044017-8fdfcd32-fbb0-11e7-9377-6321fe43c055.jpg)

Seems to round off some and leave others. Total percentage does not add up to 100%. In the image above, the first chart adds up to 99.76%; the second one adds up to 100.35%.

This issue was closed [here](https://github.com/swimlane/ngx-charts/issues/201) last January, but does not seem to be resolved for many.

**Comment by volpejoaquin** [comment]
Why @mmahmad close this issue ? I have the same problem with advance pie chart percentages !!

**Comment by mmahmad** [comment]
@volpejoaquin Because it's a duplicate of this issue 201.

**Comment by volpejoaquin** [comment]
Oh ok, sorry ! thx 👍
