### ISSUE TITLE
Combo bar chart. Error: "scheme is null"

### ISSUE THREAD

**Issue by zachlefevre** [swimlane/ngx-charts#702]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When template has a combo-chart-component the console shows "TypeError: scheme is null".
**Expected behavior**

**Reproduction of the problem**

```
            <combo-chart-component 
              [scheme]="comboBarScheme"
              [colorSchemeLine]="lineChartScheme"
              [lineChart]="lineChartSeries"
              [results]="horizData"
              [gradient]="gradient" 
              [xAxis]="true" 
              [yAxis]="true"
              [legend]="false" 
              [showXAxisLabel]="false" 
              [showYAxisLabel]="false">
            </combo-chart-component >
```

**Please tell us about your environment:**

Windows 10. Visual Studio Code.
* **ngx-charts version:** 7.0.1

* **Angular version:** 5.1.0

* **Browser:** Chrome | Firefox

* **Language:** ES5

**Comment by marjan-georgiev** [comment]
Are you passing a null value for the comboBarScheme input? Please provide a stackblitz where this can be reproduced.
