### ISSUE TITLE
Drill Down Capacity in Ngx Charts

### ISSUE THREAD

**Issue by AngularCoder89** [swimlane/ngx-charts#706]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**What is the motivation / use case for changing the behavior?**
If i want to show hourly data, is there any feature of clicking on date in x axis and the chart is drilled down to show hourly data for that day?

**Please tell us about your environment:**

* **ngx-charts version:** 6.0.1

* **Angular version:** 5.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by AngularCoder89** [comment]
the select event function did the trick.

**Comment by ramakrishnanmariyappan** [comment]
@AngularCoder89  please provide sample code for drill down chart functionality

**Comment by ramakrishnanmariyappan** [comment]
@AngularCoder89 i got your way and get successful result using drill down functionality

**Comment by iivanovgit** [comment]
@AngularCoder89 can you provide a sample on stackblitz for it ?

**Comment by adcottle** [comment]
was there an example posted?
