### ISSUE TITLE
How to add image and labels in the Vertical Bar Graph of NGX-Charts

### ISSUE THREAD

**Issue by RenukaPrasad0318** [swimlane/ngx-charts#707]
app.component.ts : 

import { Component, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgxChartsModule } from '@swimlane/ngx-charts';
import { single } from './data';

@Component({
  selector: 'my-app',
  template: `
    <ngx-charts-bar-vertical
      [view]="view"
      [scheme]="colorScheme"
      [results]="single"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      [yAxis]="showYAxis"
      [legend]="showLegend"
      [showXAxisLabel]="showXAxisLabel"
      [showYAxisLabel]="showYAxisLabel"
      [xAxisLabel]="xAxisLabel"
      [yAxisLabel]="yAxisLabel"
      (select)="onSelect($event)">
    </ngx-charts-bar-vertical>
  `,
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  single: any[];
  multi: any[];

  view: any[] = [700, 400];

  // options
  showXAxis = true;
  showYAxis = true;
  gradient = false;
  showLegend = true;
  showXAxisLabel = true;
  xAxisLabel = 'Country';
  showYAxisLabel = true;
  yAxisLabel = 'Population';

  colorScheme = {
    domain: ['#5AA454', '#A10A28', '#C7B42C', '#AAAAAA']
  };

  constructor() {
    Object.assign(this, { single })
  }

}

data.ts :  

export var single = [
  {
    "name": "Germany",
    "value": 8940000,
    "title":"Test",
    "extra":"hello"
  },
  {
    "name": "USA",
    "value": 5000000,

  },
  {
    "name": "France",
    "value": 7200000
  }
];

**Comment by marjan-georgiev** [comment]
Closing this as there is not enough information provided. Please open a new issue and explain the use case you are trying to solve by filling out the issue template.

**Comment by soothran** [comment]
@marjan it would be great if you could include an option to add images or icons on top of the bars in bar charts. I know it sounds little bit weird but if some workaround is there that can solve my problem

**Comment by sw-ms-nitishkarkar** [comment]
Is there any way to add html in the card number graph instead of data
