### ISSUE TITLE
Feature - format labels using class properties

### ISSUE THREAD

**Issue by dietergoetelen** [swimlane/ngx-charts#712]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Currently it's not possible to use class properties to format x/y axis labels.

**Expected behavior**
It should be possible to run the format functions in context of the class.

**Reproduction of the problem**
https://stackblitz.com/edit/angular-mclhhg?file=app%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
Calculations based on class properties

* **Language:** all

**Comment by marjan-georgiev** [comment]
You need to bind the function like this:
https://stackblitz.com/edit/angular-snaxag?file=app%2Fapp.component.html

Also, never pass getters into angular inputs, as they trigger change detection, putting the chart into an endless update loop.
