### ISSUE TITLE
performance issue: this is BIG

### ISSUE THREAD

**Issue by sandangel** [swimlane/ngx-charts#714]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

I'm trying to create a chart with data collected every 1s in a day.
My app become lost interaction though I tried with OnPush, disable animation, and even detach() change detection. After do some research on performance tab in Firefox, I have figured out:

![image](https://user-images.githubusercontent.com/22189661/35496805-e68f6a1c-050a-11e8-9373-4120239de16e.png)

This code block smells:

```typescript
// in LineChartComponent

getXDomain(): any[] {
    let values = [];

    for (const results of this.results) {
      for (const d of results.series) {
        if (!values.includes(d.name)) {
          values.push(d.name);
        }
      }
    }
```
2 series in my data has > 30000 objects for each, and this code block just loop through __ALL__ of it  __TWICE__. Even worse, this method is run on every __ngOnChanges__ @@

**Expected behavior**

Better approach to check unique node. Consider using `Set`

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** 7.0.1

* **Angular version:** 5.2.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Merged @EricSmekens's PR which addresses this. Will be in next release.

**Comment by weijyewang** [comment]
@marjan-georgiev  i'm on ngx-charts 7.0.1 and I am still seeing performance issues when my data is over 10k. Is this commit being released on 7.0.1?

**Comment by EricSmekens** [comment]
You'll have to update to 7.3.0.

**Comment by weijyewang** [comment]
@EricSmekens  thanks. I just checked the log and i saw the commit is in 7.3 as well. Thought I could see improvement, showing too many charts (2 line charts, 2 vertical bar charts and 2 horizontal bar charts) with 5k - 7k data still lags my laptop. I hide a few charts and show only 3 charts at a time, and the performance is better now. Thanks for the help
