### ISSUE TITLE
IE11 can't execute toString.call() without declaring it

### ISSUE THREAD

**Issue by tzeH** [swimlane/ngx-charts#734]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
In IE11, the PolarChartComponent does not render. Instead it gives an Error about not being able to "call" something.

**FIX**
The file **utils/types.js** uses the Function **toString** without declaring it. The Line 
`const toString = Object.prototype.toString;`
should fix it.

**Expected behavior**
The PolarChartComponent shows up.

**Reproduction of the problem**
This is the code:
`<ngx-charts-polar-chart [results]="[{name: 'Test', series: [{ name: 'foo', value: 1 }]}]"></ngx-charts-polar-chart>`

**Please tell us about your environment:**
IE11, Angular 5

* **ngx-charts version:** 7.1.1 (npm-package: @swimlane/ngx-charts)

* **Angular version:** 5.2.1

* **Browser:** IE 11

* **Language:** ES6/7

**Comment by jogaj** [comment]
Thank you for your report, IE is not currently supported.
