### ISSUE TITLE
TreeMap with color based on values

### ISSUE THREAD

**Issue by valefix80** [swimlane/ngx-charts#735]
First of all thanks for the lib!
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

In TreeMap colors are assigned in round robin. Specific colors can be assigned using custom colors.

**Expected behavior**

Can cells be colored based on their value? Similar to what happens with cell size.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

random colors don't give much information. And custom colors cannot be applied because values on the cells can change
**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

7.0.1
* **Angular version:** 2.x.x

5
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
You should be able to use the `customColors` input for this. You can pass it a function which accepts the data item, and returns the color for the cell.

Please let me know if that's not what you're looking for, and I will reopen.

**Comment by valefix80** [comment]
I don't think the customColors function can help me. 
I would like to color the cell with the highest value with a color (red for example), the cell with the lowest value (in green), and cell in the middle with color that goes from red to green... 

With the current version the cell with biggest value can be identified because they are bigger in size. In the would be nice to also use a color to identify them.

thank you!

**Comment by marjan-georgiev** [comment]
That's precisely what I was talking about. Take a look at this stackblitz:
https://stackblitz.com/edit/vertical-bar-chart-avyb49?file=app%2Fapp.component.ts

You can generate a linear color scale in your component based on your data and use that inside the customColors function to assign the color to the data item.

**Comment by valefix80** [comment]
Oh... that's great!  thank you very much!

**Comment by tdmitchal** [comment]
The problem is the custom method is passed the label.  If you don't have unique labels in the data, this could be a problem.  Is it assume labels are unique?

**Comment by weirdyang** [comment]
Hi I tried the stackblitz example, but it's throwing the following error;
```

 error TS2740: Type '(value: any) => any' is missing the following properties from type 'any[]': pop, push, concat, join, and 25 more.

7         [customColors]="customColors"
```

```
<div class="chartContainer">
    <ngx-charts-gauge [scheme]="colorScheme"
        [results]="single"
        [legend]="legend"
        [legendPosition]="legendPosition"
        [valueFormatting]="formatValue"
        [customColors]="customColors"
        (select)="onSelect($event)"
        (activate)="onActivate($event)"
        (deactivate)="onDeactivate($event)">
    </ngx-charts-gauge>
</div>


  customColors = (value: any) => {
    return this.colorScale(value);
  }
  colorScale: any;
  generateColorScale() {
    const values: number[] = this.single.map(s => s.value);
    return d3Scale.scaleLinear<string>()
      .domain([0, 100])
      .range(['green', 'red']);
  }
```
