### ISSUE TITLE
sparkline chart with tooltip/spot

### ISSUE THREAD

**Issue by ramakrishnanmariyappan** [swimlane/ngx-charts#739]
need this option inside sparkline chart with tooltip for data point

**Comment by ramakrishnanmariyappan** [comment]
<img width="171" alt="sparkline-with-tooltip" src="https://user-images.githubusercontent.com/34883622/36710601-09eed7c6-1ba5-11e8-9a9b-fcb4c5805c6e.png">

**Comment by marjan-georgiev** [comment]
I created a gist where I added the tooltip implementation:

https://gist.github.com/marjan-georgiev/7cc765a03561c46be9378ad6944254ad

You can replace the sparkline component in the demo with that code, and the tooltip would be present.

**Comment by ramakrishnanmariyappan** [comment]
Thanks a lot @marjan-georgiev, it is worked fine for me
