### ISSUE TITLE
Server/Client side rendering seems impossible to get working

### ISSUE THREAD

**Issue by garethrepton** [swimlane/ngx-charts#748]
I can't get ngx-charts to work in an angular app that has serverside rendering enabled and I can't find any examples of doing so. The examples seem to assume this won't be enabled, and there is only one app.module in the app.

I've mostly tried adding to app.module.shared, but there were issues with client side only functions not being enabled when I added it to that and tried to use it.

Is it possible to install these charts in this sort of setup? If so are there any examples available? Are there any workarounds if not?

**Comment by marjan-georgiev** [comment]
We have opened an issue about this back when we planned for it: https://github.com/swimlane/ngx-charts/issues/629
but we haven't worked on it yet. If someone is willing to start working on it, please go ahead.

**Comment by marjan-georgiev** [comment]
Closing as duplicate.
