### ISSUE TITLE
Legend dont generate properly

### ISSUE THREAD

**Issue by meron1122** [swimlane/ngx-charts#749]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request => Please do not submit support request here
```

**Current behavior**
![image](https://user-images.githubusercontent.com/2895090/37036678-aa8ab064-2150-11e8-9e89-3ae0c1277168.png)

Legend display nothing, but labels is property setted.

**Expected behavior**
Legend display labels.

* **ngx-charts version:** 7.1.1

* **Angular version:** 5.0.0

* **Browser:** all 

* **Language:** TypeScript 

Component with chart is nothing special:

```
<div>
    <div   style="min-height: 500px;">
        <ngx-charts-bar-vertical-stacked
                [animations]="false"
                [xAxis]="true"
                [legend]="true"
                [legendTitle]="'Legenda'"
                [yAxis]="true"
                [scheme]="colors"
                [results]="chartData"
        >
        </ngx-charts-bar-vertical-stacked>
    </div>
</div>
```

**Comment by marjan-georgiev** [comment]
Looks like you something is overriding the css classes. Could you provide a stackblitz where this can be reproduced please?
