### ISSUE TITLE
how to change data real time??

### ISSUE THREAD

**Issue by spring-learner** [swimlane/ngx-charts#753]
https://swimlane.github.io/ngx-charts/#/ngx-charts/pie-chart 
by this site,i think the data of the chart can be changed in real time,but how to write the code??
i have learning the Example on https://swimlane.gitbooks.io/ngx-charts/content/charts/pie-chart.html, i try to chang the data by setTimeout() method,but Nothing has happened。who can give me an example,please!!

**Comment by trumbitta** [comment]
@spring-learner di you solve your issue? I'm looking at using the real time feature as well. Any hints?
