### ISSUE TITLE
yAxisFormatting giving ERROR TypeError: _co.tickFormat is not a function

### ISSUE THREAD

**Issue by Fridthjof** [swimlane/ngx-charts#760]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

yRightAxisTickFormatting() {
        return this.yRightAxisData.toString();
    }

resulting in ERROR TypeError: _co.tickFormat is not a function
with console.log(this.yRightAxisData.toString() prints out the data perfectly in strings.

**Expected behavior**

Setting the yAxisTickFormat with the given strings.

**Please tell us about your environment:**

Win 10, 64 bit. IntelliJ IDE

* **ngx-charts version:** x.x.x

^7.0.1

* **Angular version:** 2.x.x

^5.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Can you provide a stackblitz where this can be reproduced please?
