### ISSUE TITLE
can we customize the color when joining two points on ngx-line graph

### ISSUE THREAD

**Issue by RRR85200** [swimlane/ngx-charts#761]
I am trying to use ngx-line charts to track the status of various jobs .
Is there a way to apply different color to the graph between two points on the graph 
this is to show  if there's  an  increase or decrease over the mean value between these two points. I am using real time data to plot this line graph.

Here is the plunker link ..
https://plnkr.co/edit/UhWbY3YiGLkKlXMfRGec?p=preview

Any help is appreciated..!

**Comment by marjan-georgiev** [comment]
This is an interesting use case. It is not possible, but you should be able to fork the line chart and implement a custom chart that does this. More on custom charts here: https://swimlane.gitbooks.io/ngx-charts/content/intro/custom-charts.html
