### ISSUE TITLE
barpadding before first bar and after last bar not set

### ISSUE THREAD

**Issue by DHoffm** [swimlane/ngx-charts#768]
**I'm submitting a:
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When is set the barPadding parameter padding is only added between bars but not before the first and the last bar.

**Expected behavior**
Padding is also added before first and after last bar.

**Reproduction of the problem**
Use ngx-charts-bar-vertical and add [barPadding]="64"

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Tested with ngx-charts-bar-vertical
* **ngx-charts version:** 7.0.1

* **Angular version:** 5.x.x

* **Browser:** all

* **Language:** all

**Comment by marjan-georgiev** [comment]
I'm not sure I understand this. What would be the use case for that behavior?

**Comment by DHoffm** [comment]
The use case is to have padding before the first bar and after the last bar. It looks better in my opinion.

The background is the following:
At this moment the only option to get the bars smaller in width is to use the barPadding but this only increases the padding between the bars.

**Comment by dvschnitz** [comment]
Are there any plans for this feature? It could work like groupPadding of the Grouped Vertical Barchart.

**Comment by dvschnitz** [comment]
It should look like this for example
![bildschirmfoto 2018-11-07 um 11 03 52](https://user-images.githubusercontent.com/7243761/48124542-e2946c00-e27c-11e8-9dbf-26ef952b989e.png)

**Comment by stankusl** [comment]
I am also in favour of this feature. It looks bad when its not centred for small data set. I've tired adding empty objects in front of array and in the end but it concats both empty objects.

**Comment by arunkumarsubburaj** [comment]
+ 1 Please give some workaround or the fix for this defect.
