### ISSUE TITLE
Extra dimension in tree map

### ISSUE THREAD

**Issue by mrhagbourne** [swimlane/ngx-charts#771]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X] feature request
[ ] support request => Please do not submit support request here
```
**What is the motivation / use case for changing the behavior?**
It would be great if it was possible to add an extra dimension to the tree map using colors. I.e there is a use case where the tree charts could show countries by population (size of the boxes) and then use color to show for example percentage of people in a specific country living in poverty. Is there any way of achieving this with  the ngx-carts tree map? The colors should change according to a gradient, so that countries with little poverty could be at one end of the scale (lets say blue), and the ones with high percentage of poverty could be at the other end of the color spectrum (ie red). I guess we are talking about combing the abilities of a tree map and a heat map in one chart.

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
You should be able to do that using the `customColors` input. You can pass it a function that accepts the value, and return a color for it. Please let me know if that is not what you are looking for, and I will reopen the issue.
