### ISSUE TITLE
Pie Grid Label property doesn't seem to be implemented

### ISSUE THREAD

**Issue by Splaktar** [swimlane/ngx-charts#773]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Trying to set the `label` property of a pie-grid throws an exception.

**Expected behavior**
It should change the text shown in front of the total value, under the pie grid chart.

**Reproduction of the problem**
https://plnkr.co/edit/7zS2fUVEFE2L9v7HBLrl?p=preview
See the console log:
```
Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'label' since it isn't a known property of 'ngx-charts-pie-grid'.
1. If 'ngx-charts-pie-grid' is an Angular component and it has 'label' input, then verify that it is part of this module.
2. If 'ngx-charts-pie-grid' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    <ngx-charts-pie-grid
      [view]="view"
      [scheme]="colorScheme" [ERROR ->][label]="'Total People'"
      [results]="single" [designatedTotal]="89400000"
      (select)="onSele"): ng:///AppModule/App.html@3:29
```

**What is the motivation / use case for changing the behavior?**
The [docs](https://swimlane.gitbooks.io/ngx-charts/content/charts/pie-grid.html#inputs) say: 

Property | Type | Default Value | Description
-- | -- | -- | --
label | string | 'Total' | the text to show under the total value

**Please tell us about your environment:**
OS X, IntelliJ IDEA, NPM, Angular CLI 1.7.3

* **ngx-charts version:** 7.1.1

* **Angular version:** 6.0.0-beta.8

* **Browser:** Chrome 67

* **Language:** TypeScript 2.7.2

**Comment by Mc128k** [comment]
Having the exact same issue here

**Comment by marjan-georgiev** [comment]
Fixed, will be in next release.

**Comment by wamburu** [comment]
@marjan-georgiev Getting same error in the plunker available in the docs.
Is the lib in the latest version?
https://swimlane.gitbook.io/ngx-charts/v/docs-test/examples/pie-charts/pie-grid-chart

**Comment by marjan-georgiev** [comment]
@wamburu we are updating the documentation. That plunkr is old.

Try this: https://stackblitz.com/edit/angular-nvpqvr?file=src%2Fapp%2Fapp.module.ts

**Comment by kavyahalani** [comment]
Is there any way to disable the label totally?
