### ISSUE TITLE
Number card is not displaying the numbers displays blank and on mouse over label text is displayed

### ISSUE THREAD

**Issue by kmanikandanmca2008** [swimlane/ngx-charts#779]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Number card displayed with empty cards even though it has value.
Some of the number cards displayed properly.
**Expected behavior**

Numbers should be rendered in all the number card charts.

**Reproduction of the problem**
Just added three charts for number cards
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
7.1.0
* **Angular version:** 2.x.x
5.0.0
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript2.4.0

![image](https://user-images.githubusercontent.com/16201678/37760141-ceb546ce-2ddb-11e8-8a3b-04cf4133bc49.png)

**Comment by marjan-georgiev** [comment]
Could you provide a stackblitz or plunkr where this can be reproduced please?

**Comment by kmanikandanmca2008** [comment]
This is working fine and the root cause for this issue is css overriding(used card layout to render charts so we have added margin and padding for its children). When I added in a separate number card alone it is rendering fine.
