### ISSUE TITLE
[advanced-legend] Colors disappear for print

### ISSUE THREAD

**Issue by milleraundra** [swimlane/ngx-charts#784]
**I'm submitting a ...**
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Printing a page (or saving a pdf of a web page) that contains an Advanced Pie Chart (which makes use of the Advanced Legend) produces a legend that is missing the color labels.

**Expected behavior**
The legend appears the same way on a print page or PDF as it does on the screen.

**Reproduction of the problem**
https://stackblitz.com/edit/ngx-legend-colors-broken-print
https://ngx-legend-colors-broken-print.stackblitz.io

[IE Example](https://github.com/swimlane/ngx-charts/files/1849082/ie.pdf) (saved as PDF)

**What is the motivation / use case for changing the behavior?**
Users want to be able to see the color correlation between the chart and the legend.

[Potential solution?](https://stackoverflow.com/a/15253634/6420195)

**Please tell us about your environment:**

* **ngx-charts version:**
7.1.1

* **Angular version:** 
Angular 4.2.4

* **Browser:**
Chrome 65
Firefox 59
IE 11

* **Language:**
Typescript 2.3

**Comment by marjan-georgiev** [comment]
Merged the PR. This will be in the next release.
