### ISSUE TITLE
Let user specify whether to include zero in bar-charts

### ISSUE THREAD

**Issue by DonaldAlan** [swimlane/ngx-charts#789]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

In a vertical bar chart, my Y values vary between 70 and 75, but the charts always start at zero. 
**Expected behavior**

Please add a feature that lets the user say whether to include zero in the bars.  If the user wants "no zero", compute minimum from y values.  Alternatively, let user specify a minimum Y value and a maximum Y value. 
**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x

ngs-charts version 7.1.1
* **Angular version:** 2.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by DonaldAlan** [comment]
Like `autoScale` in stacked area charts.

**Comment by marjan-georgiev** [comment]
Added an option to specify the minimum value on the Y scale. If there is a lower value on the chart, the input is ignored. Will be in next release.

**Comment by toriqo** [comment]
you forgot about the grouped bars...
