### ISSUE TITLE
Create a release for the xAxisTicks / yAxisTicks feature

### ISSUE THREAD

**Issue by GO3LIN** [swimlane/ngx-charts#793]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The latest version is 7.2.0 and it's what I have installed in my project. The documentation is specifying a chart parameter which is `xAxisTicks`. But this feature has just been included 3 days ago, but we cannot use it because it's not present in the 7.2.0 release. 

**Expected behavior**
xAxisTicks working according to the documentation.

**Reproduction of the problem**
Obvious

**What is the motivation / use case for changing the behavior?**
In a perfect world, you may automatically tag your commits/merges in the master branch

**Please tell us about your environment:**
Not important

* **ngx-charts version:** 2.7.0

* **Angular version:** 5.2.9

* **Browser:** all

* **Language:** TypeScript

**Comment by marjan-georgiev** [comment]
See 7.3.0
