### ISSUE TITLE
gauge chart not loading 

### ISSUE THREAD

**Issue by yashjit** [swimlane/ngx-charts#796]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request => Please do not submit support request here
```

**Current behavior**

TypeError: Cannot read property 'toLocaleString' of undefined
    at formatLabel (index.js:8634)
    at GaugeArcComponent../src/gauge/gauge-arc.component.ts.GaugeArcComponent.tooltipText (index.js:11401)
    at Object.eval [as updateDirectives] (GaugeArcComponent.html:30)
**Expected behavior**

**Reproduction of the problem**

<ngx-charts-gauge
                [view]="[130, 100]"
                [scheme]="{domain:'#ed6952'}"
                [results]="speed"
                [min]="0"
                [max]="100"
                [angleSpan]="240"
                [startAngle]="-120"
                [units]="'Km/H'"
                [bigSegments]="10"
                [smallSegments]="5"
                (select)="onSelect($event)">
              </ngx-charts-gauge>
**What is the motivation / use case for changing the behavior?**

//Speed
      this.speed = [
        {
          "name": "Speed",
          "series": [
            {
              "name" : 'Speed',
              "value" : 10
            }
          ]
        }
      ];
      //this.yAxisLabel_speed = this.speed[0].name;
      this.intervalId = setInterval(() => { 
        this.speed = [...this.add_speed()];
      }, 2000);
**Please tell us about your environment:**

* **ngx-charts version:** 5.5

* **Angular version:** 4.x+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Looks like you are passing the wrong data format. Take a look at the documentation page for the correct format:

https://swimlane.gitbooks.io/ngx-charts/content/charts/gauge.html
