### ISSUE TITLE
Rounding on Axis Values

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#80]
Need some ability to round axis values so Instead of 0, 0.5, 1 ... it just be 0, 1, etc

![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/1c3c9289-e9d9-4cfe-8510-5b2ad3b01626/2016-11-14_10-20-28.png)

**Comment by andrreea** [comment]
I'm dealing with the same issue. This would be very useful to have. Or at least to be able to specify the xScale, xDomain, and yScale, yDomain.

**Comment by marjan-georgiev** [comment]
We opted for a more generic solution to this problem.

We added `xAxisTickFormatting` and `yAxisTickFormatting` inputs to all charts that have X and Y axis.

They accept a function, in which you can return a string that will be displayed in place of the axis tick label.

If you want to hide a label, just return an empty string.

In this particular example, the function to round labels on whole numbers would be:
```
axisFormat(val) {
  if (val % 1 === 0) {
    return val.toLocaleString();
  } else {
    return '';
  }
}
```

**Comment by renemadsen** [comment]
Before doing this fix:
![image](https://github.com/swimlane/ngx-charts/assets/76994/77d211f0-107c-417c-8699-3721032bcaab)

This is fine for getting rid of the label, but how do we get rid of the line in the chart:
![image](https://github.com/swimlane/ngx-charts/assets/76994/a78bcbf0-608e-4957-ada8-d64fd104cfc8)

**Comment by johannes-isaksson** [comment]
I, too, am interested in how to remove the redundant lines. I have a data series which can not contain decimal numbers, so any indicators implying their existence is misleading to the reader.
