### ISSUE TITLE
Black chart on safari gradient doesn't work 

### ISSUE THREAD

**Issue by oiricaud** [swimlane/ngx-charts#808]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
When using ` <ngx-charts-bar-vertical  [animations]="false"
                                  [scheme]="colorScheme"
                                  [schemeType]="'linear'"
                                  [results]="data"
                                  [yAxisTickFormatting]="myYAxisTickFormatting"
                                  [xAxis]="true"
                                  [yAxis]="true"
                                  [gradient]="true"
                                  [showXAxisLabel]="true"
                                  [showYAxisLabel]="true">`
the bar graph displays black only on Safari 11

**Expected behavior**
Well considering I am using a scheme of ` 
    colorScheme = {
             domain: ['#4C75D0', '#48A6CC']
  };`
The expected behaviour should be a blueish gradient as shown on Firefox and Chrome. 

**Reproduction of the problem**

Create an Angular 5 application and import the necessary components and insert the ngx-charts-bar-vertical and load it up on safari and you'll see it displays black, despite of what the color scheme is defined. 

**What is the motivation / use case for changing the behavior?**
Well I believe it's a bug... 

**Please tell us about your environment:**
Mac OS, Intellij 

* **ngx-charts version:** x.x.x
7.0
* **Angular version:** x.x.x
5.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Safari 11 >

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by GerardoLSJ** [comment]
I think this is a dupe from #672

**Comment by bobbyg603** [comment]
We have published a mirrored version ngx-charts that should fix this issue via [@bugsplat/ngx-charts](https://www.npmjs.com/package/@bugsplat/ngx-charts) and opened PR #1637
