### ISSUE TITLE
Where does this come from?

### ISSUE THREAD

**Issue by trumbitta** [swimlane/ngx-charts#818]
I don't see any related `@Input()`

https://github.com/swimlane/ngx-charts/blob/bec3f92c57341da5793f943bd9e5ca908664d0b0/demo/combo-chart/combo-chart.component.ts#L79

**Comment by marjan-georgiev** [comment]
`results` is an input on the BaseChartComponent, which all charts extend.

Please don't open github issues for questions like these. Use the gitter channel instead: https://gitter.im/swimlane/ngx-charts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
