### ISSUE TITLE
How can  I customize  the color of the each bar element thats being added to the chart rendering using real time data ?

### ISSUE THREAD

**Issue by RRR85200** [swimlane/ngx-charts#824]
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

How can  I customize  the color of the each bar element thats being added to the chart rendering using real time data ?

**Expected behavior**
I am creating  a vertical bar graph in real time and I would like to customize the color of the bar element being added as either red or blue or gray. How Can i do that ?

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Customizing the color of each bar element in bar chart.

**Please tell us about your environment:**
Angular 5, Ngx chart v7.2

* **ngx-charts version:** x.x.x

* **Angular version:** x.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Please use StackOverflow for support questions.
