### ISSUE TITLE
Documentation examples not showing up on Gitbook

### ISSUE THREAD

**Issue by Balagii** [swimlane/ngx-charts#826]
**I'm submitting a ...** 

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
Looking for code examples I arrived at the online docs, e.g. https://swimlane.gitbook.io/ngx-charts/examples/bar-charts/vertical-bar-chart
When I compare these example pages with the corresponding pages on Github, e.g.
https://github.com/swimlane/ngx-charts/blob/master/docs/charts/bar-vertical.md
... i notice that none of the Stackblitz <iframe>s are showing up. (Being able to see these examples would have saved me a lot of time.)

**Expected behavior**
See actual examples in the documentation, as promised on the [Introduction](https://swimlane.gitbook.io/ngx-charts) page.

**Reproduction of the problem**
Navigate to any sub-page of  https://swimlane.gitbook.io/ngx-charts/examples/

**What is the motivation / use case for changing the behavior?**
assist users in adopting ngx-charts

**Please tell us about your environment:**

* **ngx-charts version:** not sure

* **Angular version:** 

* **Browser:** Chrome 66.0.3359.139

* **Language:**

**Comment by dilipui** [comment]
Even I am also not able to see examples and source code, Please add plnkr demo links to view the charts, and also need more clear documentation for spark-line charts.

**Comment by Hypercubed** [comment]
Will be fixed soon via #838
