### ISSUE TITLE
ngx-charts inside Angular Library (created using Angular CLI 6.0) gives error

### ISSUE THREAD

**Issue by jaganlal** [swimlane/ngx-charts#829]
**I'm submitting a ...**  (check one with "x")

- [ x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

With the latest Angular 6.0, if `NgxChartsModule` is included inside a library (generated by `ng generate library my-lib` command). It gives the following errors when building the library (`ng build my-lib`)

**BUILD ERROR
: Cannot determine the module for class `AxisLabelComponent` in c:/temp/.../node_modules/@swimlane/ngx-charts/release/common/axes/axis-label.component.d.ts! Add `AxisLabelComponent` to the NgModule to fix it.**

Similar error for `XAxisTicksComponent`, `XAxisComponent`, `YAxisTicksComponent` & `YAxisComponent`

**Expected behavior**
There shouldn't be any error

**Reproduction of the problem**

All i did was add `ngx-charts` version 8.0.0 to the library code (`tvmaze`) of the following repo - https://github.com/sulco/angular-lib-demo

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 7 Enterprise

* **ngx-charts version:** 8.0.0

* **Angular version:** 6.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by jaganlal** [comment]
Just now found, if i import only the module that i need (in my case i use `TreeMapModule` & `LineChartModule`, so i imported only these 2 modules), it works like a charm.
Either ways, it'll be helpful if this issue is fixed.

Thanks,
Jagan

**Comment by MonasteryJohn** [comment]
Using Angular 6.0 and ngx-charts 8.0.2 I get the same error. Like @jaganlal said, if you import the needed modules only, the error goes away. 

One thing I did note though, is if you try to import ChartCommonModule then the error comes back, so it seems the problem is something contained in that module.

Work around is ok, but would also appreciate a fix in the future.

**Comment by ramuda** [comment]
@MonasteryJohn :+1:  I am facing the same issue. refer https://github.com/swimlane/ngx-charts/issues/595
