### ISSUE TITLE
 angular2-jwt@0.2.3 requires a peer of @angular/core@^2.0.0||^4.0.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by railsonluna** [swimlane/ngx-charts#832]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [x] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
angular2-jwt@0.2.3 requires a peer of @angular/core@^2.0.0||^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by GO3LIN** [comment]
Hello, I think that this is related to angular2-jwt and not ngx-charts ! What's your angular version ? In the github main README of the angular2-jwt repo (https://github.com/auth0/angular2-jwt) they are saying: 

> @auth0/angular-jwt v2 is to be used with Angular v6+ and RxJS v6+. For Angular v4.3 to v5+, use @auth0/angular-jwt v1

So you have to pick the angular-jwt corresponding to your angular version. GL HF
