### ISSUE TITLE
EuroValueFormat function don't work in ngx-charts-advanced-pie-chart

### ISSUE THREAD

**Issue by Jumaga2015** [swimlane/ngx-charts#865]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
this function do not work with ngx-charts-advanced-pie-chart
typescript:
`  euroValueFormat(c) : any {
    return c + '€';
  }` 
html:
`<div class="container">
    <ngx-charts-advanced-pie-chart 
                                   [scheme]="colorScheme"
                                   [results]="datas"
                                   [gradient]="true"
                                   [valueFormatting]="euroValueFormat"
                                   (select)="onSelect($event)">
    </ngx-charts-advanced-pie-chart>
</div>`

**Expected behavior**
100 => 100€

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
show the type of units of the figures

**Please tell us about your environment:**

* **ngx-charts version:** 8.0.2

* **Angular version:** 6.0.3

* **Browser:** [all ]

* **Language:** [TypeScript X.X ]

**Comment by curtiscovington** [comment]
For a temp fix until my pull request is merged add: [animations]="false"

**Comment by marjan-georgiev** [comment]
Merged the PR. This will be in the next release.

**Comment by vjpc** [comment]
@marc92w - Can we have similar fix for percentageFormatting. It's not displaying the formatted percentage value in the legends. It works only if we applies [animations]="false", the workaround @curtiscovington suggested.

**Comment by marc92w** [comment]
@vjpc Sure I have already implemented a bugfix for this. I'll test it and create a pull request at the weekend.
