### ISSUE TITLE
Realtime in demo is broken on line/area charts

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ngx-charts#87]

**Comment by Dunk14** [comment]
In every possible ways real time just doesn't works on my side...
However I saw the two closed issues where it said that we have to reinstanciate data variable but no refreshing on behalf of ngx-chart

**Comment by marjan-georgiev** [comment]
This issue refers to the real-time data not being implemented on the demo page.

To update the chart, you need to pass it immutable data.

**Comment by vishd** [comment]
How do I pass real-time data from socket.io. I can't see any working example in the demo page. I appreciate if you give some example of real-time data streaming.

**Comment by cole21771** [comment]
@vishd Did you ever get real time data working with socket.io and ngx-charts?

**Comment by jeffreylim17** [comment]
Here's a good demo for this one. websockets and Ngx Charts 
https://medium.com/oril/spring-boot-websockets-angular-5-f2f4b1c14cee

Basically once you subscribed on sockets you just need to pass the data retrieved and assign those data for your charts consumption in my case. I initialized  an array 
"name": "Data",
        "series": [{
          "name": (time series data here),
          "value": ""
