### ISSUE TITLE
Can't use multi data with vertical bar chart

### ISSUE THREAD

**Issue by AhmedMasoodSiddiqui** [swimlane/ngx-charts#871]
- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [x ] support request 
questions
Hoe to use multi data in the following stackblitz example

**Current behavior**
can't use multi data 

**Expected behavior**
data with multi parts should show in different bars according to provided data

**link to example**
https://stackblitz.com/edit/vertical-bar-chart?embed=1&file=app/app.component.ts

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by angelvazquezmenendez87** [comment]
I was able to reproduce the same issue.

**Comment by Hypercubed** [comment]
I see nothing out of the ordinary with the example provided.  If you want grouped data you need to use another chart tyle... for example `ngx-charts-bar-vertical-2d`.

**Comment by angelvazquezmenendez87** [comment]
Yeah sorry about not notify it before, I solved the problem using ngx-charts-bar-vertical-2d.
Thank you so much
