### ISSUE TITLE
Export domain.helper methods

### ISSUE THREAD

**Issue by salemdar** [swimlane/ngx-charts#882]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
Sparkline demo chart is using `getUniqueXDomainValues()` method, but it is not exported by `index.ts`. It feels like a bug.

**Expected behavior**
`index.ts` should export everything.

**What is the motivation / use case for changing the behavior?**
I will be easier to implement custom charts.

**Please tell us about your environment:**

* **ngx-charts version:** 8.0.2

* **Angular version:** 6.0.5

* **Language:** TypeScript 2.7

**Comment by marjan-georgiev** [comment]
Merged the PR. This will be in the next release.
