### ISSUE TITLE
Allow a better visualisation of the axis labels instead of the raw value

### ISSUE THREAD

**Issue by ShinDarth** [swimlane/ngx-charts#910]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

![image](https://user-images.githubusercontent.com/75517/42640969-c6a1d914-85f3-11e8-84fd-1fdb0cad181e.png)

**Expected behavior**

It would be nice to have a way to customise the way we show labels. For example in my line chart I have labels like `2018-05-01 04:00:00.000` and while I want to show the full value when the mouse is over the chart, I don't want to show the full value below the chart for obvious reasons.

**Comment by marjan-georgiev** [comment]
We already have ways to do that. Look at the `xAxisTickFormatting` input that allows you to format the values however you want.

Also, in your case, it looks like you might want a time scale on the x Axis. To do that, your data needs to have actual `Date` objects rather than strings.

**Comment by ShinDarth** [comment]
thanks a lot @marjan-georgiev for your answer, I'll definitely try that. Where are those parameters explained? I couldn't find them neither in the website demo nor in the documentation.

**Comment by marjan-georgiev** [comment]
You can find a list of inputs on every chart's demo page:
https://swimlane.gitbook.io/ngx-charts/v/docs-test/examples/line-area-charts/line-chart

You can pass a function to that input that accepts the value and returns a string.

```
axisFormat(val) {
  return '$' + val.toLocaleDateString(); 
}
```

**Comment by ShinDarth** [comment]
@marjan-georgiev thanks a lot.

Using Date the output loooks indeed better, however where can I find the documentation for this specific feature?

In particular I need to solve those issues:
- how to display also the time (it's inside the Date object but the chart is not showing it)
- how to display GMT by default instead of the timezoned time

**Comment by ShinDarth** [comment]
@marjan-georgiev that allows me to change how's displayed in the x axis, but I mean the value in the chart  (when you go with the cursor over the point in the chart).

**Comment by ShinDarth** [comment]
currently it's showing only the date in format MM/DD/YYYY and I would like to change that

**Comment by marjan-georgiev** [comment]
You can do that with `tooltipTemplate` and `seriesTolltipTemplate`
```
<ngx-charts-line-chart id='chart' 
    ...
    ...
    ...
   >
    <ng-template #tooltipTemplate let-model="model">
          write your custom tooltip html here. the data is in model
    </ng-template>
 </ngx-charts-line-chart>
```

**Comment by ShinDarth** [comment]
@marjan-georgiev thanks. What is the format of the `model` object? is it documented somewhere?

**Comment by v-rayner** [comment]
Is it possible to add space between the times or limit the number of tags? This is real time data in my case and it seems extremally close to each other.
Also when setting `[rotateXAxisTicks]= "false" ` - x axis overlapping 
![35](https://github.com/swimlane/ngx-charts/assets/142643754/c8de9402-eab2-49d3-bb4f-80eb81fcee04)
![Screenshot (124)](https://github.com/swimlane/ngx-charts/assets/142643754/2b4c7563-778c-4c0f-a312-56aff0aa836b)
![37](https://github.com/swimlane/ngx-charts/assets/142643754/4226a2a5-3072-43a6-91a0-4cd55494404e)

**Comment by v-rayner** [comment]
Is it possible to add space between the times or limit the number of tags? This is real time data in my case and it seems extremally close to each other.
Also when setting [rotateXAxisTicks]= "false"  - x axis overlapping
![35](https://github.com/swimlane/ngx-charts/assets/142643754/6fcfa465-caf0-4dfa-b2c0-2dfc550a9914)
![44](https://github.com/swimlane/ngx-charts/assets/142643754/2963185a-b374-4c53-8dc1-4966aeb62764)
