### ISSUE TITLE
Angular 6 error TS2307: Cannot find module '@angular/core'.

### ISSUE THREAD

**Issue by winniejao** [swimlane/ngx-charts#931]
This error appears in @swimlane package.

I am new to angular.
I am using Windows 10.
The versions of my angular cli and other packages are in the screenshot.
The errors are in the second screenshot.

Thank you!

![angular_version](https://user-images.githubusercontent.com/28016078/43153074-250b757a-8f25-11e8-8fcd-e819c8ebef2d.PNG)
![swimlane_errors](https://user-images.githubusercontent.com/28016078/43153096-367ecbc2-8f25-11e8-8282-772e3cdc9218.PNG)

**Comment by marjan-georgiev** [comment]
Do you have @angular/core installed? Check your package.json.

**Comment by riskgod** [comment]
the same problem on my local. I have @angular/core on package.json

**Comment by nijanthan0** [comment]
yes
