### ISSUE TITLE
How to show multiple x axis elements with same name?

### ISSUE THREAD

**Issue by sajeetharan** [swimlane/ngx-charts#941]
**I'm submitting a ...**  (check one with "x")

- [x ] bug report - Not able to plot the series with duplicate names
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
The key with highest value is getting plotted

**Expected behavior**
Should show all the values.

**Reproduction of the problem**

 https://plnkr.co/edit/SVAlRkfxQYZlBBEWA2fG?p=preview

**What is the motivation / use case for changing the behavior?**
I need to plot both values using the same name

**Please tell us about your environment:**
Chrome

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Groups must have unique names. If you want to display the same name on 2 different groups you can override the tooltips and axis labels:

https://plnkr.co/edit/IbznLAXo3M1zHkK6eW3P?p=preview

**Comment by sajeetharan** [comment]
Thanks for the prompted reply. Much appreciated 👍
