### ISSUE TITLE
Tolocalestring to undefined

### ISSUE THREAD

**Issue by Loremerca** [swimlane/ngx-charts#943]
**I'm submitting a ...**  (check one with "x")

- [ x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions. 

**Current behavior**
When I try to use grouped horizontal bar I receved this error  "Cannot read property 'toLocaleString' of undefined", this happen in your exemple too, https://stackblitz.com/edit/vertical-bar-chart?embed=1&file=app/app.component.ts when try to change single in multi.

**Reproduction of the problem**

<img width="955" alt="schermata 2018-08-06 alle 14 10 15" src="https://user-images.githubusercontent.com/12910014/43716160-5b10babe-9983-11e8-9b14-d9dd95d55338.png">

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** x.x.x
9.0.0

* **Angular version:** x.x.x
6.0.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Versione 68.0.3440.84

Thanks in advance!

**Comment by marjan-georgiev** [comment]
You need to change the component too, not just the data:

https://stackblitz.com/edit/vertical-bar-chart-clzy1b?file=app%2Fapp.component.html

**Comment by Dennyfentow** [comment]
hello, this error occurred to me when git was checked out on another branch, angular bug as times, need to restart it
