### ISSUE TITLE
JAWS screen reader support (accessibility) for reading values in tables

### ISSUE THREAD

**Issue by aproberts01** [swimlane/ngx-charts#945]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
When tabbing to the first bar in the bar graph chart, JAWS screen reader reads the highest y-axis value in the page instead of the value of the currently focused bar. It again repeats this same value for all bars in the chart. 

**Expected behavior**
When tabbing to the first bar in the bar graph chart, JAWS screen reader reads the value of the currently selected bar (or of the tool tip), not the highest value in the graph. This behavior would be consistent with every bar in the table. 

**What is the motivation / use case for changing the behavior?**
More accessibility/inclusion for users with disabilities. 

**Please tell us about your environment:**

* **ngx-charts version:** 9.0.0

* **Angular version:** 5.2.9

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Thanks for reporting this. Accepting PR's.
