### ISSUE TITLE
Format values in Line Chart

### ISSUE THREAD

**Issue by AlexandreHSBueno** [swimlane/ngx-charts#946]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [x] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Expected behavior**
I'm using Line Chart and I receive my value as Total minutes, I hope to format this value to "hh:mm".

**What is the motivation / use case for changing the behavior?**
I'm work with time, but I can't create the chart based in string values "hh:mm"

* **ngx-charts version:** x.x.x
9.0.0

* **Angular version:** x.x.x
5.0.3

**Comment by eranshmil** [comment]
You can use [xAxisTickFormatting/yAxisTickFormatting](https://swimlane.gitbook.io/ngx-charts/v/docs-test/examples/line-area-charts/line-chart) inputs.
You can read more in issue #51 .

**Comment by zdenek-horak** [comment]
Actually you might use the xAxisTickFormatting/yAxisTickFormatting for axis labels only. The labels inside the chart (if you hover the point with your mouse) cannot be formatted this way.

I would suppose the yAxisTickFormatting could be used to do this, but this is not true in ngx-charts 9.0.0. Or maybe something like valueFormatting/labelFormatting from [Number Card Chart](https://swimlane.gitbook.io/ngx-charts/examples/number-card-chart) could be used.

**Comment by alaskandan** [comment]
This would definitely be the icing on the cake for all of the functionality you all have in these charts.  Being able to format the datalabels is a pretty huge ask from me as well
