### ISSUE TITLE
grouped bar charts not working, causing an error : ERROR TypeError: Cannot read property 'toLocaleString' of undefined

### ISSUE THREAD

**Issue by Shankar016** [swimlane/ngx-charts#949]
ERROR TypeError: Cannot read property 'toLocaleString' of undefined

this is input  :  

multi = [
    {
      "name": "Germany",
      "value": 10012,
      "series": [
        {
          "name": "2010",
          "value": 7300000
        },
        {
          "name": "2011",
          "value": 8940000
        }
      ]
    },
    {
      "name": "USA",
      "value": 12133,
      "series": [
        {
          "name": "2010",
          "value": 7870000
        },
        {
          "name": "2011",
          "value": 8270000
        }
      ]
    },
    {
      "name": "France",
      "value": 32323,
      "series": [
        {
          "name": "2010",
          "value": 5000002
        },
        {
          "name": "2011",
          "value": 5800000
        }
      ]
    }
  ];

  // view: any[] = [700, 400];

  // options
  showXAxis = true;
  showYAxis = true;
  gradient = false;
  showLegend = true;
  showXAxisLabel = true;
  xAxisLabel = 'Country';
  showYAxisLabel = true;
  yAxisLabel = 'Population';
  showGradient = true;
  schemeType = 'ordinal';
  yScaleMax = '900000';

  colorScheme = {
    domain: ['#5AA454', '#A10A28', '#C7B42C', '#AAAAAA']
  };

html :

<ngx-charts-bar-vertical
    [scheme]="colorScheme"
    [animations]="true"
    [schemeType]="schemeType"
    [results]="multi"
    [gradient]="showGradient"
    [xAxis]="showXAxis"
    [yAxis]="showYAxis"
    [legend]="showLegend"
    [showXAxisLabel]="showXAxisLabel"
    [showYAxisLabel]="showYAxisLabel"
    [xAxisLabel]="xAxisLabel"
    [yScaleMax]="yScaleMax"
    [gradient]="true"
    [yAxisLabel]="yAxisLabel"
    (select)="onSelect($event)">
  </ngx-charts-bar-vertical>

**Comment by Shankar016** [comment]
https://stackblitz.com/edit/vertical-bar-chart?embed=1&file=app/app.component.ts

**Comment by EmaGht** [comment]
> ERROR TypeError: Cannot read property 'toLocaleString' of undefined
This usually happens when you have a "value" set to null, in which case you should pass to it an empty string.

This is bad:
`"series": [
{
"name": "MyName",
"value": null
},`

This is good
`"series": [
{
"name": "MyName",
"value": ""
},`

You seem to not be having this error in the code you are showing but like @Shankar016 pointed out it should work, so...

**Comment by Shankar016** [comment]
@EmaGht the chart is not rendering and  I am having following errors in the browser console:

platform-browser.js:2854 Error: <path> attribute d: Expected number, "M1,NaNh78h0v0v1a0,0…".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2854
platform-browser.js:2854 Error: <path> attribute d: Expected number, "M87,NaNh78h0v0v1a0,0…".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2854
platform-browser.js:2854 Error: <path> attribute d: Expected number, "M173,NaNh78h0v0v1a0,0…".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2854
platform-browser.js:2854 Error: <path> attribute d: Expected number, "M259,NaNh78h0v0v1a0,0…".
DefaultDomRenderer2.setAttribute @ platform-browser.js:2854
platform-browser.js:2854 Error: <path> attribute d: Expected number, "M345,NaNh78h0v0v1a0,0…".

ERROR TypeError: Object(...) is not a function

**Comment by EmaGht** [comment]
![image](https://user-images.githubusercontent.com/12494403/44079337-0ff65648-9fa9-11e8-8653-eecec650a3a5.png)

@Shankar016 Empty console, chart rendering correctly.
Have you tried switching browser/cleaning cache/etc... ?

**Comment by Shankar016** [comment]
Please try the input for grouped bar chart, it's not working

**Comment by marjan-georgiev** [comment]
You are using the single bar chart with data for the grouped bar chart. You need to use the `ngx-charts-bar-vertical-2d` component with that data.

**Comment by Shankar016** [comment]
@marjan-georgiev thanks for the answer, can you tell me the source where you got this info, please send the link
