### ISSUE TITLE
Line chart tooltip template does not come up when model.value is zero

### ISSUE THREAD

**Issue by naitik95** [swimlane/ngx-charts#984]
**I'm submitting a ...**  (check one with "x")

- [X ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
Tooltip does not come up when model.value = 0
`<ng-template #tooltipTemplate let-model="model">`

**Expected behavior**
Tooltip should appear when model.value = 0

**Comment by Sergey-Ryabov** [comment]
Hi. In our project we are solve this problem with model.value = '0'. It's seems bug related with https://github.com/swimlane/ngx-charts/blob/master/projects/swimlane/ngx-charts/src/lib/common/circle-series.component.ts#:~:text=%5BpointerEvents%5D%3D%22circle.value%20%3D%3D%3D%200%20%3F%20%27none%27%20%3A%20%27all%27%22
