### ISSUE TITLE
Charts breaking page in IE11

### ISSUE THREAD

**Issue by paulinewu** [swimlane/ngx-charts#996]
**I'm submitting a ...**  (check one with "x")

- [x ] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**
With ngx-charts loaded in our Angular module, the page does not load, and receives an error in the console:
![image](https://user-images.githubusercontent.com/11036292/46488808-9d31da00-c7b8-11e8-8cd3-14830ea88dbc.png)
![image](https://user-images.githubusercontent.com/11036292/46488843-b33f9a80-c7b8-11e8-9019-5347d17a2056.png)

**Expected behavior**
Our pages to load with ngx-charts loaded in our Angular module.

**Reproduction of the problem**
After installing ngx-charts, import NgxChartsModule to an Angular module. Load page in IE11. Components declared in the same module where Ngx-Charts is imported do not load (blank page).

**What is the motivation / use case for changing the behavior?**
To use NGX-charts in web app without breaking in IE11.

**Please tell us about your environment:**
Windows, IE11

* **ngx-charts version:** x.x.x
9.0.0

* **Angular version:** x.x.x
6.1.2

* **Browser:** 
Only in IE. 

* **Language:** 
TypeScript 2.9 | ES5

**Comment by jothyv** [comment]
am facing the same issue under same environments.. issue seems to be closed.. can you provide the solution?
